### ISSUE TITLE
Proper installation of redis+hiredis library on RPi4

### ISSUE THREAD

**Issue by Danilich1994** [redis/hiredis#1007]
Hello,

I'm trying to setup RPi4 to connect to external Redis server (connected through TCP/IP). 
Redis-server 6.2.6 (along with client) is installed using https://redis.io/topics/quickstart guide on both, client (RPi), and server machine.
Server itself is running on Ubuntu(WLS), and I can interact with it through redis-cli on raspberry. Server is configured in unprotected mode (because net is local) with password.
"Hiredis" is installed with 
`git clone https://github.com/redis/hiredis.git`
`make`
`make install`
Demo program (taken from https://programmer.group/5c14b1b42b192.html) ends with timeout error. As I understand, this happens because `conn = redisConnectWithTimeout(hostname, port, timeout);` returns `err` to `conn`. So it create connection but with error.
Demo program (example.c modified to be able to make authentication) ends with same `Connection error: Connection timed out`.
What can be a problem? What is proper way to install all necessary on raspberry?

**Comment by michael-grunder** [comment]
Closing this old issue, but I'm happy to help if you are still having trouble.
