### ISSUE TITLE
Async callback function was not called if the lasted callback is not finish

### ISSUE THREAD

**Issue by nguyenctu** [redis/hiredis#1021]
Hi, I'm working on a project which need to subscribe to a channel, then when message come it will do stuffs with that message. But currently I'm facing an issue. In my callback function I have a while(1){} loop. The first time message was published to the channel the callback function was called, but the second time the callback function was not called anymore (Meanwhile the first callback function is not finish). How can I call callback function everytime the message come whether the latest callback function is finished or not?Thank you! Here is my code:

`

    redisAsyncContext *redis;
    
    // Variable For Event 
    struct event_base *base = event_base_new();

    // Init Redis Client Connect To Redis Server With IP And PORT
    redis = redisAsyncConnect(HOST_REDIS_SERVER, PORT_REDIS_SERVER);

    // Return When Connect To Redis Error
    if (redis->err) 
    {
        #ifdef DEBUG_MODE
            std::cout << "Create Redis channel error: " << redis->errstr << std::endl;
        #endif

        return false;
    }

    // Define Channel For Smartcard 
    redisLibeventAttach(redis, base);

    // Define Process Data From Subsribe Channel
    redisAsyncCommand(redis, functionHandle, (void*)dataPointer, "SUBSCRIBE %s", cChannel);

    event_base_dispatch(base);

    return true;
`

**Comment by michael-grunder** [comment]
> How can I call callback function everytime the message come whether the latest callback function is finished or not

You can't, without doing some kind of multi-threading.  Why does your callback function need to loop forever?  What is it doing?

**Comment by nguyenctu** [comment]
@michael-grunder  Thank you for your response. My company is developing a smart printer. It has 2 programs communicating with each other via Redis channel. The "Main" program will publish command in JSON string format to Redis channel. The "Database" program will listen to that channel to receive command from Main program. Sometime the command could be read a long text file, then the next command may come right after that to tell Database program to do other stuff. I'm ok with multi-threading. But currently I don't know how to implement it in my code.

**Comment by nguyenctu** [comment]
@michael-grunder in case of the while loop, it is a READ DATA command, The Database program will read through a file until it reach the end of the file, then it will move the FILE* to the beginning of the file and then read it again until it receive a STOP command from Main program.  But the callback of STOP command is never called because the latest callback (READ DATA command) is not finish. It like a circular dependency

**Comment by michael-grunder** [comment]
> The Database program will read through a file until it reach the end of the file, then it will move the FILE* to the beginning of the file and then read it again until it receive a STOP command

Why are you continuously re-reading the same file?  Is something else writing to this file?

In general the only way to continue to process `PUBLISH` messages is if your callback returns, meaning you will need to either offload the work to a different thread or make everything completely async (e.g. switch to `AIO` file operations).

If I had more to go on I might be able to provide more specific suggestions.

**Comment by nguyenctu** [comment]
@michael-grunder The file will not change in the printing process but I have to re-reading it over and over until I got a STOP command. Currently that's the way the system is designed so...I can't change it haha. I create new thread for reading data in callback function and now everything work quite well. Thank you for your support.
