### ISSUE TITLE
crash in realloc

### ISSUE THREAD

**Issue by Miner-Sty** [redis/hiredis#1023]
I'm using version 1.0.0-rc1. While I using redisCommand in my program, it crash at realloc, but no memory leak.
I create a instance at the beginning, and use in my thread. At the start everything runs fine. After a while, it crashes. The log is
````
E20211126 21:14:56.868310  7498 main.cpp:59] PC: @     0x7f5bb0ac9f7a (unknown)
E20211126 21:14:56.868525  7498 main.cpp:59] *** SIGSEGV (@0x0) received by PID 6004 (TID 0x7f56de78c700) from PID 0; stack trace: ***
***
E20211126 21:14:56.871718  7498 main.cpp:59]     @     0x7f5bb2a9b980 (unknown)
E20211126 21:14:56.874267  7498 main.cpp:59]     @     0x7f5bb0ac9f7a (unknown)
E20211126 21:14:56.876819  7498 main.cpp:59]     @     0x7f5bb0accb40 (unknown)
E20211126 21:14:56.879082  7498 main.cpp:59]     @     0x7f5bb0ad00db realloc
)
E20211126 21:14:56.880826  7498 main.cpp:59]     @     0x7f5bb33ede84 hi_realloc
E20211126 21:14:56.882565  7498 main.cpp:59]     @     0x7f5bb33ee382 sdsMakeRoomFor
E20211126 21:14:56.884164  7498 main.cpp:59]     @     0x7f5bb33eea23 sdscatlen
mFor
E20211126 21:14:56.885879  7498 main.cpp:59]     @     0x7f5bb33ed74b redisReaderFeed
E20211126 21:14:56.887501  7498 main.cpp:59]     @     0x7f5bb33e9562 redisBufferRead
E20211126 21:14:56.890071  7498 main.cpp:59]     @     0x7f5bb33e98bb redisGetReply
d
E20211126 21:14:56.892526  7498 main.cpp:59]     @     0x7f5bb33e9ca7 __redisBlockForReply
E20211126 21:14:56.895073  7498 main.cpp:59]     @     0x7f5bb33e9d19 redisvCommand
rReply
E20211126 21:14:56.897799  7498 main.cpp:59]     @     0x7f5bb33e9dd7 redisCommand
rReply
````
Here is my connection.
`bool RedisCli::ConnectDB()
{
    bool           res     = true;
    struct timeval timeout = {1, 500000};

    /* Create redis context */
    m_context = redisConnectWithTimeout(m_redisHost.c_str(), m_redisPort, timeout);
    if (m_context == NULL || m_context->err) {
        if (m_context) {
            fprintf(stderr, "Connection error: %s\n", m_context->errstr);
            redisFree(m_context);
            m_context = NULL;
        }
        else {
            fprintf(stderr, "Connection error: can't allocate redis context\n");
        }
        res = false;
    }
    return res;
}`
And here is my call function
`bool RedisCli::HMGet(const std::string &key, std::map<std::string, std::string> &elements)
{
    if (!isConnected) {
        fprintf(stderr, "redis not connected!\n");
        return false;
    }

    bool res = true;
    m_reply  = (redisReply *)redisCommand(m_context, "HGETALL %s", key.c_str());
    if (m_reply == NULL || m_reply->type == REDIS_REPLY_ERROR) {
        if (m_reply) {
            fprintf(stderr, "redis error: %s\n", m_reply->str);
            freeReplyObject(m_reply);
            m_reply = NULL;
        }
        else {
            fprintf(stderr, "redis error with null m_reply");
        }
        return false;
    }

    if (m_reply->type == REDIS_REPLY_ARRAY) {
        int i = 0;
        for (i = 0; i < m_reply->elements; i += 2) {
            elements[m_reply->element[i]->str] = m_reply->element[i+1]->str;
        }
    }

    freeReplyObject(m_reply);
    m_reply = NULL;
    return res;
}`

**Comment by michael-grunder** [comment]
I'm not sure there's enough information here to say why you're seeing a segfault.

Are you attempting to share a `redisContext` structure across threads?  If so that's likely your issue.

If you can post a complete program that crashes I can help track it down for you.

**Comment by michael-grunder** [comment]
Going to close this since we need more information.
