### ISSUE TITLE
CMake set target property OUTPUT_NAME when building linux static lib.

### ISSUE THREAD

**Issue by timrulebosch** [redis/hiredis#1024]
When using the CMakeLists.txt to build a Linux static library the output filename is `libhiredis_static.a `rather than the normally expected `libhiredis.a`.

That could be adjusted with the following snippet (at the location indicated below):

```
IF(UNIX)
    SET_TARGET_PROPERTIES(hiredis_static
        PROPERTIES
            OUTPUT_NAME hiredis
    )
ENDIF()
```

https://github.com/redis/hiredis/blob/8d31a9290c110b01b18ef5a56b7b6573a67fd65b/CMakeLists.txt#L58

**Comment by bjosv** [comment]
I believe this issue can be closed due to the merged https://github.com/redis/hiredis/pull/1057.

**Comment by timrulebosch** [comment]
Yes, thanks.
