### ISSUE TITLE
list,use llen ,size is 411. but use lrange ,reply->elements=0,why?

### ISSUE THREAD

**Issue by phenix0405** [redis/hiredis#1029]
redisReply *reply;
reply = (redisReply*)redisCommand(m_redis,"LLEN %s", key.c_str());
cout<<"List size is :"<<reply->integer<<endl;
cout<<"======================== "<<endl;
freeReplyObject(reply);

redisReply *reply1;
reply1 = (redisReply*)redisCommand(m_redis,"LRANGE %s %d %d", key.c_str(),0,-1);
cout<<"get list type = "<<reply1->type<<endl;
printf("list elements %zu  %zd   \n",reply1->elements,reply1->elements);
cout<<"======================== "<<endl;
freeReplyObject(reply1);

result:
List size is :411
======================== 
get list type = 2
list elements 0  0   
========================

**Comment by phenix0405** [comment]
reply = (redisReply*)redisCommand(m_redis,"LLEN %s", key.c_str());
    int valueSize = reply->integer;
    cout<<"List size is :"<<reply->integer<<endl;
    cout<<"======================== "<<endl;
    freeReplyObject(reply);

    redisReply *reply1;
    reply1 = (redisReply*)redisCommand(m_redis,"LRANGE %s %d %d", key.c_str(),0,-1);
    cout<<"get list type = "<<reply1->type<<endl;
    printf("elements %zu  %zd   \n",reply1->elements,reply1->elements);
    cout<<"get list elements = "<<reply1->elements<<endl;

**Comment by bjosv** [comment]
`redisCommand()` returns a pointer, so the cast gives faulty results.

**Comment by phenix0405** [comment]
> `redisCommand()` returns a pointer, so the cast gives faulty results.

How to solve this problem，thanks

**Comment by phenix0405** [comment]
> `redisCommand()` returns a pointer, so the cast gives faulty results.

I've used the pointer. The asterisk can't be displayed here.

**Comment by michael-grunder** [comment]
Hi,

I'm not sure I fully understand the question but I took a shot at modifying your program a little bit.  This works for me:

```cpp
#include <stdio.h>
#include <hiredis/hiredis.h>
#include <iostream>

using std::endl;
using std::cout;
using std::string;

int main(void) {
    string key = "mylist";

    redisContext *m_redis = redisConnect("localhost", 6379);
    if (m_redis == NULL) {
        cout << "Error:  Can't connect" << endl;
        exit(1);
    }

    redisReply *reply;
    reply = (redisReply*)redisCommand(m_redis,"LLEN %s", key.c_str());
    if (reply == NULL || m_redis->err) {
        cout << "Error:  Can't send LLEN" << endl;
        exit(1);
    }

    cout <<"List size is :"<< reply->integer << endl;
    cout << "======================== " << endl;
    freeReplyObject(reply);

    redisReply *reply1;
    reply1 = (redisReply*)redisCommand(m_redis,"LRANGE %s %d %d", key.c_str(),0,-1);
    if (reply == NULL || m_redis->err) {
        cout << "Error:  Can't send LRANGE" << endl;
        exit(1);
    }

    cout << "get list type = " << reply1->type << endl;
    printf("list elements %zu %zd \n",reply1->elements,reply1->elements);
    cout << "======================== " << endl;

    freeReplyObject(reply1);
}
```

```bash
❯ redis-cli lrange mylist 0 -1
1) "A"
2) "B"
3) "C"
4) "D"
❯ ./a.out
List size is :4
========================
get list type = 2
list elements 4 4
========================
```

**Comment by phenix0405** [comment]
I replaced ubuntu18 with ubuntu20, the problem has been solved, and the specific reason is unknown

**Comment by han-YYDS** [comment]
I also meet this problem
