### ISSUE TITLE
Carriage returns in strings returned by modules cause Protocol errors

### ISSUE THREAD

**Issue by jeffreylovitz** [redis/hiredis#1032]
Good day,

On RedisGraph, we've observed that returning strings that contain a CRLF sequence causes string parsing to terminate early.
Executing the query:
```
GRAPH.QUERY G "RETURN 'Foo\r\nBar'"
```
Triggers the reply:
```
Error: Protocol error, got "B" as reply type byte
```
The "B" referred to in this error message is the "B" character in "Bar".

This error is observed when using the `RedisModule_ReplyWithSimpleString` API (which types the string as `REDIS_REPLY_STATUS`) and when using the `RedisModule_ReplyWithStringBuffer` API (which types the string as `REDIS_REPLY_STRING`).

Do you have any advice for circumventing this issue?

**Comment by michael-grunder** [comment]
Hi, I will take a look.

**Comment by jeffreylovitz** [comment]
You are correct, sorry! I replaced one instance of `RedisModule_ReplyWithSimpleString` in our code, but missed a second one.

Everything works as intended with this change.
