### ISSUE TITLE
Strange thing in Sub in Hireredis

### ISSUE THREAD

**Issue by abhit011** [redis/hiredis#1035]
I am facing a strange issue , i have been trying to subscribe using this portion of code in my process

```c++
 pRedisAsyncForDeviceCmds = redisAsyncConnect(ipAddress, redisPort);
if (pRedisAsyncForDeviceCmds == NULL || pRedisAsyncForDeviceCmds->err) {
	if (pRedisAsyncForDeviceCmds) {
		printf("Connection error  %s\n", pRedisAsyncForDeviceCmds->errstr);
	}
	else {
		printf("Connection error can't allocate redis context\n");
	}
}

this->m_Port = redisPort;
sprintf(&m_RedisChannel[12], "%04d", this->m_Port);
pBaseEventForDeviceCommands = event_base_new();
redisLibeventAttach(pRedisAsyncForDeviceCmds, pBaseEventForDeviceCommands);
redisAsyncSetConnectCallback(pRedisAsyncForDeviceCmds,
							connectAsyncCallbackForGPRSCommands);
redisAsyncSetDisconnectCallback(pRedisAsyncForDeviceCmds,
							disconnectAsyncCallbackForGPRSCommands);
redisAsyncCommand(pRedisAsyncForDeviceCmds,
					onSubMsgRecved,
					(char *)"sub", "SUBSCRIBE  foo");

event_base_dispatch(pBaseEventForDeviceCommands);
return; 
```

and when the control comes to onSubMsgRecved , the whole redisReply * r = (redisReply *)reply; is garbage , where as when i debugged the redisAsyncContext * c there i could see the the message in this (((c)->c).reader)->buf ... but why the data is garbage in reply ....

**Comment by abhit011** [comment]
![gitbug](https://user-images.githubusercontent.com/10906885/147813444-3ca35a73-a3ff-4d3d-881d-5769346f8067.jpg)

**Comment by michael-grunder** [comment]
It's hard to say without a small working example that I can test.

I can only suggest doing the normal things like running your program under valgrind, etc.

**Comment by michael-grunder** [comment]
I'm going to close this since there's not enough information to assist and is unlikely a bug in hiredis.

Happy to help however if you post a complete example I can debug.
