### ISSUE TITLE
async disconnect callback not called if no prior read or write commands

### ISSUE THREAD

**Issue by alanyst** [redis/hiredis#104]
I was testing a simple async connect/disconnect scenario with a disconnect callback but the callback was not being invoked as expected despite a successful connection.

Sample code:

``` c
    redisAsyncContext *rac = redisAsyncConnect(app_args.redis_host, app_args.redis_port);
    if (rac->err)
    {
        fprintf(stderr, "ERROR: Cannot connect to Redis at %s:%d\n", app_args.redis_host, app_args.redis_port);
        exit(1);
    }
    else
    {
        redisAsyncSetDisconnectCallback(rac, redis_disconnect_callback);
        printf("Connected to Redis at %s:%d\n", app_args.redis_host, app_args.redis_port);
        redisAsyncDisconnect(rac);  // <--- This does not trigger the callback
    }
```

The problem is that `redisAsyncInitialize` explicitly unsets `REDIS_CONNECTED` from the `flags` field, but `__redisAsyncFree` (which triggers the disconnect callback) requires `REDIS_CONNECTED` to be set in order to trigger it.  In order for `REDIS_CONNECTED` to be set after connection, a read or write command has to be sent.

Possible ways of resolving this:
- Treat this as intended but insufficiently documented behavior, and modify README to explicitly note that the disconnect callback will only trigger if read or write commands have been issued.
- Remove the condition on `REDIS_CONNECTED` in `__redisAsyncFree` so the callback will be triggered whether that flag is set or not.
- Modify `__redisAsyncFree` so that if `REDIS_CONNECTED` is not set, some other check is done to see if there actually is a connection established, and if so then trigger the callback.

**Comment by michael-grunder** [comment]
Closing this very old issue.
