### ISSUE TITLE
FUCK YOU. Why do you define close() as macros?

### ISSUE THREAD

**Issue by tearosccebe** [redis/hiredis#1049]
If you guys do not know how to write programs. Delete your repository. Stop polluting the open source community.

https://github.com/redis/hiredis/blob/master/sockcompat.h

It is common for C++ users to use close as methods.

https://github.com/tearosccebe/fast_io/blob/b6789ea08596d2873208b5d5ccba4c2709efcb1a/include/fast_io_hosted/platforms/win32.h#L1036

FUCK YOU!

**Comment by carlosabalde** [comment]
@hernanat, thanks for put words to what many of us though!

**Comment by tearosccebe** [comment]
> you could have said nothing and gone about your day, but instead you chose to be a major asshole. if you don't like something, don't use it. better yet, write your own if you're so knowledgeable :)

I do not use this at all. The issue is that someone else uses both this and my library which screws up my library.

It is your fault. Not mine.
