### ISSUE TITLE
Redisconnect and rediscommand encapsulation or direct call problems

### ISSUE THREAD

**Issue by 3293895182** [redis/hiredis#1052]
问题：如果不封装函数，向redis写入接口不报错，但是redis中没有数据，如果封装函数，部分能写进去，但带%的语句写不进去
![image](https://user-images.githubusercontent.com/58204505/159116094-c593b2c8-eaa2-47b2-85d4-e777a9b5c781.png)
![image](https://user-images.githubusercontent.com/58204505/159116113-b872d80e-3454-4df8-adea-9382382afe49.png)
![image](https://user-images.githubusercontent.com/58204505/159116154-5fd66588-15de-4497-8b6d-beb1b1775808.png)
![image](https://user-images.githubusercontent.com/58204505/159116197-cf49dceb-4039-4868-949c-e4e245cb99c7.png)

**Comment by bjosv** [comment]
I have no clue, but as a hint you can check `s_context->err` and log `s_context->errstr` after the failure. This might give you some help.

**Comment by michael-grunder** [comment]
It's not really possible to give a definitive answer to the question as we don't have enough context.  It may however be related to the threading issue in your other question.

Closing this issue
