### ISSUE TITLE
hiredis_ssl arbitrary System Error: "Connection error: System error"

### ISSUE THREAD

**Issue by DaveLanday** [redis/hiredis#1056]
Hi, my application relies on another library (IBM CPLEX static libs) in addition to `hiredis` and `hiredis_ssl` in order to connect to an AWS Elasticache redis server (cluster mode is not enabled presently) and use the data.

The cplex portion of my code (not relevant here I don't think) and the hiredis/hiredis_ssl portion of the code are independent of one another. I simply added the cplex bits into the [minimal example](https://github.com/redis/hiredis/blob/master/examples/example-ssl.c) for hiredis_ssl taken from the repo examples folder. They also rely on the same shared libs (`-lm -lpthread -ldl`)
the only difference being hiredis_ssl's dependence on `-lssl -lcrypto`.

 Independently, both portions of the code run fine (  I can do my cplexy things and also successfully get a "PONG" back from the Elastcache redis server etc...), However, when  I combine both portions in the same .cpp file, the program no longer can connect to redis and  I get the following (extremely non descript) error:

`Connection error: System error`

I am doing a multi stage build in docker and I install hiredis in the following way:

```
# Install hiredis dependencies:
RUN git clone https://github.com/redis/hiredis.git --depth 1 && \
	cd hiredis && \
	make USE_SSL=1 PREFIX=/usr/ install && \	
	ldconfig
```

I then install cplex using an installation that I own and then running my make file to build my own application. The relevant portion of my make file looks like this:

```
#compiler
CXX		:= g++
#compiler flags -ggdb is for debugging
CXX_FLAGS	:= -std=c++17 

#define the folders
BIN			:= ./app/bin
SRC			:= ./app/src
INCLUDE		:= ./app/include
LIBRARIES	:= ./app/lib
HIR_INC     := /usr/include/
HIR_LIB     := /usr/lib/

#name of executables
EXECUTABLES := $(BIN)/ssl_cplex_test 

#define paths to CPLEX libs:
CONCERT_LIB	:= /app/CPLEX/CPLEX_Studio201/concert/lib/x86-64_linux/static_pic
CONCERT_INC	:= /app/CPLEX/CPLEX_Studio201/concert/include

CPLEX_LIB	:= /app/CPLEX/CPLEX_Studio201/cplex/lib/x86-64_linux/static_pic
CPLEX_INC	:= /app/CPLEX/CPLEX_Studio201/cplex/include

# the entry points for cleaning are here:
all: $(EXECUTABLES)

$(BIN)/ssl_cplex_test: $(SRC)/ssl_cplex_test.cpp
	$(CXX) $(CXX_FLAGS) $^ -I$(INCLUDE) -I$(CPLEX_INC) -I$(CONCERT_INC) -I$(HIR_INC) -L$(HIR_LIB) -DIL_STD -L$(CPLEX_LIB) -L$(CONCERT_LIB) -L$(LIBRARIES) -lilocplex -lconcert -lcplex -lhiredis -lhiredis_ssl -lssl -lcrypto -lm -lpthread -ldl -o $@ 

clean:
	-rm -rf $(BIN)/*
```

The program fails at this point:
```
if (c == NULL || c->err) {
        if (c) {
            printf("Connection error: %s\n", c->errstr);
            redisFree(c);
        } else {
            printf("Connection error: can't allocate redis context\n");
        }
        exit(1);
    }
```
where `c->errstr` returns `Connection error: System error`.
What would be causing the connection to fail with a System error?

**Comment by michael-grunder** [comment]
Interesting, as it's failing before the program attempts to negotiate the TLS handshake.

Are you able to step into `redisConnectWithOptions` to see exactly which call is failing?  I honestly don't know off the top of my head what `strerror(errno)` would return `System error`.

**Comment by DaveLanday** [comment]
Thank you for the reply @michael-grunder. So, I discovered that the team I am working with did switch the Elasticache redis server to "cluster mode enabled", so it probably won't be possible to get to the bottom of your first point (at this time, gotta move forward). But, I ended up switching to the [hiredis-cluster](https://github.com/Nordix/hiredis-cluster) package and can now connect and send commands with SSL/TLS enabled. On the flip-side, CPLEX will not run after I test the connection to redis. I wonder if I am just compiling things out-of-order or am just missing dependencies because both parts of the code work independently. I guess I will close this for now, but please reach out if you ever ponder this further.

**Comment by DaveLanday** [comment]
Hi @michael-grunder, I may reopen this as I am still seeing this error even after switching to the hiredis-cluster library (hiredis and hiredis_ssl are dependencies). I am fairly new to C/C++ How would I go about stepping through `redisConnectWithOptions` ?

**Comment by michael-grunder** [comment]
Sure, happy to help.

What I would do is run the program under `gdb` and step through the program to figure out exactly what call inside hiredis is failing.

I'll post more detail about exactly how to do that when I'm back at a computer.

**Comment by DaveLanday** [comment]
Hi @michael-grunder, ok I will look into `gdb`. I will run this in my build docker image. Sorry I was winding down for the day when I saw this response, but very much appreciate it!

**Comment by DaveLanday** [comment]
> Hi @michael-grunder, ok I will look into `gdb`. I will run this in my build docker image. Sorry I was winding down for the day when I saw this response, but very much appreciate it!

Additionally, will there be issues building in a `debian:buster-slim` docker build image, and copying to a`busybox:glibc` image? I have tried copying the required shared libraries to the same paths from the debian image to the busybox one, but this could be where my issue lies?

**Comment by michael-grunder** [comment]
> Additionally, will there be issues building in a debian:buster-slim docker build image, and copying to abusybox:glibc image?

This is actually a somewhat complicated question to answer.  The main issue to pay attention to is that you cannot run compiled code on a system with an older version of GLIBC than the code was compiled with, including the dependencies. 

>  I have tried copying the required shared libraries to the same paths from the debian image to the busybox one, but this could be where my issue lies

I can't say if this is your issue, but it certainly could be.  Instead of manually copying the dependencies why not install them via a package manager on the destination machine.  This should avoid issues you may encounter.

**Comment by DaveLanday** [comment]
hi @michael-grunder. Thank you again for the reply. it could very well be version conflicts with glibc, although all of the shared libraries seem to be the same between the glibc version of busybox and the debian:buster-slim image. The upside of busybox is the lightweight size. The downside is that there is no designated package manager out of the box, so that is why I resorted to copy/pasta of the libraries. I will try to see if anyone has done this.

I was able to get it to work when I use another debian:buster-slim image as my run-time. But again, I was hoping I could run it in a smaller run-time image.

**Comment by michael-grunder** [comment]
I wasn't very familiar with busybox but after looking into it I think this is likely your issue.

[Relevant SO question](https://stackoverflow.com/questions/55930279/how-to-build-a-docker-build-file-that-can-run-my-c-program-in-busybox)

As mentioned in that linked question, you may want to go with building a static binary, with your code and all of the required dependencies.  How hard this will be depends on what dependencies you're using.

It's quite easy to statically include hiredis as we build a `libhiredis.a` archive file.  I know `gcc` also has utilities to statically link the C++ standard library.

**Comment by DaveLanday** [comment]
Hi @michael-grunder, thank you again for the extra investigative work. Yes, I have been using the static libs for hiredis, hiredis_ssl, and hiredis-cluster. I am also using the static libs that come with the installation of CPLEX as well. The only shared dependencies are the following
```
# CPLEX (from static libs): 
linux-vdso.so.1 
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 
/lib64/ld-linux-x86-64.so.2 
______
# hiredis-cluster + hiredis (from static libraries): 
linux-vdso.so.1 
libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 
libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 
/lib64/ld-linux-x86-64.so.2 
```
When I `--static` compile, I still get that arbitrary `System error`, but it could be as the Relevant SO question you posted says. I have read that `-lpthread` does not play nicely with static compilation? In any case, do you reckon I should close this for now? I mean, I did get it to work in a debian image.

**Comment by michael-grunder** [comment]
Sure, you can close the issue as it doesn't appear to be a bug in hiredis.

If you need to run the binary on a busybox instance you may want to build it in a busybox container.

**Comment by DaveLanday** [comment]
Ok, may be hard to do but it might be worth a shot as the size of the run-time image will also affect where I can run it.

Thank you again @michael-grunder !
