### ISSUE TITLE
Subscribe REDIS channel with raw command by using redisFormatCommand (pub/sub)

### ISSUE THREAD

**Issue by ryanmusic** [redis/hiredis#1075]
Hi! I would like to know if it's reliable to use pub/sub with Redis by using Redis raw command with redisFormatCommand. The reason is because I have to create my own tls client:

len = redisFormatCommand(&str, "SUBSCRIBE %s", channel)

tlsClient->send(str, len)

I asked this because recently I'm seeing some delay or missing subscribed messages when the channel subscription scale is increased. Not sure if this is the right way to subscribe channel, please advice and thanks!

**Comment by michael-grunder** [comment]
Closing this old issue, but happy to help if you still have questions.

**Comment by kyang-ns** [comment]
Hi @michael-grunder , yes I would still love to know the answer for this. Thanks.

**Comment by michael-grunder** [comment]
> Hi! I would like to know if it's reliable to use pub/sub with Redis by using Redis raw command with redisFormatCommand. The reason is because I have to create my own tls client:

If you're using synchronous hiredis there should be no difference between sending a formatted command via `redisFormatCommand` or normally via `redisCommand`.  The only place where hiredis executes specific logic for pubsub is in async mode.

> I asked this because recently I'm seeing some delay or missing subscribed messages when the channel subscription scale is increased. 

I wouldn't expect this to have anything to do with how you're sending the command.  If you could provide a small example program of what you're doing I could take a look though.
