### ISSUE TITLE
redisCommand Get error

### ISSUE THREAD

**Issue by joung** [redis/hiredis#1081]
![image](https://user-images.githubusercontent.com/7401458/182874031-746e7f5c-c1bf-44e5-9898-1259bba85455.png)
 reply = (redisReply *)redisCommand(this->redisHandle, "GET %s", key.c_str());

hiredis version: hiredis-1.0.2.tar.gz 

use hiredis-1.0.0.tar.gz  code run success!

**Comment by michael-grunder** [comment]
There's not enough to go on here to be of any help.  It seems highly unlikely Hiredis is failing to process a simple string reply.  More likely there is some memory corruption happening elsewhere in the program.

If you can put together a small program that reproduces the issue I'm happy to take a look.  If that's not possible I would suggest running your program under valgrind to verify there aren't any invalid memory reads/writes occurring.

**Comment by joung** [comment]
Thank you. I will check the memory problem by myself.  The results will be updated in time.
