### ISSUE TITLE
Change of redisConnectCallback breaks legacy code

### ISSUE THREAD

**Issue by sewenew** [redis/hiredis#1086]
[This commit](https://github.com/redis/hiredis/commit/f69fac7690fb22a7fc19dba61ef70e5f79ccb2e9) drops `const` on `redisAsyncContext` in `redisConnectCallback`, and breaks legacy code:

```
// Legacy code:

void connect_callback(const redisAsyncContext *ctx, int status) {}

redisAsyncSetConnectCallback(ctx, connect_callback);
```

Error message:

```
error: invalid conversion from 'void (*)(const redisAsyncContext*, int)' to 'void (*)(redisAsyncContext*, int)' [-fpermissive]
```

Can you keep the original API, and define a new API for this purpose, i.e. dropping `const` for `redisAsyncContext`?

Regards

**Comment by michael-grunder** [comment]
Good catch, we really can't change this until a major release.  I should be able to get something up this weekend

**Comment by michael-grunder** [comment]
I'm going to go through the changes in more detail but I think I've got this sorted.

@sewnew does this solve your backward compatibility issue?

@kristjanvalur I reworked your `onConnect` improvements to maintain backward compatibility with existing code.  Let me know if my changes have broken any semantics.

**Comment by sewenew** [comment]
Great! I tested the code, and it works! Thanks!

B.T.W I also added some comment for the changes.

Regards

**Comment by kristjanvalur** [comment]
Hi there.  
When I did the original patch last year, the argument wasnt `const` at all.  I think the const modifier must have been added recently so removing the `const` was a change that I made recently.   Didn't realize that it was a breaking change.
But the change looks fine.  Thanks for fixing this.
