### ISSUE TITLE
Where is type aeEventLoop defined ? 

### ISSUE THREAD

**Issue by iamalinaji** [redis/hiredis#1111]
In file "ae.h" in adapters folder, there is a struct redisAeEvents and here is its code:
`typedef struct redisAeEvents {
    redisAsyncContext *context;
    aeEventLoop *loop;
    int fd;
    int reading, writing;
} redisAeEvents;`
I don't understand the type aeEventLoop and I searched the whole repository and I didn't find a definition for it. I appreciate it if you would help me understand what is it and what's its definition ?

**Comment by michael-grunder** [comment]
I'm not sure I follow the question, as that is the definition.

https://github.com/redis/hiredis/blob/5392adc26515e4ac26ebd612eb88282bdb23a1a4/adapters/ae.h#L38-L43

**Comment by michael-grunder** [comment]
Closing this issue, but I'm happy to answer any questions you have about `redisAeEvents` struct

**Comment by michael-grunder** [comment]
Does this answer your question?

**Comment by iamalinaji** [comment]
Hi there :)
Thanks for your assistance 
I understand that we have type "redisAeEvents" but I don't understand what aeEventloop is?
Maybe you meant : `typedef struct redisAeEvents aeEventloop` ??
