### ISSUE TITLE
redisReply->elements = 0,but it actually has content

### ISSUE THREAD

**Issue by templiang** [redis/hiredis#1114]
# Bug report

When I use RPUSH to sent data and BLPOP to receive data,encountered an errorre ,disReply->elements = 0,but it actually has content

## Steps to Reproduce

I want to use the hiredis to transfer data between two node.In the receiver,I open up multiple threads to block waiting to receive data from the sender.I made sure the data was successfully filled in at the sender,but there is an error in the receiver.
error:

```bash
reply->elements = 0, ERROR
```

``` c++
//sender
redisContext *_coordinatorCtxconn  = redisConnect("receiverIP",6379);
char cmd[]="hello world\n";
redisReply* reply;
int cmdoffset = strlen(cmd);
redisAppendCommand(_coordinatorCtx, "RPUSH dr_request_t %b", cmd, cmdoffset);
redisGetReply(_coordinatorCtx, (void**)&reply); // send "dr_request_t"
freeReplyObject(reply);
```

``` c++
//receiver
redisContext *_coordinatorCtxconn  = redisConnect("127.0.0.1",6379);
while (true) {
        if (COORDINATOR_DEBUG) cout << "waiting for requests ..." << endl;
        /* Redis command: BLPOP (LISTNAME1) [LISTNAME2 ...] TIMEOUT */
        reply = (redisReply*)redisCommand(rContext, "BLPOP dr_request_t 100"); // [0]
        if (reply->type == REDIS_REPLY_NIL) {
            cerr << __func__ << " empty queue " << endl;
            freeReplyObject(reply);
            continue;
        } else if (reply->type == REDIS_REPLY_ERROR) {
            cerr << __func__ << " ERROR happens " << endl;
            freeReplyObject(reply);
            continue;
        } else {
            if((int)reply->elements == 0) {
                cerr << __func__ << " reply->elements = 0, ERROR " << endl;
                continue;
            }
            
            //
            //
        }
}
```

I tried to write a test program ，where the data could be successfully received.

```bash
type:2
elements:2
element[0]:dr_request_t
element[1]:hello world
element[1]:hello world
```

```c++
//test code
#include <stdio.h>
#include <hiredis/hiredis.h>
#include <string>
#include <string.h>
int main(){

    redisReply *reply;
    redisContext *conn  = redisConnect("127.0.0.1",6379);
    if(conn != NULL && conn->err)
    {
        printf("connection error: %s\n",conn->errstr);
        return 0;
    }      
    reply =(redisReply*)redisCommand(conn, "BLPOP dr_request_t 100");
    printf("type:%d\n",(int)reply->type);
    printf("elements:%d\n",(int)reply->elements);
    for(int i=0;i<reply->elements;++i){
        printf("element[%d]:%s\n",i,reply->element[i]->str);
    }
    printf("element[%d]:%s\n",1,reply->element[1]->str);
    freeReplyObject(reply);
    redisFree(conn);
    return 0;
}
```

I want to know how this problem should be solved

**Comment by michael-grunder** [comment]
Are you sharing your `redisContext` structures between threads?  That could be the issue as the struct isn't threadsafe.

**Comment by templiang** [comment]
I've changed it to a single thread and requested `redisContext` resources from within that thread

**Comment by templiang** [comment]
Thank you for your answer.I requested  `redisContext`  from within  each thread separately.I've tried to changed it to a single thread,but the problem is still there.

**Comment by templiang** [comment]
> Are you sharing your `redisContext` structures between threads? That could be the issue as the struct isn't threadsafe.

Thank you for your answer.I requested redisContext from within each thread separately.I've tried to changed it to a single thread,but the problem is still there.

**Comment by templiang** [comment]
I‘ve tried to simultaneously start the test and receiver processes in receiver node to listen for the `dr_request_t`.On the other side, the sender sended `dr_request_t` to the receiver node.
Same error occured `redisReply->elements = 0` when `dr_request_t`  is received by the receiver process.
It works fine,When  `dr_request_t`   is received by the test process.
very odd problem.

**Comment by michael-grunder** [comment]
> Same error redisReply->elements = 0 occured when dr_request_t is received by the receiver process.

`reply->elements` can be zero for a variety of reply types.

You might check it when you get zero elements but not a `NIL` or `ERROR` reply.
```c
        if (reply->type == REDIS_REPLY_NIL) {
            /* ... */
        } else if (reply->type == REDIS_REPLY_ERROR) {
            /* ... */
        } else {
            /* NOTE: Perhaps print the `reply->type` here */
            if((int)reply->elements == 0) {
                cerr << __func__ << " reply->elements = 0, ERROR " << endl;
                continue;
            }
```

Other than that it's hard to say for sure what the issue might be without being able to replicate it.

You can always try running your program under `valgrind` and see if it reports any memory corruption.  Additionally, you could step through the program with `gdb` or `rr` to get a better idea about where the issue originates.

**Comment by michael-grunder** [comment]
I'm going to close this issue, since it's unlikely a bug in hiredis but if you can provide an example to replicate the problem I'm happy to help track it down.

**Comment by templiang** [comment]
> I'm going to close this issue, since it's unlikely a bug in hiredis but if you can provide an example to replicate the problem I'm happy to help track it down.

Thank you very much for your answer. The problem has been solved,which reason is that the static library does not match the header file version.
