### ISSUE TITLE
How to select different db execution "keys *"

### ISSUE THREAD

**Issue by YuanlvCold** [redis/hiredis#1120]
```c
redisReply * _reply;

 _reply = (redisReply*)redisCommand(_redisCxt, "select 1");
 _reply = (redisReply*)redisCommand(_redisCxt, "keys *");

if (_reply->type == REDIS_REPLY_ARRAY){
        for (int i = 0; i < _reply->elements; ++i){
             _reply->element[i]->str;
        }
}
```
question：
The keys I got are all in the database db0.
I need to select different db to get all keys at the same time, what do I need to do. thanks!

**Comment by bjosv** [comment]
Using `select 1` is the correct way to use tell Redis that the client wants to use logical db 1.
Either the Redis instance has been setup as a cluster node (select is not supported in cluster mode) or there are other errors.
One suggestion in to make sure the first `redisCommand(select 1)` results in a non-null reply, and is of type `REDIS_REPLY_STATUS` and str is `OK`.

**Comment by michael-grunder** [comment]
As @bjosv says, you should check to make sure the `SELECT` command is not returning an error.

```c
#include <hiredis/hiredis.h>
#include <string.h>
#include <assert.h>

#include <hiredis/hiredis.h>
#include <string.h>
#include <assert.h>

int main(void) {
    redisContext *_redisCtx;
    redisReply *_reply;

    _redisCtx = (redisContext*)redisConnect("localhost", 6379);
    assert(_redisCtx != NULL && _redisCtx->err == 0);

    _reply = (redisReply*)redisCommand(_redisCtx, "select 1");
    assert(_reply != NULL && _reply->type == REDIS_REPLY_STATUS &&
           _reply->len == 2 && !strcmp(_reply->str, "OK"));
    freeReplyObject(_reply);

    _reply = (redisReply*)redisCommand(_redisCtx, "keys *");
    assert(_reply != NULL && _reply->type == REDIS_REPLY_ARRAY);

    for (size_t i = 0; i < _reply->elements; i++) {
        assert(_reply->element[i]->type == REDIS_REPLY_STRING);
        printf("KEY[%zu]: %s\n", i, _reply->element[i]->str);
    }

    freeReplyObject(_reply);
    redisFree(_redisCtx);
}
```

Cluster mode being enabled is the most likely issue (as it disables database numbers) but you can also verify this via `redis-cli`.

I'm going to close this issue since it's unlikely to be a bug in hiredis but I'm happy to help you figure it out. 😄

**Comment by YuanlvCold** [comment]
> Using `select 1` is the correct way to tell Redis that the client wants to use logical db 1. Either the Redis instance has been setup as a cluster node (select is not supported in cluster mode) or there are other errors. One suggestion in to make sure the first `redisCommand(select 1)` results in a non-null reply, and is of type `REDIS_REPLY_STATUS` and str is `OK`.

Your reply solved my problem. Thank you!

**Comment by YuanlvCold** [comment]
Your reply solved my problem. Thanks.
 
std::vector<std::string> _vectDb;
_reply = (redisReply*)redisCommand(_redisCxt, "select %s", _vectDb[x]);
I found reply-->len==43,  

_reply = (redisReply*)redisCommand(_redisCxt, "select %s", _vectDb[x].c_str());
I found reply-->len==2,  

oh, I forget about c_str().
Thanks again！

**Comment by YuanlvCold** [comment]
> As @bjosv says, you should check to make sure the `SELECT` command is not returning an error.
> 
> ```c
> #include <hiredis/hiredis.h>
> #include <string.h>
> #include <assert.h>
> 
> #include <hiredis/hiredis.h>
> #include <string.h>
> #include <assert.h>
> 
> int main(void) {
>     redisContext *_redisCtx;
>     redisReply *_reply;
> 
>     _redisCtx = (redisContext*)redisConnect("localhost", 6379);
>     assert(_redisCtx != NULL && _redisCtx->err == 0);
> 
>     _reply = (redisReply*)redisCommand(_redisCtx, "select 1");
>     assert(_reply != NULL && _reply->type == REDIS_REPLY_STATUS &&
>            _reply->len == 2 && !strcmp(_reply->str, "OK"));
>     freeReplyObject(_reply);
> 
>     _reply = (redisReply*)redisCommand(_redisCtx, "keys *");
>     assert(_reply != NULL && _reply->type == REDIS_REPLY_ARRAY);
> 
>     for (size_t i = 0; i < _reply->elements; i++) {
>         assert(_reply->element[i]->type == REDIS_REPLY_STRING);
>         printf("KEY[%zu]: %s\n", i, _reply->element[i]->str);
>     }
> 
>     freeReplyObject(_reply);
>     redisFree(_redisCtx);
> }
> ```
> 
> Cluster mode being enabled is the most likely issue (as it disables database numbers) but you can also verify this via `redis-cli`.
> 
> I'm going to close this issue since it's unlikely to be a bug in hiredis but I'm happy to help you figure it out. 😄

Through the example you gave, I checked my code and found that reply->len==43, when "select %s", a vector parameter value forgot to convert to c_str(). Thanks you!

**Comment by YuanlvCold** [comment]
> As @bjosv says, you should check to make sure the `SELECT` command is not returning an error.
> 
> ```c
> #include <hiredis/hiredis.h>
> #include <string.h>
> #include <assert.h>
> 
> #include <hiredis/hiredis.h>
> #include <string.h>
> #include <assert.h>
> 
> int main(void) {
>     redisContext *_redisCtx;
>     redisReply *_reply;
> 
>     _redisCtx = (redisContext*)redisConnect("localhost", 6379);
>     assert(_redisCtx != NULL && _redisCtx->err == 0);
> 
>     _reply = (redisReply*)redisCommand(_redisCtx, "select 1");
>     assert(_reply != NULL && _reply->type == REDIS_REPLY_STATUS &&
>            _reply->len == 2 && !strcmp(_reply->str, "OK"));
>     freeReplyObject(_reply);
> 
>     _reply = (redisReply*)redisCommand(_redisCtx, "keys *");
>     assert(_reply != NULL && _reply->type == REDIS_REPLY_ARRAY);
> 
>     for (size_t i = 0; i < _reply->elements; i++) {
>         assert(_reply->element[i]->type == REDIS_REPLY_STRING);
>         printf("KEY[%zu]: %s\n", i, _reply->element[i]->str);
>     }
> 
>     freeReplyObject(_reply);
>     redisFree(_redisCtx);
> }
> ```
> 
> Cluster mode being enabled is the most likely issue (as it disables database numbers) but you can also verify this via `redis-cli`.
> 
> I'm going to close this issue since it's unlikely to be a bug in hiredis but I'm happy to help you figure it out. 😄

Through the example you gave, I checked my code and found that reply->len==43, when "select %s", a vector parameter value forgot to convert to c_str(). Thanks!

**Comment by YuanlvCold** [comment]
> As @bjosv says, you should check to make sure the `SELECT` command is not returning an error.
> 
> ```c
> #include <hiredis/hiredis.h>
> #include <string.h>
> #include <assert.h>
> 
> #include <hiredis/hiredis.h>
> #include <string.h>
> #include <assert.h>
> 
> int main(void) {
>     redisContext *_redisCtx;
>     redisReply *_reply;
> 
>     _redisCtx = (redisContext*)redisConnect("localhost", 6379);
>     assert(_redisCtx != NULL && _redisCtx->err == 0);
> 
>     _reply = (redisReply*)redisCommand(_redisCtx, "select 1");
>     assert(_reply != NULL && _reply->type == REDIS_REPLY_STATUS &&
>            _reply->len == 2 && !strcmp(_reply->str, "OK"));
>     freeReplyObject(_reply);
> 
>     _reply = (redisReply*)redisCommand(_redisCtx, "keys *");
>     assert(_reply != NULL && _reply->type == REDIS_REPLY_ARRAY);
> 
>     for (size_t i = 0; i < _reply->elements; i++) {
>         assert(_reply->element[i]->type == REDIS_REPLY_STRING);
>         printf("KEY[%zu]: %s\n", i, _reply->element[i]->str);
>     }
> 
>     freeReplyObject(_reply);
>     redisFree(_redisCtx);
> }
> ```
> 
> Cluster mode being enabled is the most likely issue (as it disables database numbers) but you can also verify this via `redis-cli`.
> 
> I'm going to close this issue since it's unlikely to be a bug in hiredis but I'm happy to help you figure it out. 😄

Through the example you gave, I checked my code and found that reply->len==43, when "select %s", a vector parameter value forgot to convert to c_str(). Thank you!
