### ISSUE TITLE
Mingw cross compilation error

### ISSUE THREAD

**Issue by bit0fun** [redis/hiredis#1126]
I'm working on cross compiling hiredis on linux to windows with mingw, and found that in [sockcompat.h:53](https://github.com/redis/hiredis/blob/master/sockcompat.h#L53), mingw will fail compilation due to Mstcpip.h not being found

Simply changing this to mstcpip.h, compilation succeeds on the master branch without issue. 
I didn't want to create a pull request for this change before creating an issue, because I'm not sure if this would affect anything else. 

I'm assuming that given windows doesn't care about case for file names that this would not be a problem, but I don't have a development environment for windows to test this out.

**Comment by michael-grunder** [comment]
Feel free to open a PR and I'll authorize a CI run.

As you said, it's probably fine as Windows is case-insensitive when it comes to filenames.

**Comment by bit0fun** [comment]
It's such a small change I doubt it would be an issue, but just wanted to check first

Thanks for the quick response! Give me a few and I'll make the pr
