### ISSUE TITLE
Using hiredis to write Nginx c module

### ISSUE THREAD

**Issue by bnchdan** [redis/hiredis#1129]
Is someone where that ussed hiredis to write an Nginx module?
My problem is that when I am trying to get a value of a key the reply-> str is null. Set works fine, also if the response is integer ( for example hexist the reply-> integer is correct )

```
....
 static ngx_handler(ngx_http_request_t *r) {
....
    redisContext *c;
    redisReply *reply;
    c = redisConnect( "127.0.0.1", 6379 );
   
    if (c == NULL || c->err) {
        ngx_log_error(NGX_LOG_ERR, r->connection->log, 0, "error to connect to redis",  reply->len );
        return NGX_DECLINED;
    }
    reply = redisCommand(c,"GET something"); 
    ngx_log_error(NGX_LOG_ERR, r->connection->log, 0, "reply->len=%d",  reply->len );
    ngx_log_error(NGX_LOG_ERR, r->connection->log, 0, "reply->type=%d",  reply->type );

    if (reply-> str ){
        ngx_log_error(NGX_LOG_ERR, r->connection->log, 0, "reply->str = %s", reply->str);
    }else{
        ngx_log_error(NGX_LOG_ERR, r->connection->log, 0,  "reply-> str is null"); 
    }


    freeReplyObject(reply);
    redisFree(c);
...
}
...
```
the ouput is : 
```
reply->len= 1835749360
reply->type =1 
reply->str is null
```

**Comment by michael-grunder** [comment]
It's difficult to say without more information.

You aren't testing the context for an error case after your call to `redisCommand`, although normally if there were an error the `reply` itself would be NULL.

I really only have general suggestions such as running your program via `gdb` or another debugger, to try and narrow down where things are going wrong.  You can also try running your program via `valgrind` to see if there are any reported memory errors.

**Comment by michael-grunder** [comment]
I'm going to close this issue, as the likelihood that hiredis can't perform a `GET` operation is quite low :smile:

If you provide more context, however, I'm still happy to help.

**Comment by bnchdan** [comment]
HI, @michael-grunder thanks for your response,
I knew that hiredis can perform GET operations. The examples work fine. (https://github.com/redis/hiredis/blob/master/examples/example.c ). 

I don't know exactly how can i run Nginx with gdp or valgrind. 

Currently, I solve the problem by just sending an RESP message on port 8379 ( https://github.com/bnchdan/c2redis ) and processing the response. I just need to GET, SET and INCR a key.
