### ISSUE TITLE
Segmentation Violation when redisCommand is given a NULL for an expected argument

### ISSUE THREAD

**Issue by savincen** [redis/hiredis#1141]
When using redisCommand and providing NULL for an expected argument, you can encounter a segmentation violation when hiredis attempts to use strlen on a NULL pointer.  For example, when executing:

    reply = redisCommand( ctx, "DEL %s", key );

and key is NULL, then a segv occurs when attempting to determine the length of the key that is NULL.  I have put checks for NULL in my code that prevent me from calling redisCommand with a NULL argument.  However, I thought I should mention it in case this is something that you want to address in hiredis.

SIGSEGV(0x1) - Segmentation violation.
[2460] at 0x00007FFFF7223721 libc:__strlen_sse2_pminub (+0x11)
> where 6
  1* In routine libc:__strlen_sse2_pminub (+0x11)
  2  Called from libhiredis:\hiredis\redisvFormatCommand 364 (+0x3)
  3  Called from libhiredis:\hiredis\redisvAppendCommand 1102 (+0x5)
  4  Called from libhiredis:\hiredis\redisvCommand 1172
  5  Called from libhiredis:\hiredis\redisCommand 1180
  6  Called from tkredis:\tkredis\deleteKey 1028 (+0x3F1)

**Comment by savincen** [comment]
Btw, if there are places where I neglected to check for valid arguments, where a NULL slips past me and is given to redisCommand, and a segv occurs, then I do have an exception handler that gets control.  I do check for a redisReply and when NULL, I do recreate the connection context in fear that it is bad.  However, when driving the segv as described above using a DEL comand given NULL, and my exception handler gets control, the connection context's err field has been left as zero.  I assume that since my exception handler was forced to handle it, then I can't trust the connection context in this situation even though its err field is zero.  Correct?

**Comment by savincen** [comment]
When I perform an ad hoc test as described above, where the segv occurs, I am able to subsequently use the connection successfully after handling the exception.  I assume the segv redisvFormatCommand occurs in a manner that does not render the connection bad in this test case.  However, I'm reluctant to trust context's err field in a cases where an exception has occurred, even though the connection appears ok in the test case described above.  Comments?

**Comment by michael-grunder** [comment]
Hi @savincen 

I'm not sure this is really a bug.  It's the responsibility of the caller to send non-null values with the `%s` format specifier.

I suppose we could catch the specific example of sending `NULL` for the `%s` specifier, but there are countless other ways to invoke UB with variadic functions.

**Comment by savincen** [comment]
What about my question regarding the connection context?  If I handle exceptions like this, when long-jumping out of the hiredis library, it has the potential of skipping over important hiredis code that it would have run otherwise.  Can the connection context be trusted in cases like this, or must I assume it to be un-trustworthy and re-create the connection?

**Comment by michael-grunder** [comment]
Personally, I'd be quite wary of trying to catch a `SIGSEGV` and do anything _other_ than dump a call stack and exit.

Whether or not the context is fine in that case is impossible to say, because you lose context as to what actually caused it.  It might have been a NULL pointer dereference, but maybe it was an invalid read/write and your stack is now corrupted.

Instead of trying to recover from such situations I would try and make sure they can't occur in the first place.

**Comment by michael-grunder** [comment]
Going to close this issue, since it's not really a bug in hiredis.
