### ISSUE TITLE
SEGV in redisvFormatCommand

### ISSUE THREAD

**Issue by Congyu-Liu** [redis/hiredis#1145]
Our testing tool generates a testing input `HGET 1024 w!%b` for redisvFormatCommand and triggers a segfault. It looks like redisvFormatCommand does not correctly check if the `ap` is empty before accessing it (https://github.com/redis/hiredis/blob/master/hiredis.c#L373). So even a simple "%b" could cause the crash when there is no actual bytes array parameter passed to redisvFormatCommand. This seems to be the same root cause for the issues (#1134, #1142) reported previously.

**Comment by michael-grunder** [comment]
I'm not sure this is a bug that's really fixable in C.

This would also cause a segfault:
```c
printf("%s", (char*)-1);
```
