### ISSUE TITLE
redisCommand invalid conversion from void to redisReply

### ISSUE THREAD

**Issue by fancyshirt** [redis/hiredis#1149]
Hi, I'm very new to use hiredis for my c project and I encountered an issue.
When I tried the very PING PONG code from the example.c, I got the below error:

test_hiredis.c: In function ‘int main()’:
test_hiredis.c:17:22: error: invalid conversion from ‘void*’ to ‘redisReply*’ [-fpermissive]
  reply = redisCommand(c, "PING");
          ~~~~~~~~~~~~^~~~~~~~~~~

When I SET value to the db, it works if I didn't assign the return value to it. Example as follow:
`redisCommand(c, "SET TESTVALUE my_test_value");`
I can see a new variable is created in the redis db by redis-cli.

However, if I want to assign redisCommand() to redisReply point, the above error shows up.

Please help me with this problem. Many thanks.

Here is my code:

    #include <stdlib.h>
    #include "hiredis/hiredis.h"

    int main() {
        redisContext *c = redisConnect("127.0.0.1", 6379);

        if (c != NULL && c->err) {
            printf("Error: %sn", c->errstr);
            redisFree(c);
        } else {
            printf("Connected to Redis\n");
        }

        redisReply *reply;

        reply = redisCommand(c, "PING");
        freeReplyObject(reply);
        return 0;
    }

**Comment by michael-grunder** [comment]
Are you compiling your program with a C++ compiler?  

C has a special rule that `void*` may always be converted to and from any other pointer type, whereas C++ does not.

With a slight change your program will compile as C++:

```patch
diff --git a/test_hiredis.cpp b/test_hiredis.cpp
index 151fa11..fdae710 100644
--- a/test_hiredis.cpp
+++ b/test_hiredis.cpp
@@ -13,7 +13,7 @@ int main() {

     redisReply *reply;

-    reply = redisCommand(c, "PING");
+    reply = (redisReply*)redisCommand(c, "PING");
     freeReplyObject(reply);
     return 0;
 }
```

If you don't intend to compile your program as C++ however, you'll need to change how you are invoking it.  If you're using GCC or clang it should be straightforward:

```bash
gcc -Wall test_hiredis.c -lhiredis
clang -Wall test_hiredis.c -lhiredis
```

I'm not as familiar with MSVC.

**Comment by fancyshirt** [comment]
Thanks for the reply.
I'm working on Ubuntu 18.04. I compile my file as follow:
`gcc -o example example.c -lhiredis`

I updated the code as follows and now I can compile it. But when running, it gets Segmentation fault (core dumped)

    #include <stdlib.h>
    #include "hiredis/hiredis.h"
   
    int main() {
   
        redisContext *c = redisConnect("127.0.0.1", 6379);
   
        if (c != NULL && c->err) {
            printf("Error: %sn", c->errstr);
            redisFree(c);
        } else {
            printf("Connected to Redis\n");
        }
   
        redisReply *reply;
   
        reply = (redisReply*)redisCommand(c, "PING");
        freeReplyObject(reply);
   
        printf("%s\n", reply->str);
        return 0;
    }

**Comment by michael-grunder** [comment]
> I'm working on Ubuntu 18.04. I compile my file as follow:
gcc -o example example.c -lhiredis

If you're compiling your program that way, you really shouldn't need the typecast.  It doesn't hurt anything, it just shouldn't be required in C.

The segfault is probably because you are causing undefined behavior by calling `freeReplyObject(reply)` before accessing the reply structure itself.  

```c
    redisReply *reply;

    reply = (redisReply*)redisCommand(c, "PING");
    
    // You are freeing the memory for `reply` here
    freeReplyObject(reply);

    // Now you are attempting to access `reply->str`
    printf("%s\n", reply->str);
    return 0;
```

Here's a modified program that checks for errors after connecting and then after sending the `PING` command:

```c
#include <stdlib.h>
#include "hiredis/hiredis.h"

int main() {

    redisContext *c = redisConnect("127.0.0.1", 6379);

    // Short circuit if we fail to allocate a redisContext or if it
    // reports an error state.
    if (c == NULL || c->err) {
        fprintf(stderr, "Error:  Couldn't connect to Redis (%s)\n",
                c && c->err ? c->errstr : "Unknown error");
        exit(1);
    }

    printf("Connected...\n");

    redisReply *reply;

    // You really shouldn't need this (redisReply*) typecast in C.
    reply = (redisReply*)redisCommand(c, "PING");

    // Now make sure our reply is not NULL and it is a STATUS reply.
    if (reply == NULL || reply->type != REDIS_REPLY_STATUS) {
        fprintf(stderr, "Error:  NULL or wrong type from PING!\n");
        exit(1);
    }

    // Now you know you have a reply and it's the right type
    printf("Reply: %s\n", reply->str);

    // Clean up memory.
    freeReplyObject(reply);
    redisFree(c);

    return 0;
}
```

**Comment by fancyshirt** [comment]
I tried check the error and move the freeReplyObject function after calling the printf function.
The error remains and it does not even go to the error checking section.

Here is my code:

    #include <stdlib.h>
    #include "hiredis/hiredis.h"
   
    int main() {
   
        redisContext *c = redisConnect("127.0.0.1", 6379);
   
        if (c != NULL && c->err) {
            printf("Error: %sn", c->errstr);
            redisFree(c);
        } else {
            printf("Connected to Redis\n");
        }
   
        redisReply *reply;
   
        reply = (redisReply*)redisCommand(c, "PING");
   
        if (reply == NULL || reply->type != REDIS_REPLY_STATUS) {
            fprintf(stderr, "Error: NULL or wrong type from PING!\n");
        }
   
        printf("%s\n", reply->str);
   
        freeReplyObject(reply);
        redisFree(c);
   
        return 0;
    }

The output:

    root@ubu:/home/ubu/Desktop# gcc -o test_hiredis test_hiredis.c -lhiredis
    root@ubu:/home/ubu/Desktop# ./test_hiredis
    Connected to Redis
    Segmentation fault (core dumped)
    root@ubu:/home/ubu/Desktop#


I wonder if I install hiredis correctly.

How to install hiredis on ubuntu from source code exactly? I installed it by following a youtube tutorial: https://www.youtube.com/watch?v=ECY20JGfLso&ab_channel=CodeSupplement

**Comment by michael-grunder** [comment]
C can be tricky to learn at first.

You can certainly try to reinstall hiredis.  It looks like that video has you copying hiredis source files into your directory, but you're linking with your system hiredis (that's what `-l hiredis` is doing).  This certainly could cause a problem.

Perhaps [this program will work for you](https://gist.github.com/michael-grunder/22e9c821e4e47cd2d1c72f8f3550b921).  You don't need any of hiredis' source files in your project path.  Those will come from your system.

Like the gist says you should be able to compile like so:
```bash
cc -Wall -ocheck-hiredis check_hiredis.c -lhiredis
```

If you get a linker error you will need to install hiredis either by installing it from your package manager or building it from source with:

```bash
git clone https://github.com/redis/hiredis.git && cd hiredis
git checkout v1.1.0 && make clean && make && sudo make install

# You may need to then do this
sudo ldconfig
```

And just so I mention it there is also a logic bug in this part of your program:

```bash
    if (c != NULL && c->err) {
        printf("Error: %sn", c->errstr);
        redisFree(c);
    } else {
        printf("Connected to Redis\n");
    }
```

This will print `Connected to Redis` when `c == NULL`.

**Comment by fancyshirt** [comment]
Hi michael-grunder,

I can't thank you more!

I removed the older installation file (as in the youtube video I mentioned) and used the way you recommended to install the hiredis and now everything works!

It seems like the manually installation method messed up the whole repository for invoking library for hiredis.

Thank you again for the help!

Happy new year, btw!
