### ISSUE TITLE
Linking error with hiredisAllocFns and redisAsyncHandleTimeout

### ISSUE THREAD

**Issue by pedramcode** [redis/hiredis#1152]
I installed the library but when i want to compile my projects linker raise these errors:

`/usr/bin/ld: lib/channels/libchannels.so: undefined reference to 'hiredisAllocFns'
/usr/bin/ld: lib/channels/libchannels.so: undefined reference to 'redisAsyncHandleTimeout'`

CMakeLists of my library project:

`cmake_minimum_required(VERSION 3.23)
project(channels C)

set(CMAKE_C_STANDARD 99)
file(GLOB_RECURSE SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/src/*.c)
find_library(HIREDIS hiredis REQUIRED)
find_library(EVENT event REQUIRED)

add_library(${PROJECT_NAME} SHARED ${SOURCES})
target_include_directories(${PROJECT_NAME} PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)
target_link_libraries(${PROJECT_NAME}
        PUBLIC event
        PUBLIC hiredis)`

=============== edit ==================
When i comment this section of code it works 
#include <hiredis/adapters/libevent.h>

**Comment by michael-grunder** [comment]
Thanks for the report.

Perhaps we're missing an include here.

**Comment by michael-grunder** [comment]
I just threw together a small sample project with CMake and am not having this issue.

Additionally, `redisAsyncHandleTimeout` is in `libhiredis.so` so perhaps there is a version conflict on your system?  An old version of hiredis perhaps?

```bash
❯ objdump -x /usr/local/lib/libhiredis.so.1.1.0|grep redisAsyncHandleTimeout
000000000000cf00 g     F .text	00000000000001c1              redisAsyncHandleTimeout
```

**Comment by michael-grunder** [comment]
Are you still having this issue or can it be closed
