### ISSUE TITLE
Undefined reference to SSL_ctrl

### ISSUE THREAD

**Issue by W2Q3Q1** [redis/hiredis#1159]
I am building Hiredis with SSL support using `make USE_SSL=1`. During the execution of `cc -o hiredis-test -O3 -fPIC  -DHIREDIS_TEST_SSL -Wall -W -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb  -pedantic -I. test.o libhiredis.a libhiredis_ssl.a  -lssl -lcrypto -pthread`, an error
```
usr/bin/ld: libhiredis_ssl.a(ssl.o): in function `redisSSLConnect':
hiredis-1.1.0/ssl.c:348: undefined reference to `SSL_ctrl'
/usr/bin/ld: libhiredis_ssl.a(ssl.o): in function `redisInitiateSSLWithContext':
hiredis-1.1.0/ssl.c:414: undefined reference to `SSL_ctrl'
```
 occurred. I have confirmed that:

1. OpenSSL3 is installed and the library libssl.so of it is the only libssl.so in ld system.
2. SSL_ctrl is a defined symbol in libssl.so
My system is Ubuntu20.04.

**Comment by W2Q3Q1** [comment]
The solution is interesting: 

1. Build without SSL (using `make` and `sudo make install`)
2. reBuild with SSL (using `make USE_SSL=1` and `sudo make install`)
I don't know why.

**Comment by michael-grunder** [comment]
Hi, thanks for the report.

it's hard to say for sure, but are you certain you only have `libssl3` on the system?  Doesn't Ubuntu 20.04 come with openssl 1.1f by default?

Also I don't think you can tell the version of openssl from the `libssl.so` filename.

Are you able to replicate the issue in a container?  I'd be happy to help.

**Comment by W2Q3Q1** [comment]
Thanks for your reply!

Actually, there is libssl1 library on our machine, but there is no `libssl.so` linked to this library. 

The way we verify that is:

1. Open a terminal, and execute `ldconfig -p | grep 'libssl.so'`, we can see something like 'libssl.so (xxx) => /yyy/zzz/libssl.so'
2. Go to the directory /yyy/zzz, and execute 'ls -l', we can see the original file of libssl.so, which is actually libssl.so.3.

Unfortunally, no one in our team is familiar with docker, we cannot provide the results in a container immediately.

**Comment by W2Q3Q1** [comment]
It is so weird that ld system cannot find the correct libssl.so in `cc` command, for only one libssl.so (linked to libssl.so.3) is shown after executing `ldconfig -p | grep 'libssl.so'`. I still don't know why, but fortunately, the problem is solved at last.
