### ISSUE TITLE
segfault at tc_realloc as part of redisvFormatCommand

### ISSUE THREAD

**Issue by rahulKrishnaM** [redis/hiredis#1161]
Hi, 

We are using hiredis library along with hiredis-cluster in our application to send commands out to redis server.
Today, we came across below segfault while trying to send a redis command.

```
Program terminated with signal SIGSEGV, Segmentation fault.
(gdb) bt
#0  0x00007f93ed2b5ee6 in tc_realloc () from /usr/lib64/libtcmalloc.so.4
#1  0x00007f93eca62b33 in hi_realloc (size=40, ptr=0x9b384a0) at hiredis/alloc.h:66
#2  redisvFormatCommand (target=target@entry=0x7fffe6dd4c60, format=<optimized out>, ap=ap@entry=0x7fffe6dd4c90)
    at hiredis/hiredis.c:330
```
	
Frames 3 and below are from application side and hiredis-cluster side passing the command down to hiredis.

Application was trying to send the following command to redis:

> SET /Q002-FFF-AAA:1/MMM-CCCC-COCOCON:MOMOMO-contexts/rrrrrrr/311180002005087.Op.lock yraryraryra NX PX 5000

where "_format_" argument in frame 2 of gdb session is "**SET %s %s NX PX %d**".

Tried to gather some more details from the core backtrace.
```
(gdb) f 2
#2  redisvFormatCommand (target=target@entry=0x7fffe6dd4c60, format=<optimized out>, ap=ap@entry=0x7fffe6dd4c90)
    at hiredis/hiredis.c:330
(gdb) info locals
c = 0x7f93eb6ea4b1 " %d"
cmd = 0x0
pos = <optimized out>
curarg = 0x146d725b "PX"
newarg = <optimized out>
touched = <optimized out>
curargv = 0x9b384a0
newargv = <optimized out>
argc = 4
totlen = 122
error_type = 0
j = <optimized out>
memory_err = <optimized out>
```
So looks like 4 spaces are decoded already and it has just encountered a 5th space (which is between PX and %d).

I tried printing 4 indices out from curargv.

```
(gdb) x/4gx curargv
0x9b384a0:      0x000000001d8c6d13    0x000000000993c4d3
0x9b384b0:      0x00000000044516a3    0x000000001da2e19b
(gdb) x/1bs 0x000000001d8c6d13
0x1d8c6d13:     "SET"
(gdb) x/1bs 0x000000000993c4d3
0x993c4d3:      "/Q002-FFF-AAA:1/MMM-CCCC-COCOCON:MOMOMO-contexts/rrrrrrr/311180002005087.Op.lock"
(gdb) x/1bs 0x00000000044516a3
0x44516a3:      "yraryraryra"
(gdb) x/1bs 0x000000001da2e19b
0x1da2e19b:     "NX"
(gdb) x/1bs 0x0000000009b38fa0
```

Its able to show the command parsed and saved till "NX" argument. So looks like the pointer **curargv** is sane. 
But not sure why tc_realloc() is throwing segfault. Can someone please help here.

**Comment by michael-grunder** [comment]
Hi, thanks for the report.

It's difficult to say without being able to replicate the crash.  As you said, nothing immediately jumps out as a bad/corrupted pointer.

I don't have much more insight than to recommend the standard things like trying to catch the crash using standard tools (valgrind, asan, rr).

**Comment by michael-grunder** [comment]
Were you ever able to track down your segfault?  Without more information or a way to reproduce the crash I'm tempted to close the issue.

**Comment by rahulKrishnaM** [comment]
Yes, we were able to track down the issue to an application bug. You may please close the issue. Thanks.
