### ISSUE TITLE
[BUG] Colliding options REDIS_OPT_PREFER_IPV4, IPV6

### ISSUE THREAD

**Issue by zuiderkwast** [redis/hiredis#1171]
The values chosen for `REDIS_OPT_PREFER_IPV4` and `REDIS_OPT_PREFER_IPV6` were already taken when these options were added. It was my mistake and it passed all reviews and tests and unfortunately made it to the release 1.1.0.

```C
#define REDIS_OPT_NONBLOCK 0x01
#define REDIS_OPT_REUSEADDR 0x02
#define REDIS_OPT_PREFER_IPV4 0x04
#define REDIS_OPT_PREFER_IPV6 0x08
#define REDIS_OPT_PREFER_IP_UNSPEC (REDIS_OPT_PREFER_IPV4 | REDIS_OPT_PREFER_IPV6)

/**
 * Don't automatically free the async object on a connection failure,
 * or other implicit conditions. Only free on an explicit call to disconnect() or free()
 */
#define REDIS_OPT_NOAUTOFREE 0x04

/* Don't automatically intercept and free RESP3 PUSH replies. */
#define REDIS_OPT_NO_PUSH_AUTOFREE 0x08

/**
 * Don't automatically free replies
 */
#define REDIS_OPT_NOAUTOFREEREPLIES 0x10
```

Perhaps it's the excessive spacing and multiline comment that confused us... Anyway, I think we should fix it ASAP. The effect of the bug:

* The use of either REDIS_OPT_PREFER_IPV4 or REDIS_OPT_NOAUTOFREE has the effect of specifying both of them.
* The use of either REDIS_OPT_PREFER_IPV6 or REDIS_OPT_NO_PUSH_AUTOFREE has the effect of specifying both of them.

I think the solution is to simply give new values to the new options REDIS_OPT_PREFER_IPV4,6 and to describe it properly in the next release notes. Hopefully this explanation can help a bit. I'll post a PR next.

**Comment by michael-grunder** [comment]
My fault too as I also missed it!  Will get your PR merged asap
