### ISSUE TITLE
What is the difference between redis-cli.c in redis source code and hiredis code?

### ISSUE THREAD

**Issue by MasterL-min** [redis/hiredis#1176]
What is the difference between redis-cli.c in redis source code and hiredis code?

**Comment by michael-grunder** [comment]
`redis-cli.c` implementes the `redis-cli` command-line client to Redis.  It uses hiredis internally to do the actual communication with `redis-server`.

Hiredis is a client literary that can be used to build programs that interact with redis.  Programs that include, for example `redis-cli`.

**Comment by MasterL-min** [comment]
> `redis-cli.c` implementes the `redis-cli` command-line client to Redis. It uses hiredis internally to do the actual communication with `redis-server`.
> 
> Hiredis is a client literary that can be used to build programs that interact with Redis. Programs that include, for example `redis-cli`.
> 
> For example, here's a line in [redis-cli.c](https://github.com/redis/redis/blob/a4a0eab52b351b5f152071dda2a993d90f99d64b/src/redis-cli.c#L1665) that is using the hiredis function `redisConnect`.

Thanks a lot！
