### ISSUE TITLE
After changing the hiredis part in the redis source code and compiling it, when I used redis-cli for packet capture inspection, I didn't see the changes I changed.

### ISSUE THREAD

**Issue by MasterL-min** [redis/hiredis#1183]
![6F8~KL1CGMJ_CHI@A6FYVVU](https://user-images.githubusercontent.com/71004611/233846918-59312e45-29e9-4214-82ff-e84ecb9cc097.png)
I made changes to hiredis.c in the hiredis folder in the redis source code, as shown in the picture.
The changed function is redisvFormatCommand in hiredis.c.
Change as follows
![P 6ZZ(8 $066SU43Q%9~54](https://user-images.githubusercontent.com/71004611/233847026-06fac38a-db0e-4913-9f9e-f6a9911dfde2.png)
I want to add an extra character such as 'b' when hiredis adds /r/n after the parameters passed in by the user.
but when I make changes to this and save and compile（ps,the way I compile is to use the command sudo make under the hiredis folder of the redis source code).
When I capture the package, I can't see the changes I made. The content of the package I captured is as follows:
![G$5E9L`A9S JDT}J@`)IU~6](https://user-images.githubusercontent.com/71004611/233847185-ea212e10-e9ec-4409-ae64-2999c25b8b83.png)
And this is consistent with the contents of the package without changes, so I wonder what is wrong.

**Comment by bjosv** [comment]
This issue might fit better under the [redis](https://github.com/redis/redis) repo, but it sound like you would need to rebuild redis after rebuilding its dependency hiredis. Hiredis is built as a static library and the changes needs to be linked into the redis binary as well.
You can always run `make distclean all` under the redis repo to make sure everything is rebuilt. Slow but thorough.
