### ISSUE TITLE
Improvement: More specific error message when calling redisEnableKeepAlive() with unix socket

### ISSUE THREAD

**Issue by timo-schluessler** [redis/hiredis#1185]
Unix sockets don't support setsockopt `TCP_KEEPALIVE` and currently the error message is set to `strerror(errno)`: "Operation not supported". While this is totally valid I suggest to explicitly catch this case and return a more specific error message. E.g.:

```
diff --git a/net.c b/net.c
index ec96412..114f597 100644
--- a/net.c
+++ b/net.c
@@ -172,6 +172,11 @@ int redisKeepAlive(redisContext *c, int interval) {
     int val = 1;
     redisFD fd = c->fd;
 
+    if (c->connection_type == REDIS_CONN_UNIX) {
+        __redisSetError(c,REDIS_ERR_OTHER,"Keepalive not supported for unix socket");
+        return REDIS_ERR;
+    }
+
 #ifndef _WIN32
     if (setsockopt(fd, SOL_SOCKET, SO_KEEPALIVE, &val, sizeof(val)) == -1){
         __redisSetError(c,REDIS_ERR_OTHER,strerror(errno));
```

Or maybe it would also be an option to only print a warning in this case. What do you think?

**Comment by michael-grunder** [comment]
It's actually a good question.

Typically I handle this in the application logic, but I don't see any harm in providing a more helpful error message.  I don't think we really have the option to print an error though.  We'd need to stay consistent and set the error in the context like you're suggesting.
