### ISSUE TITLE
How to use binary safe data with redis set?

### ISSUE THREAD

**Issue by Neeraj0019** [redis/hiredis#1186]
Hi,
I want to store some numbers into redis SET in binary safe mode and retrieve using SMEMBERS. Can someone give me an example how it has to be done considering belowo sample code.

void func(uint16_t value)
{
string key = "TEST";
redisReply* reply = (redisReply*)redisCommand(ctxt, "SADD %b %b",
                            Key, strlen(Key), &value, sizeof(value));
Is this correct way of using SADD? do we need to pass pointer to value?
} 

Also how to retrieve the value using SMEMBERS and compare if a particular value is available?

Thanks for the support.

**Comment by michael-grunder** [comment]
Here's a small example program that does this:
https://gist.github.com/michael-grunder/54ee26173b619f1546c60b0141bb675b

It stores binary data (emojis) in a redis set, and then prints them back, along with the hex encoded binary representation of the members.

**Comment by Neeraj0019** [comment]
Hi Michael,
Thanks for the example, currently we are using it in different way and i fill that it might have some bug. Trying to explain it with sample code( not putting complete code).

This is how we add data to redis SET. It takes integer as an input and uses address of operator to store it in binary format. Is this correct way of doing it?

void func(uint16_t value)
{
string key = "TEST";
**redisReply* reply = (redisReply*)redisCommand(ctxt, "SADD %b %b",
Key, strlen(Key), &value, sizeof(value));**
Is this correct way of using SADD? do we need to pass pointer to value?
}  

Now when we are reading the members we are doing it something like below.

redisReply* reply_elements = (redisReply*)redisCommand(ctxt, "SMEMBERS %b",
                                        Key.c_str(), key.c_str()));

And than check if particular value is present in the SET using below code:

if(reply_elements->elements > 0) {
        for(size_t element_index = 0; element_index < reply_elements->elements;
                 element_index++) {
            if(value == ***(uint16_t*)reply_elements->element[element_index]->str)**{
                free_redis_reply_object(reply_elements);
                free_redis_context(ctxt);
                return true;
            }
        }
    }
In some cases we see that this check for checking if a value is present in SET always returns true, even though value is not added. So i am doubting the way we are inserting it to the SET is having issues.

**Comment by michael-grunder** [comment]
> This is how we add data to redis SET. It takes integer as an input and uses address of operator to store it in binary format. Is this correct way of doing it?

No, this is not how I would do this.  :smile:

Just for education purposes, you could do this like so:

```c
uint16_t intval = 1337;

/* Write the data in it's binary representation */
reply = redisCommand(c, "SADD %s %b", "intset", &intval, sizeof(intval));
freeReplyObject(reply);

/* Read the data back and verify everything is good. */
reply = redisCommand(c, "SMEMBERS %s", "intset");
assert(reply != NULL && reply->elements == 1 &&
            reply->element[0]->type == REDIS_REPLY_STRING &&
            reply->element[0]->len == sizeof(uint16_t));

/* A uint16_t container to store the read value */
uint16_t decoded;

/* Copy the bytes into our destination container. */
memcpy(&decoded, reply->element[0]->str, reply->element[0]->len);
printf("decoded: %u\n", decoded);
```

This isn't portable though and will return incorrect results if you for example wrote data on a machine with a little-endian CPU and attempted to read it on a big-endian machine.

If you are only storing numbers I would just send them to Redis as strings (e.g. "12345") and then when reading them back simply use something like `number = atoi(reply->str)` to get them back as a number.  Redis actually has special encoding logic when a set contains only numbers (it is called an `intset` internally).

**Comment by michael-grunder** [comment]
Going to close this, since it's not actually a bug in hiredis.

Happy to answer any other questions you may have however.
