### ISSUE TITLE
dns resolving issue when using AWS elasticache

### ISSUE THREAD

**Issue by poznir** [redis/hiredis#1195]
Hi,
we are using AWS, elesticache service for our redis services,
using hiredis driver (with hiredis cluster, but it's not relevant)
connection is done using dns, provided by AWS
the _redisContextConnectTcp method, is suppose to resolve the hosts, and try connecting them one by one until success.
the problem is that AWS provides the first host in the resolved DNS host as constant (the "main" one), and the rest are shuffled
each time you will resolve it, first ip will stay the same,
in our use case we have thousands of connections, and all of them open the initial connection to one node, instead of them being disturbed among all hosts. 

the issue only happens when using getaddrinfo in C code, won't happen manually when using host command for example

for example:
abc.elesticache.aws.com (example) resolved to

1st try:
123.123.123.123
1.1.1.1
2.2.2.2
3.3.3.3

2nd try:
123.123.123.123
3.3.3.3
1.1.1.1
2.2.2.2

3rd try:
123.123.123.123
2.2.2.2
3.3.3.3
1.1.1.1

...

can you provide a way to shuffle the resolved list, or other alternative to solve this issue?

thank you!

**Comment by michael-grunder** [comment]
Thanks for the report,

I've never really used ElastiCache or AWS's DNS so I'm not totally sure what the right solution would be here.  I'll do some research and see if there are additional options we can push into `getaddrinfo` or some other mechanism we could add to hiredis to mitigate this.

I assume you would ideally want these connections to be made, basically at random each time?

**Comment by poznir** [comment]
Hi, yes ideally we would want them to be made at random order.
We just informed aws about this behavior, i know they are checking internally if its an issue or not on their side, so im not sure yet if they are going to fix it or not.

**Comment by poznir** [comment]
@michael-grunder 

updates:

note: when disabling v6 in the config the issue doesn't happen (os level).

alternative:
1. seems like the dns lookup mechanism priortize the "main" (closest, datacenter wise) node.
2. this issue is not unique to AWS, and may happen in other places as well.
3. we solved it locally with added random to the resolved ips in the driver in the initial connection to the first node (first is for host, next are for ips (from the mapping).

FYI :)

**Comment by michael-grunder** [comment]
Can this issue be closed then?

**Comment by poznir** [comment]
@michael-grunder 
We fixed the issue locally (with random), its your chooise if you guys wish to do it in thw actual offical driver, if not please close it
