### ISSUE TITLE
redisConnect multithread crash

### ISSUE THREAD

**Issue by sunnyinchina** [redis/hiredis#1201]
when I use a context per thread, redisConnect also crashes, can you help me?

such codes are using by several threads

redisContext* redis = redisConnect(RedisIP, nPort);
redisReply reply = (redisReply)redisCommand(redis, "set hello 2023");
freeReplyObject(reply);
redisFree(redis);when I use a context per thread, redisConnect also crashes, can you help me?

**Comment by michael-grunder** [comment]
Going to close this since there's not much we can do without more specific information.  If you have more info feel free to update the thread.
