### ISSUE TITLE
EINTR on connect.

### ISSUE THREAD

**Issue by michael-grunder** [redis/hiredis#1206]
I ran into an issue where the [poll](https://github.com/redis/hiredis/blob/d543baba671bc4609d27e2905de0d8d987f708fe/net.c#L283) syscall is interrupted, which causes hiredis to fail with this error:

```poll(2): Interrupted system call```

In other parts of hiredis, we detect `EINTR` and retry the syscall and was wondering if we should do something similar here.

To maintain backward compatibility we could make it one of our `redisOptions` options (e.g. "ignore EINTR on connect").

cc @yossigo @chayim  @bjosv What do you guys think?

Absolutely no rush on this, from the client side it's simple enough to just retry the connection, but it may be worth adding to hiredis.

**Comment by chayim** [comment]
General fan of option extension. Supportive.

**Comment by yossigo** [comment]
@michael-grunder I think we should consider this a bug and fix it. As far as I can tell, we should only hit `redisContextWaitReady` from a blocking call, so retrying `poll` on `EINTR` always seems right (especially given that we're already doing it elsewhere).
