### ISSUE TITLE
How to specify different database index other than default 0 in hiredis ?

### ISSUE THREAD

**Issue by sujz** [redis/hiredis#1217]
### Discussed in https://github.com/redis/hiredis/discussions/1216

<div type='discussions-op-text'>

<sup>Originally posted by **sujz** August  3, 2023</sup>
Hello guys,

As we know, each redis instance supports 16 databases by default, and the default database index is 0.

I don't find any hiredis api support this option, both redisConnect and redisConnectWithOptions have no such option like what Go redis client does.

Here is whtat Go redis client does: 
redisdb := redis.NewClient(&redis.Options{
		Addr:     "localhost:6379", // use default Addr
		Password: "",               // no password set
		DB:       0,                // use default DB
	})

So is it possible to specify different database index other than default 0 in hiredis ?</div>

**Comment by bjosv** [comment]
There is no specific option in the API what I know of,
but you can always change which logical database to use with the Redis command [SELECT](https://redis.io/commands/select/).
Just send this command the first thing you do after a connect.

**Comment by sujz** [comment]
That's a good idea, thanks.
