### ISSUE TITLE
redisCommand returning null

### ISSUE THREAD

**Issue by Nadav89** [redis/hiredis#1219]
Hi,
I am using Redis in a container, image redis:6-alpine, and also using the latest version of hiredis.
I have written a basic C script using the examples provided in README but I am always getting back null when using GET or HGET.
When I downgraded hiredis to v0.13.3 it all worked well, with the same code.
Here is my code:
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <hiredis/hiredis.h>

int main (int argc, char **argv) {
    redisReply *reply;
    redisContext *context;
    printf("hiredis version: v%d.%d.%d\n", HIREDIS_MAJOR, HIREDIS_MINOR, HIREDIS_PATCH);
    context = redisConnect("127.0.0.1", 6379);
    if (context->err) {
        printf("error: %s\n", context->errstr);
        return 1;
    }
    reply = redisCommand(context,"PING");
    printf("PING: %s\n", reply->str);
    freeReplyObject(reply);
    reply = redisCommand(context,"HGET %s %s","VDM", "timestamp");
    printf("GET RESPONSE: %s. TYPE: %d\n", reply->str, reply->type);
    freeReplyObject(reply);
    redisFree(context);
    return 0;
}
```
I am getting back:
hiredis version: v1.2.0
PING: (null)
GET RESPONSE: (null). TYPE: 1

When using the ```monitor``` in redis-cli I am receiving the request properly:
1691563806.860119 [0 172.17.0.1:58352] "PING"
1691563806.860797 [0 172.17.0.1:58352] "HGET" "VDM" "timestamp"
Also, when using ```nc 127.0.0.1 6397``` and sending my requests, I am receiving it as it should be:
PING
+PONG
hget VDM timestamp
$4
1111

Any thoughts on why this happens? Am I using the command the wrong way?
Thanks.

**Comment by michael-grunder** [comment]
It's hard to say without being able to replicate your specific scnerio.

Can you create or post the Dockerfile you're using here?  I'm happy to spin it up and see if I can replicate the problem.  It seems unlikely that v1.2.0 just doesn't work with basic commands as I'm pretty sure we'd have heard of it by now :smile:

One possibility is mismatched libraries (e.g. v1.2.0 headers with v0.13 binaries) but I can look into that if you post the Dockerfile.

**Comment by Nadav89** [comment]
Hi,

I'm also quite sure there is a mismatch somewhere.
I pulled an image using:
```
sudo docker pull redis:6-alpine
```
And ran it using:
```
sudo docker run --name my-redis -p 6379:6379 -d redis:6-alpine
```

I'm guessing the Dockerfile is this one:
[redis:6-alpine](https://github.com/docker-library/redis/blob/f2da8752a05b783eb805b67ad7a56a997a0fe91f/6.0/alpine/Dockerfile)

I didn't build the image using it, just pulled it.

Thanks a lot!

**Comment by michael-grunder** [comment]
Yeah, I don't have any issue communicating to redis from the host to the container.  My guess is you have some kind of incompatibility in your system.

You may need to run `sudo ldconfig` so that the system will find the upgraded binaries.  What I would do is install hiredis v1.2.0 again, do `sudo ldconfig` and then recompile your program.

Once it's compiled, run this:

```bash
ldd /path/to/your/binary
```

It should give you output like this:
```bash
❯ ldd ./a.out
	linux-vdso.so.1 (0x00007fff059fd000)
	libhiredis.so.1.2.1-dev => /usr/local/lib/libhiredis.so.1.2.1-dev (0x00007f1eedefd000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1eedc00000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1eedf3b000)
```

I'm running a prerelease version of v1.2.2 but you should see `v1.2.0` if the system is finding the right libs.  If you are using v1.2.0 headers but the linker was linking with `v0.13.0` that could certainly cause odd issues.

**Comment by Nadav89** [comment]
Thanks Michael.
I did what you suggested and now it all works great! :)

**Comment by crossoverTang** [comment]
Hi, 
I seem to have the same problem. Here is my code:

`#include <iostream>
#include <hiredis/hiredis.h>
int main() {
    const char *redis_host = "localhost";  
    int redis_port = 6379;  
    redisContext *context = redisConnect(redis_host, redis_port);
    if (context == NULL || context->err) {
        if (context) {
            std::cerr << "Connection error: " << context->errstr << std::endl;
            redisFree(context);
        } else {
            std::cerr << "Connection error: can't allocate redis context" << std::endl;
        }
        return 1;
    }
    redisReply *reply = (redisReply *)redisCommand(context, "PING");
    if (reply == NULL) {
        std::cerr << "PING command failed" << std::endl;
        redisFree(context);
        return 1;
    }
    if (reply->type == REDIS_REPLY_STATUS) {
        std::cout << "PING response: " << reply->str << std::endl;
    } else {
        std::cerr << "Invalid PING response" << std::endl;
    }
    freeReplyObject(reply);
    redisFree(context);
    return 0;
}`

The CMakeList.txt is :
`cmake_minimum_required(VERSION 3.10)
project(RedisConnection)
set(CMAKE_CXX_STANDARD 11)
find_package(hiredis REQUIRED)
add_executable(RedisConnection main.cpp)
target_link_libraries(RedisConnection PRIVATE hiredis)
`

The output is:
`test@ubuntu:~/Desktop/test$ cmake --build build
Scanning dependencies of target RedisConnection
[ 50%] Building CXX object CMakeFiles/RedisConnection.dir/main.cpp.o
[100%] Linking CXX executable RedisConnection
[100%] Built target RedisConnection
test@ubuntu:~/Desktop/test$ cd build/
test@ubuntu:~/Desktop/test/build$ ls
CMakeCache.txt  CMakeFiles  cmake_install.cmake  Makefile  RedisConnection
test@ubuntu:~/Desktop/test/build$ ./RedisConnection 
PING response: test@ubuntu:~/Desktop/test/build$ 
`
Can you help me figure out what went wrong? Thanks.
