### ISSUE TITLE
freeReplyObject() may cause a coredump

### ISSUE THREAD

**Issue by fasterpython** [redis/hiredis#122]
void freeReplyObject(void *reply) {
    redisReply *r = reply;
    size_t j;

```
switch(r->type) {
}

free(r);
```

}   

reply = redisCommand(c,"AAA_cmd);
freeReplyObject(reply);

if reply == null is True, freeReplyObject()  does not check the null argument and will cause a coredump.

**Comment by michael-grunder** [comment]
Going through old issues.  This was closed (in 2014) via 05b85ebe
