### ISSUE TITLE
【Bug】The value obtained by the get command is OK, what is this?

### ISSUE THREAD

**Issue by BenjaminBBr** [redis/hiredis#1221]
version:0.14.1
os:NeoKylin
C++

My application adopts a multi-threaded environment, with one Hiredis handle per thread.

When using the get command to obtain the value of a certain key, the return result is OK

But the values obtained through redis-cli are indeed correct, what is this?

As is well known, the set command returns OK when a key is successful, but the get command actually returns OK. Currently, it is speculated that Hiredis generated a misplacement packet and obtained unexpected results.

This problem occurs by chance, with a very low probability. Have you encountered similar problems before? What is the cause and solutions?

**Comment by michael-grunder** [comment]
There's really not enough information to make a guess.

v0.14.1 is very old, although a bug like this has not been reported to my knowledge.  

The only recommendation I have really is to try and catch the bug with a debugger (e.g. `gdb` or `rr`).  You can also try running your program through `valgrind` to see if there are any reported errors.

Without a small program that replicates the problem there's not too much more I can help with.

**Comment by BenjaminBBr** [comment]
This problem has occurred twice, and the other time I got a value that was not ok but was stored by another key. In summary, the obtained value is the value of the other key, which is equivalent to a misplacement packet. Have you encountered similar problems

**Comment by BenjaminBBr** [comment]
i found the reason，Multithreading uses the same handle.
