### ISSUE TITLE
KEYS ERROR IN VERSION 1.1.0

### ISSUE THREAD

**Issue by dorebabu** [redis/hiredis#1228]
Hello community, 

In version 1.1.0, whereever I use keys E* along with redisCommand to find the tables of redis that start with E, I am not getting any result. Is this feature depricated in this version of hiredis.

Ex: 

        reply = redisCommand (g_cfg_db.redis_db_ctxt, "KEYS PORT|E*");

This doesn't give the tables that start with PORT|E

Thank you .

**Comment by sundb** [comment]
Are you confusing glob-style pattern and regex?
glob-style pattern doesn't support `|`.

**Comment by sundb** [comment]
@dorebabu I can't find version 0.15, so i used 0.14 to test and the result is still empty.
AFAIK, The glob-style of the keys command has never had support for `|`.

**Comment by michael-grunder** [comment]
@sundb Is correct.  Redis supports glob-style (e.g `*` and `?` wildcard) pattern matching, but has never supported the regeg `|` OR operator, at least AFAIK.

You can verify this in `redis-cli`

```bash
127.0.0.1:6379> set "KEYS PORT" "some value"
OK
127.0.0.1:6379> set EGGS dozen
OK
127.0.0.1:6379> set ELEPHANTS "are big"
OK
127.0.0.1:6379> keys "KEYS PORT|E*"
(empty array)
127.0.0.1:6379> keys "KEYS PORT"
1) "KEYS PORT"
127.0.0.1:6379> keys "E*"
1) "ELEPHANTS"
2) "EGGS"

(empty array)
```

**Comment by michael-grunder** [comment]
Closing, since this isn't a bug in hiredis but happy to answer any other questions.
