### ISSUE TITLE
Assessment of the difficulty in porting CPU architecture for  hiredis

### ISSUE THREAD

**Issue by wangyuliu** [redis/hiredis#1240]
Hello everyone! I am working on implementing a tool to assess the complexity of CPU architecture porting. It primarily focuses on RISC-V architecture porting. In fact, the tool may have an average estimate of various architecture porting efforts.My focus is on the overall workload and difficulty of transplantation in the past and future,even if a project has already been ported.As part of my dataset, I have collected the **hiredis** project. **I would like to gather community opinions to support my assessment. I appreciate your help and response!** Based on scanning tools, the porting complexity is determined to be  simple, with a small amount of code related to the CPU architecture in the project.  Is this assessment accurate?Do you  have any opinions on personnel allocation and consumption time？ I look forward to your help and response.

**Comment by michael-grunder** [comment]
Appologies for such a delayed response but I missed this when you first posted it.

I'm not an expert in RISC-V but my assumption is that your initial assessment is correct.  There are likely not very many changes required to port hiredis to that architecture.

Off the top of my head only the things we do in the `sds.h` file around struct packing might cause an issue. Other than that most of the conditional compilation we do to make hiredis work on different operating systems.

**Comment by michael-grunder** [comment]
I was curious about this so I spun up a riscv64 container (via emulation) and was able to build and run the hiredis tests without any issues.

So it would seem that porting would in fact be very simple :smile:

Going to close this since it's not really an issue/bug with hiredis but happy to answer any further questions.
