### ISSUE TITLE
redisCommand crashes on FreeBSD x86

### ISSUE THREAD

**Issue by paxter** [redis/hiredis#1242]
In some circumstances `redisCommand()` with arguments fails. In such cases `redisCommand()` hangs and the process takes all system memory. After that the program crashs if there is no space left (check out htop screenshot).

![htop](https://github.com/redis/hiredis/assets/5040710/6c2a4625-d72d-49fc-a49c-ae98b7cd4af5)

```
root@freebsd-124-qemu-x86:~/devel # ./redis_tests
Debug 1
/: write failed, filesystem is full
Bus error
```

It's no general bug and difficult to find, because the bug only appears on FreeBSD with x86 architecture and only on a few argument combinations. Same code on FreeBSD with ARM64 works fine. Same redis command works fine with phpredis.

**Tested on**

- FreeBSD 11.2 x86: crash
- FreeBSD 12.4 x86: crash
- FreeBSD 13.2 x86: crash
- FreeBSD 13.1 ARM64: works
- Solaris x86: works
- RHEL x86: works

**Tested with**

- Redis 7.2.3, 7.0.14, 7.0.2
- hiredis 1.2.0, 1.1.0, 1.0.2

For test cases I wrote a little c program. Just start `redis-server` (empty db, no keys) with unix domain socket configured and set the correct path to the socket in the code. Program crashes only with the first uncommented `redisCommand()`.

For me, it looks like there is something wrong with `memcpy`.

**Compiling and running**

```
setenv LD_LIBRARY_PATH '/usr/local/lib'
clang -I/usr/local/include -o redis_tests redis_tests.c -L/usr/local/lib -lhiredis
./redis_tests
```

**Test program**

```c
/* system */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

/* hiredis */
#include <hiredis/hiredis.h>

#define KEY_PREFIX "testprefix"
#define BINARY_LENGHT 20

/* globals */
redisContext *redis_ctx;
char *redis_path = "/tmp/redis_test.sock";

redisContext* create_redis_context() {
	redisContext *context = redisConnectUnix(redis_path);

	if (context == NULL || context->err) {
		if (context)
			printf("Redis error on context creation: %s\n", context->errstr);
		else
			printf("Can't allocate redis context\n");

		redisFree(context);
		exit(EXIT_FAILURE);
	}

	return context;
}

int main() {
	redis_ctx = create_redis_context();

	redisReply *reply;
	unsigned int id1 = 9;
	unsigned int id2 = 1337;
	unsigned int id3 = 13245;
	char binary_data[20];

	printf("Debug 1\n");
	
	/* fails */
	reply = redisCommand(redis_ctx, "HMGET %s:%u:%u:%u:%b field1 field2 field3 field4 field5 field6 field7 field8", KEY_PREFIX, id1, id2, id3, binary_data, BINARY_LENGHT);
	
	/* works*/
	//reply = redisCommand(redis_ctx, "HMGET testprefix:9:1337:13245:12345678901234567890 field1 field2 field3 field4 field5 field6 field7 field8");
	
	/* works*/
	//reply = redisCommand(redis_ctx, "HMGET %s:%u:%u:%u: field1 field2 field3 field4 field5 field6 field7 field8", KEY_PREFIX, id1, id2, id3);

	/* works*/
	//reply = redisCommand(redis_ctx, "HMGET %s:%u:%u:%u:%b:%u field1 field2 field3 field4 field5 field6 field7 field8", KEY_PREFIX, id1, id2, id3, binary_data, BINARY_LENGHT, id3);

	/* works*/
	//reply = redisCommand(redis_ctx, "HMGET %u:%b field1 field2 field3 field4 field5 field6 field7 field8", id1, binary_data, BINARY_LENGHT);
	
	printf("Debug 2\n");

	if (reply == NULL) {
		printf("Redis error\n");
		freeReplyObject(reply);

		return 1;
	} else if (reply->type == REDIS_REPLY_ARRAY && reply->elements == 8) {
		printf("Redis command fine\n");
		freeReplyObject(reply);
	} else {
		printf("Unsuspected reply\n");
		freeReplyObject(reply);

		return 1;
	}

	printf("All tests done\n");
	return 0;
}
```

Let me know, if you need any further information or I was missing something. :)

**Comment by paxter** [comment]
Any idea how to fix this issue?

**Comment by michael-grunder** [comment]
I'm going to try and replicate this on an AWS FreeBSD instance.  Just to clarify though, when you say x86 I assume you mean x86-64 and not i386.

Also I am pretty much clueless about FreeBSD so it may take me a little bit to get it tested :smile:

**Comment by paxter** [comment]
Thanks for your reply @michael-grunder :)

> I'm going to try and replicate this on an AWS FreeBSD instance. Just to clarify though, when you say x86 I assume you mean x86-64 and not i386.

Yes, I'm talking about x86-64. Sorry, I missed that information.

> Also I am pretty much clueless about FreeBSD so it may take me a little bit to get it tested

Sorry, was not my intention to make any pressure.

Compiling of redis and hiredis works pretty well on FreeBSD with default makefiles. But you may need `gmake` if `make` throws errors.

**Comment by michael-grunder** [comment]
Your problem has to do with the `BINARY_LENGTH` constant.  You are just defining it like this:

```c
#define BINARY_LENGTH 20
```

This is a four byte integer constant to C.  Hiredis however, is expecting this to be a `size_t` (8 bytes on 64 bit systems).  We're doing something like:

```c
arg = va_arg(ap, char*);
size = va_arg(ap, size_t);
```

So `va_arg` happily reads 8 bytes (your size + some other garbage) and ends up with a massive length.  Then we subsequently try to read it in and 💥 .

The solution is simple.  You can either redefine your constant like this:

```c
#define BINARY_LENGTH ((size_t)20)
```

Or do it at the callsite:

```c
redisCommand(ctx, "%b", binary-data, (size_t)BINARY_LENGTH);
```

Or in your case since you are using a static array you could use sizeof:

```c
redisCommand(ctx, "%b", binary_data, sizeof(binary_data));
```

I tried a variety of those and it fixed the issue.

I'm not sure why it's only apparent on FreeBSD other than that the gods of undefined behavior are capricious.  😄

**Comment by paxter** [comment]
Oh my god. 😄

Thanks for checking and finding the issue!

I'm no experienced C programmer, but learned another lesson now: Always use well defined data types to avoid trouble on different platforms. I thought, I had covered that, but obviously missed the defines. 🙄 

Sorry for bothering you with this issue and thanks a lot for maintaining this awesome library. :)
