### ISSUE TITLE
[warn] epoll_wait: Function not implemented

### ISSUE THREAD

**Issue by Rsaliu** [redis/hiredis#1243]
@michael-grunder 

I encounter this issue when using hiredis on arm64 ubuntu. Any ideas how to resolve.

PS: I have confirmed that CONFIG_EPOLL is enabled from kernel.

**Comment by michael-grunder** [comment]
It looks like `epoll_wait` is deprecated in some kernels in favor of `epoll_pwait`.  That's what I can gather doing a quick search at least.

I'll take a look tomorrow morning at what our options are.  Can you post the exact kernel you're running?

**Comment by Rsaliu** [comment]
Thanks for your response @michael-grunder .

kernel version is: 4.9

I can't pin-point the exact point causing but from my investigation, it happening somewhere in hiredis_ipc/third-party/event/event.c, in function event_base_loop. 

I hope this helps

**Comment by michael-grunder** [comment]
I don't know what `hiredis_ipc/third-party/event/event.c` is but it's not part of hiredis.

`event_base_loop` is in `libevent` so I don't actually think this error has anything to do with hiredis but is rather a problem happening in `libevent`.

**Comment by Rsaliu** [comment]
@michael-grunder Thanks for your response.

It was my bad. I somehow mixed up the file path. Issue is indeed with libevent. had to run the app by using.

`EVENT_NOEPOLL=1 ./app`

it works now.

Just putting it here, in case anyone face this issue.
