### ISSUE TITLE
hiredis doesn't build with openssl3

### ISSUE THREAD

**Issue by thebaptiste** [redis/hiredis#1264]
Hy
On my system (rockylinux 8), I would like to build hiredis with openssl3
The rpm `openssl3-devel` is installed, providing `openssl3.pc`
`pkg-config --cflags openssl3` gives `-I/usr/include/openssl3`
`pkg-config --libs openssl3` gives `-L/usr/lib64/openssl3 -lssl -lcrypto`
But this is not taken into account in hiredis Makefile. 

I think something should be added in this case (maybe `USE_SSL3=1` ?)
The build with `openssl3` should be privileged, especially since all releases of `openssl1` have reached their eol (see https://endoflife.date/openssl)

Regards

**Comment by thebaptiste** [comment]
Something as below should probably more or less do the job : 
```
ifeq ($(USE_SSL3),1)
  CFLAGS+=$(shell pkg-config --cflags openssl3)
  SSL_LDFLAGS+=$(shell pkg-config --libs openssl3)
endif
```

**Comment by michael-grunder** [comment]
Interesting, so on RockyLinux there is an explicit `openssl3.pc` for that. I suppose that's so both libraries (e.g. 1.1 and 3.x) can exist beside each other?

I'm not opposed to adding something like `USE_OPENSSL3` for this but will try to see what other projects are doing for this.  I'm honestly not sure what's standard here.

**Comment by thebaptiste** [comment]
> Interesting, so on RockyLinux there is an explicit `openssl3.pc` for that. I suppose that's so both libraries (e.g. 1.1 and 3.x) can exist beside each other?
> 
Yes, they can and they do (on rockylinux 8 or 9, openssl 1.1.1.k is a system dependency)

`openssl3.pc` and openssl3 include files (on `/usr/include/openssl3/openssl`) are part of the `openssl3-devel` rpm, but the libraries (`/usr/lib64/libssl.so.3` and `/usr/lib64/libcrypto.so.3`) are part of the `openssl3-libs` rpm

**Comment by thebaptiste** [comment]
`openssl3-devel` with `openssl3.pc` is from epel repository, so maybe it is not standard...

**Comment by thebaptiste** [comment]
I will probably use openssl3 on RockyLinux 8 by building it from source (with an `OPENSSL_PREFIX`) rather than using the epel rpm. I think it will work with hiredis.

So feel free to close my issue without doing anything !

**Comment by michael-grunder** [comment]
Glad you found a solution!  Using `OPENSSL_PREFIX` with where you built openssl3 should work nicely.

I'll close the issue for now but if more people start to run into this kind of issue we can always revisit. With any luck though it will happen less frequently as openSSL 1.x is EOL.
