### ISSUE TITLE
hiredis-test run error

### ISSUE THREAD

**Issue by 20072330** [redis/hiredis#1265]
when run test_resp3_push_handler function，if set redisSetPushCallback， RESP3 PUSH received at next call redisCommand

![1718354347408](https://github.com/redis/hiredis/assets/32033879/4b51e2ba-7a9d-42e8-a0c0-5135546e4931)
![1718354370431](https://github.com/redis/hiredis/assets/32033879/871f8f29-fbaa-4c1f-9c2a-79a167034052)

**Comment by bjosv** [comment]
This seem to work fine in CI, where there are some different jobs that runs on windows, like:
https://github.com/redis/hiredis/actions/runs/8540919275/job/23399070664#step:10:84
https://github.com/redis/hiredis/actions/runs/8540919275/job/23399070998#step:6:136

Have you spot any difference compared to these runs?

**Comment by 20072330** [comment]
@bjosv 
Thanks for your answer.
This problem was caused by my negligence.I used hiredis in the deps in the redis source code to do the test, which is inconsistent with the code on the github master branch.
![1718373113676](https://github.com/redis/hiredis/assets/32033879/23c24afa-a3bb-482e-a3ba-2ebc3d24e8e4)

**Comment by michael-grunder** [comment]
So can this issue be closed then?
