### ISSUE TITLE
Ambiguous license in macos adapter and example

### ISSUE THREAD

**Issue by michael-grunder** [redis/hiredis#1271]
Hi @dizzus 

Just noticed that the macos adapter and example have an [ambiguous license](https://github.com/redis/hiredis/commit/c18a5648181801aa6fddd1856940b7dd20cdf74a)

Would you be willing to sign-off on a commit with the standard [BSD 3-clause](https://github.com/redis/hiredis/blob/19cfd60d92da1fdb958568cdd7d36264ab14e666/adapters/ae.h#L1-L29) preamble?

You can use your name of course.

**Comment by dizzus** [comment]
Hello,

You may change the license as you see fit. Just keep my name around :))

Dmitry.
