### ISSUE TITLE
[Question] What will happen if I subscribe fd in redisContext with EPOLLIN?

### ISSUE THREAD

**Issue by w1nda** [redis/hiredis#1277]
The code link: https://github.com/redis/hiredis/blob/e0f48202aaf556a8ca17e02017c1c2559a20d433/hiredis.h#L262

Thanks for attention,
My understanding is that EPOLLIN means when the associated file(fd) is available for read it will notify subscriber.

If I subscribe fd in redisContext with EPOLLIN, when I will got notified? 
Or, put it in another way, what the fd means in redisContext? can I communicate with redis server with that fd(socket?)?
Or, put it in another way, when the socket is not ready for read?

**Comment by michael-grunder** [comment]
On Linux (or Linux-like) systems, `redisFD` is just a plain integer file descriptor. The reason there is an abstraction is to handle Windows.

https://github.com/redis/hiredis/blob/e0f48202aaf556a8ca17e02017c1c2559a20d433/hiredis.h#L173-L183

You can use any of the common functions to operate against file descriptors. It's important to be careful if you manually poll/read/write to the fd while the `redisContext` owns it, but this is perfectly doable.
