### ISSUE TITLE
Assertion fails in async.c 411 with certain subscribe/unsibscribe sequences

### ISSUE THREAD

**Issue by ilya-i** [redis/hiredis#140]
If you issue UNSUBSCRIBE command for the last subscribed channel and then immediately SUBSCRIBE, hiredis crashes in async.c line 411. It happens because attribute REDIS_SUBSCRIBED is set and cleared in two different places (it is set when SUBSCRIBED is handled when command is added to the queue, while it is cleared when UNSUBSCRIBED is handled when hiredis gets reply from Redis). When these 2 commands are issued back to back (so that they both get queued first, and then both sent to Redis), first hiredis sets REDIS_SUBSCRIBED in line 556 of async.c. Then, UNSUBSCRIBE command gets executed and reply is received, and REDIS_SUBSCRIBED is cleared in line 350. After that, SUBSCRIBE is executed, reply for it is received, and I guess since hiredis thinks that the context is not in subscribe mode, it crashes in line 411.

**Comment by badboy** [comment]
Unclear whether this is still a bug, no followup for quite some time and no reproducible test case. Closing for now.
