### ISSUE TITLE
LIBRARY_PATH in Makefile conflict with environment var.

### ISSUE THREAD

**Issue by cinsk** [redis/hiredis#176]
hiredis `Makefile` uses `LIBRARY_PATH` to determine actual library directory for installation.

```
LIBRARY_PATH?=lib
INSTALL_LIBRARY_PATH=$(PREFIX)/$(LIBRARY_PATH)
```

Unfortunately, GCC uses LIBRARY_PATH for searching non-standard library directories.  Some users has exported this environment variables like this:

```
export LIBRARY_PATH=/opt/lib:$HOME/lib
```

When running `make install`, since LIBRARY_PATH in Makefile uses `?=` operator, it uses value from the environment variables, thus `make install` failed.

Solution 1:
- use different name (not LIBRARY_PATH) in Makefile

Solution 2:
- use different assignment operator, not `?=`.

**Comment by ryandesign** [comment]
The fix was later reverted, so the problem exists again. The problem was reported again as #382.
