### ISSUE TITLE
redisvAppendCommand() sets always set "Out of memory" on format error

### ISSUE THREAD

**Issue by mezzatto** [redis/hiredis#177]
redisvFormatCommand() always returns -1 for various reasons, but:

```
    len = redisvFormatCommand(&cmd,format,ap);
    if (len == -1) {
        __redisSetError(c,REDIS_ERR_OOM,"Out of memory");
        return REDIS_ERR;
    }
```

We can end up having "Out of memory" set inside redisContext even though the error has nothing to do with the lack of memory.

**Comment by mattsta** [comment]
Thanks for the report! Adding a fix for this in the next version.
