### ISSUE TITLE
Interpret %b length argument as int

### ISSUE THREAD

**Issue by pietern** [redis/hiredis#183]
This can only be done in a major release, because users expect to have to cast the length argument for the %b specifier to a size_t.

Redis doesn't even support 4GB values, so it doesn't make sense to interpret it as a size_t.

**Comment by michael-grunder** [comment]
I'm not sure we want to do this, but I didn't look deeply at the associated issues.  To me, `size_t` is the correct specifier for length.

@mnunberg It seems like this change would break a great deal of code.  We haven't seen any issues around this in years AFAIK.
