### ISSUE TITLE
Connection to server on localhost incorrectly marked as successful

### ISSUE THREAD

**Issue by vmrob** [redis/hiredis#209]
I have a Redis server that I run in a VirtualBox Ubuntu virtual machine and have VBox port forwarding rules to reroute the host port 6379 to the guest port 6379.

Connecting to the server with a hiredis client works as expected both when the server is running and when it has stopped as long as the vm is responsive. However, if the vm is paused, then the connection is incorrectly marked as successful and successive calls to redisCommand block indefinitely.

Here is an example program that demonstrates the behavior:

	#include <hiredis/hiredis.h>
	#include <stdio.h>
	#include <assert.h>

	int main() {

		redisContext* c = redisConnect("127.0.0.1", 6379);

		assert(c && !c->err);		

		printf("connected:\nPING\n");

		redisReply* r = redisCommand(c, "PING");
		assert(r);

		printf("%s\n", r->str);

		freeReplyObject(r);
		redisFree(c);

		return 0;
	}

---
Edit: problem description / source

**Comment by badboy** [comment]
From hiredis' point of view the connection is successful, most likely because VirtualBox keeps the socket open on the host machine. There's no way for hiredis to detect that request don't actually go through.
