### ISSUE TITLE
hiredis on Redis Cluster?

### ISSUE THREAD

**Issue by YifanYuan** [redis/hiredis#237]
Hi~
Does anybody can tell me if Hiredis support on redis cluster?

**Comment by nysenthil** [comment]
Hi,
There is a nice hiredis-cluster wrapper API built by Dmitrii Shinkevich. It became available in the second week of April/2015 (a few days after the Redis 3 release). It is simply a set of include files you have to use on top of hiredis 0.12 or higher versions. I tried it to port my single Redis instance based C/C++ application code to work with the new Redis 3 cluster. Dmitrii's hiredis-cluster wrapper works great.

You can get it from here: https://github.com/shinberg/cpp-hiredis-cluster

Good Luck.
