### ISSUE TITLE
Strange behavior.

### ISSUE THREAD

**Issue by antmat** [redis/hiredis#244]
I'm writing a c++ wrapper on hiredis and faced a problem with ZINCRBY command.
When I tried to issue this command I constantly get adding empty string member to zset (I provided non empty member). In order to determine if this problem is on my side or hiredis I've created small test and it got me segfault.
https://gist.github.com/antmat/eef39309badc7f24cc5d
I would expect that I'm wrongly using "%b" in format, but I can't find any error in it myself.

Thanks a lot!

**Comment by mattsta** [comment]
Thanks for the report!

Your test code works for me using the latest version.  Any older versions in distro packages are the responsibility of the packagers.
