### ISSUE TITLE
Refactoring hiredis reader parser outside of the other code

### ISSUE THREAD

**Issue by tzickel** [redis/hiredis#249]
In attempt to make it easier to port the reader parser code that is used in hiredis-py (and other languages) to other OS like Windows, I've decided to factor out all this specific code outside of the other hiredis code into seperate files.

The effort shows this is feasible and makes porting to Windows much more easier:
https://github.com/tzickel/hiredis/tree/reader_refactor
(I've mainly split hiredis.c/.h into read.c/.h and hiredis.c/.h)

The question now is on which version of hiredis to concentrate the full porting efforts (if the official release has the reader parser code refactored outside, it will be easier to patch it on updates). 

The hiredis-py official version links to an hiredis version from 2 years ago. The question is are there any plans to update the hiredis version there any time soon, if so, I would move to do the refactoring on the master branch, otherwise I can continue working on that branch).

BTW atleast in that 2 years ago version there is a few issues mainly involving void * pointer arithmetic, percision lost in the case of putting "long long" variables into "long", etc...

**Comment by mattsta** [comment]
Works for me.

I've brought in https://github.com/tzickel/hiredis/commit/05060680859ea91c7f1e28365c214e0dd592160d (and cleaned up merge conflicts against newer code) into the next maint release.

Breaking out the reader functions doesn't change any existing behavior and it gives external users more flexibility for reuse.
