### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by tt33415366** [redis/hiredis#256]
Still, there is memory leak in *async.c*.
       When you use pubsub, and you subscribes a channel for two or more times, the *sname* (key) will be leaked(async.c:599).
Also, when we did:
{
       redisAsyncCommand(.."subscribe"..);
       redisAsyncCommand(.."unsubscribe"..);
       redisAsyncCommand(.."subscribe"..);
       redisAsyncCommand(.."unsubscribe"..);
}
we will get  a an assert failed sooner or later: because the hiredis code set *REDIS_SUBSCRIBED* flag sync and unset it async.

**Comment by hyjin** [comment]
Hi, It looks the following is still an open issue. Do you have any plan for it?

> The second issue can be reproduced with the following example: https://gist.github.com/badboy/823e9c97d249a65307cd
