### ISSUE TITLE
New hiredis maintainer?

### ISSUE THREAD

**Issue by antirez** [redis/hiredis#283]
Hello, I created this issue in order to understand how to move forward with hiredis.

1. I'm not maintaining it for a lot of time, if you exclude fixes that were necessary for Redis.
2. @mattsta is more or less doing the same as me.
3. @pietern was the one that was pushing hiredis forward, but I understand he got no time now (and we thank you, Pieter, for the work you put into it so far).

@pietern are you ok with the idea of looking for a new maintainer? Apparently nobody is handling it right now but it is a critical piece of code since it's also part of Redis, Sentinel, the foundation of many other client libs, and so forth.

Anyone interested to maintain it? This is not Redis, a more liberal model of development is possible, so we'll give commit access to the new maintainer that will schedule the releases and so forth.

**Comment by analytically** [comment]
Now that hiredis 0.12.0 is out, would be awesome if we could get a new hiredis-node version out ...

**Comment by mattsta** [comment]
Does it just require repointing the submodule at https://github.com/redis/hiredis-node/tree/master/deps to the new release?

**Comment by analytically** [comment]
Yeah that should work. And then bump the version to 0.2.0? Maybe pull https://github.com/redis/hiredis-node/pull/67 and https://github.com/redis/hiredis-node/pull/71 and then publish to npm.

**Comment by badboy** [comment]
@pietern Will you take care of that? Right now you're the solely owner of that package on npm. I could jump in if you want, you'd just have to add me as an owner.

**Comment by pietern** [comment]
Yep, that's pretty much it. @badboy @mattsta How do you feel about taking on not only hiredis-node, but also hiredis-rb and hiredis-py? If the pace on hiredis is going to be picking up, I'm sure I won't be able to keep up and it would be easier if you would push out new versions directly. Let me know what you think and I can add you to the repo's and the respective package management systems for publishing.

**Comment by badboy** [comment]
I'm happy to take on hiredis-node and hiredis-rb.
Gonna pass on hiredis-py though. I have absolutely no experience with Python. 
Any other takers?

**Comment by tzickel** [comment]
Wait up, if you move to 0.12.0 please make of the newly refactored code base.

hiredis-py should now depends on read.c instead of hiredis.c, since it only uses the hiredis parsing code, this should make it possible to finally compile hiredis-py on windows without modification (still didn't get a chance to check it out yet).

It seems that hiredis-node (not a node user) should do the same move, but hiredis-node seems to depend on async.c (not sure where it's being used if it is), if it's not required, maybe hiredis-node can be compiling in windows without modification as well.

Check out my pull request here:
https://github.com/redis/hiredis-py/pull/30

**Comment by badboy** [comment]
@pietern ping.

**Comment by pietern** [comment]
@mattsta @badboy @michael-grunder I have added you to the repo's for the hiredis bindings.

I think this issue can now be closed :)

We can take care of the Rubygems/NPM/PyPI credentials/ownership in separate issues with these repositories.

**Comment by badboy** [comment]
Thanks @pietern. *now using his power*
