### ISSUE TITLE
Hiredis 0.12.0

### ISSUE THREAD

**Issue by michael-grunder** [redis/hiredis#288]
Hey everybody,

I have created a ```develop``` branch for hiredis, and would like to get this going by going through a variety of outstanding issues and pull requests to see what we might want to get tested and incorporated for the next official release :smiley_cat:!

Things I'm pretty sure we _should_ merge:
* #286 -- This one looks good.  I agree with @mattsta that we should probably backport dict.c from Redis, but it seems reasonable to incorporate this one first (as it's a quick one).
* #285, #282, #267 -- Just a tiny grammar fixes, but they look correct to me, so we should merge.
* #268 -- I need to test this one, but generally speaking I like being idiomatic and using ```const char *``` vs. ```char *``` so it's clear that the string isn't going to be modified.
* #260 -- We've been using this in production for ages, and as of yet it has not ruined everything.  I think we should merge.
* #251 -- This fixes a libuv compile error, and I favor it over the similar #258 as the non-static declaration isn't necessary at all as far as I can tell.

Things we _might_ want to merge:
* #279 -- This is probably _technically_ correct, but it's not something that really bothers me one way or the other.  There are only a few calloc calls in hiredis, and they vary on argument order (when creating just 1 thing).
* #264 -- This one looks fine to me, but I'm only mildly familiar with this TCP option.  Just read up on it and I don't see how it would cause any issues.
* #261 -- I vote yes on this one, but @pietern mentioned that it would break downstream packages, so I'm curious in what way that would be.
* #254 -- I would like some input from fancier individuals such as @mattsta or @badboy.  :smiley:
* #250 -- IMHO I can see why this could be useful (in the case where a custom ```free``` was being used), but is not something I have personally run into.
* #239 -- I'll investigate and test this myself, but on first glance it looks good.

So that takes us back roughly a year for pull requests.  I am going to familiarize myself with the ```ng``` branch next and see about moving that forward.  I think however this is a good start.  Most of these are very small and should be pretty safe.

Cheers guys!
Mike

**Comment by mattsta** [comment]
All the PRs above look good (with changes where necessary).  I've got them in a local `develop` branch and I'll push it up here later today.

**Comment by mattsta** [comment]
`develop` updated with:

f28872c Cleanup tabs and end of line whitespace
dad0516 Update dependency list in Makefile
9abfdf9 Build static library by default
1d2b4d3 Generate pkgconf during build
cc20232 Fix errno error buffers to not clobber errors
ba3e74c Refactor reading code into read.c
0cacb48 Fix sds building with C++
6a00a46 Fix redisAppendCommand error result
0c9ff5b Add GLib 2.0 adapter
e30c96e Add empty pointer check in error cleanup
d1e820d Add error check in redisContextInit
b6a8607 Fix redisvFormatCommand format parsing
9a753b4 Add API to free hiredis (sds) formattings
1b392eb Add API to free hiredis (char *) formattings
85c6bfb Fix build under kfreebsd
9b83ddc Fix clang analyzer warning
7c4d255 Add support for SO_REUSEADDR
a1bc89b Improve calloc() correctness
9c57314 Cleanup libuv adapter
40f7035 Improve redisAppendCommandArgv performance
3315c09 Use stricter function argument types
865a368 Fix README typos
2d814b8 Fix minor comment problems
abbd340 Fix README typo
2a6dbdd Free string if it is unused
a1f6ce0 Add syntax highlighting to README.md

Test/read/check those commits and keep suggesting a few more fixes/changes for the next version!

**Comment by badboy** [comment]
How about including the following patch to avoid the ugly warning:

```
/usr/include/features.h:148:3: warning: "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
      [-W#warnings]
```

Patch:
```patch
diff --git i/fmacros.h w/fmacros.h
index 9e5fec0..1beee89 100644
--- i/fmacros.h
+++ w/fmacros.h
@@ -3,6 +3,7 @@
 
 #if !defined(_BSD_SOURCE)
 #define _BSD_SOURCE
+#define _DEFAULT_SOURCE
 #endif
 
 #if defined(__sun__)
```

**Comment by mattsta** [comment]
Any more requests before `develop` gets promoted to `master` in a few days?

**Comment by mattsta** [comment]
Creating new version tomorrow.  Looking at the release page, the last proper release was over two years ago.  Whoops.

**Comment by badboy** [comment]
All good things are worth waiting for. (or in German: Was lange währt, wird endlich gut)

**Comment by mattsta** [comment]
0.12.0 is done as of https://github.com/redis/hiredis/tree/7b51834c165133cf6816b1991920a55bdc64ea78

We can add any bug fixes in 0.12.x versions and the next major release will be 1.0.0.

**Comment by mattsta** [comment]
oh, and big thanks to @michael-grunder and @badboy for doing all the real work of figuring out exactly _what_ to add/fix and _how_ to add/fix things out of the hiredis issues/PR backlog.  :)

**Comment by pietern** [comment]
Nice! Great work.

**Comment by mattsta** [comment]
At this point it's mostly open source gardening.  You did all the real great work years ago.  :)

**Comment by badboy** [comment]
I'm happy to contribute here. Again thanks to all of you.
