### ISSUE TITLE
Missing SETERRNO after connect failure

### ISSUE THREAD

**Issue by halybang** [redis/hiredis#291]
There is a missing call to SETERRNO in function static int _redisContextConnectTcp(...).
This will make it incompatible when compile with mingw.
Old code:

```
if (connect(s,p->ai_addr,p->ai_addrlen) == -1) {
    if (errno == EHOSTUNREACH) {
     ....
    }
}
```

Should be change to:
```
if (connect(s,p->ai_addr,p->ai_addrlen) == -1) {
    SETERRNO;
    if (errno == EHOSTUNREACH) {
     ....
    }
}
```

**Comment by mattsta** [comment]
Closing because we can't figure out what this means.

**Comment by halybang** [comment]
When compile with mingw in Windows:
If a call to connect() failure, you should get the error return by connect() function before determinate what is error [ if (errno == ) {...} ]. This done by call to WSAGetLastError() or call your macro: SETERRNO.
Missing call to SETERRNO, the variable errnox will not be update to lastest error ( if call connect() failure). So, check it by using IF always failure if we get an error before.
This affect if we use loop connect()/failure/reconnect() on same Redis context.
You can see in your code again, you always call to SETERRNO before check *errno* variable. But, you are missing when call to connect() function.

**Comment by badboy** [comment]
You're referring to the Windows port of hiredis. This repository has no Windows support at the moment and there is no `SETERRNO` macro, so for now your patch is not necessary ;)

**Comment by badboy** [comment]
You're referring to the Windows port of hiredis. This repository has no Windows support at the moment and there is no `SETERRNO` macro, so for now your patch is not necessary ;)

(Figured this out looking through https://github.com/redis/hiredis/pull/52)
