### ISSUE TITLE
A strange spot in intlen() method, line 671, hiredis.c

### ISSUE THREAD

**Issue by jacky--wang** [redis/hiredis#295]
intlen()  is used to calculate the number of bytes needed to represent an integer as string

If the argument passed is the smallest integer, that is **INT_MIN** in limits.h
``` i = -i```
The value of i will be unchanged after the assignment, still be a negative number. A general way might be to use an unsigned integer instead of i. 

I report it just because the overall code looks somewhat strange. Since the purpose of that line should be convert negative to positive, but it does not absolutely correct. And in fact,  the conversion is not necessary in this case.

Project **hiredis**, Branch: **master**

**Comment by mattsta** [comment]
Good point.  We can collapse that entire check down to:

```diff
diff --git a/hiredis.c b/hiredis.c
index 0297361..e8d9a5b 100644
--- a/hiredis.c
+++ b/hiredis.c
@@ -188,11 +188,8 @@ static void *createNilObject(const redisReadTask *task) {
 
 /* Calculate the number of bytes needed to represent an integer as string. */
 static int intlen(int i) {
-    int len = 0;
-    if (i < 0) {
-        len++;
-        i = -i;
-    }
+    /* If negative, add one to length for '-' sign. */
+    int len = (i < 0) ? 1 : 0;
     do {
         len++;
         i /= 10;
```
