### ISSUE TITLE
 Connect and Disconnect callbacks with an additional arg for private data  ! 

### ISSUE THREAD

**Issue by saivamsi75** [redis/hiredis#298]
Use Case:
If  hiredis  being used in  asynchronous mode, then the callers should update their data structures upon on disconnect/connect like updating the flags or removing the redis context from their data structures.  Today, there is no way to pass the private data as an argument to these callbacks, so  having this facility would be very handy and reduces additional code in the caller modules .

For an instance, each thread maintains its own  global  data structure and redis client context is also saved in its data structure. So when disconnect happens , the callback need to update this data structure like removing the context or invalidating the context. This can be addressed in two ways:
1. Maintaining an array of entries that contain thread ID and and  data structure specfic to the thread.
   In  Connect /disconnect  call backs, getting the  thread global data strcuture and updating the context.
2. The above overhead can be simply avoided by introducing an additional arg to provide the private data to connect and disconnect call backs.

**Comment by hmartiro** [comment]
Maybe I'm misunderstanding, but can you just use the `void* data` inside `redisAsyncContext` to point to your data structure? That's worked for me in a multithreaded library using hiredis.

**Comment by michael-grunder** [comment]
Closing the old issue but you are able to use the `data` pointer for arbitrary user-supplied data as mentioned.
