### ISSUE TITLE
net.h file link error for c++

### ISSUE THREAD

**Issue by zade** [redis/hiredis#303]
hiredis.h is wrapped with "
#ifdef __cplusplus  
extern "C" {  
#endif
"
but net.h is not. So when I used net.h in c++, it links error with message like "
undefined reference to `redisContextSetTimeout(redisContext*, timeval)'
".

Why net.h is not same with hiredis.h?

**Comment by duckie** [comment]
You are not supposed to use the `net.h` functions directly but those from `hiredis.h` or `async.h`. `net.h` is intended to be used by hiredis when compiling with a C compiler, not to be used from C++ by a user. 

But if you need it so bad, you can add wrap yourself the `#include` directive inside an `extern "C"` block.

**Comment by zade** [comment]
So why redisContextSetTimeout function not defined in hiredis.h but in net.h ? I think this is a common function used often .

**Comment by badboy** [comment]
`redisSetTimeout` is defined in hiredis.h, doesn't this do what you want?
