### ISSUE TITLE
Pipelining without reply

### ISSUE THREAD

**Issue by Daemon22** [redis/hiredis#305]
Hello,
I'm using pipeline on command that I do not need the reply of the.
Do I have to use the redisGetReply() anyway like this and just free the reply?

redisAppendCommand(context, "APPEND key %s", str) 
redisAppendCommand(context, "PERSIST key")
redisGetReply(context, &reply);
freeReplyObject(reply);
redisGetReply(context, &reply);
freeReplyObject(reply);

**Comment by badboy** [comment]
Yes, Redis will still send a reply, so you have to read it to remove it from the buffer.

**Comment by Daemon22** [comment]
Thanks
