### ISSUE TITLE
In async calls,  is there a way to free the reply by user instead of by hiredis after the callback

### ISSUE THREAD

**Issue by echoma** [redis/hiredis#313]
hiredis free the reply immediatelly after the callback. how can I make hiredis to not do this, I would like to free the reply by myself.

**Comment by ppLorins** [comment]
Sorry, I can't answer your question . But why do you need this and at which point will you do the free operation manually ?

**Comment by badboy** [comment]
Nope, there's no way to handle the reply-freeing yourself. You probably just want to copy out the relevant data and store it.

**Comment by echoma** [comment]
@ppLorins   I am using hiredis with a coroutine library. When I got a redisReply object, I will resume the coroutine. But the redisReply object was freed by hiredis when the CPU context switch to the coroutine.

@badboy  as you say, I wrote a copy function. so far it works great.

**Comment by echoma** [comment]
@badboy I've written a dupRedisReply() function which clones a reply. May I send a pull request?

```C
redisReply* dupReplyObject(redisReply* reply)
{
	redisReply* r = (redisReply*)calloc(1, sizeof(*r));
	memcpy(r, reply, sizeof(*r));
	if(REDIS_REPLY_ERROR==reply->type || REDIS_REPLY_STRING==reply->ype || REDIS_REPLY_STATUS==reply->type)	//copy str
	{
		r->str = (char*)malloc(reply->len+1);
		memcpy(r->str, reply->str, reply->len);
		r->str[reply->len] = '\0';
	}
	else if(REDIS_REPLY_ARRAY==reply->type)	//copy array
	{
		r->element = (redisReply**)calloc(reply->elements, sizeof(redisReply*));
		memset(r->element, 0, r->elements*sizeof(redisReply*));
		for(uint32_t i=0; i<reply->elements; ++i)
		{
			if(NULL!=reply->element[i])
			{
				if( NULL == (r->element[i] = dupRedisReply(reply->element[i])) )
				{
					//clone child failed, free current reply, and return NULL
				        freeReplyObject(r);
					return NULL;
				}
			}
		}
	}
	return r;
}
```

**Comment by badboy** [comment]
I'm not sure we need this in the core library.

**Comment by echoma** [comment]
I'am not sure either, so I came to ask you first. 
So just forget it :D

**Comment by badboy** [comment]
In any case, we have it around in an issue if we ever decide to need it.

**Comment by stephan-blueriver** [comment]
+1 for adding it to the core library.
