### ISSUE TITLE
can't run example/example.c on mac OS

### ISSUE THREAD

**Issue by ppLorins** [redis/hiredis#320]
I compile example.c successfully ,   but can't run on mac os, here is what the error look like : 

![image](https://cloud.githubusercontent.com/assets/5534049/7005515/0a384b5e-dcab-11e4-8455-4069b2bb83d2.png)

There only one  libhiredis.dylib file locate in the hiredis's root directory, no dylib file whose name is "libhiredis.0.12.dylib".
 I know how to debug such a lib-dependence issure on linux by run a "ldd -r", but have no idea how to deal with it on macOS  .Any ideas to fix the issure ? thank you !

**Comment by badboy** [comment]
Try the following please:
Compile the example using make:
```
make hiredis-example
```

Then run it with:

```
./examples/hiredis-example
```

Still got an error?

**Comment by ppLorins** [comment]
yep, it worked！ I notice it use libhiredis.a to link the outout execution file.     And all the example is the compile-target defined in the Makefile file, thanks a lot sir!
