### ISSUE TITLE
issue in hiredis.h

### ISSUE THREAD

**Issue by ahju** [redis/hiredis#321]
Hi, I am using hiredis.h in my program, and when I compile my program an error return "/usr/local/include/hiredis/hiredis.h:158: error：expected unqualified-id before numeric constant". I checked that the line of 158 in hiredis.h is a struct :
struct {
        char *path;
    } unix;//this is line 158

Is there any complicit in centos when using hiredis.h?

**Comment by carlosabalde** [comment]
Same problem here using CentOS 6.5 and hiredis 0.13.0 (no problems with 0.12.1).

**Comment by olive-oasis** [comment]
I had the same problem when I compile with hiredis.
Check out commit d8145d79ce715054980938c751067ebaa541573c and issue #31.
You must use C99 compiler when you compile your code. (or 0.12.1)

**Comment by ahju** [comment]
no problems when I use 0.12.1

**Comment by olive-oasis** [comment]
Have you compiled your program with C99 compiler (v 0.13.0)??

**Comment by carlosabalde** [comment]
I forced C99 in the Varnish module I'm using hiredis + did a minor fix and it's working for me: https://github.com/carlosabalde/libvmod-redis/commit/f5e00d49024bb3b8714e4079a780a8458bce30f5 Thanks!

**Comment by badboy** [comment]
This is indeed a small regression. hiredis itself was compiled with c99 before anyway, but now it can't be build with anything lower. I will probably change this to work with everything else (if the `unix` is the only problem, who even made the decision to define `unix` to `1` in c89? gnaaah!)

**Comment by bachwehbi** [comment]
I have the same issue on ubuntu 14.04 and gcc v4.8.2

```
gcc -o example example.c -I../ -lhiredis
../hiredis.h:158:7: error: expected identifier or ( before numeric constant
     } unix;
       ^
```

If i set the language standard to c99 it compiles just fine

```
gcc -std=c99 -o example example.c -I../ -lhiredis
```

**Comment by ncopa** [comment]
I don't think it is possible to require that all projects using hiredis needs to use c99. For example, kamailio does not build with c99 atm.

We should probably avoid using names that might collide.

**Comment by ncopa** [comment]
Something like this (and fix all places using those structs):
```diff
diff --git a/hiredis.h b/hiredis.h
index 092ded2..17e8683 100644
--- a/hiredis.h
+++ b/hiredis.h
@@ -151,11 +151,11 @@ typedef struct redisContext {
         char *host;
         char *source_addr;
         int port;
-    } tcp;
+    } c_tcp;
 
     struct {
         char *path;
-    } unix;
+    } c_unix;
 
 } redisContext;
 
```

I know this breaks the API but IMHO, the current API is broken already.

**Comment by badboy** [comment]
It doesn't break any public API to rename this, so we're free to name it whatever we want. I'll change that ASAP and will release a bugfix this week.

**Comment by badboy** [comment]
Fixed. Release upcoming.
