### ISSUE TITLE
SONAMEs and ABI compatibility

### ISSUE THREAD

**Issue by thomaslee** [redis/hiredis#327]
Or: "backward compatibility between hiredis releases?"

A SONAME change implies ABI-incompatible changes in a shared library.

Prior to v0.12.1, hiredis was explicitly setting its SONAME=0.10 implying each release from 0.10.x upward was ABI-compatible with the release before it. From 0.12.1 onward, hiredis sets the SONAME of its shared libraries to the MAJOR.MINOR version of each respective release.

From a quick objdump comparison between v0.13.1 and v0.11.0, I can't see functions in 0.11.0 that are not in 0.13.1 -- it's possible that other things have changed to break compatibility between 0.11.x-0.12.x and 0.12.x-0.13.x, but I'm wondering if that's actually the case.

Is 0.13.1 backward compatible with 0.12.1 and 0.11.0? If so, any possibility we could reconsider the way SONAMEs change between minor version bumps? It's kind of a pain for packaging hiredis downstream (e.g. Debian requires an entirely new binary package for each SONAME change so that multiple versions of the same potentially-backward-incompatible package can run side-by-side with one another. I'm not familiar enough with RedHat's policies to say if they do the same, but I'd be surprised if they didn't.)

More information available here: https://www.netfort.gr.jp/~dancer/column/libpkg-guide/libpkg-guide.html#sonameapiabi

See also the discussion on debian-mentors, where I'm asking silly questions about the topic: https://lists.debian.org/debian-mentors/2015/05/msg00041.html

**Comment by badboy** [comment]
Looking into it.

From what I understand right now they _should_ be fully backward-compatible in the `SONAME` way, so it is just a matter of providing the correct SONAME, right?
You're right in that all functions from 0.11 are in 0.12.x and 0.13.x as well. We changed an exposed structure (`redisContext`) to contain some info, but this doesn't change the user-facing API. Would such a change break ABI compatibility?

**Comment by badboy** [comment]
One more thing: If we would use SONAME=0, we would commit to not breaking API compatibility in all following 0.x released, correct?

**Comment by badboy** [comment]
> Signs of binary incompatibility include: function declaration change, change of "struct" contents, and changing semantics of functions (hard to detect).

Ok, that answers the question regarding 0.12/0.13

So now our current options are: Stick to `SONAME=0.13` for the remaining 0.x releases, explicitely _NOT_ breaking any ABI compatibility, that means not changing structs and functions.

**Comment by thomaslee** [comment]
> One more thing: If we would use SONAME=0, we would commit to not breaking API compatibility in all following 0.x released, correct?

I'm not 100% sure if the relationship between SONAMEs and version numbers / file names is so strict, but that certainly seems to be what most folks do.

> So now our current options are: Stick to SONAME=0.13 for the remaining 0.x releases, explicitely NOT breaking any ABI compatibility, that means not changing structs and functions.

I think so. At least, that'd certainly make my life easier :smiley: I've got a patch for 0.13.1 that I'm planning to use on the Debian packaging for 0.13.1 that should do the right thing if you want an easy PR.

And of course, it's fine if you change the SONAME when ABI compatibility *does* change too, though obviously my preference from a downstream perspective would be for that to happen somewhat infrequently -- assuming hiredis is considered stable by its users/developers.

**Comment by antirez** [comment]
For future versions one my think of making the API completely opaque from the point of view of the structures used, so that it is possible to commit only in the functions fingerprint but the internal structures may be redesigned completely.

To do this the user should never pass structures but obtain *handles* in form of pointers. Sometimes this is limiting, sometimes not really... depends on the kind of library. For *hiredis* probably this could be done easily.

**Comment by badboy** [comment]
Well, I want to be a good citizen as well and thus keeping stability where possible makes perfect sense (especially if we make life of packagers and users easier). 
I'd say we can stick to 0.13 for now, but I will read up on this.

@antirez: We already hand out pointers, pointers to a `redisContext` struct. So for what I understand, this makes `redisContext` part of the ABI and when we change it we break it (which was done in the last release). I consider all existing functions pretty much stable already.

**Comment by antirez** [comment]
@badboy there is a trick where in the header file you actually alias (typedef) the redisContext name to `void*`, even if inside the lib itself instead you use the actual structure of course. This is useful in two ways:

1. The structure is no longer part of the ABI.
2. The structure is opaque and basically protected from *smart* users from accessing the internals.

However you need accessor functions for everything, like `redisGetErrorStringPtr(reply)` or alike.

**Comment by badboy** [comment]
Hm, that would mean we break a whole lot of other things, i.e. user code.
Let's just keep redisContext stable :D

**Comment by antirez** [comment]
Yep, that's why I specified "For future versions one may think of". Once you break the API for other reasons you may consider to break it in a way that makes future breakage less common.

**Comment by thomaslee** [comment]
Sounds great -- thanks!

**Comment by badboy** [comment]
I now set a explicit soname version (9644a96a4849be185e4b9bb39ceb19bcdae4cd4e), I hope I don't accidentallly break it again.
