### ISSUE TITLE
redisBufferRead early return affecting redisGetReply timeouts

### ISSUE THREAD

**Issue by alexyoung91** [redis/hiredis#332]
```c	
rv = redisSetTimeout(c, tv); // tv is 1s
if (rv == REDIS_ERR) {
	subscriber_set_error("redis: %s", c->errstr);
	return NULL;
}

while (subscriber_is_running()) {
	rv = redisGetReply(c, (void**)&reply);
	if (rv == REDIS_ERR) {
		if (c->err == REDIS_ERR_IO && errno == EAGAIN) {
			c->err = 0; // stop redisBufferRead from returning early
			continue;
		}
		subscriber_set_error("redis: %s", c->errstr);
		break;
	}

	...
}
```

Above is a snippet of a blocking subscriber I have implemented using the synchronous API. When using a timeout with redisGetReply and EGAIN occurs, i have to set c->err to 0 to stop redisGetReply from continuously looping due to redisBufferRead early return. It doesn't seem good practise to manually set c->err, is the early return intended behaviour for such a use case and if not is there something that can be done to avoid manually setting c->err?

**Comment by badboy** [comment]
Currently clearing the error state yourself is the way to go. This also make it clear that you handled that error and you know what you are doing.
I don't think we can change it in a backwards-compatible way.

Hopefully this helps you. Feel free to re-open the issue if this causes other bugs or you have an idea how this should be handled better.
