### ISSUE TITLE
mget issue

### ISSUE THREAD

**Issue by limbo127** [redis/hiredis#334]
hello, 
when using mget redis command with hiredis, reply->element[i]->str send me null whereas redis-cli send me the rigth values.
Exemple : 
reply = redisCommand(c,"MGET 829297961@327168");
 reply->element[0]->str => null 

redis-cli > mget 829297961@327168
1) "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"

regards, 
Nicolas Prochazka

**Comment by badboy** [comment]
Is it really `NULL` or just an *empty* string?

```c
reply = redisCommand(c,"MGET foo");
printf("parsed length: %d\n", reply->element[0]->len);
printf("String: '%s'\n", reply->element[0]->str);
printf("strlen: %d\n", strlen(reply->element[0]->str));
```

gives me:

```c
parsed length: 20
String: ''
strlen: 0
```

In C strings are null-terminated, so a *string* of just zero bytes appears to be empty, but the data is still there.

I don't think this is a bug, feel free to re-open if necessary.

**Comment by limbo127** [comment]
ok, thanks for that, in my case reply->element[0]->type == nil

in fact the issue comes with concatenation of MGET key 
s = sdscatprintf(s, " %s", key);
reply = redisCommand(c,"MGET %s",s);
does not work ( key not found ) 
but with s = sdscatprintf(s, "%s", key);  // no space before %s
does work 

so when i concatenate a lot of key, with 
s = sdscatprintf(s, "%s %s", s,key);   
it does not work. 

I'm not using pipeling command, just MGET and MSET
Regards

**Comment by badboy** [comment]
`redisCommand` does it's own interpolation, from the README:

> The specifier %s interpolates a string in the command, and uses strlen to determine the length of the string:

Thus if you first concatenate all keys into `s` and then pass them as a single value to `redisCommand` it will indeed pass this one as _one single argument_

If you have multiple keys, it's best to use `redisCommandArgv`, where you can simply pass an array of all arguments.

**Comment by limbo127** [comment]
ok, thanks it 's working very well with redisCommandArgv.
Regards, 
NIcolas Prochazka
