### ISSUE TITLE
No answer from sentinel

### ISSUE THREAD

**Issue by pgroen** [redis/hiredis#336]
If i make a connection to sentinel, PING works perfectly.. However if I send the command : SENTINEL masters, I expect an ARRAY with approx. 38 entries, but in fact it is a string which is empty...

Am I missing something? A reply is just that, a struct storing the reply from the server without interpretation..

My Code :  
    /* Get the master ip-structure from the sentinel.. */
    reply = static_cast<redisReply*>(redisCommand(c,"SENTINEL", "masters"));
    if ( reply->elements > 0 )
    {
        for ( size_t j = 0; j < reply->elements; j++) {
            printf ("(%u) %s\n", j,  reply->element[j]->str);
        }
    }
    freeReplyObject(reply);

Regards,

Peter

**Comment by badboy** [comment]
Is `reply->elements` actually `> 0`?

**Comment by pgroen** [comment]
Beste Jan-Erik Rediger

If done through hiredis, then yes.. If done through redox.. No, but 1
with an empty string...

-- 
Open Systems Development
Peter M. Groen
Het Buitenwater 54
2235 TB  Valkenburg (Zuid-Holland)
Mobiel : +31 6 811 0 3537
Email  : pgroen@osdev.nl
www    : http://www.osdev.nl
Skype  : peter_m_groen


On Tue, 09 Jun 2015 09:08:25 -0700, Jan-Erik Rediger wrote :

**Comment by badboy** [comment]
Investigating.

**Comment by badboy** [comment]
Ah, well. I guess I see your problem. You should always check the actual returned type, then it's easier to figure out what's going on. In your case: `reply->type == 6`, which is a `REDIS_REPLY_ERROR`.

Why you're asking? You're holding it wrong! (sorry, pad pun)
`redisCommand` takes a format string and adds all remaining arguments according to this string. But your string is `"SENTINEL"` which doesn't include any format specified. See https://github.com/redis/hiredis#synchronous-api for more.

Fix: use on of the following:

```c
redisCommand(c, "SENTINEL masters");
redisCommand(c, "SENTINEL %s", "masters");
```

**Comment by pgroen** [comment]
Hi Jan-Erik,

Thank you for your suggestion. We've already tried that without any success.
Maybe I'm missing something else, but this is the reply :

===[ Code ] ===

    /* Get the master ip-structure from the sentinel.. */
    printf( "===[ Sentinel Query ]===\n" );

    reply = static_cast<redisReply*>(redisCommand(c,"SENTINEL %s",
"masters"));

    printf( "Reply Type = %u\n", reply->type );
    printf( "Reply String = %s\n", reply->str );
    printf( "Reply Int = %u\n", reply->integer );
    printf( "Reply elements = %u\n", reply->elements );

    if ( reply->elements > 0 )
    {
        for ( size_t j = 0; j < reply->elements; j++) {
            printf ("(%u) %s\n", j,  reply->element[j]->str);
        }
    }

    freeReplyObject(reply);

===[ /Code ]===

==[ OUTPUT ]==

===[ Sentinel Query ]===
Reply Type = 2
Reply String = (null)
Reply Int = 0
Reply elements = 1
(0) (null)

==[ /OUTPUT ]==

If I query the same ip / portnumber (Sentinel) with telnet the response is :

Trying 172.31.226.202...
Connected to 172.31.226.202.
Escape character is '^]'.
SENTINEL masters
*1
*38
$4
name
$10
the_master
$2
ip
$14
172.31.226.204
$4
port
$4
6379
$5
runid
$40
bf6f964833e8fe9ca01e662426136165100ae6e3
$5
flags
$6
master
$16
pending-commands
$1
0
$14
last-ping-sent
$1
0
$18
last-ok-ping-reply
$3
670
$15
last-ping-reply
$3
670
$23
down-after-milliseconds
$5
60000
$12
info-refresh
$4
5886
$13
role-reported
$6
master
$18
role-reported-time
$9
766832389
$12
config-epoch
$1
9
$10
num-slaves
$1
5
$19
num-other-sentinels
$1
5
$6
quorum
$1
2
$16
failover-timeout
$6
180000
$14
parallel-syncs
$1
6

Hope this helps..

-- 
Open Systems Development
Peter M. Groen
Het Buitenwater 54
2235 TB  Valkenburg (ZH)
+31 6 811 0 3537

**Comment by badboy** [comment]
Check the output format of `sentinel masters` again: it's a nested array.
Example from redis-cli:

```
127.0.0.1:26380> sentinel masters
1)  1) "name"
    2) "mymaster"
    3) "ip"
    4) "127.0.0.1"
    5) "port"
    6) "6380"
    7) "runid"
    ....
```

Again: _always_ check the type of each reply you use:

```
    printf("Reply elements[0] Type = %u\n", reply->element[0]->type);
```

gives you `2`: an array.

**Comment by nidhhoggr** [comment]
Following works for me:

  reply = redisCommand(c,"SENTINEL %s","masters");
  printf("PING: %s\n", reply->str);
  if (reply->type == REDIS_REPLY_ARRAY) {
    for (j = 0; j < reply->elements; j++) {
      for (k = 0; k < reply->element[j]->elements; k++) {
        printf("%s\n", reply->element[j]->element[k]->str);
      }
    }
  }
