### ISSUE TITLE
./hiredis-test fails with Unix socket error

### ISSUE THREAD

**Issue by xennygrimmato** [redis/hiredis#338]
I cloned the repo and did the following:
1. make
2. ./hiredis-test

I got this error:

```
Testing against Unix socket connection (/tmp/redis.sock):
Connection error: No such file or directory
```
This issue is same as Issue #125 .
The step suggested as a solution on that issue is to uncomment the unixscoket lines in the redis.conf file:

```
# unixsocket /tmp/redis.sock
# unixsocketperm 755
```

However, on my machine, the file /etc/redis/redis.conf doesn't exist, but /etc/redis/6379.conf does exist.
When I uncomment the 2 lines mentioned in #125 , the test still fails.

**Comment by badboy** [comment]
Yeah, not every system has the config in the same place.
Did you restart Redis? Does it even use that config file? Does it create a socket file?

**Comment by xennygrimmato** [comment]
```sudo ./hiredis-test``` worked.
