### ISSUE TITLE
We've get REDIS_REPLY_STATUS and reply->str 'OK'. What is that?

### ISSUE THREAD

**Issue by ujlim** [redis/hiredis#346]
We use hiredis 0.11.0 and redis 2.8.8.

Our application met the error of REDIS_REPLY_STATUS. After that time it continue to do wrong and log that error util we restart. 

We found REDIS_REPLY_STATUS has reply->str 'OK'. What does mean?

Now we stop its continuous wrong doing by adding code to setup a new connection.
But we want to know the way to avoid REDIS_REPLY_STATUS,  its cause and
that 'OK' is really okay.

**Comment by badboy** [comment]
It means that the command replied with a status message of "OK". Which is the documented response for a lot of commands and is no bug or error or wrong doing.

```
127.0.0.1:6379> SET foo bar
OK
```

**Comment by ujlim** [comment]
Please. check this issue again. 

Our application have code as like following.
Every time, we get 'REDIS_REPLY_ARRAY' when our application go well. About once a month it happen that REDIS_REPLY_STATUS and reply->str 'OK' then our application go into malfunction.


if (reply->type == REDIS_REPLY_ARRAY) {
    // Normal execution logic
} else {
      if ( reply->type == REDIS_REPLY_ERROR ) {
            // Error Treatments
      } else if (reply -> type != REDIS_REPLY_ARRAY ) {
            //  HERE! We get REDIS_REPLY_STATUS and reply->str 'OK'
      }
}


}

**Comment by badboy** [comment]
hiredis only parses what it receives from Redis. If you get a `REDIS_REPLY_STATUS`, it received this status.

1. Check your code again. Which commands are you sending in which order?
2. Do you re-use the connection object from another thread? hiredis is not thread-safe. Such usage can thus lead to wrong results
3. If none of the above works out, check the received commands on Redis directly (either using MONITOR or by capturing the network requests directly)
