### ISSUE TITLE
redisGetReply returns REDIS_ERR_IO

### ISSUE THREAD

**Issue by darshan-ghumare** [redis/hiredis#353]
Hi,

When I am using RocksDB as backend for LedisDB then redisGetReply returns REDIS_ERR_IO but this won't when I used LevelDB.
Please help.

Thanks,
Darshan

**Comment by badboy** [comment]
I have no idea of RocksDB, LedisDB or LevelDB nor do I know your code. 
If hiredis returns `REDIS_ERR_IO`, you need to check `errno` to find out what is wrong.
