### ISSUE TITLE
a few questions about async calls

### ISSUE THREAD

**Issue by echoma** [redis/hiredis#358]
* If err of the context returned by redisAsyncConnect() is not NULL, should I use  redisAsyncFree() or redisAsyncDisconnect() to free this context?
* In the callback function set by redisAsyncSetConnectCallback(), if status is not REDIS_OK, should I use redisAsyncFree() or redisAsyncDisconnect() to free this context?
* In the callback function set by redisAsyncSetDisconnectCallback(), should I use redisAsyncFree() or redisAsyncDisconnect() to free this context?
* When I want to actively close the connection, can I use redisAsyncFree() instead of redisAsyncDisconnect()?
* After I called redisAsyncFree() or redisAsyncDisconnect(), I use redisAsyncConnect() to create new context immediately which set the same callback functions as the previous context. Will the callback functions be invoked with the previos context? It seems that redisAsyncDisconnect() will not clean everything immediately.

**Comment by echoma** [comment]
I see... the bug mentioned in #359 is the reason that my app crash when I call redisAsyncFree() and redisAsyncDisconnect(). But still, I am confused with when a redisAsyncFree() call should be made. It seems that if a connection is not established, redisAsyncFree() will lead to crash.

**Comment by badboy** [comment]
1. Right after a call to `redisAsyncConnect`, `ac->err` should always be `0` afaik. If not, can you give an example which error pops up?
2. If the onConnect callback is called with `REDIS_ERR` the context will be disconnected (and the inner context freed) after that callback anyway. No need to call it yourself (atleast that's what I get from the code right now)
3. The same applies. The context is already disconnected and the inner context will be freed.
4. You should call redisAsyncDisconnect`, which will correctly handle flushing all pending replies and calling the callbacks as necessary. It will also make sure the inner context is freed upon completion of the other tasks.
5. `redisAsyncFree` and `redisAsyncDisconnect` might do their work asynchronously if there are pending replies to be processed. `redisAsyncConnect` will create a new context object. The old context might still call your callbacks when necessary. (Does this answer the question? I'm not sure I get your question right, maybe provide a short example?)

I will look into the bug (#359) and see if we need to revert the commit.

I hope I could answer your questions. If there are still some left, feel free to re-open this issue.

**Comment by xiaotaoz** [comment]
For item 1, if the destination ip is unreachable, e.g. 1.2.3.4, the ac->err is not 0
