### ISSUE TITLE
commit 1db17f257b1999114c699e77e204f1a91143e5ad create a new bug

### ISSUE THREAD

**Issue by echoma** [redis/hiredis#359]
in 1db17f257b1999114c699e77e204f1a91143e5ad :  redisBufferRead: Clear REDIS_CONNECTED flag when server closed connection

in __redisAsyncFree()  [async.c:275], see the following code:
```
 if (ac->onDisconnect && (c->flags & REDIS_CONNECTED)) {
        if (c->flags & REDIS_FREEING) {
            ac->onDisconnect(ac,REDIS_OK);
        } else {
            ac->onDisconnect(ac,(ac->err == 0) ? REDIS_OK : REDIS_ERR);
        }
    }
```
if the REDIS_CONNECTED flag is cleared, the async onDisconnect callback function will never be called.

**Comment by badboy** [comment]
Ok, I could verify that it causes problems, even with our very basic example.
We just have too many states in hiredis ¬_¬

I will revert the code.

**Comment by olgeni** [comment]
Hi, can you roll a minor release once this is reverted? I got caught by this a few times :)
