### ISSUE TITLE
redisAsyncConnect failed in cygwin or msys(Windows)

### ISSUE THREAD

**Issue by owt5008137** [redis/hiredis#360]
stdout or stderr output
```
redis connect to 127.0.0.1:6379 failed, msg: setsockopt(TCP_NODELAY): Invalid argument
```

**Comment by badboy** [comment]
Right now we set the NODELAY option for all connections (not sure why we do this). Seems this option is not supported on Cygwin/Windows. Then again, hiredis does not officially support Cygwin/Windows anyway.

**Comment by echoma** [comment]
https://github.com/echoma/hiredis.cygwin
I am maintaining a fork which works on cygwin. but it's not suitable for production, it only aim to make your dev work more happy.

**Comment by owt5008137** [comment]
@echoma thanks
