### ISSUE TITLE
document example has a error?

### ISSUE THREAD

**Issue by wapeyang** [redis/hiredis#361]
redisContext *c = redisConnect("127.0.0.1", 6379);
if (c != NULL && c->err) {
    printf("Error: %s\n", c->errstr);
    // handle error
}
======
actually it is.
if(c==NULL && c->err)
in file example/example.c it is.

**Comment by badboy** [comment]
Your proposed check is still wrong ;)
Atleast the current example doesn't crash. But I will update it anyway.
