### ISSUE TITLE
redis3.0

### ISSUE THREAD

**Issue by udoyu** [redis/hiredis#362]
Does it supply redis-cluster?

**Comment by badboy** [comment]
> Hiredis supports connecting to an individual server. Any clustering is to be implemented on top.
([Pietern in April 2014](https://github.com/redis/hiredis/issues/237#issuecomment-40491215))

Therefore: yep, it does support Cluster. It does not bring any special tools, automatic redirection or special Cluster handling though. Anything useful is too be implemented on top. 
There is currently no roadmap to include it in hiredis directly.
