### ISSUE TITLE
static inline functions are not within extern C

### ISSUE THREAD

**Issue by rikvdh** [redis/hiredis#364]
Hi all,

Actually the complete sds.h is not inside an `extern C {`. This causes issues when hiredis is included in C++.

Why not put the extern C at the top of hiredis.h?

https://github.com/redis/hiredis/blob/master/hiredis.h#L107-L109

Thanks,

Rik

**Comment by echoma** [comment]
I am using hiredis with g++ without any problem. 
What problem do you have exactly?

**Comment by rikvdh** [comment]
I'm compiling my code with -Wold-style-cast and -Werror, now I need to make an exception for every file where hiredis is included.

**Comment by owt5008137** [comment]
@rikvdh You can use this way to include hiredis.h
```
extern "C" {
#include "hiredis/hiredis.h"
}
```
