### ISSUE TITLE
"Connection timed out"

### ISSUE THREAD

**Issue by wrz19900218** [redis/hiredis#365]
our client may sometimes receive null reply, and just print "Connection timed out", we analyzes that our redis server(our redis server is a distributed redis paltform which based redis) takes a high pressure and it really sends a reply a long time after it receives request. My question is can we set hiredis timeout higher?(we think the problem is hiredis cannot wait for the reply from redis and closed the fd itself)
thank you very much~

**Comment by wrz19900218** [comment]
we use raw epoll_wait, instead of libevent, ae and so on. non-blocking and async

**Comment by echoma** [comment]
I am doing this in this way:  Use a timer, When timeout,  free the asyncContext. So far so good.

**Comment by wrz19900218** [comment]
did you find the "setting timeout internal" method in hiredis?(non-blocking and async)
and what is exactly the timeout internal hiredis set default?

thx~

**Comment by echoma** [comment]
do you mean this redisContextSetTimeout() here : https://github.com/redis/hiredis/blob/master/net.c#L247
This is for blocking mode only.
I don't find a non-blocking timeout interface in hiredis.

**Comment by wrz19900218** [comment]
thx first~
no, I mean although I use non-blocking mode, it must have timeout internal(is it right?)
so if non-blocking timeout interface does not exist, where is its default timeout internal?

**Comment by echoma** [comment]
I think that it's implemented by the operatiing system TCP stack. But I don't know how to tune this.

**Comment by rangan337** [comment]
Looks like adding this explicitly to *hiredis* was vetoed down in https://github.com/redis/hiredis/issues/152

**Comment by xiaotaoz** [comment]
@wrz19900218 @echoma 
I happened to study the same question several days ago, below info is fyi:
system configuration is: /proc/sys/net/ipv4/tcp-syn-retries
used for control how many times we will retry.

tcp_syn_retries is not an exact calculation.

It is input into a calculation which estimates how long that many
retransmits (with suitable backoff applied) will take, and that time
estimte in turn determines the time limit for when we'll kill the
connection attempt.

Feel free to update the documentation in
Documentation/networking/ip-sysctl.txt to more closely match the
behavior.

The logic is in net/ipv4/tcp_timer.c:retransmits_timed_out().

On Linux we can
int syncnt = 1;
int syncnt_sz = sizeof(syncnt);
setsockopt(sockfd, IPPROTO_TCP, TCP_SYNCNT, &syncnt, syncnt_sz);
to reduce (or increase) the number of SYN retries per connect per socket.

**Comment by echoma** [comment]
Thanks, @xiaotaoz
