### ISSUE TITLE
we support redis cluster for hiredis

### ISSUE THREAD

**Issue by deep011** [redis/hiredis#366]
@badboy 
Hi, we support redis cluster for hiredis that based on hiredis-0.13.1.
Can you help me review it and will i can pull request for this?

github:  https://github.com/vipshop/hiredis-vip
some examples: https://github.com/vipshop/hiredis-vip/wiki

think you very much!

**Comment by w3hacker** [comment]
@deep011 正需要

**Comment by arr2036** [comment]
There's absolutely no reason to include cluster support in hiredis.  As one of the maintainers said, it should be implemented on top of hiredis.  That could be a separate library, or implemented by the application.

**Comment by badboy** [comment]
It's still good to know about the project and I will take a look at it when I've got time.

**Comment by arr2036** [comment]
If it does get merged, can it please be built as a separate library, so there's a clean distinction between the code that deals with the protocol, and the code that deals with representing the state of the cluster.

**Comment by badboy** [comment]
I'm not even talking about merging yet ;)

**Comment by w3hacker** [comment]
@deep011 hiredis不会断线重连 咋办呢 我是phper 不是很会写c 求帮助

**Comment by deep011** [comment]
@w3hacker ,Please give your code.
