### ISSUE TITLE
cannot parse list

### ISSUE THREAD

**Issue by usergoodvery** [redis/hiredis#370]
Hi,

I could be missing something, but I am trying to parse the output of "zrange 'BF' 0 -1", which in the redis-cl environment returns a list, but in my c program I am unable to see the same list:

roughly my code flows along the lines of, using blocking mode:

void *reply;

va_start(ap,format);
reply=redisvCommand(ctx, format, ap);
va_end(ap);

if (!reply) error();
if (reply->type==REDIS_REPLY_ERROR) error();
if (reply->type != REDIS_REPLY_ARRAY) error();
syslog(LOG_INFO, " RESULT: Received (%d) elements ", reply->elements);

I get zero elements, so obviously cannot loop, but no logical errors as per the conditionals above.
Can you please provide feedback as to what I am doing wrong here?

regards

**Comment by badboy** [comment]
Did you consider the fact that the sorted set could indeed be empty (= nonexistent)?

**Comment by usergoodvery** [comment]
As per my post, the same command manually returns a populated list in the redis client environment. i am trying to retrieve the same list programatically.

**Comment by usergoodvery** [comment]
Hi
I think I worked out what the issue was. hiredis doesn't like  the  apostrophe round BF as in "zrange 'BF' 0 -1". if I remove that, then programming semantics are OK. It works though with the apostrophe in the coomand line client. 

Seems like a feeble issue though for a mature client like hdredis; surely it should be able to cope with that, or issue some feedback if doesn't like it.

**Comment by badboy** [comment]
`redisvCommand` sends the command based on the format you give it. This format is split by spaces. It thus send the literal `'BF'` as a key (that is a 4-character key). Of course this doesn't work.

`redis-cli` on the other hand is a smart command line tool, which does a lot more with your input, such as correctly parsing quote-surrounded text.
