### ISSUE TITLE
For redisAsyncContext, user or hiredis itself is reponsible for freeing the context with error?

### ISSUE THREAD

**Issue by xiaotaoz** [redis/hiredis#371]
in example-libevent.c, below code already has a note mentioning there will be a leak here.
If real product, we may try different destinations, then free the contexts with error(e.g. unreachable IP) and use the available ones.

But who should be responsible for freeing this context with err?
If let hiredis user take the job, there will be many issues since some cases the context was freed by hiredis but user didn't know that and continue to use it.

Code:
   redisAsyncContext _c = redisAsyncConnect("127.0.0.1", 6379);
    if (c->err) {
        /_ Let *c leak for now... */
        printf("Error: %s\n", c->errstr);
        return 1;
    }

**Comment by echoma** [comment]
my experiences：
```
redisAsyncContext c = redisAsyncConnect(...)
if(NULL==c) return;
if(c->err)
{
    ////user should free it
    return;
}

void connect_callback(c, status)
{
    if(status!=REDIS_OK)
    {
        //let it go, hiredis will free *c
        return
    }
    else
    {
        //user should free it
        return
    }
}
```

**Comment by xiaotaoz** [comment]
Thanks! @echoma
