### ISSUE TITLE
How to add new commands for asynchronous api after the event_base_dispatch() has been called?

### ISSUE THREAD

**Issue by deep011** [redis/hiredis#374]
I read the asynchronous example in  example-libevent.c file.
After the event_base_dispatch() function was called, How to add other new commands for this event_base?

**Comment by badboy** [comment]
You don't. That's the whole point of an event library: it will spin up a loop to wait for events and calls your callbacks on those events.

**Comment by deep011** [comment]
That means if i want execute additional commands after the event_base_dispatch() had called, i must create an new evevt loop?

**Comment by badboy** [comment]
You either need to add new event and event handlers or launch an additional thread which works along side the thread running the event loop.
Please lookup how a event loop works and how you need to work with it. This is not a hiredis-specific issue.

**Comment by deep011** [comment]
Hi, @badboy ,thank you! But i was a little confused.
If use an additional thread to run the event loop, maybe the code is follow.
But i test it and not all keys can be writed to redis. Whether the code is wrong?
If so, please show me a correct examples, thank you very much! I need it ;)


int count, start, end, middle;

void getCallback(redisAsyncContext *c, void *r, void *privdata) {
    redisReply *reply = r;
    count ++;
    printf("count: %d\n", count);
    if (reply == NULL) 
	{
        printf("reply is null\n");
        printf("count: %d\n", count);
        printf("error: %s\n", c->errstr);
		return;
	}	
	if(count == end - start)
	{
		redisAsyncDisconnect(c);
	}
}

void connectCallback(const redisAsyncContext *c, int status) {
    if (status != REDIS_OK) {
        printf("Error: %s\n", c->errstr);
        return;
    }
    printf("Connected...\n");
}

void disconnectCallback(const redisAsyncContext *c, int status) {
    if (status != REDIS_OK) {
        printf("Error: %s\n", c->errstr);
        return;
    }
    printf("\nDisconnected...\n");
}


void* event_run(void *args)
{
    struct event_base *base = args;    
    event_base_dispatch(base);
    printf("event_run end\n");
    return NULL;
}

int main(int argc, char **argv)
{
    struct event_base *base = event_base_new();
    pthread_t thread_id;
    int i;
    int ret;
    
    count = 0;
    start = 0;
    middle = 100;
    end = 200;

    redisAsyncContext *c = redisAsyncConnect("127.0.0.1", 12301);
    if (c->err) {
        printf("Error: %s\n", c->errstr);
        return -1;
    }

    redisLibeventAttach(c,base);
    redisAsyncSetConnectCallback(c,connectCallback);
    redisAsyncSetDisconnectCallback(c,disconnectCallback);
    
    for(i = start; i < middle; i ++)
    {	
        ret = redisAsyncCommand(c, getCallback, &count, "set %d %d", i, i);
        if(ret != REDIS_OK)
        {
            printf("c->err: %s\n", c->errstr);
        }
    }
	
    pthread_create(&thread_id, NULL, event_run, base);

    for(i = middle; i < end; i ++)
    {
        ret = redisAsyncCommand(c, getCallback, &count, "set %d %d", i, i);
        if(ret != REDIS_OK)
        {
            printf("c->err: %s\n", c->errstr);
        }
    }
	
    printf("all commands added, count: %d\n", count);

    pthread_join(thread_id,NULL);

    return 0;
}

**Comment by badboy** [comment]
hiredis is _not_ thread-safe. You should not use one context from multiple threads. This _will_ break.

**Comment by deep011** [comment]
You said "launch an additional thread which works along side the thread running the event loop", how can i do with it? Give me some examples?

**Comment by deep011** [comment]
In one thread, event_base_dispatch() would block, so if i want continue execute commands, what i can do?

**Comment by badboy** [comment]
I really gave you all the information already: hiredis is _not_ thread-safe, you cannot re-use a context object in another thread. Therefore you have to create a new context in the other thread to use.

**Comment by deep011** [comment]
Sorry, i really can't understand, could you give me some examples? I neet it!

**Comment by deep011** [comment]
I just want to create one context, one event_base and just call event_base_dispatch() one time, then it can handle my commands continuously.
Can hiredis asynchronous api works like that?
Or it just can handle commands before event_base_dispatch() called, if i want handle later commands, i must recreate context, event_base and recall event_base_dispatch() ?
I searched on the internet, but few answers can help me.

**Comment by echoma** [comment]
@deep011 you do not need to care about the network event things, event_base_dispatch() will notify hiredis when there is some data to read. your callback will be invoked if there is a Reply.

I think that you are a Chinese, so Chinese version:
很简单：redisLibeventAttach()会让hiredis把他自己的fd事件注册到libevent上，event_base_dispatch()会在有网络事件的时候通知hiredis去收发数据。 hiredis收到完整的reply后就会调用你的getCallback()函数了。
在这个过程中你可以继续发很多请求，不受影响的。

**Comment by deep011** [comment]
@badboy @echoma Thank you to help me!
Now, i had know how to send commands continuously with hiredis asynchronous api, maybe the code is like follow(in the main thread, i can send commands as many as possible):

```c
static aeEventLoop *loop;
list *l;
pthread_mutex_t lmutex = PTHREAD_MUTEX_INITIALIZER;
int ok_count, total_cmd_count;

void getCallback(redisAsyncContext *ac, void *r, void *privdata) {
    redisReply *reply = r;
	
    ok_count ++
    if(ok_count >= total_cmd_count)
    {
        printf("ok count: %d\n", ok_count);
        redisAsyncDisconnect(acc); 
    }
}

void connectCallback(const redisAsyncContext *c, int status) {
    if (status != REDIS_OK) {
        printf("Error: %s\n", c->errstr);
        return;
    }

    printf("Connected...\n");
}

void disconnectCallback(const redisAsyncContext *c, int status) {
    if (status != REDIS_OK) {
        printf("Error: %s\n", c->errstr);
        return;
    }
    
	printf("\nDisconnected...\n");

    aeStop(loop);
}

void *event_run(void *args)
{
    aeMain(loop);
    return 0;
}

void handle_event(aeEventLoop *el, int fd, void *privdata, int mask)
{
    listIter *iter;
    listNode *node;
    redisAsyncContext *ac = privdata;
    
    int i, count = 0;
    
    if(ac == NULL)
    {
        printf("error: privdata is null\n");
        return;
    }
    
    if(listLength(l) == 0)
    {
        return;
    }    

    pthread_mutex_lock(&lmutex); 
    while(listLength(l) > 0) {
        node = listFirst(l);
        i = *(int *)(listNodeValue(node));
        listDelNode(l, node);
        redisAsyncCommand(ac, getCallback, NULL, "set %d %d", i, i);
    }
    pthread_mutex_unlock(&lmutex);    
}

int main(int argc, char **argv)
{
	int i, begin, end;
    pthread_t thread_id;

	begin = 0;
	end = 1000;
        ok_count = 0;
    redisAsyncContext *ac = redisAsyncConnect("127.0.0.1", 34501);
    if (ac->err) {
        printf("Error: %s\n", ac->errstr);
        return -1;
    }

    loop = aeCreateEventLoop(64);
    redisAeAttach(loop, acc);
    redisAsyncSetConnectCallback(acc,connectCallback);
    redisAsyncSetDisconnectCallback(acc,disconnectCallback);

    int sd_notice = socket(AF_INET, SOCK_STREAM, 0);
    if (sd_notice < 0) {
        
        return -1;
    }

    l = listCreate();
    
	total_cmd_count = end - begin;

    pthread_create(&thread_id, NULL, event_run, loop);

	for(i = begin; i < end; i ++)
	{
        int *va = malloc(sizeof(*va));
        *va = i;
        pthread_mutex_lock(&lmutex);    
        listAddNodeTail(l, va);
        pthread_mutex_unlock(&lmutex);

        aeCreateFileEvent(loop, sd_notice, AE_WRITABLE, handle_event, acc);
    }
	
    pthread_join(thread_id,NULL);
	
	return 0;
}
```

**Comment by echoma** [comment]
so, problem solved, right?

**Comment by deep011** [comment]
Yes, thank you very much ;)
