### ISSUE TITLE
redisAsyncCommand reach redis after 60 seconds

### ISSUE THREAD

**Issue by week008** [redis/hiredis#376]
I send "subscribe" command with redisAsyncCommand, but the command reach redis server after 60 seconds. I used libev, After ev_loop(EV_DEFAULT_ 0), I send the "subscribe" command in the other thread. If it has bug when Hiredis flushing async command to buffer?

**Comment by badboy** [comment]
Can you show a minimal example?

**Comment by week008** [comment]
#define RECONNECT_WAIT_TIME_SEC 2

void subCallback(redisAsyncContext *c, void *r, void *priv) 
{
    redisReply *reply = (redisReply *)r;
    if (reply == NULL) return; 
    if ( reply->type == REDIS_REPLY_ARRAY && reply->elements == 3 ) 
	{ 
        if (strncmp(reply->element[0]->str, MESSAGE, strlen(MESSAGE)) == 0
			&& reply->element[1]->str != NULL 
			&& reply->element[2]->str != NULL)
		{ 
            LogDebugEx("Received[subCallback] channel %s: %s",
          //          (char*)priv,
                    reply->element[1]->str,
                    reply->element[2]->str );
			return ;
        } 
    } 
}  

bool RedisSub::asynConnect()
{
	c = redisAsyncConnect(ip.c_str(), port);
	if (c->err) 
	{
        /* Let *c leak for now... */
        LogErrorEx("Error: %s", c->errstr);
        return false;
    }
	return true;
}

void RedisSub::run() 
{
	bool first = true;
	while (true)
	{
		if (!first)
			sleep(RECONNECT_WAIT_TIME_SEC);
		if (!asynConnect())
		{
			continue;
		}
	    redisLibevAttach(EV_DEFAULT_ c);
	    redisAsyncSetConnectCallback(c,RedisSub::connectCallback);	
	    redisAsyncSetDisconnectCallback(c,RedisSub::disconnectCallback);
	    ev_loop(EV_DEFAULT_ 0);
		first = false;
	}
}

I send subscribe command in another thread, but redis server receives this command after 60 seconds

bool RedisSub::subscribe(const std::string value)
{
	if (NULL == c)
		return false;
	else
	{
		int ret = redisAsyncCommand(c, subCallback, this, "%s %s", SUBSCRIBE, value.c_str());
		LogInfoEx("%s, ret:%d, %s %s", __FUNCTION__, ret, SUBSCRIBE, value.c_str());
		if (REDIS_OK == ret)
			return true;
		else
			return false;
	}
}

**Comment by badboy** [comment]
Is the other thread using the same `redisAsyncContext` object as th main thread?

**Comment by badboy** [comment]
[`libev` doesn't really like to be used from multiple threads simultaneously](http://doc.dvgu.ru/devel/ev.html#threads_and_coroutines).
`redisAsyncCommand` internally calls `ev_io_start` on the loop you created. Doing this from another thread does not work as expected There might be ways to work around this using `ev_async_send`, but I do not know enough of libev to give you an example how to use it. 

For now this is still true: hiredis is not thread-safe. Do not use a context object from multiple threads.

**Comment by week008** [comment]
I also try to use libevent. it has the same problem and redis server received "subscribe” command after a long time， Not 60 seconds.
I use redisAsyncContext object in multiple threads, Even if I added a lock, it's no use.

**Comment by badboy** [comment]
As I said: that's a limitation of the used event libraries, not of hiredis.
