### ISSUE TITLE
problem with compile if env has DEBUG variable

### ISSUE THREAD

**Issue by artofhuman** [redis/hiredis#381]
I have some problem with install gem `hiredis` and compile hiredis extension.

See trace:

```
ERROR:  Error installing hiredis:
        ERROR: Failed to build gem native extension.

    /home/artofhuman/.rvm/rubies/ruby-2.2.0/bin/ruby -r ./siteconf20151121-12872-jj3ndx.rb extconf.rb
gcc -std=c99 -pedantic -c -O3 -fPIC  -Wall -W -Wstrict-prototypes -Wwrite-strings true  net.c
```

In the last string exists true argument. 

I found in https://github.com/redis/hiredis/blob/master/Makefile#L43-L44
exist debug option wich conflicted with env variable `DEBUG`

For reproduce it just set `export DEBUG=true`

**Comment by amallia** [comment]
This can be closed @badboy
