### ISSUE TITLE
cmake build  Policy CMP0043 is not set: Ignore COMPILE_DEFINITIONS_<Config> properties.

### ISSUE THREAD

**Issue by tsuibin** [redis/hiredis#384]
tsuibin@compiler01:~/src/LeanClub/src/redis3m/build$ cmake ..
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   unit_test_framework
--   date_time
--   regex
-- Configuring done
CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0043 is not set: Ignore COMPILE_DEFINITIONS_<Config> properties.
  Run "cmake --help-policy CMP0043" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

how to fix it ?

**Comment by badboy** [comment]
Looks like you're trying to compile [redis3m](https://github.com/luca3m/redis3m), so all bugs and issues should be reported there.
