### ISSUE TITLE
Example fails to compile: undefined reference to redisCommand

### ISSUE THREAD

**Issue by hoschiCZ** [redis/hiredis#386]
How to reproduce: Clone the today's (27.12.2015) repo, adjust the #import <hiredis.h> to suit your file location (for me: #import "hiredis/hiredis.h", compile.

It fails right in the linker:
```
main.c:(.text+0x10f): undefined reference to `redisConnectWithTimeout'
main.c:(.text+0x16a): undefined reference to `redisFree'
main.c:(.text+0x1a1): undefined reference to `redisCommand'
main.c:(.text+0x1ce): undefined reference to `freeReplyObject'
```

**Comment by badboy** [comment]
Are you using hiredis as a dependency in your own project?
In that case you either need to link against a compiled hiredis library or compile it statically into your own project.
