### ISSUE TITLE
Got "TypeError: must be convertible to a buffer, not bytearray" in PyPy

### ISSUE THREAD

**Issue by ethe** [redis/hiredis#393]
PyPy version: 4.0.1 with GCC 4.8.4 on linux2
System: Ubuntu 15.04 x84 64bit
Error line: `./site-packages/redis/connection.py line 360` `self._reader.feed(self._buffer, 0, bufflen)`

Find where define attribute `_reader`: `line 314` `self._reader = hiredis.Reader(**kwargs)`
`self._buffer`'s type: `line 293` `self._buffer = bytearray(socket_read_size)`

I tried to change `self._reader`'s type, do like this: `self._reader.feed(buffer(self._buffer), 0, bufflen)`, but if i do this, process would crash.

**Comment by badboy** [comment]
Not directly a hiredis issue, but a problem with [hiredis-py](https://github.com/redis/hiredis-py/).
Looks like hiredis-py is just not compatible wiht PyPy. As I have never used it nor am I a Python dev I have no idea how to fix it and rely on external contributions only.

**Comment by ethe** [comment]
Thanks for your help.
