### ISSUE TITLE
When to cleanup after redisAsyncCommand?

### ISSUE THREAD

**Issue by wjackson** [redis/hiredis#395]
I have Perl bindings for the async features of hiredis: https://github.com/wjackson/hiredis-raw

I'd like to add support for PUBLISH/SUBSCRIBE but ran into a snag.

One thing that changes with PUB/SUB is that there are potentially multiple replies for every request. My bindings wrongly assume there's a single reply for each request. That's an easy correction except for one thing: how do I know when it's safe to cleanup the provided callbacks?

My bindings are used liked this:

`$redis->command(['GET', 'foo'], sub { say shift });`

In the non-subscribe case it makes sense for me to increment the ref counter for the anonymous sub when it's provided and decrement just after the callback is executed. That way the callback is cleaned up and we avoid memory leaks.

However, that's not appropriate in the subscribe case:

`$redis->command(['SUBSCRIBE', 'mytopic'], sub { say shift });`

In that case, I can't decrement the ref count for the provided anonymous sub after calling it because there will be more replies coming and we're not done.

Is there a clean way to know when async commands are done and it's safe to cleanup their callback? Or do I have to special case SUBSCRIBE?

**Comment by badboy** [comment]
I'm not sure I understand your problem here.
`SUBSCRIBE` gives you a defined reply per channel you subscribed too, and _afterwards_ you get a reply for every message sent to one of the subscribed channels.
This continues as long as the client is connected and subscribed.

Should the single callback you gave be for all published messages? In that case you have to keep it around until you disconnect (so yes, special-casing `(P)SUBSCRIBE` is the answer)

**Comment by wjackson** [comment]
> This continues as long as the client is connected and subscribed.

Yep. My question is how to detect if I'm subscribed. I don't want to have to infer that by observing commands and looking for corresponding replies that indicate the subscription is over.

I just spotted `REDIS_SUBSCRIBED` in the hiredis.h so I'm guessing that's the ticket. I'm probably supposed to check `redisAsyncContext->redisContext->flags` to see if that's set? I'll give that a try. 

Assuming that's right, it might be worth documenting `REDIS_SUBSCRIBED` and `redisContext->flags` in the docs. Want a PR for that?

**Comment by wjackson** [comment]
Yes the `REDIS_SUBSCRIBED` flag was what I needed.
