### ISSUE TITLE
Make redisReply.len size_t

### ISSUE THREAD

**Issue by OndrejBudai** [redis/hiredis#397]
I'm wondering why redisReply.len is defined as int. As it denotes the size of string, therefore the size of array, it should be defined as size_t. It would make the API more self-explanatory and remove the need for casting when comparing with size_t.

**Comment by badboy** [comment]
Legacy decisions. Changing it would mean we break stuff, though this would be a very light break.
As were heading for a next stable version anyway we might as well do it though.
