### ISSUE TITLE
RedisFeed Error

### ISSUE THREAD

**Issue by sharathm** [redis/hiredis#399]
Hi All,

We are currently using `node-redis` to connect to a ElastiCache instance.
Everything runs fine for a while.. but, we see the following error in our nodejs application..

```
nodejs: ../src/reader.cc:191: static Nan::NAN_METHOD_RETURN_TYPE
hiredis::Reader::Feed(Nan::NAN_METHOD_ARGS_TYPE): 
Assertion `redisReaderFeed(r->reader, data, length) == 0' failed.
```

After this, our application crashes and needs to be restarted. 

At first we thought it might be a availability issue since we were running a single instance inside a cluster. 
Then  we thought it might be memory issue and so we upgraded our EC2 instances. 

We do experience some peak in our load but that is ~4000 keys being written to ElastiCache. 
ElastiCache does not show any signs of down time.

Can anyone shed some light as to what could be going on here?

We are running..

`node 4.3.1`
`node-redis 2.4.2`
`node-hiredis 0.4.1`

**Comment by badboy** [comment]
hiredis-node related. Closing.
