### ISSUE TITLE
How to handle async events with libev and hiredis

### ISSUE THREAD

**Issue by emacsuser123** [redis/hiredis#402]
Hi.

I'm trying to develop an application using both hiredis and libevent.
This application has to handle an infinite loop of async events coming from the kernel.
For every event received, a query to the redis server has to be sent, and the response is used for further processing.

I'm having problems trying to find out where the ev_loop call should be placed as well as the redisAsyncCommand (with cb registration).

Using pseudocode, the kernel loop would look like the following:

```
while (m = recv_from_kernel(...)) {
    do_processing(m)
}

```
Prior to that loop, I need a connect to the redis server already established.
Inside the do_processing function, a new command based on the received info has to be sent to the redis server.

I'm following the example included in example-libev.c file.

First, at the very beginning of the main routine, redisLibevAttach is used to attach functions to the redis async context.
Then, redisAsyncSetConnectCallback is used to register the connection cb.
Then, same thing for the disconnection cb.

Then, my kernel loop is executed.

I could include a statement to issue a redisAsyncCommand before the kernel loop, registering the callback associated to event processing.
But this does not work, since the message to be sent is obtained through an infinite loop from the kernel, and at this place would be yet to be received from the kernel.

If I put the ev_loop statement after the kernel loop, then I'm able to get messages from the kernel, but none of the cbs are called at all.
If I put the ev_loop before the kernel loop, then I get the redis server connection/disconnection cbs, but I do not get the redisAsyncCommand callback, because it has been called after calling the event_loop.

If I put the ev_loop after the call to redisAsyncCommand, issued upon receipt of every message from the kernel, then the redis-connect-cb is called upon receipt of first message (not at app startup), then the redisAsyncCommand cb is executed, with the response from the redis server.
But after that, no other message causes any notify from the event loop.

How can I make the ev_loop to work ok with my endless kernel loop, including the connect/disconnect cbs?

Thanks a lot.
-Bob

**Comment by badboy** [comment]
This sounds like your *kernel loop* is completely detached from the libevent loop.
Async hiredis relies on a event library to execute on certain events, so you need to run it.
You have different options to make this work.

1. Do you need Redis commands to be async? If not, use the sync API
2. Integrate your own loop into libevent. If it operates on io events, it might be easy. Or maybe timers can help?
3. Run the libevent loop in another thread. This won't block the main thread then. Depending on what you need to do this could work. hiredis is not thread-safe, you can't share a context object across threads.
4. Run the libevent loop until the first event (look for `EVRUN_ONCE` or similar in the documentation)
