### ISSUE TITLE
How to build hiredis on windows (Visual studio 2010)

### ISSUE THREAD

**Issue by ukrit-himakoon** [redis/hiredis#403]
Is there any guidelines for this?

Thanks

**Comment by badboy** [comment]
the full hiredis project does _not_ support Windows. The parser part can be used on Windows (and is used in several other libraries now), but the rest is not Windows compatible at all.

**Comment by ukrit-himakoon** [comment]
Okay in the case that I would like to create the redis client (dll) on windows is there any recommended library?

**Comment by badboy** [comment]
You can't. Hiredis simply does not work on Windows. There might be a fork around that works (see #52) or you can look for another client.

**Comment by ukrit-himakoon** [comment]
Thanks, for the clarification. 

One last question, I see that some of the files below are working with WIN32 what are they used for?

https://github.com/redis/hiredis/commit/ec229678c22e673e8d48070593f7b028a514882a

**Comment by badboy** [comment]
It's in the commit message: 

> Added support for compiling the parser code with Microsoft Visual C compiler.
> For hiredis-py and others support on windows.

**Comment by NarendraNy** [comment]
Able to generate the hiredis.lib in visual studio 2012/2013. But unable to consume the same lib in application(redis app). Please suggest on this.

**Comment by michael-grunder** [comment]
Hi @NarendraNy,

Unfortunately I don't think anyone that works on hiredis has access to Windows machines and compilers to help diagnose and hiredis itself doesn't officially support Windows AFAIK.

There may be a fork that does but I'm not sure.  Perhaps you could try building this:
https://github.com/MicrosoftArchive/redis/tree/3.0/deps

**Comment by badboy** [comment]
Michael is right, Windows is only partially supported. The parser should work on Windows natively, the rest does not. 
I don't use Windows at all, so there's not much I can help with.

**Comment by hippokylejan** [comment]
You can try building this: https://github.com/kylejan/hiredis-msvc.git

**Comment by RameshKandukuriB** [comment]
> You can try building this: https://github.com/kylejan/hiredis-msvc.git
Does it uses latest hiredis? Will it work on Win64? I can compile it however how to use it, are there any dependencies?
