### ISSUE TITLE
Hiredis does not compile on Windows

### ISSUE THREAD

**Issue by koenvandesande** [redis/hiredis#42]
With Visual Studio 2008, I can't get it to compile.
- On "va_arg(ap,void);", the compiler complains about "error: C2070: 'void': illegal sizeof operand" and "error: C2100: illegal indirection"
- sys/time.h include on Windows should be just time.h
- there is no unistd.h on Windows
- stdarg.h should be included in hiredis.c for va_\* functions

**Comment by NarendraNy** [comment]
Able to generate the hiredis.lib in visual studio 2012/2013. But unable to consume the same lib in application(redis app). Please suggest on this.
