### ISSUE TITLE
Remove the depth limitation

### ISSUE THREAD

**Issue by luin** [redis/hiredis#421]
When parsing a nested result with depth greater than 7, hiredis will return an error (https://github.com/redis/hiredis/blob/d3c7df33a1e278c6f0ae86506e0cbe5de35e36e3/read.c#L310-L314) which doesn't make sense since it's a common case to deal with a nested array (e.g. tree structure).

I found a related pull request: https://github.com/redis/hiredis/pull/70. Should we just remove this limitation now?

**Comment by michael-grunder** [comment]
Closing in favor of #794
