### ISSUE TITLE
How to use hiredis in thread environments?

### ISSUE THREAD

**Issue by chadfurman** [redis/hiredis#424]
I see you say RedisContext and RedisAsyncContext are not thread-safe -- how can I use non-threadsafe code in a threaded environment?  Do I simply create/destroy RedisContext in a mutex?  That doesn't sound like the right path, but maybe I'm wrong?

**Comment by badboy** [comment]
hiredis does no locking internally. So either you wrap a single context in a Mutex (or some other lock) or use a context per thread.

**Comment by chadfurman** [comment]
Thank you.  And what about eredis which claims to be thread-safe but has significantly fewer stars, forks, and watchers?

**Comment by badboy** [comment]
No idea. I don't use it. You should ask the maintainers there.

**Comment by sunnyinchina** [comment]
when I use a context per thread, redisConnect also crashes, can you help me?

such codes are using by several threads

redisContext* redis = redisConnect(RedisIP, nPort);
redisReply *reply = (redisReply*)redisCommand(redis, "set hello 2023");
freeReplyObject(reply);
redisFree(redis);when I use a context per thread, redisConnect also crashes, can you help me?
