### ISSUE TITLE
redisCommandArgv crashes when non-existent redis unix socket connection

### ISSUE THREAD

**Issue by emacsuser123** [redis/hiredis#432]
Hi.

If I connect an app to my local redis server thru unix socket, and afterwards I stop the redis server, my app crashes when a call to RedisCommandArgv is made.
But, on the other hand, if the connection is made thru TCP/IP socket, and then I stop the redis server, any subsequent call to redisCommandArgv returns ERROR.

According to the documentation, I guess the TCP/IP behavior is the expected one. An error is returned to the app, and the redis context is no longer valid.

redis server version: 3.0.7
hiredis version: 0.13

Any ideas?

Thanks.
-Bob

**Comment by michael-grunder** [comment]
Hey,

I can't say for certain what issue you're running into, but I have a decent guess.  I created this simple test program:

```c
int main(int argc, const char **argv) {
    int i = 0;

    /*
     * Ignore SIGPIPE if we have an argument
     */
    if (argc > 1) {
        printf("Ignoring SIGPIPE\n");
        signal(SIGPIPE, SIG_IGN);
    } else {
        printf("Not ignoring SIGPIPE\n");
    }

    redisContext *c = redisConnectUnix("/tmp/bob.sock");
    if (!c || c->err) {
        printf("Can't connect!\n");
        return -1;
    }

    redisReply *r;

    r = redisCommand(c, "SET %s %s", "foo", "bar");
    freeReplyObject(r);

    while (1) {
        r = redisCommand(c, "GET %s", "foo");
        if (r && !c->err && r->type == REDIS_REPLY_STRING) {
            printf("[%d] Returned: %s\n", i, r->str);
        } else {
            printf("[%d] Error: %s (%d)\n", i, c->errstr, c->err);
        }

        sleep(1);
        i++;
    }

    return 0;
}
```

When I run the program without an argument (and therefore not ignoring SIGPIPE), it silently fails for me from the console, but reports a segmentation fault from within valgrind and gdb.

If I ignore the signal, it works and I get this:

```bash
➜  examples git:(master) ✗ ./sock 1
Ignoring SIGPIPE
[0] Returned: bar
[1] Returned: bar
[2] Returned: bar
[3] Error: Broken pipe (1)
[4] Error: Broken pipe (1)
[5] Error: Broken pipe (1)
```

I'm not sure if this is something we would want included in hiredis itself (@badboy would know better), or something that is better handled from the client program itself.

Hopefully this helps!

Cheers,
Mike

**Comment by emacsuser123** [comment]
Hello.

Thanks for the followup on this matter.

The issue I'm running into is the following:

- create unix socket connection to redis server
- send commands to redis server by means of redisCommandArgv
- now, kill the redis server
- send command to redis server (non-existent) by means of redisCommandArgv
- The call to redisCommandArgv makes the app to crash, instead of returning ERROR.
The crash happens when running the application normally, not thru gdb nor valgrind.

I'm not sure why it is behaving as expected on your case. Maybe the redisCommand you're using makes a difference here.

But I can reproduce the same problem over and over again, using redisCommandArgv.

Thanks.
-Bob

**Comment by badboy** [comment]
I'll look into it.

**Comment by emacsuser123** [comment]
Thanks a lot !

**Comment by michael-grunder** [comment]
@badboy @emacsuser123 am i missing something here?  :smiley:

I'm doing exactly that.  I kill the server while the program is running.  If I don't ignore `SIGPIPE` it crashes in hiredis when attempting to write to the (broken pipe) socket.  If I ignore `SIGPIPE` it does not crash.

`redisCommand` vs. `redisCommandArgv` is irrelevant.

Try ignoring sigpipe in your client program and tell me if it still crashes, or comes back properly with a broken pipe error :)

**Comment by badboy** [comment]
@michael-grunder is right. This behaviour of the write function is documented in its man page (`man 2 page`, I actually found it in [this StackOverflow answer](http://stackoverflow.com/a/11552492)):

```
EPIPE  fd is connected to a pipe or socket whose reading end  is  closed.   When  this  happens  the  writing
       process will also receive a SIGPIPE signal.  (Thus, the write return value is seen only if the program
       catches, blocks or ignores this signal.)
```

Catching/Ignoring `SIGPIPE` is up to the user program. If it is ignored, hiredis correctly receives the `EPIPE` error and passes it on.

**Comment by emacsuser123** [comment]
Hi.

I've used your recommendation and it actually works!
Now, SIGPIPE signal is ignored from the app  and the application does not crash when trying to send a redis command to an unavailable redis server.

Thanks a lot.
-Bob
