### ISSUE TITLE
redisvFormatCommand() fails with "%lf" format

### ISSUE THREAD

**Issue by npeer2004** [redis/hiredis#436]
`redisvFormatCommand()` doesn't handle `%lf` properly, it only considers integer formatters after `%l`, and yields an error otherwise.

**Comment by rojingeorge** [comment]
Yes, hiredis does not support `l` modifiers for double. Actually no modifiers at all for double.
`redisvFormatCommand()` formats are designed similar to printf, And printf doesn't need `l` modifiers for double unlike scanf.

**Comment by michael-grunder** [comment]
Closing the issue as it's been answered.
