### ISSUE TITLE
Cannot access memory at address 0x7fc2d4080230

### ISSUE THREAD

**Issue by abigbigbird** [redis/hiredis#442]
code works well most of time, it appeared several times, so far.
the gdb core stack as below:
![image](https://cloud.githubusercontent.com/assets/12706510/16301610/d1b3d128-3978-11e6-804c-76c3213e382d.png)
![image](https://cloud.githubusercontent.com/assets/12706510/16301624/e60ed9b0-3978-11e6-90b8-25ca4f01e27e.png)
os：Red Hat Enterprise Linux Server release 6.4 (Santiago)
gcc version:4.6.3
hiredis version:0.13.3

**Comment by badboy** [comment]
Please post these things as text. Images are not searchable, copyable or easily read.
Also:
* What code did you execute?
* What did you expect to happen?
* What happened instead?

**Comment by abigbigbird** [comment]
I use hiredis in my project,It works fine in most of the time，but there are several times ，it hangs。

## the gdb core stack as below:：
#0 redisBufferRead (c=0x7f26c4013a10) at hiredis.c:800
#1 0x00007f27479e9cd0 in redisGetReply (c=0x7f26c4013a10, reply=0x7f26ea4e7ea0) at hiredis.c:903
#2 0x00007f27479ea02b in __redisBlockForReply (c=0x7f26c4013a10, argc=, argv=, 
argvlen=) at hiredis.c:1010
#3 redisCommandArgv (c=0x7f26c4013a10, argc=, argv=, argvlen=)
at hiredis.c:1035
#4 0x00007f27479d31cc in bfd::codis::CodisClient::RedisCommand (this=0x200ceb0, command=..., tt=0) at src/CodisClient.cpp:995
#5 0x00007f27479d3662 in bfd::codis::CodisClient::RedisCommand (this=0x200ceb0, command=..., tt=0) at src/CodisClient.cpp:1035
#6 0x00007f27479c9f64 in bfd::codis::CodisClient::get (this=0x200ceb0, key=..., tt=0) at src/CodisClient.cpp:152
#7 0x00007f27479e5a18 in bfd::codis::BfdCodis::get (this=0x2130120, key=..., tt=0) at src/BfdCodis.cpp:60
#8 0x000000000050d89e in RedisClientProxy::get (this=0x20e34f0, key=...)
(gdb) p c
$1 = {err = 0, errstr = '\000' , fd = 72, flags = 3, obuf = 0x7f26b40087c8 "", reader = 0x7f26c4013af0, 
connection_type = REDIS_CONN_TCP, timeout = 0x0, tcp = {host = 0x7f26c4013d50 "192.168.*", source_addr = 0x0, port = 19000}, 
unix_sock = {path = 0x0}}
(gdb) p *buf
Cannot access memory at address 0x7f26ea4e3d80


os：Red Hat Enterprise Linux Server release 6.4 (Santiago)
gcc version:4.6.3
hiredis version:0.13.3

**Comment by abigbigbird** [comment]
thanks or sorry，Maybe i am not express my situation，i use a demo work fine all the time which just use set/get command，but when it run on my application ，it hangs！i can't find there are any different between the demo and my application。maybe it is not the hiredis‘s issue，but i don't know what i can do for resolve it。’

**Comment by badboy** [comment]
See the first comment. I can't act without more info.
Also are you using the context object from multiple threads? If so, that is likely the fault.

**Comment by liuxyc** [comment]
as badboy mentioned, hiredis is not thread safe

**Comment by abigbigbird** [comment]
Thanks，Maybe my code‘s fault，i will have a ’unit test to find the bug！Any progress，i would tell you here.
