### ISSUE TITLE
ERR wrong number of arguments for HMSET

### ISSUE THREAD

**Issue by weingithub** [redis/hiredis#444]
I call redisCommand function, the command like that:
hmset D11BA97064C28242739B7A5E06A3887B_178 content 'a plus b'  href just_test.

I got error, and message is ERR wrong number of arguments for HMSET. but I can run this command in redis-cli and it worked fine.

the reason is because the space in single quote. how can I make it work fine when I call redisCommand ?

**Comment by badboy** [comment]
`redisCommand` expects a format string and will simply split on whitespace. It does not handle quotes at all.
You should use:

```c
redisCommand(c, "hmset %s %s %s %s %s", "D11BA97064C28242739B7A5E06A3887B_178", "content", "a plus b", "href", "just_test");
```
This will correctly format the command and handle whitespace without problems.

redis-cli does the quote-splitting for convenience because it is used interactively.
