### ISSUE TITLE
provide interface specifying socket properties(e.g. SO_LINGER)

### ISSUE THREAD

**Issue by xiaotaoz** [redis/hiredis#449]
Can we add a new parameter in all existing connecting API to specify the socket properties, such as SO_LINGER? Or some other ways such as new hiredis API to set them.
e.g.

redisAsyncConnectBind(, +++int socket_flags+++);
redisAsyncConnectBindWithReuse(, +++int socket_flags+++);
redisConnectNonBlock()
....

**Comment by xiaotaoz** [comment]
any update?

**Comment by badboy** [comment]
Adding yet another argument would be a breaking change. I hesitate to do that.
If those flags can be set after connect/bind, you can do so today by accessing the internal file descriptor.

**Comment by badboy** [comment]
Some options can be very well set after the connection is established. At the moment I don't see the need for a (breaking) change to accept arbitrary flags (which wouldn't even work for those that need additional data).
