### ISSUE TITLE
libuv example not printing Connection refused error message.

### ISSUE THREAD

**Issue by dimd** [redis/hiredis#450]
I accidentally ran the libuv example without having my redis server up, and no message was printed.

I then ran the libevent example and the Connection refused message was printed to the stdout.

Shouldn't the same message be printed for the libuv example also?

Edit: libuv version used 1.9.1

**Comment by badboy** [comment]
In theory it should report this error, yes. If it does not I'm happy to merge patches that fix this, though I don't have the time to investigate it.

**Comment by michael-grunder** [comment]
It seems to work fine for me.  I just changed the port in the example program as I have an instance on 6379 that I don't want to take down.

```bash
➜  examples git:(master) ✗ cc example-libuv.c -luv -lhiredis -o example-libuv
➜  examples git:(master) ✗ ./example-libuv
Connecting on port 6388...
Error: Connection refused
```

Cheers,
Mike

**Comment by michael-grunder** [comment]
Closing this issue since it's very old and doesn't appear to be a bug in hiredis.
