### ISSUE TITLE
how should i issue cmds like 'get' after subscribe

### ISSUE THREAD

**Issue by derekzhuo** [redis/hiredis#453]
The requirement is to implement a writer and reader, both of them are clients.
1.reader subscribe msg of channel, say XXX;
2.writer update data on redis server, and publish on the channel XXX;
2.reader receive msg on the channel XXX, and issue other cmds.

The problem here is that there is a limit that other cmds can not be issued after subscribe.
How should i do in this situation?

thks!

**Comment by michael-grunder** [comment]
Hey,

There are a number of ways to do this, but honestly it depends on a lot of things :smiley:.  For instance, is your producer and consumer going to live in one process or will they be separate?

Assuming they are separate processes, the most trivial way to issue commands based on the publish messages you receive is to simply use two context objects.

Essentially, you would create two context objects (one for the subscribe loop, and one to execute commands):

```c
redisContext *readctx = redisConnect("127.0.0.1", 6379);
redisContext *writectx = redisConnect("127.0.0.1", 6379);
```

Then, you can read messages in a subscribe loop, and use your `writectx` variable to execute commands.

```c
redisReply *readreply = redisCommand(readctx, "subscribe %s", "foo");
if (!readreply || readctx->err) {
    fprintf(stderr, "Can't subscribe\n");
    exit(1);
}

freeReplyObject(readreply);

while (redisGetReply(readctx, (void*)&readreply) == REDIS_OK) {
    /* Validate your message, and figure out what you need to execute */
    /* Then use your writectx to send commands */
}
```

You could also use the hiredis async capabilities with the event library of your choosing.  There are examples in for a variety of different libraries in the source tree.

Cheers
Mike

**Comment by derekzhuo** [comment]
What if they live in one process?

**Comment by derekzhuo** [comment]
There is another problem.

I found reader reading quite slow for 320,000 simple key-value data while using sync APIs.

Could this be any faster?

`    //subscribe
    redisReply *subreply = redisCommand(subs_ctx, "subscribe %s", PSCHNL);
    if (!subreply || subs_ctx->err) {
        fprintf(stderr, "Can't subscribe\n");
        exit(1);
    }
    freeReplyObject(subreply);

    int mtid = 0;
    while (redisGetReply(subs_ctx, (void*)&subreply) == REDIS_OK) {
        //get msg from pubsub channel
        freeReplyObject(subreply);

        //read
        for(int keyid = 0; keyid < MAX_UPDATE_EVERY_MT; keyid++) {
            sprintf(key, "%s%d/%s%d", MT_ID, mtid, MT_PRE, keyid);
            sprintf(val, "%s%d%d", "val", mtid, keyid);
            redisReply* readreply = get(read_ctx, key);
            assert(strcmp(readreply->str, val) == 0);
        }

        printf("read meeting complete: %d ", mtid);
        gettime();
        mtid++;
    }`

**Comment by michael-grunder** [comment]
> I found reader reading quite slow for 320,000 simple key-value data while using sync APIs.

You want to pipeline something like that, which is easy to do in hiredis.  Specifically you want to use the `redisAppendCommand` function(s).  Here is a simple example:

Non pipelined:
```c
/* This will send and retrieve one key at a time */
int main(void) {
    redisContext *reader;
    redisReply *reply;
    char val[255];
    int i;

    reader = redisConnect("127.0.0.1", 6379);

    for (i = 0; i < 320000; i++) {
        reply = redisCommand(reader, "GET key:%d", i);
        sprintf(val, "val:%d", i);
        assert(strcmp(reply->str, val) == 0);
    }

    redisFree(reader);
}
```

Pipelined:
```c
#include <stdio.h>
#include <string.h>
#include <hiredis/hiredis.h>
#include <assert.h>

/* This will send every GET command, then read them all back at once */
int main(void) {
    redisContext *reader;
    redisReply *reply;
    char val[255];
    int i;

    reader = redisConnect("127.0.0.1", 6379);

    for (i = 0; i < 320000; i++) {
        redisAppendCommand(reader, "GET key:%d", i);
    }

    for (i = 0; i < 320000 && redisGetReply(reader, (void*)&reply) == REDIS_OK; i++) {
        sprintf(val, "val:%d", i);
        assert(strcmp(reply->str, val) == 0);
        freeReplyObject(reply);
    }

    redisFree(reader);
}
```

```bash
./slowread  1.88s user 3.24s system 36% cpu 14.180 total
./fastread  0.59s user 0.02s system 32% cpu 1.853 total
```

I do recommend reading through the hiredis documentation as a lot of this is explained there.  :smiley_cat:

**Comment by derekzhuo** [comment]
You mean the file README in the project? I have read it yesterday and tested the piplined coed, it is good!!! 
thks.

**Comment by abhit011** [comment]
```
redisReply *readreply = redisCommand(readctx, "subscribe %s", "foo");
if (!readreply || readctx->err) {
    fprintf(stderr, "Can't subscribe\n");
    exit(1);
}

freeReplyObject(readreply);

while (redisGetReply(readctx, (void*)&readreply) == REDIS_OK) {
    /* Validate your message, and figure out what you need to execute */
    /* Then use your writectx to send commands */
}
```

I am also using something like this , but i never receive the message sent from publish command ? 
pRedisReply->str is always NULL ? 

I am using redis-cli.exe to publish like publish foo "hello there..."

**Comment by mhdansari** [comment]
> redisReply *readreply = redisCommand(readctx, "subscribe %s", "foo");
> if (!readreply || readctx->err) {
>     fprintf(stderr, "Can't subscribe\n");
>     exit(1);
> }
> 
> freeReplyObject(readreply);
> 
> while (redisGetReply(readctx, (void*)&readreply) == REDIS_OK) {
>     /* Validate your message, and figure out what you need to execute */
>     /* Then use your writectx to send commands */
> }
> 
> I am also using something like this , but i never receive the message sent from publish command ?
> pRedisReply->str is always NULL ?
> I am using redis-cli.exe to publish like publish foo "hello there..."

Has anyone managed to achieve this? I too have a similar code, but I am not even getting the callback for the second publish.
Basically I have created two redis contexts say, rediscontext1 and rediscontext2. And from rediscontext1 I am subscribing for two channels and defined two different callback functions and from main function I am publishing to channel1 and eventually I get a callback on callback1() function and from within this function I am publishing for channel2 and expecting a callback on callback2() function which is not happening.

any suggestions?

Pseudo code:
`
void callback1()
{
   ……
   redis_context2->publish(channel2)
   waiting on Linux msgrcv funciton

}

void callback2()
{
   ……
   sends message using msgsnd function which will be received by callback1
}

int main()
{
 redis_context1 = redis connect
 redis_context2 = redis connect
 
  redis_context1->subscribe(channel1, callback1)
  redis_context1->subscribe(channel2, callback2)

   redis_context1->publish(channel1)

}

`
