### ISSUE TITLE
junk coming out of redisvCommand

### ISSUE THREAD

**Issue by usergoodvery** [redis/hiredis#454]
Hi,
I sometimes get my commands and arguments padded with junk when run through redisvCommand especially with strings. When I  pre-construct the string via sprintf and feed it into redisvCommand I get what I expect. 
I thought I may have some memory corruption, but my application is instrumented with Valgrind so I kind of got handle on that. I like to think I am the source of the problem,but  I was hoping somebody might offer a hint.

**Comment by michael-grunder** [comment]
Can you post a small sample of code that replicates the problem?

Also requisite question:  Is your program multithreaded?

Cheers,
Mike

**Comment by usergoodvery** [comment]
Hi,

I can't replicate the problem in an isolated way because it just happens in the context of my application at one specific point. Yes it is multi threaded environment, persistent worker threads each with its own handle into redis. I pump many redis commands through the threads it just that one spot where corruption happens, a simple "GET %s:%s".  However as I said earlier, pre-constructing that command with sprintf works fine. I did a quick trace and the corruption happens at
 redisvFormatCommand, where it tries to fetch the string arguments. Below I included the corrupted version of the final string. 
_OPEN:911251beeccd8e006036d8ba7a52e7a3d6113ee3

//correct
'*2#015#012$3#015#012GET#015#012$46#015#012_OPEN:911251beeccd8e006036d8ba7a52e7a3d6113ee3#015#012'

//corrupted
'*2#015#012$3#015#012GET#015#012$10#015#012UH‰åHìð: #015#012'

**Comment by michael-grunder** [comment]
Hey,

It will be hard to help track down the problem if there isn't a way I can replicate it.  That being said, this looks _a lot_ like corruption do to threading in the sense that it's exactly what I would expect from that sort of problem.

Random corruption, hard to reproduce, etc.

It certainly could be a problem in hiredis, but we use it ourselves to pipe many terabytes of data in production and haven't seen any issues like the one you are describing.  We are also using it in a highly threaded way.

**Comment by usergoodvery** [comment]
where a redis context is owned by a thread and is resused within the same thread for successive calls, is there a requirement to "reset" the redis context at some "logical" point  or is issuing freeReplyObject(redis_ptr); suffices?

What I find weird is that even when I limit concurrent threads to one, I still get the problem

**Comment by badboy** [comment]
@usergoodvery: So with a single thread you see the same problem? Reproducible? If so, can you try to find a minimal example so we can take a look? (even a minimal example with multiple threads could help)

If a single redis context is kept in a thread, that should work just fine. You are calling `freeReplyObject` on the reply pointer, correct?

**Comment by usergoodvery** [comment]
Yes even when I limit my workers to one i get corruption at that one particular point. It is reproducible in the sense that in my environment it consistently happens, and issue many redis calls through the engine without issues.

Yes freeReplyObject on reply.

I'll spend some time with gdb and  poke around and see why the memory around redisvFormatCommand and va_list is not bounded correctly.

**Comment by usergoodvery** [comment]
I am closing this one as it appears to be related to my own processing environment. Thanks for everybody who tipped in.
