### ISSUE TITLE
redisAsyncCommand with libev4.20 can not be written immediately, block too long

### ISSUE THREAD

**Issue by webnoise** [redis/hiredis#457]
Hi

  I use example-libev.c to test redisAsyncCommand with libev4.20 under ubuntu 14.04, and hiredis version with git commit hash 5f98e1d35dcf00a026793ada2662f6e1ba77eb17. I issue redisAsyncCommand in another thread every 2 seconds, the first async command callback return immediately, but others callbacks block after 52 seconds. 

  I use wireshark tool to capture the network packet, I found that the reason is the command not write out immediately.

**the logs shows below with time prefix.**

> 1472090477 >>>>>> issue async command
> 1472090477 <<<<<< getCallback2 called
> 1472090479 >>>>>> issue async command
> 1472090481 >>>>>> issue async command
> 1472090483 >>>>>> issue async command
> 1472090485 >>>>>> issue async command
> 1472090537 <<<<<< getCallback2 called
> 1472090537 <<<<<< getCallback2 called
> 1472090537 <<<<<< getCallback2 called
> 1472090537 <<<<<< getCallback2 called

**part code shows below.**

```
int now(){
    time_t seconds;
    seconds = time((time_t *)NULL);
    return seconds;
}

static void getCallback2(redisAsyncContext *c, void *r, void *privdata) {
    redisReply *reply = r;
    int i;
    printf("%d <<<<<< getCallback2 called\n", now());
}

void *thr_fn1(void *arg)
{
    int i;
    for(i=0; i<5;i++) {
        printf("%d >>>>>> issue async command\n", now());
        redisAsyncCommand(rc, getCallback2, NULL, "zrange topush 0 -1");
        usleep(2*1000000);
    }
    return NULL;
}

int main (int argc, char **argv) {
    signal(SIGPIPE, SIG_IGN);
    int         err;
    pthread_t   tid1;

    redisAsyncContext *c = redisAsyncConnect("127.0.0.1", 59379);
    if (c->err) {
        /* Let *c leak for now... */
        printf("Error: %s\n", c->errstr);
        return 1;
    }
    rc = c;

    redisLibevAttach(EV_DEFAULT_ c);
    redisAsyncSetConnectCallback(c,connectCallback);
    redisAsyncSetDisconnectCallback(c,disconnectCallback);
    redisAsyncCommand(c, NULL, NULL, "AUTH %s", "TmpPwd");
    redisAsyncCommand(c, NULL, NULL, "SELECT %d", 6);
    redisAsyncCommand(c, NULL, NULL, "SET key %b", argv[argc-1], strlen(argv[argc-1]));
    err = pthread_create(&tid1, NULL, thr_fn1, NULL);
    ev_loop(EV_DEFAULT_ 0);
    return 0;
}

```

**Comment by michael-grunder** [comment]
Hey,

I have only played with the async functionality in hiredis a bit, but it seems to me that your program will almost certainly fail, because you're using a single `redisAsyncContext` which makes no thread safety guarantees in two threads.  My guess is you're running into a classic race or deadlock.

For one, I believe you have to write specific logic for `libev` if you want to run it threaded.  I don't believe `EV_DEFAULT_` is the loop you want.

**Comment by michael-grunder** [comment]
Closing this old issue since it's not likely still presenting a problem.
