### ISSUE TITLE
Little problem

### ISSUE THREAD

**Issue by JaguXam** [redis/hiredis#458]
Hello.
Sometimes i have error in my node.js srcript.

```
app-0 (err): Error: Redis connection to /tmp/redis.sock failed - write EPIPE
app-0 (err):     at exports._errnoException (util.js:907:11)
app-0 (err):     at WriteWrap.afterWrite (net.js:785:14)

```

Before that, the redis begins to work very slowly.

 nginx + PHP-FPM + nodejs + redis + laravel

**Comment by sinisterstuf** [comment]
Is this problem specific to the hiredis library at all?

**Comment by badboy** [comment]
Nope, looks more like the socket file is gone.
