### ISSUE TITLE
coredump at srscatlen

### ISSUE THREAD

**Issue by enoa2014** [redis/hiredis#460]
Stable most of the time 

 gdb stack:

> Program terminated with signal 11, Segmentation fault.
> # 0  0x00007f7f4a73d751 in memcpy () from /lib64/libc.so.6
> 
> Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.149.el6_6.5.x86_64
> (gdb) bt
> # 0  0x00007f7f4a73d751 in memcpy () from /lib64/libc.so.6
> # 1  0x00007f7f4ac523a5 in sdscatlen (
> 
> ```
> s=0x7f7e7fe73018 "*4\r\n$6\r\nHSETNX\r\n$29\r\ncid:2-1121964960-4-2930133422\r\n$13\r\nno-4-2"..., t=0xba1fc40, len=78) at sds.c:244
> ```
> # 2  0x00007f7f4ac4f990 in __redisAppendCommand (c=0xf73700, cmd=<value optimized out>, len=<v
> # 3  0x00007f7f4ac506e7 in redisvAppendCommand (c=0xf73700, format=<value optimized out>, ap=<
> # 4  0x00007f7f4ac51c1d in redisvCommand (c=0xf73700, format=<value optimized out>, ap=<value
> # 5  0x00007f7f4ac51cd8 in redisCommand (c=<value optimized out>, format=<value optimized out>

and like #394 , cann't make it happen again. 
someone help me explain what went wrong ?

os: CentOS release 6.5 (Final)
hiredis version: 0.11.0

Thanks.

**Comment by dagostinelli** [comment]
FYI: This is the same issue as https://github.com/redis/hiredis/issues/493
