### ISSUE TITLE
redisFree

### ISSUE THREAD

**Issue by ibyte2011** [redis/hiredis#462]
In this func,after free,for example:
`if (c->tcp.host)
        free(c->tcp.host);`
don not set the c->tcp.host = NULL,
Is it safe?

**Comment by amallia** [comment]
Yes, because after `c` is unconditionally freed as well.

```cpp
void redisFree(redisContext *c) {
    ...
    if (c->tcp.host)
        free(c->tcp.host);
    ...
    free(c);
}
```

@badboy, this can be closed
