### ISSUE TITLE
with-timeout branch

### ISSUE THREAD

**Issue by jiaorenyu** [redis/hiredis#463]
I need read a redis with timeout，but there is no function in master branch, I found it in with-timeout branch，but is it stable?

**Comment by michael-grunder** [comment]
Hey,

To set a connection timeout you want to use `redisConnectWithTimeout` https://github.com/redis/hiredis/blob/master/hiredis.h#L164

Once you're connected, you can use the `redisSetTimeout` function, to manage how long hiredis will block while reading or writing to redis.
https://github.com/redis/hiredis/blob/master/hiredis.h#L186

Cheers!
Mike

**Comment by jiaorenyu** [comment]
Thank you very much, it works!
