### ISSUE TITLE
how to use ae event loop(how to run example-ae.c)

### ISSUE THREAD

**Issue by fanbojie** [redis/hiredis#464]
I have  ar ae.c as libae.a, but when i compile example-ae.c, it report undefined reference to `aeCreateFileEvent'

**Comment by badboy** [comment]
The example is currently statically linked to the object file of ae, see [the Makefile](https://github.com/redis/hiredis/blob/with-timeout/Makefile#L103).
I can't help you at the moment with dynamically linking it.
