### ISSUE TITLE
Is hiredis' object destruction functions as thread-safe as the system?

### ISSUE THREAD

**Issue by yeputons** [redis/hiredis#465]
We're using hiredis in multithreaded environment and protect access to `redisContext` with a mutex. At some point we receive pointers to `redisReply`, release the mutex, process the reply, and then call `freeReplyObject()` on it. As far as I can tell, current implementation of `freeReplyObject()` is as thread-safe as `free()` from stdlib is, and it does not do anything with `redisContext` at all.

I'm wondering if there are any possibilities or plans to change that behavior in the future? For example, one may want to recycle `redisReply` objects in a `redisContext` to avoid few system calls.

**Comment by badboy** [comment]
There are no plans to change that behaviour at this time.
If we ever plan to do so, we will consider the threaded usage as well.
