### ISSUE TITLE
Using libhiredis.010 on ubuntu server 12-04 LTS - SEGSEV signal received when not connected or lost connection

### ISSUE THREAD

**Issue by ronigonzalez** [redis/hiredis#470]
HI all, I found this problem with hiredis.
If i am not connected or redis server is down, I receive a SEGSEV executing any command ( no exceptions, directly a signal )
example :
redisReply* reply = 0;
redisContext* context = NULL;
reply = (redisReply*) redisCommand(_context, "SELECT %d", (int)Node );

SEGSEV and not a exception.

this is a obvious example, but if I'm connected to a redis server and lost the connection, finally a Get the same result. 

Should be nice to get an exception or a error code or just a null replay, but never a SEGSEV.

Thank you a lot

**Comment by badboy** [comment]
You're passing a null pointer to `redisCommand`. Don't do that.
All command functions expect a non-null pointer (a valid connection context). 

If another example still segfaults, please provide this. Keep in mind that `libhredis.010` sounds like a really old version. Please upgrade to the latest release of hiredis first.

Until then I close this pull request.
