### ISSUE TITLE
Unchecked malloc 

### ISSUE THREAD

**Issue by graetzer** [redis/hiredis#471]
There is a potential null pointer access in `sdsnewlen` if malloc returns NULL and `const void *init` was set to null as well:
https://github.com/redis/hiredis/blob/be2c4272c434c21149f8603a6f61e5e348539ebe/sds.c#L93

``` c
 #define s_malloc malloc
 // ...
 sh = s_malloc(hdrlen+initlen+1);
 if (!init)
     memset(sh, 0, hdrlen+initlen+1);
 if (sh == NULL) return NULL;
```

**Comment by badboy** [comment]
Indeed. We should just move the null check above the memset check.
Care to send a PR here and to sds?

fun fact: The null check will probably be optimized out in the current code, due to the compiler deciding that `sh` can't be null anymore as it was used in a non-nullable location already.
