### ISSUE TITLE
Question about sentinel implementation

### ISSUE THREAD

**Issue by vin-d** [redis/hiredis#474]
Hi, I'm looking for an API that uses hiredis to implement sentinel support.
Does anything already exists ? or do everybody implement this in their "private code"  ?

Thank you.

**Comment by badboy** [comment]
Sentinel support could be built on top of hiredis. There's no native support in hiredis itself and no plans to integrate it. I have no knowledge of a C library implementing it at the moment.

**Comment by paulcaskey** [comment]
I am also seeking this feature. Maybe I will add it. I wonder if anyone else cares. I'm surprised there's not more demand for this. Redis cluster support instead? I should look at that, but I'm currently very happy with my sentinel setup.
