### ISSUE TITLE
a defect of example-libevent.c

### ISSUE THREAD

**Issue by isfull** [redis/hiredis#475]
example-libevent.c
`redisAsyncContext *c = redisAsyncConnect("127.0.0.1", 6379);
    if (c->err) {
        /* Let *c leak for now... */
        printf("Error: %s\n", c->errstr);
        return 1;
    }`
Need check "c==NULL"
(PS. async.c base on pipeline. how async.c  handle redis cluster?)

**Comment by badboy** [comment]
Indeed. The check is necessary. 
hiredis does not handle Redis Cluster at all. It's up to you to implement it on top or use a library  that does it.

**Comment by isfull** [comment]
thank u
