### ISSUE TITLE
redis with haproxy

### ISSUE THREAD

**Issue by aidevr** [redis/hiredis#477]
I'm using redis with haproxy for failover and I don't want my connection with haproxy to get in an erroneous state once master is down....

**Comment by badboy** [comment]
Is there any actual question or issue you face?

**Comment by aidevr** [comment]
in redisConnect i'm giving the address of haproxy ip and port which has configuration of redis backend servers such that it will always connect with master by doing it provides automatic failover and i don't have to maintain connections with sentinels in my application. But the problem once the master goes down an error is returned on the connection and the connection which is actually with the haproxy gets into an invalid state ...so what i want is to reuse the same connection.

**Comment by badboy** [comment]
hiredis has no knowledge about whether it speaks to haproxy or a Redis node directly. All it sees is a TCP connection. If it encouters a problem with this connection it gets into a failure state.
I don't know how haproxy works, but breaking client connections if upstream goes down seem unfortunate. Talk to the haproxy project to figure it out. Nothing hiredis can do here.
