### ISSUE TITLE
freeReplyObject crash each time.

### ISSUE THREAD

**Issue by litaozhang** [redis/hiredis#478]
I create a thread for redis keyspace event notification.  my application core each time when I edit the listened value in redis database 

(gdb) bt
#0  0xf776ece0 in __kernel_vsyscall ()
#1  0xf674b667 in raise () from /lib/libc.so.6
#2  0xf674cea3 in abort () from /lib/libc.so.6
#3  0xf678aa55 in __libc_message () from /lib/libc.so.6
#4  0xf679271d in _int_free () from /lib/libc.so.6
#5  0xf73f5f47 in free (ptr=ptr@entry=0xf0b00920) at ../../../../../glob/CPLmem/CPL_MEMdlsym.c:148
#6  0xf6a2728e in freeReplyObject (reply=0xf0b00920) at hiredis.c:99
#7  0xf6a6cb8c in cmAPIKeySpaceReply (arg=0x0) at ../../../../../../../obj/target_ind/sde/utas/yang/target_ind/cmApi/cm_core/cm_baseapi.c:2148
#8  0xf7752b2c in start_thread () from /lib/libpthread.so.0
#9  0xf681477e in clone () from /lib/libc.so.6

following is my code

```
while(1)
{
    ret = redisGetReply(connNtfy, (void **)&reply);

    if(ret ==REDIS_OK)
    {
        cmAPIProcessReply(reply); // didn't free reply in this function
    }
    if(reply  != NULL)
    {
        freeReplyObject(reply);
    }
}

pthread_exit(RET_OK);
```

**Comment by badboy** [comment]
Can you provide a minimal working example?
Your simple code snippet doesn't really show the problem and otherwise it's hard to track down what's going wrong.

**Comment by michael-grunder** [comment]
Nothing actionable here (and from 2016) so closing the issue.
