### ISSUE TITLE
Problem in sdsMakeRoomFor() in sds.c #221 

### ISSUE THREAD

**Issue by shashikirang** [redis/hiredis#480]
segmentation fault when trying realloc.
the backtrace is as below:
0 __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:138
1 0x00007f0618b3ee84 in ?? () from /usr/lib/libjemalloc.so.2
0000002 0x00007f0618b332e9 in realloc () from /usr/lib/libjemalloc.so.2
3 0x00007f06182e0c0d in sdsMakeRoomFor (s=0x7f060da0d34b "NM", addlen=addlen@entry=1) at sds.c:221
4 0x00007f06182e154c in sdscatlen (s=s@entry=0x7f060da0d34b "NM", t=t@entry=0x7f06188b3987, len=len@entry=1) at sds.c:379
5 0x00007f06182de354 in redisvFormatCommand (target=target@entry=0x7f060edfb9b0, format=<optimized out>, ap=0x7f060edfb9f8) at hiredis.c:247
6 0x00007f06182e0462 in redisvAppendCommand (c=0x7f060da13000, format=<optimized out>, ap=<optimized out>) at hiredis.c:933
7 0x00007f06182e060d in redisvCommand (c=0x7f060da13000, format=<optimized out>, ap=ap@entry=0x7f060edfb9f8) at hiredis.c:1003
8 0x00007f06182e06d7 in redisCommand (c=<optimized out>, format=<optimized out>) at hiredis.c:1012

Any clue?
or could it be memory corruption ?

**Comment by fenglonz** [comment]
I have the same coredump. Have you known how to fixed it? Thanks!

**Comment by dagostinelli** [comment]
FYI This is related to https://github.com/redis/hiredis/issues/493

**Comment by michael-grunder** [comment]
I think this can be closed as many of the potential culprits have been fixed in newer versions of sds.

Feel free to reopen if it's still happening
