### ISSUE TITLE
Can anyone help me illustrating HSCAN command with hiredis client

### ISSUE THREAD

**Issue by shashikirang** [redis/hiredis#481]

**Comment by badboy** [comment]
What exactly do you need? `HSCAN` is a simple command you can send like any other command, its [return type](http://redis.io/commands/scan#return-value) is clearly defined. You need to extract the cursor and re-issue the command yourself.

**Comment by shashikirang** [comment]
I tried the same with the following syntax:
reply = redisCommand(c,"HSCAN test-hscan 0 match \"100:20:*\" count 10");
I can see the command being sent to redis (while "MONITOR" -ing through redis-cli).

But then , when i try to read the reply as per the repyType,
the reply->elements shows some value and reply->element[index]  contains nothing (no reply->str) 

Is there anything wrong i am doing or should i follow any other approach to achieve this ?

**Comment by badboy** [comment]
`reply->elements` is likely 2, with `reply->element[0]` being of type int or string (check that). and `reply->element[1]` being a (nested) array again, containing the found elements.
Always check the type of each element you touch!

**Comment by shashikirang** [comment]
Sorry !
i think i m missing something !
I did as shown below:

output of command ::
redis /tmp/redis.sock> HSCAN test-scan 0 match "100:21:*" count 10
1) "0"
2) 1) "100:21:1"
   2) "tt211"
   3) "100:21:2"
   4) "tt212"


and reading the reply ::
(gdb) p *reply
$16 = {type = 2, integer = 0, len = 0, str = 0x0, elements = 2, element = 0x8053248}
(gdb) p reply->element[0]
$17 = (struct redisReply *) 0x8053290
(gdb) p *reply->element[0]
$18 = {type = 1, integer = 0, len = 1, str = 0x80532b0 "0", elements = 0, element = 0x0}
(gdb) p reply->element[1]
$19 = (struct redisReply *) 0x80532c0
(gdb) p *reply->element[1]
$20 = {type = 2, integer = 0, len = 0, str = 0x0, elements = 0, element = 0x0}
(gdb)

**Comment by shashikirang** [comment]
Thanks got it !

**Comment by sailorsiraj** [comment]
I am facing the exact same problem. 
Shashikirang, Can you please let me know what you did right to make this work ?

**Comment by shashikirang** [comment]
Hi @sailorsiraj,
Its is something similar to HGETALL and the way you read, except that the
first element will be cursor.

For example:
reply = (redisReply*) redisCommand(rCon,"HSCAN XYZ 0");
                 if ( reply && reply->type == REDIS_REPLY_ARRAY)
                 {
                      //j = 0 will be the cursor reply->element[j]->str
will be the cursor value
                     for (int j= 1, i=0; j< reply->elements; i++)
                     {
                         i= 1, 2, 3, etc will contain the entries from
HSCAN
                         reply->element[j]->elment[i]
                     }

                 }
                 freeReplyObject(reply);

Please let me know if you are unable to figure out with this as well.

-
