### ISSUE TITLE
redisAsyncCommand reply timeout

### ISSUE THREAD

**Issue by fanbojie** [redis/hiredis#482]
how do i control redisAsyncCommand  reply timeout

**Comment by DobbinFox** [comment]
I used an extra timer to redisAsyncCommand reply timeout.

**Comment by PhilipSchmid** [comment]
@dobbinfox do you have some sample code how you solved it? Would be awesome. Thanks.

Regards,
Phliip

**Comment by mnunberg** [comment]
Timeout is now part of the API

**Comment by rreddy-ns** [comment]
Hi @mnunberg does redisAsyncSetTimeout works like health-check timeout? OR
Does this timeout works per request? i.e Can this API helps me to timeout all the pending requests which got timed-out, even if replies are coming for previous requests.

I am facing scenario where few async lookups are taking 10-20 sec when there is high load of lookups are happening at one shot. The connection is live and replies are keep coming. My requirement is to timeout all the pending requests which are timed-out, even if replies are coming for previous lookups.
