### ISSUE TITLE
How to use this Hiredis API ---- void redisAppendCommandArgv(redisContext *c, int argc, const char **argv, const size_t *argvlen)

### ISSUE THREAD

**Issue by 13642245956** [redis/hiredis#483]
I have tried many times, but every time it's not right, who can give an DEMOof use
Thanks！

**Comment by badboy** [comment]
The Readme has some documentation on this: https://github.com/redis/hiredis#pipelining
The `*Argv` variant works similar to the other `*Argv` commands: you give it the number of arguments and a list of those arguments to process.
The `redisAppend` commands are _only_ send once you actually try to get the reply.

Does that help?

**Comment by 13642245956** [comment]
I still can't understand your answer., I used this API to be like this:

`const char *buf[3] = {"get friend", "get name", "get foo"};
	redisAppendCommandArgv(conn, 3, buf, NULL);`

And my redisDB have three key-value : friend-BillGates, name-Jobs, foo--ymw. But redis server reply this: 
`ERR Unknown Command: get friend`.

So， I still need your help.  @badboy  ,THANKS!

**Comment by michael-grunder** [comment]
Hi,

The issue you're having is that you are attempting to pass both `get` arguments in a single string, per key.  Hiredis expects each command argument to be separate, as in {`get`, `friend`}.

Here is a simple script which does basically what you're trying to do:
```c
int main(void) {
    int i;

    const char *buf[3][2] = {
        {"get", "friend"},
        {"get", "name"},
        {"get", "foo"}
    };

    char *result;

    redisContext *c = redisConnect("127.0.0.1", 6379);

    /* Append each GET command */
    for (i = 0; i < 3; i++) {
        redisAppendCommandArgv(c, 2, buf[i], NULL);
    }

    redisReply *r;

    /* Read them back and display */
    for (i = 0; i < 3; i++) {
        if (redisGetReply(c, (void**)&r) != REDIS_OK) {
            printf("Error getting reply\n");
            return -1;
        }

        if (r->type == REDIS_REPLY_STRING) {
            printf("[%s] => %s\n", buf[i][1], r->str);
        } else {
            printf("Key '%s' not found or isn't a string\n", buf[i][1]);
        }

        freeReplyObject(r);
    }

    return 0;
}
```

I hope it helps :smiley_cat:

**Comment by 13642245956** [comment]
Oh, that's the way it is. I know how to use it, :+1:  Thank you ! @badboy @michael-grunder ！It's fun to learn from you.
