### ISSUE TITLE
Library incorrectly rute

### ISSUE THREAD

**Issue by jarriztg** [redis/hiredis#484]
Isnt working 
#include \<hiredis.h\>

`apt install libhiredis-dev` already installed

Needs: `#include "/usr/local/include/hiredis/hiredis.h"`

or:  `gcc myscript.c -o test $(pkg-config --cflags --libs hiredis)`

**Comment by badboy** [comment]
What's the issue here? If you install it to some location you need to make your compiler aware of it. If it is a non-standard location that's what pkg-config does for you.

**Comment by jarriztg** [comment]
So, if I have a new language and I want add hiredis, how can I add a "pkg-config" in CMakeLists?

**Comment by jarriztg** [comment]
always will be this location? `/usr/local/include/hiredis/hiredis.h`

**Comment by badboy** [comment]
I don't know about cmake. 
And I also looked it up: `/usr/local/include/` is in the default search path of gcc, so `#include <hiredis/hiredis.h>` should already work without passing aditional include directories.
