### ISSUE TITLE
¿What is it?

### ISSUE THREAD

**Issue by jarriztg** [redis/hiredis#485]
`free(): invalid next size (fast): 0x00000000016f8cf0 ***`

**Comment by jarriztg** [comment]
I have that errors in hincrby and hset

**Comment by michael-grunder** [comment]
Could you post some sample code that can replicate the problem?  Also what OS you're running.

Obligatory question:  is your program multithreaded?

**Comment by jarriztg** [comment]
Here is an example:

https://github.com/primitivorm/latino/blob/master/ejemplos/45-redis.lat

But in the REPL (executing Latino and making hset) i have that error, this is the code:

https://github.com/primitivorm/latino/blob/master/src/libio.c#L245-L278

**Comment by badboy** [comment]
Not enough info to act on. Please provide a full stack trace and, if possible, a minimal example. Feel free to re-open issue if this is still an issue.
