### ISSUE TITLE
can I run Psubscribe for Async context?

### ISSUE THREAD

**Issue by litaozhang** [redis/hiredis#486]
hello,

if I use Async  conext to connect redis. And I want to subscribe one record in redis db.  I don't know how to set subscribe call back. what should I do?

Thanks,
Alpha

**Comment by badboy** [comment]
Simply attach a callback when sending the `*SUBSCRIBE` command. This callback is called on each received message:

```c
void process_messages(redisAsyncContext *c, void *r, void *privdata) {
    redisReply *reply = r;
    printf("Elements: %d\n", reply->elements);
}

...

redisAsyncCommand(c, process_messages, NULL, "SUBSCRIBE foo");
```
