### ISSUE TITLE
Repeated failures of redisAsyncCommandArgv with libev SIGSEGVs

### ISSUE THREAD

**Issue by rtyler** [redis/hiredis#49]
Program received signal SIGSEGV, Segmentation fault.                                              
    0x0000000000401f68 in redisLibevAddWrite (privdata=0x71) at /home/tyler/source/lookout/git/       cloudpushd/reddy/..//hiredis/adapters/libev.h:56
    56          struct ev_loop *loop = e->loop;
    (gdb) bt
    #0  0x0000000000401f68 in redisLibevAddWrite (privdata=0x71) at /home/tyler/source/lookout/git/   cloudpushd/reddy/..//hiredis/adapters/libev.h:56
    #1  0x00000000004053ed in __redisAsyncCommand (ac=<value optimized out>, fn=<value optimized      out>, privdata=<value optimized out>, cmd=<value optimized out>, len=<value optimized out>) at async. c:520
    #2  0x0000000000405539 in redisAsyncCommandArgv (ac=<value optimized out>, fn=Unhandled dwarf     expression opcode 0x0
    ) at async.c:549
    #3  0x0000000000402687 in reddyRequeueableCommand (context=0x614810, commands=0x614280, count=1,  callback=0, data=0x0, internal=true) at reddy.c:130
    #4  0x000000000040331a in reconnect (loop=0x613930, watcher=0x614820, revents=256) at reddy.c:64
    #5  0x000000000040aa7b in ev_invoke_pending (loop=<value optimized out>) at ev.c:2117
    #6  0x000000000040b443 in ev_run (loop=<value optimized out>, flags=<value optimized out>) at ev. c:2483
    #7  0x00000000004025bb in ev_loop (loop=0x613930, flags=0) at /home/tyler/source/lookout/git/     cloudpushd/reddy/../libev//ev.h:810
    #8  0x000000000040257f in main (argc=1, argv=0x7fffffffca48) at test.c:71
    (gdb) quit

I'm working on wrapping hiredis with some reconnect/requeue logic for our application specific needs. Inside of the reconnect `ev_timer` we will create a new `char**` and try to execute a `PING` command. In the case where the server is remaining down and hasn't come back up, we will immediately receive a `REDIS_ERR` from the `redisAsyncCommandArgv`, free the `char**` and exit.

After some number of these reconnect loop round-trips, the program will SIGSEGV with the above backtrace.

Somehow switching to a call to `redisAsyncCommand` has "solved the issue" insofar that I've gone for almost 15 minutes with numerous failed `PING` commands and no SIGSEGVs

**Comment by badboy** [comment]
I can't reproduce this (anymore?) So hopefully it's not a bug anymore.
