### ISSUE TITLE
version 0.13.3   event_base_dispatch in sub-thread failed

### ISSUE THREAD

**Issue by elitetony** [redis/hiredis#491]
Hi, 
I  update hiredis with version 0.13.3  in my project , but event_base_dispatch in sub-thread failed.
Using  hiredis pre version libhiredis.so.0.11 or 0.12 is ok .

Can you help me ,thank you very much .
.....
//in sub thread
{
struct event_base *base = event_base_new();
    redisAsyncContext *c = redisAsyncConnect("127.0.0.1", 6370);
    if (c->err) {
        /* Let *c leak for now... */
        printf("Error: %s\n", c->errstr);
        return 1;
    }
 redisAsyncCommand(c, NULL, NULL, "auth %s", "abcdefg");	
    redisLibeventAttach(c,base);
    redisAsyncSetConnectCallback(c,connectCallback);
    redisAsyncSetDisconnectCallback(c,disconnectCallback);
redisAsyncCommand(c, getCallback, (char*)"end-1", “PSUBSCRIBE date_update”);
.....
 event_base_dispatch(base);
printf("1111111\n");
return 0；
}
This function can not enter the event loop.

**Comment by badboy** [comment]
Can you show a full example showing the failure?

**Comment by elitetony** [comment]
Thanks for you  reply！

//////
the same code compiling with version v0.12.0 runing is ok.
result like this:
sub_cli is running...
tmp_buffer:PSUBSCRIBE check_sync
Connected...

with version v0.13.0+:
sub_cli is running...
tmp_buffer:PSUBSCRIBEcheck_sync
dispath end return:1
start subcli server error, exit(1) 

///////
int SubBaseEvent::sub_loop_start() 
{
    signal(SIGPIPE, SIG_IGN);
    if (event_base_){
		event_base_free(event_base_);
		event_base_ = NULL;
	}
	if (!event_base_)
		event_base_  = event_base_new();

	if (event_base_ == NULL){
		printf("event base new error\n");
		return 1;
	}

        AddrIpPort addr_ip_port;
       Config::instance().sub_addr_m(addr_ip_port);
       redisAsyncContext *c = redisAsyncConnect(addr_ip_port.ip, addr_ip_port.port);
       if (c->err){
        printf("Error: %s\n", c->errstr);
        return 1;
    }

	
     redisAsyncCommand(c, NULL, NULL, "auth %s", Config::instance().sub_m_passwd());
     redisLibeventAttach(c, event_base_);
     redisAsyncSetConnectCallback(c, SubBaseEvent::connectCallback);
     redisAsyncSetDisconnectCallback(c, SubBaseEvent::disconnectCallback);
     char tmp_buffer[64] = {0};
     sprintf(tmp_buffer, "PSUBSCRIBE %s", Config::instance().response_update_cmd());
     redisAsyncCommand(c, SubBaseEvent::getCallback, (char*)"end-1", tmp_buffer);

     memset(tmp_buffer, 0, sizeof(tmp_buffer));
     sprintf(tmp_buffer, "PSUBSCRIBE %s", Config::instance().check_sync_cmd());
     printf("tmp_buffer:%s\n", tmp_buffer);
     redisAsyncCommand(c, SubBaseEvent::getCallback, (char*)"end-1", tmp_buffer);

    int ige = event_base_dispatch(event_base_);
   printf("dispath end return:%d\n", ige);
  
  if (event_base_)
	event_base_free(event_base_);
	event_base_ = NULL;
    return 1;
}
//////
I'm not sure whether this error is related to the version。
If not, I will review my code further 。
Thank you  very much.
