### ISSUE TITLE
Inconsistent use of const

### ISSUE THREAD

**Issue by dagostinelli** [redis/hiredis#496]
I'm running into a little chicken-egg problem with const.  

**TLDR; add more const or remove const all together or provide more examples or ...?**

In `async.h`, `redisConnectCallback` wants a `const redisAsyncContext*`.  In that callback, I would like to call `redisEnableKeepAlive` method that could be const, but isn't const.  

On the other hand, maybe I shouldn't be calling `redisEnableKeepAlive` from that callback.  If not, when should I be calling that? (example?)

**Comment by dagostinelli** [comment]
Forgot to include the error message:

```
note: expected ‘redisContext * {aka struct redisContext *}’ but argument is of type ‘const redisContext * {aka const struct redisContext *}’
 int redisEnableKeepAlive(redisContext *c);

```

My code:

```
static void _on_connect(const redisAsyncContext *c, int status)
{
	/* snip error handling */
	redisEnableKeepAlive(&c->c);
}
```

**Comment by dagostinelli** [comment]
Another one is the disconnect handler.  In that one, I am experimenting with trying to call `redisReconnect()` in it.  Again, maybe this is wrong and I shouldn't be attempting to reconnect in here (if not, where should I do it and how to detect the connection state of the context?)

```
static void _on_disconnect(const redisAsyncContext *c, int status)
{
	/* snip error handling */

	redisReconnect(&c->c);
}
```

**Comment by badboy** [comment]
(Un)luckily the const-nes of an argument in C can be circumvented easily, even if it is not pretty.
I'd love to audit the current usage, but I don't really have time to track everything down.

**Comment by michael-grunder** [comment]
Closing this old issue.  We can look at const correctness before releasing a new major version.
