### ISSUE TITLE
Tag 1.0.0 in github

### ISSUE THREAD

**Issue by adityapatadia** [redis/hiredis#498]

**Comment by badboy** [comment]
We don't even have an official 1.0.0 release yet ¯\_(ツ)_/¯

(but yeah, I want to have one, if I find the time to clear it all up, merge remaining PRs and just damn release it)

**Comment by adityapatadia** [comment]
Haha, I thought it is released because readme in master branch said about 1.0.0. Anyway I have more problems with python hiredis than this module.

**Comment by badboy** [comment]
*cough* yeah, I once planned a 1.0 release *cough* I never did, sorry for that (master branch is more or less the development branch)
