### ISSUE TITLE
Warnings in sdssetlen and sdssetalloc

### ISSUE THREAD

**Issue by vronin** [redis/hiredis#500]
It would be nice in both of these function explicitly convert to newlen to appropriate uint8_t, uint16_t and so on. It compiles file. However, it shows warning about implicit conversion with loss of integer precision.

  ```
      case SDS_TYPE_8:
            SDS_HDR(8,s)->alloc = (uint8_t)newlen;
            break;
        case SDS_TYPE_16:
            SDS_HDR(16,s)->alloc = (uint16_t)newlen;
            break;
        case SDS_TYPE_32:
            SDS_HDR(32,s)->alloc = (uint32_t)newlen;
            break;
        case SDS_TYPE_64:
            SDS_HDR(64,s)->alloc = (uint64_t)newlen;
```

**Comment by badboy** [comment]
Please report those at the upstream project: https://github.com/antirez/sds
