### ISSUE TITLE
Memory leak patch in Redis

### ISSUE THREAD

**Issue by aaronjwood** [redis/hiredis#502]
I had submitted this https://github.com/antirez/redis/pull/3439/files a while back to redis but am just now realizing that this probably should have gone into this project. Should I resubmit this here?

**Comment by badboy** [comment]
To be totally correct it should go to [sds](https://github.com/antirez/sds/), but we're currently really bad at synchronizing all three projects. It shouldn't be a problem for Redis, as all `*alloc` calls are wrapped and will invoke the OOM handler on `NULL` values.
But we probably should fix it in sds itself and here, yes.

**Comment by aaronjwood** [comment]
Thanks for clarifying! Would you like me to submit this here and to https://github.com/antirez/sds/ then?

**Comment by aaronjwood** [comment]
https://github.com/redis/hiredis/pull/504
https://github.com/antirez/sds/pull/75

**Comment by michael-grunder** [comment]
Looks like this was fixed in 471557c3
