### ISSUE TITLE
Just a doubt: how can I know if some var redis is already assigned?

### ISSUE THREAD

**Issue by jarriztg** [redis/hiredis#503]
redisContext *conexion = __cdato(o);
  redisReply *respuesta;
  respuesta = redisCommand(conexion, "GET %s", __cadena(hash));
  lat_objeto *tmp;
  if (respuesta->str) {
      tmp = lat_cadena_nueva(mv, strdup(respuesta->str));
  } else {
      tmp = mv->objeto_nulo;
  }

"respuesta->str" is always "OK" and "respuesta->integer" dont work with that

im meaning, if my users assign the same key, how can i return something like "false" ?

**Comment by badboy** [comment]
I'm not sure I understand your question. A `GET` command will return the value of the key you're getting (or nil if the key does not exist).

In general you should check `reply->type` for the correct return type.

**Comment by jarriztg** [comment]
im meaning, im using this:
redisCommand(conexion, "SET %s %s", hash, key);
if the key exist in the hash, how can i know that?

**Comment by badboy** [comment]
It seems you're not facing a problem with hiredis, but rather with the specifics on how to use Redis.
Your call to the [`SET` command](https://redis.io/commands/set) will set the key referenced by `hash` to the value referenced by `key` and will _always_ return OK.
If you need to check for the previous value or if it exists at all you can either reach for [`GETSET`](https://redis.io/commands/getset) or use [`EXISTS`](https://redis.io/commands/exists) to check first.

Keep in mind that this issue tracker should be used for bugs or improvements for hiredis. For questions like yours please ask on [/r/redis](https://www.reddit.com/r/redis), the [mailing list](http://groups.google.com/group/redis-db) or ask in the irc channel `#redis` on freenode.

**Comment by jarriztg** [comment]
thanks a lot @badboy ! :+1:
