### ISSUE TITLE
API/ABI changes analysis

### ISSUE THREAD

**Issue by lvc** [redis/hiredis#506]
Hi,

I've created report on API/ABI interface changes for the Hiredis C library: https://abi-laboratory.pro/tracker/timeline/hiredis/

You can check for added, removed and changed API/ABI symbols with the help of the report. Hope it will be helpful for users and maintainers of the library. It's updated regularly, so you can always look at this page if you'd like to review backward compatibility of the latest library versions.

Machine-readable JSON-format mirror report is available on Github: https://github.com/lvc/abi-reports/blob/master/report/hiredis.json

Thank you.

![hiredis-1](https://cloud.githubusercontent.com/assets/1517837/24091373/2cb750f6-0d61-11e7-8178-4471359942b0.png)

![hiredis-2](https://cloud.githubusercontent.com/assets/1517837/24091381/3884ea74-0d61-11e7-9a5c-c10503e34664.png)

**Comment by badboy** [comment]
Thanks! This looks great. 

* is there an easy way to generate this report by myself?
* does this site update with new releases? 

Would be nice to link to it or provide our own instance of it with each release.

**Comment by lvc** [comment]
> is there an easy way to generate this report by myself?

Yes. All used tools are open-source tools:

* https://github.com/lvc/abi-tracker
* https://github.com/lvc/abi-dumper
* https://github.com/lvc/abi-compliance-checker

> does this site update with new releases?

Yes. The report is updated automatically three times a week: https://abi-laboratory.pro/index.php?view=abi-tracker

Thank you.

**Comment by badboy** [comment]
Thanks! I will look into it

**Comment by michael-grunder** [comment]
I went ahead and added a link to your ABI tracker on our readme so I'll close this issue.

Thanks!
