### ISSUE TITLE
I download the v11,but the version is v10?

### ISSUE THREAD

**Issue by zs851** [redis/hiredis#511]

**Comment by badboy** [comment]
The current latest version of hiredis is v0.13.3. See [the releases page](https://github.com/redis/hiredis/releases).

I don't know what you downloaded.

**Comment by zs851** [comment]
https://github.com/redis/hiredis/releases/tag/v0.11.0   this version，but its v10

**Comment by badboy** [comment]
Then please take the latest version. It should be correct. I can check the old version later.

**Comment by zs851** [comment]
Thank You very mach！

**Comment by badboy** [comment]
you are right in that the makefile contains a version 0.10, but that is only used for the dynamic lib and afaik, as we did not break the ABI, it should be fine. The code still has everything from 0.11
