### ISSUE TITLE
valgrind warning of uninitialised byte(s)

### ISSUE THREAD

**Issue by usergoodvery** [redis/hiredis#512]
Hi,
I am doing a fairly standard MULTI/EXEC stuff in my code, but I am getting valgrind warning 
I am getting the right results, otherwise.

c code triggering the warning is at redisGetReply:
```
//standard MULTI/command/EXEC sequence

		{
		size_t 			i;
		redisReply	*replies[commands_processed]; 

		for (i=0; i<commands_processed; i++)
		{
			if ((redisGetReply(pers_ptr->persistance_agent, (void*)&replies[i])) != REDIS_OK)
			{.....

```

==00:00:00:02.883 23106==
==00:00:01:24.567 23106== Syscall param write(buf) points to uninitialised byte(s)
==00:00:01:24.567 23106==    at 0x504C19D: ??? (syscall-template.S:82)
==00:00:01:24.567 23106==    by 0x4E3816A: redisBufferWrite (hiredis.c:1191)
==00:00:01:24.567 23106==    by 0x4E382BA: redisGetReply (hiredis.c:1234)
...

have you seen this one before?

regards,

**Comment by badboy** [comment]
Which version of hiredis?
Can you provide a minimal example to reproduce this?

**Comment by usergoodvery** [comment]
I am closing this for now as I have not been able to cleanly reproduce it
