### ISSUE TITLE
Hiredis Hang on redisBufferRead

### ISSUE THREAD

**Issue by naugaria7** [redis/hiredis#517]
Hi All,

I have connection pool from which Redis Contexts are shared across different threads. HiRedis Hangs on RedisBufferRead() with following bt:

#0  0x0000000808bd6d0c in read () from /lib/libc.so.7

#1  0x000000080859a830 in read () from /lib/libthr.so.3
#2  0x0000000803c01b07 in redisBufferRead () from ./lib/libhiredis.so.0.11
#3  0x0000000803c03006 in redisGetReply () from ./lib/libhiredis.so.0.11
#4  0x0000000803c03084 in redisvCommand () from ./lib/libhiredis.so.0.11
#5  0x0000000806d99486 in RedisUtil::run_redis_query_set (command=@0x7ffff73b5350) at RedisUtil.cpp:60
#6  0x0000000806d9e422 in RedisUtil::set_redis_session (sess_id=@0x7ffff73b5d60, scope_map_temp=<value optimized out>, is_external=false) at RedisUtil.cpp:122

I see in other posts that this could happen if same Context is used by two threads at same time. Since I am using a pool, this should not have caused the issue. Any leads would be appreciated.

Chinmay

**Comment by michael-grunder** [comment]
Nothing actionable here and I'm guessing it's been resolved since this is from 2017
