### ISSUE TITLE
confusing with redisSetTimeout when use pipeline

### ISSUE THREAD

**Issue by workforme** [redis/hiredis#520]
I set redisSetTimeout to 100ms(this is the max timeout my app can tolerate),then I call cmd pipeline  like this:

suppose it split request to some(in my product is 4) tasks,

```
for each task in tasks do{
    mstime begin;

    for each request/cmd in task do{
        redisAppendCommandArgv(context,cmd...)
    }
    n= request num in this task;
    for 1..n {
        redisGetReply(context...)` 
    }
    mstime end;
    print end-begin
}
```

each outer  loop of tasks ,i get time cost int ms=(end-begin) is about 1ms;
but,why i some times get fail in the last loop?

when i change context timeout from 100 to 300ms,this problem disappear....

so ,i am confused with the timeout using in pipeline,if the timeout just limit r/w time of the block redis fd(network is fast enough,each success loop is 1ms,timeout 100ms should be enough),why it always fail in last loop while context timeout is 100ms(but not happen when set to 300ms)?

**Comment by badboy** [comment]
What is the exact error you get?
Can you give a minimal example to reproduce this issue?

**Comment by michael-grunder** [comment]
Closing this old issue.  Feel free to reopen if you're still having the problem.
