### ISSUE TITLE
How can I send a list of param to hmset without format?

### ISSUE THREAD

**Issue by KingaChou** [redis/hiredis#527]
===================================
redisCommand expects a format string and will simply split on whitespace. It does not handle quotes at all.
You should use:

redisCommand(c, "hmset %s %s %s %s %s", "D11BA97064C28242739B7A5E06A3887B_178", "content", "a plus b", "href", "just_test");
This will correctly format the command and handle whitespace without problems.

redis-cli does the quote-splitting for convenience because it is used interactively.
===================================
I see the explain for how to use hmset.
But I have a problem that I want to use hmset with uncertain num of field and value. How can I do that?

**Comment by badboy** [comment]
You have to dynamically create your array of arguments and then pass it to `redisCommandArgv`. See [my example code](https://gist.github.com/badboy/c956c30ef77e904181c3c7efc9a503a1).
