### ISSUE TITLE
Hiredis connection file descriptor

### ISSUE THREAD

**Issue by psprint** [redis/hiredis#528]
Hello,
I'm writing a module to Zsh, and it manages file descriptors. I should add hires connection descriptor with `addmodulefd(..., FDT_MODULE)`, to prevent the descriptor being closed by shell's regular `dup`, `dup2`, etc. activity. Is the descriptor somehow exposed by hiredis? For example, `gdbm` library has `gdbm_fdesc()` call.

**Comment by badboy** [comment]
The `redisContext` object contains a field `fd` which is the socket file descriptor.
As we have the structure publicly exposed, we won't break it anytime soon, so it's safe to use.

**Comment by psprint** [comment]
That's fully cool, for example SQLite guys rejected requests (not mine) for FD exposure claiming that it isn't abstract, because Windows doesn't have file descriptors. And it caused severe problems, FD was needed to lock the database, people were implementing things themselves, patches circulated.

**Comment by badboy** [comment]
We only support hiredis on Windows under cygwin. I don't know the exact story, but there file descriptors should work just fine as well. No guarantuees beyond that though.
