### ISSUE TITLE
What if redisContextConnectTcp inside redisConnect returns error code? why redisConnect dose not care about the return value of redisContextConnectTcp?

### ISSUE THREAD

**Issue by hylepo** [redis/hiredis#534]
Based on the implementation of [redisContextConnectTcp](https://github.com/redis/hiredis/blob/5f98e1d35dcf00a026793ada2662f6e1ba77eb17/net.c#L418), we will have the error code if it fails, but why [redisConnect](https://github.com/redis/hiredis/blob/5f98e1d35dcf00a026793ada2662f6e1ba77eb17/hiredis.c#L674) ignores the return value, in this case, even `redisContextConnectTcp` fails, `redisConnect` behavior has no difference, How can I know redisContext connected or not before issue redis command?

**Comment by badboy** [comment]
> On error the field error in the returned context will be set to the return value of the error function.

All error paths in `redisContextConnectTcp` do this, so it is up to the user calling `redisConnect` to check for a connection error.
