### ISSUE TITLE
Building on Solaris 10

### ISSUE THREAD

**Issue by rzearreta** [redis/hiredis#535]
Hello,

first, sorry about my English.

Is there any special caution when building on Solaris 10 x86?

I'm able to build it taking the code from master and last release (0.13.3) branches without problem, but when I call the shared library trying to build collectd-5.7.2, i get:

    write_redis . . . . . no (symbol 'redisCommand' not found)

So I don't know if this is a collectd or hiredis issue.

I'm using gcc 5.2.0 from opencsw.org, bintuils 2.28, and make 4.1. 

Any idea? Many thanks.

**Comment by michael-grunder** [comment]
Closing the old issue.  Feel free to reopen if you're having issues in solaris.
