### ISSUE TITLE
ruby-2.2.2 hiredis-0.4.5  dyld: Symbol not found: _rb_thread_select

### ISSUE THREAD

**Issue by ericeche** [redis/hiredis#537]
OSX = 10.12.4
ruby-2.2.2
hiredis-0.4.5
Rails 4.1.1

Processing by MoviesController#index as HTML
  Movie Load (0.4ms)  SELECT `movies`.* FROM `movies`
  Rendered movies/index.html.erb within layouts/application (140.3ms)
  User Load (0.2ms)  SELECT  `users`.* FROM `users`  WHERE `users`.`id` = 1  ORDER BY `users`.`id` ASC LIMIT 1
dyld: lazy symbol binding failed: Symbol not found: _rb_thread_select
  Referenced from: /Users/eecheverri/.rvm/gems/ruby-2.2.2/gems/hiredis-0.4.5/lib/hiredis/ext/hiredis_ext.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_thread_select
  Referenced from: /Users/eecheverri/.rvm/gems/ruby-2.2.2/gems/hiredis-0.4.5/lib/hiredis/ext/hiredis_ext.bundle
  Expected in: flat namespace

Abort trap: 6

Any help immensely appreciated

**Comment by ericeche** [comment]
Solution

Deleted hiredis from the Gem file and used redis and redis-namespace:
#gem "hiredis", "~> 0.4.0"
gem 'redis'
gem 'redis-namespace'


In redis.rb
$redis = Redis::Namespace.new("my_app", :redis => Redis.new)

**Comment by badboy** [comment]
if you still require it, try again with hiredis 0.6.1
