### ISSUE TITLE
best way to mix sync and async API 

### ISSUE THREAD

**Issue by jefshe** [redis/hiredis#540]
Is there a way to use the synchronous API from the async context? I noticed that there's a toggle in net.c to set the socket to blocking/non-blocking. Is it possible to reuse the same socket to make sync and async calls? 

Or is the only option to create another context?

**Comment by michael-grunder** [comment]
Sorry for such a late response, but I'm going through old issues.

My suggestion would be to use separate contexts for mixing sync/async workflows.  It's _possible_ you could get something to work by manually working with the underlying file descriptors but it strikes me as way more effort than it's worth.

**Comment by jefshe** [comment]
I came to the same conclusion but thanks for replying haha
