### ISSUE TITLE
no one have the free error？

### ISSUE THREAD

**Issue by owen200008** [redis/hiredis#541]
in createArrayObject it is no set the r->element = NULL； when the elements = 0
so free is error,  it is error point r->element

**Comment by owen200008** [comment]
debug totally correct because it auto set null. but release must be error

**Comment by cdliuqiang** [comment]
createArrayObject  used calloc,  The calloc  function  allocates  memory
and set the memory to zero。

2017-08-21 11:24 GMT+08:00 Owen.Cai <notifications@github.com>:

**Comment by badboy** [comment]
Indeed. `calloc` is used and thus all memory is set to `0`, so there will be no problem.

**Comment by owen200008** [comment]
ok, all memory oper hook. so it no set 0 in my code. i have change it. thanks
