### ISSUE TITLE
redisLibuvPoll crash when server closes the connetion

### ISSUE THREAD

**Issue by mannol** [redis/hiredis#545]
When server closes the connection, either by shutting down or some protocol irregularity, the libuv adapter crashes in `redisLibuvPoll()` when calling `redisAsyncHandleWrite()`. Reason for the crash is that the prior call to `redisAsyncHandleRead()` frees the context.

I have solved it by placing `redisAsyncHandleWrite()` before `redisAsyncHandleRead()`, however, considering that this happens because `redisBufferRead(c) == REDIS_ERR` causes the `__redisAsyncDisconnect(ac)` call, the better solution would be to make `redisAsyncHandleRead()` and `redisAsyncHandleWrite()` return status.

**Comment by michael-grunder** [comment]
Hi, I'm going through old issues.

I think this may have been fixed in 9ce15c4b. Please reopen if that actually doesn't solve the problem and I will take the time to replicate the bug and submit a patch.
