### ISSUE TITLE
problems with using mget

### ISSUE THREAD

**Issue by yangl326-Dylan** [redis/hiredis#549]
cmd is “MGET key1 key2 key3”
but one of my key including the '%' punc. return format string error, please tell me why and how to fix, if my key has %?

**Comment by badboy** [comment]
In general Redis itself doesn’t care, but without the code I can’t tell you what’s wrong.

**Comment by michael-grunder** [comment]
@yangl326-Dylan It's impossible to know what's wrong without a code sample, but this works to set the key `funky%key` to `myvalue`:

```c
    redisReply *r = redisCommand(c, "SET funky%%key %s", "myvalue");
```

**Comment by yangl326-Dylan** [comment]
string keys = "MGET people_39711_CTX_电影 people_39711_CTX_香港 people_39711_CTX_07%的盐  people_1130634_CTX_07%的盐 people_1130634_CTX_原版 people_1130634_CTX_预告片";
this is my request looks like. it's chinese

**Comment by michael-grunder** [comment]
Again, it's really difficult to diagnose the problem you're running into unless you post some actual code :smiley_cat:

The following works just fine:

```c
#include <hiredis/hiredis.h>
#include <stdio.h>

const char *keys[] = {
    "people_39711_CTX_电影",
    "people_39711_CTX_香港",
    "people_39711_CTX_07%的盐",
    "people_1130634_CTX_07%的盐",
    "people_1130634_CTX_原版",
    "people_1130634_CTX_预告片"
};

int main(void) {
    int i;
    redisContext *c;
    redisReply *r;

    c = redisConnect("127.0.0.1", 6379);

    for (i = 0; i < 5; i++) {
        r = redisCommand(c, "SET %s %s", keys[i], keys[i]);
        freeReplyObject(r);
    }

    r = redisCommand(c, "MGET %s %s %s %s %s", keys[0], keys[1], keys[2],
                     keys[3], keys[4]);

    for (i = 0; i < r->elements; i++) {
        printf("key '%s' => '%s'\n", keys[i], r->element[i]->str);
    }

    freeReplyObject(r);
    return 0;
}
```

(note that I am doing absolutely no error handling at all so this will crash if we can't connect, etc)

**Comment by yangl326-Dylan** [comment]
int CRedisCache::GetBatchRedisCache(string &keys, vector<string>* outputs){
    redisReply *rly;
    int dwRetCode = 0;

    rly=(redisReply*)redisCommand(m_pRctx,
            keys.c_str());
    VLOG(3)<<"redisCommand:"<<keys;
    if(rly == NULL) // || rly->type != REDIS_REPLY_ARRAY){
    {
        if (m_pRctx == NULL) //m_pRctx->err)
        {
            VLOG(1)<<"m_pRctx is NULL ";
            //return m_pRctx->err;
        }
        VLOG(1)<<"redisCommand NULL"<<m_pRctx->errstr<<" " << keys;
        goto errExit;
    }
    if (rly->type == REDIS_REPLY_NIL)
    {
        VLOG(1)<<"redisCommand NIL" << (int)REDIS_REPLY_NIL;
        goto errExit;
    }
    if (rly->type == REDIS_REPLY_ERROR)
    {
        VLOG(1)<<"redisCommand ERROR " << (int)REDIS_REPLY_ERROR << keys;
        goto errExit;
    }
    if (rly->type != REDIS_REPLY_ARRAY)
    {
        VLOG(1)<<"redisCommand not Array" << (int)REDIS_REPLY_ARRAY<<" rly elements: "<<rly->elements;
        goto errExit;
    }
    
    VLOG(3)<<"rly elements: "<<rly->elements;
    for (int i = 0; i < rly->elements; i++){
        redisReply* childRly = rly->element[i];
        if(childRly->type != REDIS_REPLY_STRING){
            //VLOG(3) << "rly warning , not REDIS_REPLY_STRING";
            //no relations 
            outputs->push_back("0");
            //goto errExit;
            continue;
        }
        outputs->push_back(childRly->str);
        //VLOG(3)<<childRly->str;
    }
    freeReplyObject(rly);
    return 0;
errExit:
    freeReplyObject(rly);
    return dwRetCode;
}

**Comment by yangl326-Dylan** [comment]
the code is very simple:
`rly=(redisReply*)redisCommand(m_pRctx,
            keys.c_str());
    VLOG(3)<<"redisCommand:"<<keys;
    if(rly == NULL) // || rly->type != REDIS_REPLY_ARRAY){
    {
        if (m_pRctx == NULL) //m_pRctx->err)
        {
            VLOG(1)<<"m_pRctx is NULL ";
            //return m_pRctx->err;
        }
        VLOG(1)<<"redisCommand NULL"<<m_pRctx->errstr<<" " << keys;
        goto errExit;
    }`

**Comment by yangl326-Dylan** [comment]
`int main(int argc, char** argv) {
    /*
    base::ParseCommandLineFlags(&argc, &argv, false);
    CRedisCache redis_;
    redis_.Init(string("all.entity_linker_ctx.redis.com"));
    vector<std::string> output;
    string keys = "MGET people_39711_CTX_电影 people_39711_CTX_香港 people_39711_CTX_07%的盐";
	redis_.GetBatchRedisCache(keys,&output);
    redis_.Uninit(); 
    */
    int i;
    redisContext *c;
    redisReply *r;

    c = redisConnect("100.66.8.160", 9018);
    
    r = (redisReply *)redisCommand(c, "MGET people_39711_CTX_电影 people_39711_CTX_香港 people_39711_CTX_07%的盐");
    if(r == NULL){
        printf("r is NULL, ERROR is %s", c->errstr);
        freeReplyObject(r);
        exit(1);
    }
    for (i = 0; i < r->elements; i++) {
        printf("key 'xxx' => '%s'\n", r->element[i]->str);
    }

    freeReplyObject(r);
}`

**Comment by michael-grunder** [comment]
Hey,

The reason that your call is failing is that the first argument of `redisCommand` is a format string (like printf) and one of your keys has a `%` sign in it followed by a chinese character which is not a valid format specifier.

I've rewritten your program so that if you pass no arguments it uses your call to `redisCommand` and if you pass an argument uses one which will work:

```c
#include <hiredis/hiredis.h>
#include <stdio.h>
#include <stdlib.h>

int main(int argc, const char **argv) {
    int i;
    redisContext *c;
    redisReply *r;

    c = redisConnect("127.0.0.1", 6379);

    if (argc < 2) {
        r = (redisReply *)redisCommand(c, "MGET people_39711_CTX_电影 people_39711_CTX_香港 people_39711_CTX_07%的盐");
    } else {
        r = (redisReply*)redisCommand(c, "MGET %s %s %s", "people_39711_CTX_电影", "people_39711_CTX_香港", "people_39711_CTX_07%的盐");
    }

    if(r == NULL) {
        printf("r is NULL, ERROR is %s", c->errstr);
        freeReplyObject(r);
        exit(1);
    }

    for (i = 0; i < r->elements; i++) {
        printf("key 'xxx' => '%s'\n", r->element[i]->str);
    }

    freeReplyObject(r);
}
```

```
➜  /tmp ./example
r is NULL, ERROR is Invalid format string
➜  /tmp ./example 1
key 'xxx' => 'people_39711_CTX_电影'
key 'xxx' => 'people_39711_CTX_香港'
key 'xxx' => 'people_39711_CTX_07%的盐'
```

You could also fix your program by changing your `redisCommand` line to this:
```
r = (redisReply *)redisCommand(c, "MGET people_39711_CTX_电影 people_39711_CTX_香港 people_39711_CTX_07%%的盐");
```

As a `%%` is how you denote a percent sign in a format string.

Cheers,
Mike

**Comment by yangl326-Dylan** [comment]
thanks.
I have another problem, it seams that once get the "r is NULL, ERROR is Invalid format string" error. it will have error all the time after that request.
