### ISSUE TITLE
the error message string of redis context is messy

### ISSUE THREAD

**Issue by magenious** [redis/hiredis#551]
code snippet:
`std::function<void(const void *& buf, int& size)> f = [data2, read_buf,key_name](const void *& buf, int& size) {
            auto ctx = data2->GetContext();

            void *reply = NULL;
            auto status = redisGetReply(ctx, &reply);

            if (status == REDIS_OK) {
                redisReply *r = (redisReply *) reply;

                char *data_buf = 0;
                int data_size = 0;

                if (GetData(r, data_buf, data_size, 3, 2)) {
                    if (read_buf->capacity() < data_size) {
                        read_buf->resize(data_size * 2);
                    }

                    memcpy(&(*read_buf)[0], data_buf, data_size);

                    buf = (const void *) &(*read_buf)[0];
                    size = data_size;
                }
            }
            else {
                std::cerr << "[redis-io]: subscribe get message returns status: " << status << ", Error Code : " << ctx->err << ", Error Details : " << ctx->errstr << ", Channel Info : " << key_name << std::endl;
                throw runtime_error("[redis-io] subscribe get message returns error.");
            }

            if (reply != NULL)
                freeReplyObject(reply);
        };`
the problem is when redisGetReply(ctx, &reply) returns error and enter the else branch, the printed out  error message string of ctx->errstr is messy code, which is unreadable as follows:

![image](https://user-images.githubusercontent.com/23720252/31987767-743c14a8-b99f-11e7-8f53-84b36c893c61.png)

**Comment by badboy** [comment]
Without a minimal test case to reproduce there's not much I can do.
