### ISSUE TITLE
redisFree segfault

### ISSUE THREAD

**Issue by gameyin** [redis/hiredis#552]
hello, I am using hiredis lib for my redis class in cpp program, but sometime it will occur segfault.
I find this segfault from _dmesg_ command and the wrong was point to my redis class's destructor by using _addr2line_ command.
Here is part of my redis class:
Redis::Redis()
{
    _connect = NULL;
    _reply = NULL; 
}

Redis::~Redis()
{
    if (_connect != NULL)
    {
        redisFree(_connect);
    }
    _connect = NULL;
    _reply = NULL;                
}

I only use redisFree when _connect is not NULL, but how could it cause segfault ? Thanks for help!

**Comment by badboy** [comment]
Without example showing the segfault I can’t say anything about the problem

**Comment by michael-grunder** [comment]
Like badboy said, there isn't any way to determine what is causing your segfault without a sample that causes the problem.

Running your program under valgrind will likely help you pinpoint the error, however.
