### ISSUE TITLE
update_zmalloc_stat_alloc

### ISSUE THREAD

**Issue by helloworld-0** [redis/hiredis#562]
#define update_zmalloc_stat_alloc(__n) do { \
    size_t _n = (__n); \
    if (_n&(sizeof(long)-1)) _n += sizeof(long)-(_n&(sizeof(long)-1)); \
    atomicIncr(used_memory,__n); \
} while(0)

_n not use.

**Comment by badboy** [comment]
That's not in hiredis, but in upstream redis. Please report there.
