### ISSUE TITLE
Is there a list of things to implement replica failover with transaction support on hiredis?

### ISSUE THREAD

**Issue by lxyscls** [redis/hiredis#563]
My usage is "1 master, N slaves, M sentinels". The master takes on all write and read, and sentinels take on failover. 

"PING" for connectivity, "ROLE" for role? Is there a list of things just like those?

Can i use transcation "MULTI/EXEC/WATCH" under my usage?

**Comment by badboy** [comment]
This is not the place to discuss usage issues with Redis, ask on the Redis mailing list, in the subreddit or on IRC.
