### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by KingHust** [redis/hiredis#566]
/* Find pointer to \r\n. */
static char *seekNewline(char *s, size_t len) {
    int pos = 0;
    int _len = len-1;

    /* Position should be < len-1 because the character at "pos" should be
     * followed by a \n. Note that strchr cannot be used because it doesn't
     * allow to search a limited length and the buffer that is being searched
     * might not have a trailing NULL character. */
    while (pos < _len) {
        while(pos < _len && s[pos] != '\r') {
            pos++;
        }
        if (s[pos] != '\r') {
            /* Not found. */
            return NULL;
        } else {
            if (s[pos+1] == '\n') {
                /* Found. */
                return s+pos;
            } else {
                /* Continue searching. */
                pos++;
            }
        }
    }
    return NULL;
}

in this function, if (s[pos+1] == '\n') may access memory beyond s, may this cause illegal access?
for example, s is "$5\r", and the next byte in memory after the end of s is just '\n', this function can return non-NULL, but we expect a NULL return.

**Comment by KingHust** [comment]
I think it shoud be like this:

/* Find pointer to \r\n. */
char *seekNewline(char *s, size_t len) {
    int pos = 0;
    int _len = len-1;

    /* Position should be < len-1 because the character at "pos" should be
     * followed by a \n. Note that strchr cannot be used because it doesn't
     * allow to search a limited length and the buffer that is being searched
     * might not have a trailing NULL character. */
    while (pos < _len) {
        while(pos < _len && s[pos] != '\r') {
            pos++;
        }
        if (s[pos] != '\r') {
            /* Not found. */
            return NULL;
        } else {
			if (pos == _len) {
				return NULL;
			}
            if (s[pos+1] == '\n') {
                /* Found. */
                return s+pos;
            } else {
                /* Continue searching. */
                pos++;
            }
        }
    }
    return NULL;
}

**Comment by popsky** [comment]
HI,KingHust.
I don't think this is true,cause the _len = len-1, so in the beginning of loop ,pos maximal value whuld be  len-2,and so pos+1 maximal  value whuld be len-1, this not exceed the string buf.
