### ISSUE TITLE
Can't get binary data (string) from hiredis, Emergency!

### ISSUE THREAD

**Issue by liuzhuoling2011** [redis/hiredis#567]
Currently I face a problem witch makes me so confusing, when I get binary data (string) from redis:
```reply->type=1, reply->len=296, reply->str=""```
Therefor, I can't get anything from hiredis reply.
I use the same command in redis-cli, it will return the binary data.
![1](https://user-images.githubusercontent.com/8407297/34596403-6d35d618-f21a-11e7-8ea3-f04d50681f08.png)
![2](https://user-images.githubusercontent.com/8407297/34596404-6d71e54a-f21a-11e7-8cd8-c920d8ac56fb.png)

**Comment by badboy** [comment]
Looks just fine to me. Strings in C are null-terminated, so if you print them they will be empty if there are only null values in it. The length however is correct, so you can safely copy out the necessary data (only zeroes in your case)

**Comment by liuzhuoling2011** [comment]
Thank you for your time!
