### ISSUE TITLE
ReJSON support?

### ISSUE THREAD

**Issue by andrewkuk** [redis/hiredis#574]
Hello! Redis has a module to store JSON - ReJSON, so I want to know if you plan to realize functionality to work with this module in hiredis?
Thank you.

**Comment by itamarhaber** [comment]
@andrewkuk what's stopping you from using it?

**Comment by badboy** [comment]
You can call all commands already. Deserializing JSON is left to your application.

**Comment by andrewkuk** [comment]
I'm getting error when I use JSON...
`set { ReplyError: WRONGTYPE Operation against a key holding the wrong kind of value
api_1         |     at HiredisReplyParser.execute (/usr/src/app/node_modules/redis-parser/lib/hiredis.js:45:24)
api_1         |     at Socket.<anonymous> (/usr/src/app/node_modules/redis/index.js:274:27)
api_1         | 
api_1         |   command: 'JSON.SET',
api_1         |   args: [ 'test', '.', { test: 1 } ],
api_1         |   code: 'WRONGTYPE' }`

**Comment by badboy** [comment]
That's an error because you're trying to use a command against a key for which that command is not supported. It is **not** an issue in the hiredis library. I can't help you debug your application.

**Comment by andrewkuk** [comment]
This error happens because I pass deserialized JSON as an argument, if I pass serialized JSON - it's works fine, but as I understand from you answer "Deserializing JSON is left to your application." - serializing and deserialing of JSON happen inside hiredis? Or I didn't understand you correctly?
Thank you for the answer.

**Comment by badboy** [comment]
hiredis does not know about JSON at all. All it knows about is a string/bytes, which it sends unmodified.
I never used ReJSON so I don't know what data it expects. 
Sorry, I can't help with that anymore.

**Comment by andrewkuk** [comment]
Thank you for the answer. I understand you.
