### ISSUE TITLE
EXC_BAD_ACCESS in redisCommand

### ISSUE THREAD

**Issue by roger-blain** [redis/hiredis#577]
My application is calling a LUA script to pass data to redis.
After 5min or a few hours execution, I get a memory exception, this is after several hundred trasactions.

When I examine the variables going in to the redisCommand function, which is being called hundreds of times with no issues, they are all valid and within scope.

`redisReply *reply2 = (redisReply *) redisCommand(redis_context_, "EVALSHA %s 6 %s %s %s %s %s %s", sha1_.c_str(),ap_id.c_str(), device_id.c_str(), area_id.c_str(), floorindex.c_str(), message.c_str());`

redis_context_ is also within scope.

On examining the stack trace it fails deep within hiredis:
EXC_BAD_ACCESS (code=1, address=0xfffffff0)

`strlen 0x00007fff951da132  <--- Point of exception
redisvFormatCommand 0x0000000101418490
redisvAppendCommand 0x0000000101419738
redisvCommand 0x00000001014198df
redisCommand 0x00000001014199b7
C_client_processor::check_monitor_filter(..) client_processor.h:426  <--- My code entry poing
`

Does anyone have any idea how I can go about diagnosing this issue. I can only assume some variable is going out of scope on the call stack.

My build and test environment is on OSx

**Comment by michael-grunder** [comment]
Hi,

It will be really difficult to diagnose what the problem might be without more information.  For example, can you produce a self-contained program that causes this crash?

My best guess is that either one of your pointers is, in fact, invalid (e.g. gets freed before Hiredis calls `strlen` on it), or the strings are somehow not null terminated (or the null terminator is getting clobbered by a different memory overwrite).

Have you tried running your program in Valgrind to see if any memory errors are reported?

Cheers!
Mike

**Comment by michael-grunder** [comment]
I'm closing this old issue since there isn't any new information.
