### ISSUE TITLE
install hiredis failed, arm directory or files no found

### ISSUE THREAD

**Issue by rvlta** [redis/hiredis#579]
Hello, 

 

I'm trying an installation of Mastodon instance on tinkerboard running with Armbian OS.

 

I follow this topic : https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md

 

the last command i ran was 

bundle install -j$(getconf _NPROCESSORS_ONLN) --deployment --without development test

 

it returned me : 

    Fetching:
    ERROR:  Error installing hiredis:
    ERROR: Failed to build gem native extension.

        current directory: /home/mastodon/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/hiredis-0.6.1/ext/hiredis_ext
    /home/mastodon/.rbenv/versions/2.5.0/bin/ruby -r ./siteconf20180315-22972-ynlyve.rb extconf.rb
    checking for sys/socket.h... yes
    cc -std=c99 -pedantic -c -O3 -fPIC  -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb arm net.c
    cc: error: arm: Aucun fichier ou dossier de ce type
    Makefile:136 : la recette pour la cible « net.o » a échouée
    make: *** [net.o] Erreur 1
    *** extconf.rb failed ***
    Could not create Makefile due to some reason, probably lack of necessary
    libraries and/or headers.  Check the mkmf.log file for more details.  You may
    need configuration options.

    Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/mastodon/.rbenv/versions/2.5.0/bin/$(RUBY_BASE_NAME)
    extconf.rb:33:in `block in <main>': Building hiredis failed (RuntimeError)
        from extconf.rb:31:in `chdir'
        from extconf.rb:31:in `<main>'

    To see why this extension failed to compile, please check the mkmf.log which can be found here:

     /home/mastodon/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/extensions/armv7l-linux/2.5.0-static/hiredis-0.6.1/mkmf.log

    extconf failed, exit code 1

    Gem files will remain installed in /home/mastodon/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/hiredis-0.6.1 for inspection.
    Results logged to /home/mastodon/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/extensions/armv7l-linux/2.5.0-static/hiredis-0.6.1/gem_make.out

The problem seems to be that arm files or directory doesn't exist but i didn't find any issues. 

 

Anybody get an idea ?

 

Thanks a lot and i'apologize to my English expression.

``

**Comment by asonix** [comment]
I'm having the same issue trying to set up mastodon with hiredis on arm64

```
cc -std=c99 -pedantic -c -O3 -fPIC  -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb arm64 net.c
cc: error: arm64: No such file or directory
```

**Comment by asonix** [comment]
Just for followup, I have a Rock64, and I tried all 3 of Armbian's offerings. This issue occurred on every one. The [minimal Bionic 18.04 image for the Rock64](https://github.com/ayufan-rock64/linux-build/releases) did not have this issue.

**Comment by hsupu** [comment]
Same problem and OS. but I got a patch: Make hiredis alone with `ARCH="-marm"`.

```sh
ARCH="-marm" make static
```

But why, and can it be fix?

**Comment by michael-grunder** [comment]
Looks like this has been fixed, closing.
