### ISSUE TITLE
hiredis core on unsubscribe and subscribe

### ISSUE THREAD

**Issue by zhuizhuhaomeng** [redis/hiredis#581]
on async model,
i subscribe topic "test", after a while a unsubscrbie "test" and subscrbie "test" immediately.
the assert on async.c:464

Missing separate debuginfos, use: debuginfo-install openssl-1.0.1e-57.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  0x000000350ae325e5 in raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1  0x000000350ae33dc5 in abort () at abort.c:92
#2  0x000000350ae2b70e in __assert_fail_base (fmt=<value optimized out>, assertion=0x7f0d4e284ab0 "(c->flags & 0x20 || c->flags & 0x40)", file=0x7f0d4e284916 "async.c", 
    line=<value optimized out>, function=<value optimized out>) at assert.c:96
#3  0x000000350ae2b7d0 in __assert_fail (assertion=0x7f0d4e284ab0 "(c->flags & 0x20 || c->flags & 0x40)", file=0x7f0d4e284916 "async.c", line=464, 
    function=0x7f0d4e284a70 "redisProcessCallbacks") at assert.c:105
#4  0x00007f0d4e282b9f in redisProcessCallbacks (ac=0x7f0d48001370) at async.c:464
#5  0x0000000000400ef0 in redisLibeventReadEvent (fd=8, event=2, arg=0x7f0d48000f70) at /usr/local/include/hiredis/adapters/libevent.h:45
#6  0x00007f0d4e04622b in event_process_active_single_queue (base=0x7f0d48000900, activeq=0x7f0d48000d50, max_to_process=2147483647, endtime=0x0) at event.c:1646
#7  0x00007f0d4e0469af in event_process_active (base=0x7f0d48000900, flags=<value optimized out>) at event.c:1738
#8  event_base_loop (base=0x7f0d48000900, flags=<value optimized out>) at event.c:1961
#9  0x00000000004015d1 in RedisThreadFunc (param=0x0) at RedisClient.c:192
#10 0x000000350b607aa1 in start_thread (arg=0x7f0d4e020700) at pthread_create.c:301
#11 0x000000350aee8aad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:115

**Comment by michael-grunder** [comment]
Fixed via fbc4971d7d49e9e39c3ba278be1ee9e99d00d41d
