### ISSUE TITLE
New to hiredis

### ISSUE THREAD

**Issue by Irminrics** [redis/hiredis#585]
Hi I'm new to hiredis or in general key value database, and I am quite lost now. Sorry for asking but after downloading the source code. Do I have to do anything before I compile? I tried to compile and run with some of the examples here: https://redislabs.com/lp/hiredis/. However it seems like there is an error saying some methods example sdsempty() in the hiredis.c file is not defined. Am I missing a step of making files or installing the hiredis library? I am very clueless right now and will appreciate any help I can get. Thanks in advance.

**Comment by michael-grunder** [comment]
Hi,

There are a variety of ways to install hiredis on Linux and Mac but from source the process would look like this:

```bash
$ git clone https://github.com/redis/hiredis.git
$ cd hiredis
$ make && sudo make install
```

That will install the required headers on your system.

Once hiredis is installed, you can get started by simply including `hiredis/hiredis.h`.

Here's a quick example program:

```c
#include <hiredis/hiredis.h>
#include <stdio.h>

int main(void) {
    redisContext *context;
    redisReply *reply;

    context = redisConnect("127.0.0.1", 6379);
    reply = redisCommand(context, "SET %s %s", "foo", "bar");
    if (!reply || context->err) {
        printf("Error setting key\n");
        return -1;
    }

    freeReplyObject(reply);

    reply = redisCommand(context, "GET %s", "foo");
    if (!reply || context->err) {
        printf("Error gettihng key\n");
        return -1;
    }

    printf("Key foo = '%s'\n", reply->str);

    freeReplyObject(reply);
    redisFree(context);
}
```

Compile like so:
```bash
cc hiredis-hello.c -o hiredis-hello -lhiredis
```

**Comment by Irminrics** [comment]
omg I'm sorry i forgot to mention that I was doing it on Windows. Is it technically possible to do it?

**Comment by michael-grunder** [comment]
The main hiredis repository doesn't support windows so I can't help much there :/

Here are a couple of Microsoft forks of hiredis and Redis which _might_ work, but I don't have any experience with them:
https://github.com/Microsoft/hiredis
https://github.com/MicrosoftArchive/redis

**Comment by Irminrics** [comment]
Its alright! Thanks for the help here. Really appreciate it!
