### ISSUE TITLE
ERR value is not an integer or out of range

### ISSUE THREAD

**Issue by vikrant-verma** [redis/hiredis#586]
const string script = " if redis.call('EXISTS', '{0}') == 1 then" +
                                  " local user = redis.call('get','{0}')" +
                                  " local value = cjson.decode(user)" +
                                  " value['UserPreferences'] = cjson.decode('{1}')" +
                                  " value['Timestamp'] = cjson.decode('{2}')" +
                                  " local val=cjson.encode(value)" +
                                  " redis.call('set', '{0}', val)" +
                                  " redis.call('EXPIRE', '{0}','{3}')" +
                                  " end";

            var redisScript = string.Format(script, "User_" + userId, JsonConvert.SerializeObject(userPreferences), JsonConvert.SerializeObject(DateTime.UtcNow), ConfigurationManager.AppSettings["RedisKeyExpiryTime"]);
          
                await Cache.ScriptEvaluateAsync(redisScript);
          

Please someone let me know what can be the issue I am getting this error.

**Comment by michael-grunder** [comment]
Hi,

Are you sure you're posting this issue to the right place?  This repo is for the official C library to Redis, but that looks like javascript?

**Comment by vikrant-verma** [comment]
I am using c#

**Comment by michael-grunder** [comment]
I'm not sure which client library you're using, but it'll be one of the C# clients listed [here](https://redis.io/clients)

This repo is for the C library (as in C/C++).  I'm closing this issue but I hope you find your solution.  😸
