### ISSUE TITLE
memory leak  libevent  async read

### ISSUE THREAD

**Issue by valdemarpavesi** [redis/hiredis#588]
memory leak during  libevent  async read

CallStack[1]: memory expires with 48 bytes, backtrace:
    0x00000000102cc080  calloc()+0
    0x00000000102737ec  hiredis.c:66
    0x0000000010276ce0  hiredis/read.c:235
    0x00000000102752e8  hiredis/hiredis.c:863
    0x0000000010275349  hiredis/hiredis.c:875
    0x0000000010272fbb  hiredis/async.c:417 (discriminator 1)
    0x00007ff28dd66a14  libevent-2.0.so  event_base_loop()+1908
    0x00000000102752e8  hiredis/hiredis.c:863

**Comment by valdemarpavesi** [comment]
0x00000000102737ec hiredis.c:66

https://github.com/redis/hiredis/blob/master/hiredis.c

calloc


/* Create a reply object */
static redisReply *createReplyObject(int type) {
    redisReply *r = calloc(1,sizeof(*r));

    if (r == NULL)
        return NULL;

    r->type = type;
    return r;
}

**Comment by michael-grunder** [comment]
Hi,

I'm not sure what you're trying to report here.  I don't see any leak when using hiredis async under libevent.  Can you provide a small program that demonstrates this leak?

**Comment by michael-grunder** [comment]
I'm going to close this issue since doesn't seem to be an actual bug.  If you can show a way to replicate a leak feel free to reopen.
