### ISSUE TITLE
no reply for event publish request

### ISSUE THREAD

**Issue by wangzhezhe** [redis/hiredis#589]
Hello, I want to use following function to send event publish request to redis server:

```
void redisPublish(redisContext *c, char *publishEventStrList, char *publishMessages)
{

    //publish command
    char command[COMMANDLEN];
    if (publishMessages == NULL)
    {
        strcpy(publishMessages, "null");
    }
    sprintf(command, "PUBLISH %s %s", publishEventStrList, publishMessages);
    printf("command:%s\n", command);

    redisReply *reply = (redisReply *)redisCommand(c, command);
    int j;
    printf("waiting for the reply\n");
    int returnValue = redisGetReply(c, (void **)&reply);
    printf("return value %d\n", returnValue);
    if (returnValue == REDIS_OK)
    {
        printf("get the publish return value (%s) element %d \n", reply->str, (int)reply->elements);
        if (reply->type == REDIS_REPLY_ARRAY)
        {
            for (j = 0; j < reply->elements; j++)
            {
                printf("%u) %s\n", j, reply->element[j]->str);
            }
        }
        freeReplyObject(reply);
    }
    else
    {
        printf("publish fail\n");
    }

    /* Disconnects and frees the context */
    redisFree(c);

    return;
}
```

But there is no reply, the code stop at the line of "waiting for the reply", even if the subscribed client have got the reply, I'm a little bit confused about this, thanks for your help.

**Comment by michael-grunder** [comment]
Hi,

I think you may be mixing up a few concepts which is why this isn't doing what you want it to do.

First, you're doing this:

```C
redisReply *reply = (redisReply *)redisCommand(c, command);
```

This will already consume the reply to `PUBLISH`, meaning that the next line:

```C
int returnValue = redisGetReply(c, (void **)&reply);
```

Will hang, because you've already consumed the reply to the _single_ command you sent.

Additionally, the [PUBLISH](https://redis.io/commands/publish) command is just going to return an integer (the number of subscribed clients).

You'll need to execute your SUBSCRIBE loop either in a separate program or at least using a different `redisContext` object.

**Comment by wangzhezhe** [comment]
Hi ,thanks for your reply, I got it.
But I'm still a little bit confused about the example in README file:
```
reply = redisCommand(context,"SUBSCRIBE foo");
freeReplyObject(reply);
while(redisGetReply(context,&reply) == REDIS_OK) {
    // consume message
    freeReplyObject(reply);
}
```
why the this example code use both  `redisCommand` and `redisGetReply` .

**Comment by michael-grunder** [comment]
The call to `redisCommand` is consuming the response to `SUBSCRIBE` itself.  Then, the idea is to call `redisGetReply` in a loop to consume the messages as they come in.

Here is a small example program that demonstrates this.  Run this program and then in `redis-cli` you can publish to the channel 'foo' and see messages.

```C
#include <hiredis/hiredis.h>
#include <stdio.h>
#include <stdlib.h>

int main(void) {
    redisContext *context = redisConnect("127.0.0.1", 6379);

    redisReply *reply = redisCommand(context,"SUBSCRIBE foo");
    if (!reply || context->err) {
        fprintf(stderr, "Error:  Cannot send SUBSCRIBE!\n");
        exit(-1);
    }

    printf("Subscribed to channel 'foo', ready to get messages!\n");
    freeReplyObject(reply);

    while(redisGetReply(context,(void**)&reply) == REDIS_OK) {
        if (reply->type != REDIS_REPLY_ARRAY || reply->elements != 3) {
            fprintf(stderr, "Error:  Malformed subscribe response!\n");
            exit(-1);
        }

        /* Print our message */
        printf("Received message: %s\n", reply->element[2]->str);

        freeReplyObject(reply);
    }
}
```

**Comment by wangzhezhe** [comment]
Got it, thanks for your clarification!
