### ISSUE TITLE
I get this error, ' sdslen   out of bounds at sds.h:87 '

### ISSUE THREAD

**Issue by Jayhello** [redis/hiredis#590]
#0  sdslen (s=0x32203d3d20657079 <Address 0x32203d3d20657079 out of bounds>) at sds.h:87
87      sds.h: No such file or directory.
(gdb) bt
#0  sdslen (s=0x32203d3d20657079 <Address 0x32203d3d20657079 out of bounds>) at sds.h:87
#1  sdscatlen (s=0x32203d3d20657079 <Address 0x32203d3d20657079 out of bounds>, t=0x7f6f8c001100, len=122) at sds.c:377
#2  0x00000000004187a0 in __redisAppendCommand (c=0x429070, cmd=<optimized out>, len=<optimized out>) at hiredis.c:1250
#3  0x0000000000418917 in redisAppendCommandArgv (c=0x429070, argc=<optimized out>, argv=<optimized out>, 
    argvlen=<optimized out>) at hiredis.c:1308
#4  0x0000000000418a68 in redisCommandArgv (c=0x429070, argc=<optimized out>, argv=<optimized out>, 
    argvlen=<optimized out>) at hiredis.c:1355

What may cause the above error ?

**Comment by michael-grunder** [comment]
There's no way we could figure out what is causing this error without much more information.  Have you tried running your program with valgrind to see what it reports?

**Comment by michael-grunder** [comment]
Closing this old issue.  Feel free to re-open if you can provide an example that demonstrates the problem.
