### ISSUE TITLE
Cluster support ?

### ISSUE THREAD

**Issue by naerion89** [redis/hiredis#591]
Will hiredis support Redis Cluster ? 

Regards

**Comment by michael-grunder** [comment]
No, hiredis does not support cluster but I believe there are various libraries that have wrapped hiredis and do support cluster.

I don't have any experience with them though, so I can't make a recommendation.

**Comment by rcosnita** [comment]
Hiredis-vip is a great library for redis cluster. It relies internally on hiredis-vip. It supports both batch and async modes.

**Comment by ping2balaji** [comment]
@michael-grunder , can i know why it does not make sense to add redis-cluster support in hiredis itself?
Hiredis is officially supported C library for redis. Isn't it good to add support for redis features ?

**Comment by michael-grunder** [comment]
Hey,

Hiredis has a pretty minimal API that lets you communicate with Redis (or any service that uses the RESP protocol).  In fact, a lot of projects just use hiredis as the protocol layer to their higher level library (e.g. hiredis-rb, hiredis-py, hiredis-node).

Providing cluster support would add a substantial amount of complexity to the project, and at least so far that's out of scope for what hiredis does.

In addition, it would be quite a large project to implement.
