### ISSUE TITLE
Maintainers?

### ISSUE THREAD

**Issue by justinbrewer** [redis/hiredis#594]
Does this project have any maintainers? There's been no code activity or responses to PRs in several months. Apart from the occasion response to issues, this project seems to be dead in the water.

**Comment by michael-grunder** [comment]
Hey Justin,

As far as I know, there isn't really anyone actively maintaining the project.  The closest thing is probably me.

I try to help with issue reports and do have access to update the repo but I also maintain phpredis and have a day job.

I got the async subscribe/unsubscribe PR merged, and will take a closer look at yours this weekend.

**Comment by justinbrewer** [comment]
Thanks for your efforts, Michael. I don't mean to pressure you into spending time you don't have. I'm happy to volunteer to help out if you need it.

**Comment by justinbrewer** [comment]
I also use Hiredis as a large part of my job, so I've got more lined up.
