### ISSUE TITLE
New hiredis fails to compile on Windows

### ISSUE THREAD

**Issue by galuszkak** [redis/hiredis#599]
I started working on upgrade of hiredis in hiredis-py to new version of hiredis (from `master` branch) and while it compiles well on Linux & macOS then I have a problem on Windows. Stack trace from compilation:
```
c:\projects\hiredis-py\vendor\hiredis\sds.h(46) : error C2061: syntax error : identifier 'sdshdr5'
c:\projects\hiredis-py\vendor\hiredis\sds.h(46) : error C2059: syntax error : ';'
c:\projects\hiredis-py\vendor\hiredis\sds.h(46) : error C2449: found '{' at file scope (missing function header?)
c:\projects\hiredis-py\vendor\hiredis\sds.h(49) : error C2059: syntax error : '}'
c:\projects\hiredis-py\vendor\hiredis\sds.h(56) : error C2061: syntax error : identifier 'sdshdr16'
c:\projects\hiredis-py\vendor\hiredis\sds.h(56) : error C2059: syntax error : ';'
c:\projects\hiredis-py\vendor\hiredis\sds.h(56) : error C2449: found '{' at file scope (missing function header?)
c:\projects\hiredis-py\vendor\hiredis\sds.h(61) : error C2059: syntax error : '}'
c:\projects\hiredis-py\vendor\hiredis\sds.h(68) : error C2061: syntax error : identifier 'sdshdr64'
c:\projects\hiredis-py\vendor\hiredis\sds.h(68) : error C2059: syntax error : ';'
c:\projects\hiredis-py\vendor\hiredis\sds.h(68) : error C2449: found '{' at file scope (missing function header?)
c:\projects\hiredis-py\vendor\hiredis\sds.h(73) : error C2059: syntax error : '}'
c:\projects\hiredis-py\vendor\hiredis\sds.h(103) : error C2054: expected '(' to follow 'inline'
c:\projects\hiredis-py\vendor\hiredis\sds.h(103) : error C2085: 'sdsavail' : not in formal parameter list
c:\projects\hiredis-py\vendor\hiredis\sds.h(103) : error C2143: syntax error : missing ';' before '{'
c:\projects\hiredis-py\vendor\hiredis\sds.h(129) : error C2054: expected '(' to follow 'inline'
c:\projects\hiredis-py\vendor\hiredis\sds.h(129) : error C2085: 'sdssetlen' : not in formal parameter list
c:\projects\hiredis-py\vendor\hiredis\sds.h(129) : error C2143: syntax error : missing ';' before '{'
c:\projects\hiredis-py\vendor\hiredis\sds.h(153) : error C2054: expected '(' to follow 'inline'
c:\projects\hiredis-py\vendor\hiredis\sds.h(153) : error C2085: 'sdsinclen' : not in formal parameter list
c:\projects\hiredis-py\vendor\hiredis\sds.h(153) : error C2143: syntax error : missing ';' before '{'
c:\projects\hiredis-py\vendor\hiredis\sds.h(179) : error C2054: expected '(' to follow 'inline'
c:\projects\hiredis-py\vendor\hiredis\sds.h(179) : error C2085: 'sdsalloc' : not in formal parameter list
c:\projects\hiredis-py\vendor\hiredis\sds.h(179) : error C2143: syntax error : missing ';' before '{'
c:\projects\hiredis-py\vendor\hiredis\sds.h(196) : error C2054: expected '(' to follow 'inline'
c:\projects\hiredis-py\vendor\hiredis\sds.h(196) : error C2085: 'sdssetalloc' : not in formal parameter list
c:\projects\hiredis-py\vendor\hiredis\sds.h(196) : error C2143: syntax error : missing ';' before '{'
vendor/hiredis/read.c(77) : warning C4013: 'snprintf' undefined; assuming extern returning int
vendor/hiredis/read.c(121) : warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data
vendor/hiredis/read.c(211) : warning C4146: unary minus operator applied to unsigned type, result still unsigned
vendor/hiredis/read.c(227) : warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data
vendor/hiredis/read.c(313) : warning C4267: '=' : conversion from 'size_t' to 'unsigned long', possible loss of data
vendor/hiredis/read.c(336) : warning C4244: '+=' : conversion from '__int64' to 'unsigned long', possible loss of data
```

On Python 2.7 build we have this problem:
```
c:\projects\hiredis-py\vendor\hiredis\sds.h(40) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
```

PR that I'm referring to:
https://github.com/redis/hiredis-py/pull/66

AppVeyor build:
https://ci.appveyor.com/project/badboy/hiredis-py/build/51

Thanks for any help

**Comment by michael-grunder** [comment]
Hey, thanks for the report.

Disclaimer:  I haven't developed on Windows in many years so take this with a grain of salt.

I don't know if there is a simple way to solve these problem(s).  It looks like MSVC is choking on the added [\_\_attribute_\_ ((\_\_packed\_\_))](https://github.com/redis/hiredis/blob/master/sds.h#L46) declarations in the updated `sds.h` library and according a bit of googling it looks like there aren't really clean ways to solve it.

A couple of solutions are described in this [StackOverflow question](https://stackoverflow.com/questions/1537964/visual-c-equivalent-of-gccs-attribute-packed), but that leads to a separate issue where Hiredis and Redis will have diverging sds implementations.

Regardless I'll look into it a bit more and see if any of the above solutions are reasonable.

**Comment by galuszkak** [comment]
Thanks @michael-grunder for looking into that.

I don't have any significant experience with C, so I can't help with that. If there is anything I can test or give feedback let me know.

**Comment by mnunberg** [comment]
Most likely it's actually the missing `stdint.h` header. Python 2.7 uses an ancient version of MSVC (I believe 2008?) to compile it; that version of MSVC (and all versions up to 2013) lack support for C99. There are some additional add-on headers that can be used in its stead, though.

**Comment by mnunberg** [comment]
Is Windows compatibility still a goal for us?

**Comment by uglide** [comment]
@michael-grunder Using `PACK` macro as described here https://stackoverflow.com/a/3312896 looks quite reasonable for hiredis.

**Comment by mbitsnbites** [comment]
Just to chime in... I think that support for Windows (ideally at least MSVC and MinGW) should be natural for a project like hiredis, especially as it's considered the "the official C client" for redis (according to the [redis.io homepage](https://redis.io/clients#c)).

Since Travis-CI now has support for building on Windows, it should make it easier to prevent platform breakage (even if most hiredis developers don't use Windows).

(I personally only develop on Linux, but since I want my projects to be portable I need them to work on Windows too - thus I can't use hiredis for my projects at the moment).

**Comment by mbitsnbites** [comment]
BTW, this is the project where I'm using hiredis right now: https://github.com/mbitsnbites/buildcache (Redis support for Windows is disabled).

**Comment by michael-grunder** [comment]
Closing via #652
