### ISSUE TITLE
support for SSL?

### ISSUE THREAD

**Issue by egbertn** [redis/hiredis#603]
Hi, Are there any plans to support an SSL encrypted connection to Redis?

Thanks.

**Comment by mnunberg** [comment]
There's quite an old pull request which I've done to make hiredis use SSL: https://github.com/redis/hiredis/pull/570

**Comment by jcohen02** [comment]
Hi. It would be great to see the SSL support merged into master. I've had some success testing the SSL updates rebased onto 0.14.0, talking to redis via stunnel. Happy to try and assist if there's anything I can do to help take this forward.

**Comment by itamarhaber** [comment]
This is currently under consideration in #570

**Comment by mnunberg** [comment]
Merged

**Comment by pchoudhary-jnpr** [comment]
Hi @mnunberg 
Will there be another minor release 0.15 which has SSL support ?

Thanks,
Pradeep
