### ISSUE TITLE
async callback functions

### ISSUE THREAD

**Issue by pbarry1** [redis/hiredis#605]
I have a question re. the hiredis async library.   In particular the callback function associated with a redisAsyncCommand command.   I am doing the following in my application. 

// Get a redis async connection
_redidContext =   redisAsyncConnect(“127.0.0.1”) 

//Executes a redis “subscribe” command and specifies a callback function “subCallback” defined //elsewhere in the application 
Status =   redisAsyncCommand(_redisContext, subCallback, (char*)”sub”, command.c_str());    

I'm using the libEvent library to listen for messages published to a redis channel.  When they occur the callback function is executed.  My main question is "Does the callback function run in a separate thread or does it execute within the main thread of execution?"  My concern is that hiredis or libevent will create a new thread for this callback that executes concurrently with the application's main execution thread. Thus introducing possible concurrent processing problems.

The hiredis readme.md file reads *Note: A `redisAsyncContext` is not thread-safe.*   Maybe you could explain in a little more detail what is meant by this statement. But my understanding of this is if you have a multi-threaded application you cannot use a single  redis connection with more than one thread and be assured exclusive access at any one time to redis data by a single thread of execution.   My application is single threaded so I don’t expect this is a concern for me.   But maybe you could you confirm this for me?   

Thank you,   Paul Barry

**Comment by michael-grunder** [comment]
I haven't done much work with async hiredis but it is my understanding that everything will run on one thread unless you explicitely create the event loop in a different thread.

Take for example, this quick and dirty program:

```c
#include <stdio.h>
#include <signal.h>
#include <unistd.h>
#include <hiredis/hiredis.h>
#include <hiredis/async.h>
#include <hiredis/adapters/libevent.h>

void subscribeCallback(redisAsyncContext *c, void *r, void *privdata) {
    redisReply *reply = r;
    if (reply && reply->type == REDIS_REPLY_ARRAY) {
        for (int i = 0; i < reply->elements; i++) {
            printf("reply->element[i] = ");
            switch (reply->element[i]->type) {
                case REDIS_REPLY_STRING:
                    printf("%s\n", reply->element[i]->str);
                    break;
                case REDIS_REPLY_INTEGER:
                    printf("%lld\n", reply->element[i]->integer);
                    break;
                default:
                    printf("OTHER TYPE (not handled)\n");
            }
        }
    }
}

int main (int argc, char **argv) {
    signal(SIGPIPE, SIG_IGN);
    struct event_base *base = event_base_new();

    printf("Our PID is: %d\n", getpid());

    redisAsyncContext *c = redisAsyncConnect("127.0.0.1", 6379);

    redisLibeventAttach(c,base);
    redisAsyncCommand(c, subscribeCallback, NULL, "SUBSCRIBE %s", "foo");
    event_base_dispatch(base);
    return 0;
}
```

This works to print published messages, and I only see a single thread:

```bash
➜  examples git:(master) ✗ ./asyncsubscribe
Our PID is: 696
reply->element[i] = subscribe
reply->element[i] = foo
reply->element[i] = 1
```

```bash
➜  ~ ps huH 696
mike       696  0.0  0.0  11180  1036 pts/4    S+   10:02   0:00 ./asyncsubscribe
➜  ~ ls /proc/696/task
696
```

**Comment by pbarry1** [comment]
thanks,  
So the pid for the main thread is 696.  I don't see how this shows that the callback executes within the same thread though.  Shouldn't you also execute getpid() within the callback function to see if it's the same?

**Comment by michael-grunder** [comment]
The PID and TID (thread id) are the same in `main()` and `subscribeCallback()`.  You can check for yourself [with this modified example](https://gist.github.com/michael-grunder/bb914ef4801f2dd769509ed486d4a2f1).

```bash
Our PID is: 5751, TID: 5751
Callback PID: 5751, TID: 5751
reply->element[i] = subscribe
reply->element[i] = foo
reply->element[i] = 1
```

It would be highly inefficient for libevent to spawn a new thread per callback invocation.  That would defeat the whole purpose of an event loop! :smile:
