### ISSUE TITLE
npm ERR! hiredis@0.5.0 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by ikewyz** [redis/hiredis#607]
my linux is ubuntu1604, node 8.11.4, npm 4.6.1.  I use ioredis in my express webapp, when i npm install in ubuntu, there was a error. It is ok in my mac OS. 
I search by google and stackoverflow, but there has not solution to solve it. Please help me!!!

1. when i run "npm install" +++++++++++++++++++++++++++
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/work/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command "/home/work/.nvm/versions/node/v8.11.4/bin/node" "/home/work/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/work/services/node/code/shijin3_backend/node_modules/hiredis
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.3 (node_modules/sane/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/cpx/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open '/home/work/services/node/code/shijin3_backend/node_modules/build/package.json'
npm WARN shijin-app@0.1.0 license should be a valid SPDX license expression
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hiredis@0.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hiredis@0.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

2.when I run "node-gyp rebuild" +++++++++++++++++++++++
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.11.4 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/work/.nvm/versions/node/v8.11.4/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/work/services/node/code/shijin3_backend/node_modules/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/work/.nvm/versions/node/v8.11.4/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/work/.node-gyp/8.11.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/work/.node-gyp/8.11.4',
gyp info spawn args   '-Dnode_gyp_dir=/home/work/.nvm/versions/node/v8.11.4/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/work/.node-gyp/8.11.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/work/services/node/code/shijin3_backend/node_modules',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /home/work/services/node/code/shijin3_backend/node_modules) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/work/.nvm/versions/node/v8.11.4/lib/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command "/home/work/.nvm/versions/node/v8.11.4/bin/node" "/home/work/.nvm/versions/node/v8.11.4/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/work/services/node/code/shijin3_backend/node_modules
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by michael-grunder** [comment]
Hi,

I think you might have better luck if you post your issue here:
https://github.com/redis/hiredis-node/issues

**Comment by ikewyz** [comment]
thanks
