### ISSUE TITLE
Add CMake support

### ISSUE THREAD

**Issue by mnunberg** [redis/hiredis#611]
CMake would live side-by-side a simpler Makefile, and would allow easier integration into existing CMake projects, as well as easy building for Windows. Right now our Windows build environment seems to use Cygwin and/or Mingw32, which is less than optimal, especially if we are targeting MSVC for PHP/Python.

**Comment by thomaslee** [comment]
If it's helpful, these are the steps I took to add some simple cmake support to the Debian packaging: https://github.com/thomaslee/hiredis-debian/blob/master/debian/patches/07_cmake.patch. I'm not a particularly active user of hiredis+cmake, so I wouldn't say it's well-exercised but I haven't received any bug reports. Might be a reasonable starting point if nothing else.

Also worth mentioning the capnproto guys went through something similar a while back over in https://github.com/capnproto/capnproto/pull/575. More discussion RE: capnproto, autotools & cmake over in https://github.com/capnproto/capnproto/issues/523 too. Maybe some lessons to learn from how they did it, I didn't follow along as closely as I maybe should have. :sweat_smile:

**Comment by justinbrewer** [comment]
If there's any interest, I had put together an autotools port a few months ago, though never submitted it for review. It's now freshly rebased.

https://github.com/justinbrewer/hiredis/tree/autotools

**Comment by mnunberg** [comment]
I don't mind adding autotools, but I can't promise to maintain it. If someone else wants to maintain it if we ever change structure, etc. then I have no issue. The more systems, the better- though I obviously prefer CMake from a maintainability standpoint.

**Comment by michael-grunder** [comment]
I've got nothing against CMake or autotools but we should be mindful that this code is periodically pulled into Redis, which doesn't use either of those systems.

Jemalloc does use autotools so it's certainly doable, but just something to keep in mind.

**Comment by thomaslee** [comment]
FWIW it would be trivial to generate pkg-config .pc files from the existing Makefile, which in turn can be used by CMake users via 

```
find_package(PkgConfig)
pkg_check_modules(LIBFOO REQUIRED libfoo)
```

Happy to PR this at some point if it's useful.

**Comment by thomaslee** [comment]
Oh, looks like we're already doing that -- nm.

**Comment by mnunberg** [comment]
The main reason I’d like to use CMake is in order to be able to test/run it on as many platforms as possible. But adding a specific CMake project (vs just adding a FindHiredis.cmake file) allows users to embed it into their project, rather than just link it as a DSO. This is of course an antipattern in Debian, but helpful in case things want to vendor it. :)

**Comment by thomaslee** [comment]
Why do you hate freedom? :sob: Kidding, totally understand.

More seriously, vendoring _is_ something of a pain in the butt for package maintainers -- but a) that's not what you're doing in hiredis itself, and b) I've certainly been in the position where it would've been nice to have fist-class/supported cmake files for the purposes of vendoring in personal projects. :wink: 

And yeah, for better or worse hard to beat cmake for cross-platform stuff at the moment.

**Comment by mnunberg** [comment]
I've been using Debian since sarge. My first Linux distro and probably the one I'll always continue using :)

**Comment by justinbrewer** [comment]
If first-class support for Visual Studio / MSVC is intended, then CMake is probably the only option. OTOH, if all you want is to be able to produce a native Windows DLL, then MinGW + autotools is perfectly capable of that.

I don't mind either way (and it's not my decision). I just saw the discussion and wanted to offer up some work I had already done. And autotools files aren't _too_ complicated to maintain. :wink:

BTW,

> CMake would live side-by-side a simpler Makefile

If you're supporting a Makefile generator, you may as well go all-in and drop the bare Makefile.

**Comment by michael-grunder** [comment]
Hiredis has never officially supported Windows:
https://github.com/redis/hiredis/issues/403#issuecomment-360224993

We could certainly change that but I'm not really sure how big a job it would be, as I have no Windows machines (just Linux and a hipster Mac) :smile:

**Comment by mnunberg** [comment]
I don't personally use Windows, but at least on Python, I know that it *generally* requires to use the same compiler that was used to compile Python itself, i.e. MSVC. I'd hazard to guess that if we compiled hiredis on Windows today, it would fail, *including* the parser part. One of the things CMake can do for us quite easily, is let us write a test target for the parser itself, and only compiling the non-parser code if the platform is not Win32.

**Comment by mnunberg** [comment]
And it appears that the sds version used is too old anyway.. oh well, no Windows support :/

**Comment by mnunberg** [comment]
done!
