### ISSUE TITLE
compile with libevent

### ISSUE THREAD

**Issue by DGuco** [redis/hiredis#617]
the adapters/libevent.h use the function  of stand library: free and malloc,when i compile with libevent,the compile give me the error:‘free’ was not declared in this scope and malloc’ was not declared in this scope,
and i included the <stdlib.h> to adapters/libevent.h  and recompile ,then everyting is right

**Comment by DGuco** [comment]
forgive my lousy english

**Comment by michael-grunder** [comment]
It's true that the adapter is missing an include to `stdlib.h` and we could add it, but I can only really cause an issue if I _only_ include that file (and not hiredis).
