### ISSUE TITLE
sdsMakeRoomFor, realloc(): invalid next size

### ISSUE THREAD

**Issue by Denny007** [redis/hiredis#619]
Hi, it comes up coredump when I write data to redis used hiredis, This is backstrace:
`#0  0x00007fceed66f277 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fceed670968 in __GI_abort () at abort.c:90
#2  0x00007fceed6b1d37 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7fceed7c3d58 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/unix/sysv/linux/libc_fatal.c:196
#3  0x00007fceed6b85e4 in malloc_printerr (action=<optimized out>, str=0x7fceed7c1477 "realloc(): invalid next size", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5025
#4  0x00007fceed6bdc39 in _int_realloc (av=av@entry=0x7fc694000020, oldp=oldp@entry=0x7fc6940125d0, oldsize=oldsize@entry=32, nb=nb@entry=32) at malloc.c:4244
#5  0x00007fceed6beeb2 in __GI___libc_realloc (oldmem=0x7fc6940125e0, bytes=6) at malloc.c:3030
#6  0x00000000006937eb in sdsMakeRoomFor (s=0x7fc6940125e3 "", addlen=1) at sds.c:221
#7  0x0000000000693e85 in sdscatlen (s=0x7fc6940125e3 "", t=0x86e170, len=1) at sds.c:382
#8  0x000000000069109d in redisvFormatCommand (target=0x7fc69effafa0, format=0x86e170 "ECHO suricata", ap=0x7fc69effafe0) at hiredis.c:245
#9  0x0000000000697c02 in redisvAsyncCommand (ac=0x7fc694011f30, fn=0x40b79d <SCRedisAsyncEchoCommandCallback>, privdata=0x7fc694000a40, format=0x86e170 "ECHO suricata", ap=0x7fc69effafe0) at async.c:681
#10 0x0000000000697cfb in redisAsyncCommand (ac=0x7fc694011f30, fn=0x40b79d <SCRedisAsyncEchoCommandCallback>, privdata=0x7fc694000a40, format=0x86e170 "ECHO suricata") at async.c:696
#11 0x000000000040ba52 in SCLogAsyncRedisSendEcho (ctx=0x7fc694000a40) at /data/denny/DPI/suricata_4.0/util-log-redis.c:155
#12 0x000000000040c1da in SCLogRedisWriteAsync (file_ctx=0x7fc694000940, 
    string=0x7fc694000ac0 "{\"timestamp\":\"2018-10-23T11:20:06.002118+0800\",\"flow_id\":1056392625111016,\"event_type\":\"flow\",\"src_ip\":\"106.75.151.132\",\"src_port\":46771,\"dest_ip\":\"106.75.39.24\",\"dest_port\":48237,\"proto\":\"TCP\",\"flow\""..., string_len=503) at /data/denny/DPI/suricata_4.0/util-log-redis.c:254
#13 0x000000000040ceac in LogFileWriteRedis (lf_ctx=0x7fc694000940, 
    string=0x7fc694000ac0 "{\"timestamp\":\"2018-10-23T11:20:06.002118+0800\",\"flow_id\":1056392625111016,\"event_type\":\"flow\",\"src_ip\":\"106.75.151.132\",\"src_port\":46771,\"dest_ip\":\"106.75.39.24\",\"dest_port\":48237,\"proto\":\"TCP\",\"flow\""..., string_len=503) at /data/denny/DPI/suricata_4.0/util-log-redis.c:427
#14 0x000000000064b778 in LogFileWrite (file_ctx=0x7fc694000940, buffer=0x7fc694000ab0) at /data/denny/DPI/suricata_4.0/util-logopenfile.c:665
#15 0x0000000000644803 in OutputJSONBuffer (js=0x7fc694010b20, file_ctx=0x7fc694000940, buffer=0x7fc694000910) at /data/denny/DPI/suricata_4.0/output-json.c:529
#16 0x0000000000594aae in JsonFlowLogger (tv=0x3895be0, thread_data=0x7fc694000900, f=0x352e630) at /data/denny/DPI/suricata_4.0/output-json-flow.c:368
#17 0x000000000051774c in OutputFlowLog (tv=0x3895be0, thread_data=0x7fc6940008e0, f=0x352e630) at /data/denny/DPI/suricata_4.0/output-flow.c:112
#18 0x00000000004e6d29 in FlowRecycler (th_v=0x3895be0, thread_data=0x7fc6940008c0) at /data/denny/DPI/suricata_4.0/flow-manager.c:933
#19 0x00000000004d425a in TmThreadsManagement (td=0x3895be0) at /data/denny/DPI/suricata_4.0/tm-threads.c:709
#20 0x00007fceefa4ce25 in start_thread (arg=0x7fc69effd700) at pthread_create.c:308
#21 0x00007fceed737bad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
`

**Comment by michael-grunder** [comment]
I'm assuming this has been resolved on your end, but fee free to reopen if you can provide an example to replicate the issue
