### ISSUE TITLE
add private data on connection callbacks in async APIs

### ISSUE THREAD

**Issue by linuxrc** [redis/hiredis#622]
It's very not convenient when use the connection and discnnection callback for the async APIs, for the user doesn't know their context in the callback.
I advised that add the private data to the connection callback functions.
Just as follows:

typedef struct redisAsyncContext {
   ........
    /* Subscription callbacks */
    struct {
        redisCallbackList invalid;
        struct dict *channels;
        struct dict *patterns;
    } sub;
    +void *connection_data;
}

And then add two APIs:

 +int redisAsyncSetConnectionData(redisAsyncContext *ac, void *privdata)
 +{
+if (ac->onConnect!=NULL || ac->onDisconnect!=NULL) {
+return REDIS_ERR;
+}
+ac->connection_data = privdata;
+return REDIS_OK;
+}

+void *redisAsyncGetConnectionData(const redisAsyncContext *ac)
+{
+return ac->connection_data;
+}

 And in the initialize function:
 static redisAsyncContext *redisAsyncInitialize(redisContext *c) {
   .....
    +ac->connection_data=NULL;
   ......
 }

And finaly, in the connection and disconnection callbacks, we can use redisAsyncGetConnectionData to get the user context.

**Comment by Crunsher** [comment]
I had the same issue and found you can use `ac->data` to can hold arbitrary user data.
