### ISSUE TITLE
Async connect failure with unix socket. Regression from merge pull request #578

### ISSUE THREAD

**Issue by guillaumef** [redis/hiredis#629]
It broke my 'eredis' client library so I investigated. #578 @mnunberg 

The new redisCheckConnectDone() is only managing tcp socket.
With unix socket, c->saddr is NULL and the connect fails, of course invariably, with an errno EINVAL => REDIS_ERR.

To keep the logic, for the unix socket, redisContextConnectUnix() need to store also its sockaddr_un in the redis context and redisCheckConnectDone() need to use it.

**Comment by mnunberg** [comment]
Thanks for the bug report. Indeed, I didn't test it with Unix sockets when I implemented it, but the fix seems simple enough.

**Comment by vstakhov** [comment]
Am I alone who sees a clear memory leak in 088d146?

**Comment by mnunberg** [comment]
@vstakhov this should be freed when the object is freed as well, see https://github.com/redis/hiredis/blob/master/hiredis.c#L692

**Comment by vstakhov** [comment]
Ok, it now makes some sense indeed as it is also assigned to `c->saddr`, thanks. The return result from `malloc` should be checked for NULL however.
