### ISSUE TITLE
hiredis Perform write and read operations and report an error as "Resource temporarily unavailable"

### ISSUE THREAD

**Issue by xingmengyoulan** [redis/hiredis#630]

**Comment by mnunberg** [comment]
This needs more information.

**Comment by mnunberg** [comment]
This certainly sounds odd.. I believe this is the string error form of `EAGAIN`... and of course, you shouldnn't be getting EAGAIN in blocking mode....

**Comment by michael-grunder** [comment]
Going to close this old issue because there really isn't enough to go on without code that can reproduce the problem.
