### ISSUE TITLE
about Synchronous command interface callback function

### ISSUE THREAD

**Issue by rongzl** [redis/hiredis#633]
Programming with qt, and I Using the code Refer to the qt example in the example
`    if(m_redisCtx == NULL){
        m_redisCtx = redisAsyncConnect(m_strServerIp.c_str(), 6379);

        if (!m_redisCtx || m_redisCtx->err) {
            cout << "Error: " << m_redisCtx->errstr << endl;
            redisAsyncFree(m_redisCtx);
            m_redisCtx = NULL;
            return -1;
        }

        m_redisCtx->ev.data = this;
        m_redisCtx->ev.addRead = redisAddRead;
        m_redisCtx->ev.delRead = redisDelRead;
        m_redisCtx->ev.addWrite = redisAddWrite;
        m_redisCtx->ev.delWrite = redisDelWrite;
        m_redisCtx->ev.cleanup = redisCleanup;

        redisAsyncSetConnectCallback(m_redisCtx, m_connectHandle);
        redisAsyncSetDisconnectCallback(m_redisCtx, m_disconnectHandle);
    }`
Everything is normal, Both connect and disconnect callbacks running well, There are some problems with executing command callbacks. when i use GET/SET command: 
`redisAsyncCommand(m_redisCtx, m_commandHandle, this, "SET key %s", "hello");
redisAsyncCommand(m_redisCtx, m_commandHandle, this, "GET key");`
In this case, you can enter the callback function. but how to use subscribe interface command callback function?
I use "redisAsyncCommand(m_redisCtx, m_commandHandle, this, "SUBSCRIBE channel-test");",but nothing happened.
        m_redisCtx->ev.data = this;
        m_redisCtx->ev.addRead = redisAddRead;
        m_redisCtx->ev.delRead = redisDelRead;
        m_redisCtx->ev.addWrite = redisAddWrite;
        m_redisCtx->ev.delWrite = redisDelWrite;
        m_redisCtx->ev.cleanup = redisCleanup;
        m_redisCtx->onConnect = connectCallback;
        m_redisCtx->onDisconnect = disConnectCallback; 
using the current way not libevt way，how should I set the callback function?
there are variables in the structure  redisAsyncContext, as follow: 
m_redisCtx->replies
m_redisCtx->sub
I don't know how to use the subscription command callback, How should I use the subscription command callback?

**Comment by michael-grunder** [comment]
Closing this old issue.
