### ISSUE TITLE
redisvFormatCommand "out of memory"

### ISSUE THREAD

**Issue by qqzhou2018** [redis/hiredis#637]
hi manager,

When we use API redisvFormatCommand which exists in hiredis interface as below:
redisvFormatCommand("%.*s", 4, "this is a test");

We will get "Out of memroy"

It seems that function redisvFormatCommandwill not treat '*s' follow '.' as a format.

```c
/* Precision */
if (*_p == '.') {
    _p++;
    while (*_p != '\0' && isdigit(*_p)) _p++;
}
```

**Comment by qqzhou2018** [comment]
compare with printf.c, below code should be added

/* get field width */
    field_width = -1;
    if (isdigit(*fmt))
      field_width = skip_atou(&fmt);
    else if (*fmt == '*') {
      ++fmt;
      /* it's the next argument */
      field_width = va_arg(args, int);
      if (field_width < 0) {
    field_width = -field_width;
    flags |= LEFT;
      }
    }

**Comment by michael-grunder** [comment]
This is a difference between printf, but I don't think our goal is to support every single standard printf specifier.
