### ISSUE TITLE
Could be better to avoid the unused-variable warning when the assert() is disabled

### ISSUE THREAD

**Issue by axqd** [redis/hiredis#642]
There are many ways to avoid this warning with assert().

> error: unused variable 'ret' [-Werror=unused-variable]

https://github.com/redis/hiredis/blob/e6e5a2cba66edfb4b422f996640672e056328380/async.c#L339

```
    if (ac->err == 0) {
        /* For clean disconnects, there should be no pending callbacks. */
        int ret = __redisShiftCallback(&ac->replies,NULL);
        assert(ret == REDIS_ERR);
    } else {
```

**Comment by michael-grunder** [comment]
Looks like we already handle this in [test.c](https://github.com/redis/hiredis/blob/5d0568d9ae49363ad21b512c52025e45bbf8d02e/test.c#L63) and could do something similar.
