### ISSUE TITLE
Allow to change SSL Mode

### ISSUE THREAD

**Issue by huyphams** [redis/hiredis#646]
Updated:
- Hiredis SSL default mode is SSL_VERIFY_PEER, which requires a valid certification.
- Amazon ElasticCache (and some servers) doesn't require a certification because the client is a trusted source. So it would be great if Hiredis support an ability to change the SSL mode in the `redisSecureConnection`

======
Original content:

I can connect to the ElastiCache instance without SSL successfully but when I tried to connect to the ElastiCache using SSL, I got this error:

I'm using the master with this merge: https://github.com/redis/hiredis/pull/645 thanks for supporting SSL

```
ST(0x10). before/connect initialization. R(0x1)U
ST(0x1001). before/connect initialization. R(0x1)U
ST(0x1001). SSLv2/v3 write client hello A. R(0x1)U
ST(0x1001). unknown state. R(0x1)U
ST(0x4008). unknown state. R(0x230)F
ST(0x1002). error. R(0xffffffff)U
ST(0x1002). error. R(0xffffffff)U
```

Error message: SSL_connect() failed

ElastiCache Redis 5.0.0
Encryption in-transit: Yes
Hiredis at commit: https://github.com/redis/hiredis/commit/297de989a647a6f96f25aabea267aa0d18c43328

Let me know if you need anything else, thanks!

**Comment by mnunberg** [comment]
have you tried with openssl s_client? this might help debug some issues beforehand.

**Comment by huyphams** [comment]
I've tried the lasted commit on master but still got the same error, here is the openssl s_client detail.
```
[centos]$ openssl s_client -connect master.xxxx.ewbgtg.use1.cache.amazonaws.com:6379
CONNECTED(00000003)
depth=4 C = US, O = "Starfield Technologies, Inc.", OU = Starfield Class 2 Certification Authority
verify return:1
depth=3 C = US, ST = Arizona, L = Scottsdale, O = "Starfield Technologies, Inc.", CN = Starfield Services Root Certificate Authority - G2
verify return:1
depth=2 C = US, O = Amazon, CN = Amazon Root CA 1
verify return:1
depth=1 C = US, O = Amazon, OU = Server CA 1B, CN = Amazon
verify return:1
depth=0 CN = *.xxxx.ewbgtg.use1.cache.amazonaws.com
verify return:1
---
Certificate chain
 0 s:/CN=*.xxxx.ewbgtg.use1.cache.amazonaws.com
   i:/C=US/O=Amazon/OU=Server CA 1B/CN=Amazon
 1 s:/C=US/O=Amazon/OU=Server CA 1B/CN=Amazon
   i:/C=US/O=Amazon/CN=Amazon Root CA 1
 2 s:/C=US/O=Amazon/CN=Amazon Root CA 1
   i:/C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./CN=Starfield Services Root Certificate Authority - G2
 3 s:/C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./CN=Starfield Services Root Certificate Authority - G2
   i:/C=US/O=Starfield Technologies, Inc./OU=Starfield Class 2 Certification Authority
---
Server certificate
-----BEGIN CERTIFICATE-----
THE CERTIFICATION
-----END CERTIFICATE-----
subject=/CN=*.xxxx.ewbgtg.use1.cache.amazonaws.com
issuer=/C=US/O=Amazon/OU=Server CA 1B/CN=Amazon
---
No client certificate CA names sent
Peer signing digest: SHA256
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 5128 bytes and written 415 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: _THE SESSION ID_
    Session-ID-ctx:
    Master-Key: _____THE MASTER KEY____
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1559301405
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

**Comment by mnunberg** [comment]
What arguments are you passing?

**Comment by huyphams** [comment]
After making the connection, I called the `redisSecureConnection(redis, nil, nil, nil, nil)`

**Comment by huyphams** [comment]
I see that in the SSL log, hiredis sent `SSLv2/v3 write client hello ` but in the Amazon returned ` New, TLSv1/SSLv3` is it related?

**Comment by mnunberg** [comment]
if you’re passing all NULLs, it’s possible the library doesn’t know how to authenticate your CA. I might need to call load_verify_locations or similar, maybe.

Try passing the exact server-side certificate as the `ca` argument, and see if that works.

I don’t think the v2/v3 vs. TLS matters, but it’s possible. It just refers to the SSL_METHOD name.

**Comment by huyphams** [comment]
Amazon ElasticCache doesn't provide any certification, If I change the SSL mode to SSL_VERIFY_NONE, it will work. Maybe we should allow changing the SSL mode?
<img width="1209" alt="abc" src="https://user-images.githubusercontent.com/3654622/58712852-97de6b00-83eb-11e9-9af3-2ebd556ddd79.png">

**Comment by mnunberg** [comment]
Using VERIFY_NONE kind of defeats the point of using SSL in the first place, since you then become subject to man-in-the-middle attacks.
I’m unsure what the screenshot is displaying though. Can you explain?

**Comment by huyphams** [comment]
Yup, maybe our case is very special, I develop a database tool which allows the user to connect to the Amazon Redis instance.
We can connect to ElastiCache instance without SSL successfully, but can't connect to the ElastiCache with TLS.
So, this case is not about security, it's about the possibility. (Sorry for posting the image without a description, I just wanna show you that I can make it work with the `SSL_VERIFY_NONE`)

**Comment by huyphams** [comment]
I've submitted a PR following this issue. Let me know if you need anything else (C is not my primary language) thank you @mnunberg for adding support SSL.

**Comment by michael-grunder** [comment]
Closing via #821 because you can now do all interaction with `SSL_CTX` yourself if you wish.

**Comment by stanhu** [comment]
@michael-grunder I think we should revisit this. By default, if no SSL parameters are set, we should disable peer verification by default, as `redis-rb` does. 

Currently `redisCreateSSLContext()` does a lot of useful things, and right now for `hiredis-rb` to disable peer verification we have to either:

1. Re-implement this function and add our own tweaks.
1. Call `redisCreateSSLContext()` and then reach into the SSL context. https://github.com/redis/hiredis-rb/pull/72/files attempts to reuse the OpenSSL wrappers **and** also reach into the context to set, but it's a bit of a hack: notice the definition of `struct redisSSLContext` in the C extension. Plus, the C extension now needs to include OpenSSL just to switch verify modes.

Some ideas for improvement:

1. Make `redisCreateSSLContext()` take a `verify_mode` parameter, as this pull request does.
2. Export the `redisSSLContext` structure in `hiredis_ssl.h`.
3. Add a new function `redisUpdateSSLVerifyMode()`.
 
What do you think?

**Comment by stanhu** [comment]
Submitted https://github.com/redis/hiredis/pull/1085.
