### ISSUE TITLE
RESP 3 Support

### ISSUE THREAD

**Issue by schlitzered** [redis/hiredis#648]
are there any plans to add RESP 3 support, or is it maybe already supported?

**Comment by mnunberg** [comment]
Hi, antirez is working on support, there will be a PR eventually

**Comment by michael-grunder** [comment]
Closing this issue as RESP3 support was added in ff4fa45422dc104f3377cdc3bc88d2d24ac2fcf3, a7a1886b7eaeac0265af419a3f9c0793e7098d46, and 91de9c975ac66b6eaddb6de96440a282e4227447.
