### ISSUE TITLE
BZPOPMIN - "ERR unknown command 'BZPOPMIN'"

### ISSUE THREAD

**Issue by roger-blain** [redis/hiredis#649]
I am trying to execute the BZPOPMIN command:
```
"BZPOPMIN OP:QUEUE:iviu:p00390 OP:QUEUE:iviu:p00160 10"

It fails with:
```
"ERR unknown command 'BZPOPMIN'"

I have tried all sorts of variations, lower case, and "BZPOPMIN tests", same failure.

If i execute the command via redis-cli:
```
BZPOPMIN OP:QUEUE:iviu:p00160 OP:QUEUE:iviu:p00390 10
1) "OP:QUEUE:iviu:p00390"
2) "{\"database\

There are no issues.

Does anyone have any advice on next steps ?

**Comment by roger-blain** [comment]
I forgot to mention, I have tried both redisCommand and redisCommandArgv
If i substitute "BRPOP" I get a usual response for no data.

**Comment by itamarhaber** [comment]
Hello @Intellipower

Most likely your Redis server's version is lower than 5.

**Comment by michael-grunder** [comment]
Hey, @roger-blain 

Are you absolutely certain you're connecting to the exact same Redis instance using `hiredis` as you are using `redis-cli`?

Or are you potentially double quoting the command in hiredis, like this:

```c
// This will return: 'ERR unknown command `'BZPOPMIN'`
redisReply *r = redisCommand(c, "'BZPOPMIN' %s %d", "myzset", 1);
```

If you can, please post a small snippet of code illustrating how you're attempting to use hiredis, which might help us diagnose the issue.

**Comment by roger-blain** [comment]
Gents you are spot on, I was inadvertently connecting to my local V4 server, when I thought I was connecting to my cloud server V5!

Thanks so much!
