### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by mbitsnbites** [redis/hiredis#651]
(This is a follow-up to #599)

I don't know if Windows support is on the radar for hiredis, but I for one think that it's missing.

Since i needed Redis support under Windows in my application, I went ahead and made a quick patch to my forked version of hiredis, and for my application it seems to work well (otherwise the code is largely untested).

The required patches are the "hiredis-patch" commits in this PR: https://github.com/mbitsnbites/buildcache/pull/28

**NOTE:** I only made the code work with MinGW, as supporting MSVC was too much work (and it's not part of my pipeline anyway).

If this is of interest, I could prepare a corresponding PR for hiredis. You could als add a MinGW compilation test for travis or appveyor.

**Comment by mnunberg** [comment]
I don't see why we wouldn't be able to target mingw. I'd be interested in seeing the PR

**Comment by mbitsnbites** [comment]
PR: #652

**Comment by michael-grunder** [comment]
Closing this issue, since #652 has been merged!
