### ISSUE TITLE
Request for new release with SSL support

### ISSUE THREAD

**Issue by brian-kephart** [redis/hiredis#655]
I see that SSL support was recently merged in. This is something I've been waiting for, and I'm sure others have as well. Since many wrapper libraries use the latest released version, can we get a new release to help push this feature downstream to those libraries?

**Comment by gkorland** [comment]
@mnunberg

**Comment by pchoudhary-jnpr** [comment]
Hi @mnunberg Any plans to release the new version of hiredis with SSL support ?

**Comment by njuyang14** [comment]
Hello, I have the same question. May I ask when will the next version which contains ssl feature be released? Thanks.

**Comment by michael-grunder** [comment]
Closing as we've released [v1.0.0](https://github.com/redis/hiredis/tree/v1.0.0) with SSL support :partying_face:

**Comment by pelargir** [comment]
> Closing as we've released [v1.0.0](https://github.com/redis/hiredis/tree/v1.0.0) with SSL support 🥳

That's great but... it's not available on rubygems.org so `bundle install hiredis` installs 0.6.3 from Nov 2018.
