### ISSUE TITLE
when redisReaderFeed big buffer, redisReaderGetReply will cause high cpu usage

### ISSUE THREAD

**Issue by hongliuliao** [redis/hiredis#656]
when redis reader feed 40m buffer, the get reply will cause high cpu usage like as follow:
![image](https://user-images.githubusercontent.com/1174006/55712758-ea219200-5a21-11e9-976d-0c051be35852.png)
Because in redisReaderGetReply method, after a reply parsed, it will use "sdsrange" to move mem and when the buffer is big, the memmove() will cost many time & cpu!
![image](https://user-images.githubusercontent.com/1174006/55712839-09b8ba80-5a22-11e9-9bd6-4c6a8dc8299e.png)

**Comment by mnunberg** [comment]
Perhaps we should make this setting configurable. I am assuming most of our users are using buffers in the size of several K than in the size of several M?

**Comment by hongliuliao** [comment]
Thanks for your reply! I think "this setting configurable" may better. I use redisReaderFeed & redisReaderGetReply to read a big aof file and parse, and then i think when the read buffer is bigger, the performance will better.

**Comment by michael-grunder** [comment]
It would be a non-trivial change, but we could look into using a ring buffer.

**Comment by michael-grunder** [comment]
Closing in favor of #866
