### ISSUE TITLE
Key length in binary API

### ISSUE THREAD

**Issue by fkengun** [redis/hiredis#657]
I'm trying to put binary data into Redis using binary API. Here is my code:
`reply = redisCommand(c, "SET %b %b", key, (size_t)strlen(key), value, (size_t)size);`
I find out that the command fails every time when key is longer or equal to 8, such as "helloaaa". The key cannot be found in Redis after I ran my code.
Similar things happen when the key contains other characters such as '_' and digits.
I don't actually need binary key. I just need binary value. Is there any way to use string key but binary value?

**Comment by mnunberg** [comment]
`set %s %b`?

**Comment by fkengun** [comment]
It seems like all my `SET ` commands work only when I'm connected to the corresponding node with the slot. `set %s %b` works when the connected node is right one. Am I doing something wrong? Do I need to add anything when I try to access a Redis cluster using hiredis?

**Comment by michael-grunder** [comment]
Hi @fkengun,

Hiredis doesn't have any specific support for redis-cluster but you have a couple of options.  You could use something like [hireids-vip](https://github.com/vipshop/hiredis-vip) which will handle redis-cluster redirections, or configure a proxy like [corvus](https://github.com/eleme/corvus) and then just connect to the proxy.

**Comment by fkengun** [comment]
Thank you for the reply. I did not notice hiredis does not support redis-cluster. I will switch to hiredis-vip.
