### ISSUE TITLE
capath in redisSslCreate seems to be used as wrong parameter in SSL_CTX_verify_locations

### ISSUE THREAD

**Issue by azmtnruz** [redis/hiredis#659]
In sslio.c the function redisSslCreate (line 90) takes as a parameter capath then uses this in SSL_CTX_load_verify_locations (line 114) but I think it is being used as the wrong parameter in the SSL call.  It is being used in 2nd parameter which is CAfile instead of 3rd parameter which is CApath.  SSL describes CApath as "If CApath is not NULL, it points to a directory containing CA certificates in PEM format"

If a file of certificates was intended to be used can the redisSslCreate api be expanded to allow a directory of certificates to also be used?

Also in sslio.c there are 2 printf statements at line 34 and line 37. These seem helpful for debug but can they be wrapped so if not debugging the printf are not being called?

**Comment by yossigo** [comment]
@azmtnruz the messages have been cleaned.  SSL support have gone through some refactoring and you can now configure OpenSSL yourself and just provide a `SSL*` so I believe these are no longer outstanding issues.

**Comment by jamesruzewski** [comment]
Sounds good..Thanks..

**Comment by michael-grunder** [comment]
Closing the issue since it's been taken care of.
