### ISSUE TITLE
Why do I get multiple responses for ZRANGEBYSCORE even with the pipeline?

### ISSUE THREAD

**Issue by azam-noob** [redis/hiredis#660]
Hello,

I have the following code to set multiple values in single request using pipelines;

```
for(int i = 0; i < size; i++) {
    redisAppendCommand(c, set_str(key[i], score[i], msg[i]));
}

for(int i = 0; i < size; i++) {
    redisGetReply(c, &r);
}
freeReplyObject(r);

```
It works really well, I wrote similar code to get the response from the server in a single message. It looks like this;
```
for(int i = 0; i < size; i++) {
    redisAppendCommand(c, get_str(key[i], score[i]));
}

for(int i = 0; i < size; i++) {
    reply[i] = redisGetReply(c, &r);
}
freeReplyObject(r);
```
`set_str` and `get_str` are just simple functions which return redis command such as `ZADD key score msg` and `ZRANGEBYSCORE key -inf score WITHSCORES`.

When I run the above code, it uses single request to set all the elements. However, the server sends `size` responses back rather than just one. You can see the trace of wireshark [here](https://imgur.com/a/CYVeSQs). First, I sent two batch messages to set six different keys and later I tried to retrieve all those six keys back by using two batched requests. But, the server sends me six different replies for every key.

I tried `(printf "GET foo\r\nGet foo2\r\nGet foo3\r\n"; sleep 1) | nc localhost 6379` in terminal to see the result. It only take one single response to return all three values but why does it send multiple response in the case of sorted set?

**Comment by michael-grunder** [comment]
Hi @azam-noob,

I'm not sure I understand your question, but I think you misunderstand `redisAppendCommand` and `redisGetReply`.

In the following code, you are sending `size` commands to redis, and therefor will receive `size` replies:

```C
for(int i = 0; i < size; i++) {
    redisAppendCommand(c, get_str(key[i], score[i]));
}
```

I don't know what `MAX` is or what relation it has to `size`, but you have a couple of issues with the following loop.  First, you're leaking `r` in each iteration of the loop, since on success, hiredis will return allocated memory for each call to `redisGetReply`.

```C
for(int i = 0; i < MAX; i++) {
    reply[i] = redisGetReply(c, &r);
}
freeReplyObject(r);
```

In order to send multiple members in one `ZADD` command, you would have to do  [something like this.](https://gist.github.com/michael-grunder/88dc2bf927c9e15f42200076f8ba3ef2)

**Comment by azam-noob** [comment]
Thanks @michael-grunder for a quick reply. I forgot to change the code a bit, actually `MAX` is `size`, I was changing it to make the code more clear.

I took your example code and modified it in trying to make my point clear. I used the following code to do three `GET` requests;
```
int main() {
    redisReply *reply;
    redisContext *c = redisConnect("127.0.0.1", 6379);

    // Do multiple get requests.
    redisAppendCommand(c, "GET foo");
    redisAppendCommand(c, "GET bar");
    redisAppendCommand(c, "GET baz");

    int i = 3;
    // Read multiple results.
    while (i-- > 0) {
        if (redisGetReply(c, (void**)&reply) != REDIS_OK) {
            fprintf(stderr, "Error:  Can't read reply\n");
            exit(-1);
        }
        printf("Redis returned: %s\n", reply->str);
    }

    freeReplyObject(reply);
    return 0;
}
```
In the above program, it will queue all three get request in a single request and sends the whole request to the server when I called `redisGetReply` for the first time. In response of this call to `redisGetReply`, the server will send me only one reply (here I am talking about the raw packet, in response to the pipeline request the server only sends a single packet) containing the response of all three requests. From there, I'll call `redisGetReply` two more times to read all the replies. However, in these two subsequent requests we don't send any request to the server because we already have all the responses therefore we pops out the required result and returned from the memory.

So far so good. Now I just change the `GET` request to `ZRANGEBYSCORE` and the code looks like this;
```
int main() {
    redisReply *reply;
    redisContext *c = redisConnect("127.0.0.1", 6379);

    // Do multiple ZRANGEBYSCORE requests.
    redisAppendCommand(c, "ZRANGEBYSCORE foo 0 2");
    redisAppendCommand(c, "ZRANGEBYSCORE bar 0 2");
    redisAppendCommand(c, "ZRANGEBYSCORE baz 0 2");

    int i = 3;
    // Read multiple results.
    while (i-- > 0) {
        if (redisGetReply(c, (void**)&reply) != REDIS_OK) {
            fprintf(stderr, "Error:  Can't read reply\n");
            exit(-1);
        }
        printf("Redis returned: %s and %s\n", reply->element[0]->str, reply->element[1]->str);
    }

    freeReplyObject(reply);
    return 0;
}
```
The problem now is when I call `redisGetReply` for the first time, the server only sends a single response (only one packet) which contains the response for `foo`. The second time I call `redisGetReply`, it sends me another request with the response for `bar` and finally another request to get the response for `baz`. Why the server is sending three separate message now? I have also attached the trace of both simple get request and sorted set get request.

[pcap.zip](https://github.com/redis/hiredis/files/3123530/pcap.zip)

**Comment by michael-grunder** [comment]
Hey @azam-noob sorry about that I misunderstood your question.

I don't have a great deal of experience working with the low-level networking layer of Redis, so you'll probably need to ask someone on the Redis team for a definitive answer.

That said, I believe what's happening is Redis is using an output buffer to attempt to send more than one response in a given packet.  My assumption is that Redis is able to pack multiple BULK responses in one network packet, whereas MULTI-BULK responses are harder to buffer in that way.

For example, [this function](https://github.com/antirez/redis/blob/843de8b786562d8d77c78d83a971060adc61f77a/src/networking.c#L243) in networking.c is buffering internally before doing any delivery.

I hope that was at least somewhat useful! 

Cheers,
Mike

**Comment by azam-noob** [comment]
I believe that is indeed whats happening in the backend but I would still ask somebody on the Redis team just to make sure.

Thanks for your help anyway.
