### ISSUE TITLE
Some problem about install on MacOS

### ISSUE THREAD

**Issue by Bayesky** [redis/hiredis#661]
I maybe have some problems on installing for Mac :(
Here are my installation steps:
1.Make
2.sodu make install
3. I copy a `.c` file to test.
```
#include <stdio.h>
#include <hiredis/hiredis.h>
int main()
{
     redisContext *conn  = redisConnect("127.0.0.1",6379);
     if(conn != NULL && conn->err)
     {
         printf("connection error: %s\n",conn->errstr);
         return 0;
     }
     redisReply *reply = (redisReply*)redisCommand(conn,"set foo 1234");
     freeReplyObject(reply);
 
     reply = redisCommand(conn,"get foo");
     printf("%s\n",reply->str);
     freeReplyObject(reply);
 
     redisFree(conn);
     return 0;
}
```
4. I run it with `gcc -o  RedisTest RedisTest.c -L/usr/local/lib/ -lhiredis and succeed`
5. but when I run it with `./RedisTest`, an error occurs which is 

> Segmentation fault: 11

Then I add the lib to Qt with `LIBS += -L/usr/local/lib -lhiredis`, but the massage `error: 'hiredis/hiredis.h' file not found` still exist. How to deal with that? I am confused.

Many thanks~~

**Comment by michael-grunder** [comment]
Hi @Bayesky,

Your program ran just fine on my MacBook (running High Sierra).  You should change `if(conn != NULL && conn->err)` to `if(conn == NULL || conn->err)` but it doesn't seem like you'd have an allocation error in this small test program.

Theoretically, you shouldn't need the `-L/usr/local/lib` option if hiredis was installed correctly.

This could potentially segfault if `reply` were NULL:
```c
     reply = redisCommand(conn,"get foo");
     printf("%s\n",reply->str);
```

What I would do is either run your program through GDB or insert printf statements so you can figure out where it's crashing.

Good luck!

**Comment by Bayesky** [comment]
Thank you very much. The segfault indeed occur where reply is NULL. The reason is protected-mode is set to no when I connect to my Redis server.  
And when I don't use -L/usr/local/lib, the program was running well.

**Comment by michael-grunder** [comment]
Glad you got it working!
