### ISSUE TITLE
How to add support for a command created by Redis Modules?

### ISSUE THREAD

**Issue by vishal14101993** [redis/hiredis#667]
How can I add a command which has been custom created using Redis Modules? Can someone guide me?

**Comment by mnunberg** [comment]
Hi, what command do you need support for? If it's a normal request-response command, then all you need to do is execute it like any other command.

**Comment by vishal14101993** [comment]
Can I make and then use a command which will take multiple arguments and will perform multiple operations(on multiple keys)? Please note that I'm using Redis Cluster.

**Comment by mnunberg** [comment]
Sure. hiredis doesn’t really have any awareness of the kind of command you’re executing. The only special handling is with pubsub and monitor(?) because those can receive an indeterminate number of replies.
