### ISSUE TITLE
redisCommand got "Unknown error"

### ISSUE THREAD

**Issue by beita1** [redis/hiredis#668]
# problem
- after connecting redis it secceed,i tried to get auth with this command: 
```
	string pwd = "111";
	reply = static_cast<redisReply *>(redisCommand(c, "AUTH %s", pwd.c_str()));
```
- but i got a error like this:
![image](https://user-images.githubusercontent.com/13329945/58266586-87f3d500-7db4-11e9-895f-8104fc2eb44b.png)

#  some infomation
- redis server is running in docker and version is 5.0.5
- i tried to exec this command： AUTH 111 in redis-cli,it success
- redis client code is cloned from master
- i tried to read source code to find the reason but i failed,could you help me?

**Comment by michael-grunder** [comment]
No real way to know what's happening, but you could check to see if this program works for you:

```cpp
// Compile with: g++ auth.cpp -lhiredis

#include <string>
#include <cstring>
#include <stdio.h>
#include <stdlib.h>
#include <hiredis/hiredis.h>

using namespace std;

int main(int argc, const char **argv) {
    if (argc < 4) {
        fprintf(stderr, "Error:  Pass host, port and password\n");
        exit(-1);
    }

    string host = argv[1];
    int port = atoi(argv[2]);
    string pwd = argv[3];

    redisContext *c = redisConnect(host.c_str(), port);
    if (c == NULL || c->err) {
        fprintf(stderr, "Error:  Can't connect (%s)\n", c->errstr);
        exit(-1);
    }

	redisReply *reply = static_cast<redisReply *>(redisCommand(c, "AUTH %s", pwd.c_str()));
    if (!reply || c->err) {
        fprintf(stderr, "Error:  %s\n", c->errstr);
        exit(-1);
    } else if (reply->type == REDIS_REPLY_ERROR) {
        fprintf(stderr, "Error:  %s\n", reply->str);
        exit(-1);
    }

    printf("Success\n");
    return 0;
}
```

This is mostly C because I don't do a whole lot of C++, but it's calling Redis the way you are in your issue report.

**Comment by beita1** [comment]
- it works!!thank you very much.I compared our difference code,and i find the reason.
- I used redisConnectWithTimeout to cause this problem.
- when i replace redisConnectWithTimeout  with redisConnect,it succeed!

**Comment by beita1** [comment]
- Besides, do you know why redisConnectWithTimeout cause this problem?
- thank you for your reply

**Comment by michael-grunder** [comment]
I really can't say without more information but are you possibly setting the timeout too low?  That would be the most common reason connecting with a timeout would fail.

To connect with a timeout you'd do something like this:
```c
#include <stdio.h>
#include <stdlib.h>
#include <sys/time.h>
#include <hiredis/hiredis.h>

int main(int argc, const char **argv) {
    struct timeval tv = { .tv_sec = 5, .tv_usec = 0 };

    redisContext *c = redisConnectWithTimeout("127.0.0.1", 6379, tv);
    if (!c || c->err) {
        fprintf(stderr, "Error:  Can't connect\n");
        exit(-1);
    }

	/* Actual commands... */
}
```

**Comment by beita1** [comment]
- It occurs the same mistake: unknown error.but i set timeval.tv_sec = 50,it succeed!
- besides, i  stepped through redisCommand with your code,i found a strange thing.when i stepped in redisGetReply function which is called by  redisvCommand, it also succeed!But when i skip this function, it occurs the same mistake. 
- so i guess that redisGetReply  function  needs to wait sometime or wait after something succeed to deal data. but it did not .Do you think is that a redis bug?

**Comment by michael-grunder** [comment]
There's no way for me to know without a complete program that I can look at.

It's unlikely that hiredis has a bug in its basic ability to connect with a timeout but I suppose it is possible.  What operating system are you using?

> so i guess that redisGetReply function needs to wait some time or wait after something succeed to deal data. but it did not.Do you think is that a Redis bug?

Yes, you can only call `redisGetReply` after you have called one of the `redisAppendCommand` function.

```c
#include <stdlib.h>
#include <hiredis/hiredis.h>


int main(void) {
    redisContext *c = redisConnect("localhost", 6379);
    if (!c || c->err) {
        fprintf(stderr, "Can't connect\n");
        exit(-1);
    }

    // Send 5 commands to redis
    for (int i = 0; i < 5; i++) {
        redisAppendCommand(c, "PING");
    }

    // Consume 5 commands (This is OK)
    redisReply *reply;
    for (int i = 0; i < 5; i ++) {
        if (redisGetReply(c, (void**)&reply) != REDIS_OK) {
            fprintf(stderr, "Error!\n");
            exit(-1);
        } else if (reply->type != REDIS_REPLY_STATUS) {
            fprintf(stderr, "Error:  Wrong reply type!\n");
        }

        printf("Redis says: %s\n", reply->str);
    }

    // One too many (This will hang).
    redisGetReply(c, (void**)&reply);
}
```

**Comment by beita1** [comment]
- This is the error code mentioned before. 
```
#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <hiredis.h>

using namespace std;

int main(int argc, const char **argv) {
	struct timeval tv;
	tv.tv_sec = 5;//set 50 will be successful
	tv.tv_usec = 0;

	redisContext *c = redisConnectWithTimeout("127.0.0.1", 6379, tv); //use redisConnect function will be successful
	if (!c || c->err) {
		fprintf(stderr, "Error:  Can't connect\n");
		exit(-1);
	}

	string pwd = "XXX";
	redisReply *reply = static_cast<redisReply *>(redisCommand(c, "AUTH %s", pwd.c_str()));//step in this function and dont skip redisGetReply function will be successful
	if (!reply || c->err) {
		fprintf(stderr, "Error:  %s\n", c->errstr);
		exit(-1);
		/* Actual commands... */
	}
}
```
- My operating system is windows10 in mac(use bootcamp to start)
- I copy your code and excute, it runs normally

**Comment by michael-grunder** [comment]
Hey,

I don't have any Windows machines but you may have run into an actual bug with respect to setting timeouts on Windows:

Here's a PR that looks suspiciously like it's fixing your issue:
https://github.com/redis/hiredis/pull/662/files

A more specific change, doing something similar:
https://github.com/redis/hiredis/pull/669/files

**Comment by beita1** [comment]
- You are right! I merge these changes in hiredis project and rebuild it into my project.
- it works and throw no more error.

**Comment by michael-grunder** [comment]
I'm glad you were able to get it working.  I expect the fixes will be merged soon.

I'll close this issue in favor of the PRs above.
