### ISSUE TITLE
redis compilation error

### ISSUE THREAD

**Issue by weiwang999** [redis/hiredis#673]
LINK redis-server
server.c:1146: error: undefined reference to 'lua_gc'
server.c:3182: error: undefined reference to 'lua_gc'
debug.c:1236: error: undefined reference to 'dladdr'
debug.c:1303: error: undefined reference to 'dladdr'
cluster.c:2388: error: undefined reference to 'floor'
scripting.c:145: error: undefined reference to 'lua_pushnumber'
scripting.c:158: error: undefined reference to 'lua_pushlstring'
scripting.c:166: error: undefined reference to 'lua_createtable'
scripting.c:176: error: undefined reference to 'lua_createtable'
scripting.c:167: error: undefined reference to 'lua_pushstring'
scripting.c:168: error: undefined reference to 'lua_pushlstring'
scripting.c:169: error: undefined reference to 'lua_settable'
scripting.c:155: error: undefined reference to 'lua_pushboolean'
scripting.c:145: error: undefined reference to 'lua_pushnumber'
scripting.c:158: error: undefined reference to 'lua_pushlstring'
scripting.c:155: error: undefined reference to 'lua_pushboolean'
scripting.c:166: error: undefined reference to 'lua_createtable'
scripting.c:167: error: undefined reference to 'lua_pushstring'
scripting.c:168: error: undefined reference to 'lua_pushlstring'
scripting.c:169: error: undefined reference to 'lua_settable'
scripting.c:176: error: undefined reference to 'lua_createtable'
scripting.c:177: error: undefined reference to 'lua_pushstring'
scripting.c:179: error: undefined reference to 'lua_settable'
scripting.c:196: error: undefined reference to 'lua_pushnumber'
scripting.c:198: error: undefined reference to 'lua_settable'
scripting.c:191: error: undefined reference to 'lua_pushboolean'
scripting.c:218: error: undefined reference to 'lua_pushstring'
scripting.c:221: error: undefined reference to 'lua_getstack'
scripting.c:221: error: undefined reference to 'lua_getinfo'
scripting.c:238: error: undefined reference to 'lua_gettable'
scripting.c:239: error: undefined reference to 'lua_error'
scripting.c:250: error: undefined reference to 'lua_getfield'
scripting.c:252: error: undefined reference to 'lua_gettable'
scripting.c:253: error: undefined reference to 'lua_pushvalue'
scripting.c:254: error: undefined reference to 'lua_pcall'
scripting.c:261: error: undefined reference to 'lua_settop'
scripting.c:263: error: undefined reference to 'lua_gettable'
scripting.c:264: error: undefined reference to 'lua_pushvalue'
scripting.c:265: error: undefined reference to 'lua_getfield'
scripting.c:267: error: undefined reference to 'lua_call'
scripting.c:270: error: undefined reference to 'lua_settop'
scripting.c:278: error: undefined reference to 'lua_type'
scripting.c:285: error: undefined reference to 'lua_toboolean'
scripting.c:339: error: undefined reference to 'lua_settop'
scripting.c:288: error: undefined reference to 'lua_tonumber'
scripting.c:282: error: undefined reference to 'lua_tolstring'
scripting.c:282: error: undefined reference to 'lua_objlen'
scripting.c:296: error: undefined reference to 'lua_gettable'
scripting.c:297: error: undefined reference to 'lua_type'
scripting.c:299: error: undefined reference to 'lua_tolstring'
scripting.c:307: error: undefined reference to 'lua_settop'
scripting.c:310: error: undefined reference to 'lua_type'
scripting.c:312: error: undefined reference to 'lua_tolstring'
scripting.c:323: error: undefined reference to 'lua_pushnumber'
scripting.c:325: error: undefined reference to 'lua_type'
scripting.c:349: error: undefined reference to 'lua_gettop'
scripting.c:404: error: undefined reference to 'lua_tonumber'
scripting.c:409: error: undefined reference to 'lua_tolstring'
scripting.c:239: error: undefined reference to 'lua_error'
scripting.c:239: error: undefined reference to 'lua_error'
scripting.c:664: error: undefined reference to 'lua_gettop'
scripting.c:671: error: undefined reference to 'lua_error'
scripting.c:688: error: undefined reference to 'lua_gettop'
scripting.c:695: error: undefined reference to 'lua_pushvalue'
scripting.c:725: error: undefined reference to 'lua_pushboolean'
scripting.c:752: error: undefined reference to 'lua_gettop'
scripting.c:778: error: undefined reference to 'lua_tonumber'
scripting.c:796: error: undefined reference to 'lua_isnumber'
scripting.c:800: error: undefined reference to 'lua_tonumber'
scripting.c:828: error: undefined reference to 'lua_pushcclosure'
scripting.c:830: error: undefined reference to 'lua_call'
scripting.c:828: error: undefined reference to 'luaopen_base'
scripting.c:828: error: undefined reference to 'lua_pushcclosure'
scripting.c:830: error: undefined reference to 'lua_call'
scripting.c:828: error: undefined reference to 'luaopen_table'
scripting.c:828: error: undefined reference to 'lua_pushcclosure'
scripting.c:830: error: undefined reference to 'lua_call'
scripting.c:828: error: undefined reference to 'luaopen_string'
scripting.c:828: error: undefined reference to 'lua_pushcclosure'
scripting.c:828: error: undefined reference to 'luaopen_math'
scripting.c:828: error: undefined reference to 'luaopen_debug'
scripting.c:828: error: undefined reference to 'luaopen_cjson'
scripting.c:828: error: undefined reference to 'luaopen_struct'
scripting.c:828: error: undefined reference to 'luaopen_cmsgpack'
scripting.c:828: error: undefined reference to 'luaopen_bit'
scripting.c:858: error: undefined reference to 'lua_pushnil'
scripting.c:859: error: undefined reference to 'lua_setfield'
scripting.c:860: error: undefined reference to 'lua_pushnil'
scripting.c:861: error: undefined reference to 'lua_setfield'
scripting.c:898: error: undefined reference to 'luaL_loadbuffer'
scripting.c:899: error: undefined reference to 'lua_pcall'
scripting.c:914: error: undefined reference to 'luaL_newstate'
scripting.c:858: error: undefined reference to 'lua_pushnil'
scripting.c:859: error: undefined reference to 'lua_setfield'
scripting.c:860: error: undefined reference to 'lua_pushnil'
scripting.c:861: error: undefined reference to 'lua_setfield'
scripting.c:1023: error: undefined reference to 'lua_getfield'
scripting.c:1043: error: undefined reference to 'luaL_loadbuffer'
scripting.c:1044: error: undefined reference to 'lua_pcall'
scripting.c:1064: error: undefined reference to 'luaL_loadbuffer'
scripting.c:1065: error: undefined reference to 'lua_pcall'
scripting.c:1132: error: undefined reference to 'luaL_checkinteger'
scripting.c:1133: error: undefined reference to 'luaL_argerror'
scripting.c:1134: error: undefined reference to 'floor'
scripting.c:1138: error: undefined reference to 'luaL_checkinteger'
scripting.c:1139: error: undefined reference to 'luaL_checkinteger'
scripting.c:1140: error: undefined reference to 'luaL_argerror'
scripting.c:1141: error: undefined reference to 'floor'
scripting.c:1144: error: undefined reference to 'luaL_error'
scripting.c:1150: error: undefined reference to 'luaL_checkinteger'
scripting.c:1090: error: undefined reference to 'lua_close'
scripting.c:1090: error: undefined reference to 'lua_close'
scripting.c:1106: error: undefined reference to 'lua_rawseti'
scripting.c:1196: error: undefined reference to 'luaL_loadbuffer'
scripting.c:1313: error: undefined reference to 'lua_getfield'
scripting.c:1360: error: undefined reference to 'lua_sethook'
scripting.c:1370: error: undefined reference to 'lua_sethook'
scripting.c:1393: error: undefined reference to 'lua_gc'
scripting.c:2405: error: undefined reference to 'lua_getstack'
scripting.c:2406: error: undefined reference to 'lua_getinfo'
scripting.c:1090: error: undefined reference to 'lua_close'
scripting.c:1982: error: undefined reference to 'lua_topointer'
scripting.c:1930: error: undefined reference to 'lua_toboolean'
scripting.c:1948: error: undefined reference to 'lua_next'
scripting.c:1948: error: undefined reference to 'lua_next'
scripting.c:2101: error: undefined reference to 'lua_getstack'
scripting.c:2105: error: undefined reference to 'lua_getlocal'
scripting.c:2105: error: undefined reference to 'lua_getlocal'
scripting.c:2101: error: undefined reference to 'lua_getstack'
scripting.c:2136: error: undefined reference to 'lua_getlocal'
scripting.c:2136: error: undefined reference to 'lua_getlocal'
scripting.c:2254: error: undefined reference to 'lua_getinfo'
bio.c:113: error: undefined reference to 'pthread_attr_getstacksize'
bio.c:116: error: undefined reference to 'pthread_attr_setstacksize'
sentinel.c:985: error: undefined reference to 'redisAsyncFree'
sentinel.c:985: error: undefined reference to 'redisAsyncFree'
sentinel.c:985: error: undefined reference to 'redisAsyncFree'
sentinel.c:985: error: undefined reference to 'redisAsyncFree'
sentinel.c:1967: error: undefined reference to 'redisAsyncCommand'
sentinel.c:1983: error: undefined reference to 'redisAsyncCommand'
sentinel.c:2006: error: undefined reference to 'redisAsyncConnectBind'
sentinel.c:2016: error: undefined reference to 'redisAsyncSetConnectCallback'
sentinel.c:2018: error: undefined reference to 'redisAsyncSetDisconnectCallback'
sentinel.c:2029: error: undefined reference to 'redisAsyncConnectBind'
sentinel.c:2040: error: undefined reference to 'redisAsyncSetConnectCallback'
sentinel.c:2042: error: undefined reference to 'redisAsyncSetDisconnectCallback'
sentinel.c:2047: error: undefined reference to 'redisAsyncCommand'
sentinel.c:2640: error: undefined reference to 'redisAsyncCommand'
sentinel.c:282: error: undefined reference to 'redisAsyncHandleRead'
sentinel.c:289: error: undefined reference to 'redisAsyncHandleWrite'
hyperloglog.c:987: error: undefined reference to 'sqrt'
hyperloglog.c:987: error: undefined reference to 'sqrt'
hyperloglog.c:1039: error: undefined reference to 'llroundl'
hyperloglog.c:1457: error: undefined reference to 'ceil'
sparkline.c:108: error: undefined reference to 'log'
sparkline.c:121: error: undefined reference to 'log'
module.c:4745: error: undefined reference to 'dlopen'
module.c:4750: error: undefined reference to 'dlsym'
module.c:4763: error: undefined reference to 'dlclose'
module.c:4747: error: undefined reference to 'dlerror'
module.c:4752: error: undefined reference to 'dlclose'
module.c:4805: error: undefined reference to 'dlclose'
module.c:4806: error: undefined reference to 'dlerror'
geohash_helper.c:107: error: undefined reference to 'cos'
geohash_helper.c:108: error: undefined reference to 'cos'
geohash_helper.c:107: error: undefined reference to 'cos'
geohash_helper.c:108: error: undefined reference to 'cos'
geohash_helper.c:217: error: undefined reference to 'sin'
geohash_helper.c:218: error: undefined reference to 'sin'
geohash_helper.c:220: error: undefined reference to 'sqrt'
geohash_helper.c:220: error: undefined reference to 'asin'
geohash_helper.c:217: error: undefined reference to 'sin'
geohash_helper.c:218: error: undefined reference to 'sin'
geohash_helper.c:220: error: undefined reference to 'sqrt'
geohash_helper.c:220: error: undefined reference to 'asin'
geohash_helper.c:220: error: undefined reference to 'asin'
geohash_helper.c:220: error: undefined reference to 'asin'
rax.c:1739: error: undefined reference to 'log'
rax.c:1739: error: undefined reference to 'floor'
lolwut5.c:155: error: undefined reference to 'roundf'
lolwut5.c:160: error: undefined reference to 'round'
lolwut5.c:161: error: undefined reference to 'round'
lolwut5.c:160: error: undefined reference to 'round'
lolwut5.c:161: error: undefined reference to 'round'
clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:237: recipe for target 'redis-server' failed
make[1]: *** [redis-server] Error 1

**Comment by mnunberg** [comment]
This issue should be filed under https://github.com/antirez/redis, not redis/hiredis, which is just the C client.

**Comment by weiwang999** [comment]
I failed to understand it.
actually, I executed the command make distclean before building.
