### ISSUE TITLE
How to inform outside data-changed in callback function?

### ISSUE THREAD

**Issue by Bayesky** [redis/hiredis#674]
I have suffered from some trouble for a long time when I used hiredis in my app with Qt.
In order to get subscribe response, I have to write a static function as a callback function. In this function, I change some data and emit signal to inform my main thread to update display.
The question is the emit signal must be static in callback function, but I couldn't use signal&slot(connect) when I declare the signal static.
So how to inform outside in static function?
Thank you.

**Comment by michael-grunder** [comment]
Hi,

I'm not sure I fully understand the question, but hiredis will pass the `privdata` struct member into your subscribe callback and you can put whatever you want there.

Can you provide a small bit of code to illustrate the issue you're having?

**Comment by Bayesky** [comment]
Thank you! It works : )
