### ISSUE TITLE
Why do hiredis functions use void* instead of redisReply*?

### ISSUE THREAD

**Issue by david-eckardt-frequenz** [redis/hiredis#678]
I am new to hiredis, and I have a question. I hope this is the appropriate place to ask.
In `hiredis.h` the comment for `struct redisReply` says
> This is the reply object returned by redisCommand()

The `redisCommand()` function, however, returns `void*` rather than `redisReply*`. In fact it seems to me that all functions which accept or return `redisReply*` use `void*` for that argument or return type. Why is that so? Are they meant to be generic functions?

**Comment by mnunberg** [comment]
Indeed. This is in theory dependent on the `redisReader` implementation, which can return something other than `redisReply`. In practice, I don't know of any alternative implementations; and we dereference the `redisReply` structure internally, too.
