### ISSUE TITLE
redisSetTcpNoDelay  on windows  mac error 

### ISSUE THREAD

**Issue by dadaxiaoxiaobaba** [redis/hiredis#679]
//int yes = 1; // error 
    const char yes = 1;  // edit  
    if (setsockopt(c->fd, IPPROTO_TCP, TCP_NODELAY, &yes, sizeof(yes)) == -1) {
        __redisSetErrorFromErrno(c,REDIS_ERR_IO,"setsockopt(TCP_NODELAY)");
        redisNetClose(c);
        return REDIS_ERR;
    }
    return REDIS_OK;

**Comment by michael-grunder** [comment]
Closing in favor of #785
