### ISSUE TITLE
Compatibility with Node 12

### ISSUE THREAD

**Issue by rj-david** [redis/hiredis#680]
Hiredis does not compile properly in node 12

**Comment by dustinblackman** [comment]
Here's an example output of a build fail when you attempt to install `hiredis` with Node 12.6.0.

https://gist.github.com/dustinblackman/1205c3e79a918a58d361fbadf4c048c7

**Comment by pzrq** [comment]
@rj-david @dustinblackman As [others have noted](https://github.com/redis/hiredis/issues/607#issuecomment-416289247), this is the C language `hiredis`.

It looks like `hiredis-node` is [currently looking for a maintainer](https://github.com/redis/hiredis-node/issues/138).

**Comment by yosiat** [comment]
Added support for node 12 in this PR - https://github.com/redis/hiredis-node/pull/144
Hopefully, someone will look at it.
