### ISSUE TITLE
Does hiredis-vip support DNS resolution of the server hosthomes?

### ISSUE THREAD

**Issue by raghuiisc** [redis/hiredis#685]

**Comment by raghuiisc** [comment]
In the provided api i see we need to pass IP:PORT as argument, is there any api which takes host-name instead of ip:port

**Comment by michael-grunder** [comment]
I've never used hiredis-vip, but I assume since it uses hiredis internally that hostnames should work transparently (they do in hiredis anyway).

Since I _think_ this is a question about `hiredis-vip` I'm going to try to use the fancy new GitHub transfer feature.
