### ISSUE TITLE
about the example-libuv, maybe have bug

### ISSUE THREAD

**Issue by Matrixcpp** [redis/hiredis#690]
on my computer(win7 and win10),  running the example-libuv will crash, than I found if I change the uv_poll_init in the redisLibuvAttach function to uv_poll_init_socket it will fine,

(I'm sorry for my bad english, can you undrestand me ?)

**Comment by Matrixcpp** [comment]
crash in uv__get_osfhandle

**Comment by BeanLiu1994** [comment]
#726

**Comment by michael-grunder** [comment]
This may be the same bug, and we have a PR in #736.  

The only issue is that I don't have a Windows machine to verify the fix.

**Comment by michael-grunder** [comment]
Closing as #784 was merged (also see #785 for the TCP_NODELAY discussion)
