### ISSUE TITLE
latency between push data and llen in another procedure.

### ISSUE THREAD

**Issue by madlee** [redis/hiredis#693]
I have two procedures. The one will rpush data into a keyword and the other will count the lenth of it by llen command.
The code is very simple , 

`
#include "hiredis.h" 
#include <iostream> 
   
int main() { 
     redisContext* _connection = redisConnect("127.0.0.1", 6379); 
     void* result = redisCommand(_connection, "SELECT 15"); 
     freeReplyObject(result); 
   
     for (;;) { 
         void* reply = redisCommand(_connection, "LLEN TEST"); 
         std::cout << ((redisReply*)reply)->integer << std::endl; 
         freeReplyObject(reply); 
     } 
   
}`

It reads out the corrent length on start up. But then, when the new data was pushed into redis it will cost many seconds to reflect the change. On the other hand, when we try the similar code in Python or other clients, they reporeted the change immediately. 

Is there some advance settings/commands to sync the hiredis client with server?
Thank you.

**Comment by michael-grunder** [comment]
Hi,

It's hard to say why you're seeing that kind of latency but it doesn't sound like an issue with Hiredis.  In fact, your Python library is probably using [hiredis](https://github.com/andymccurdy/redis-py#parsers) [anyway](https://github.com/redis/hiredis-py).

It's important to note that if there are other long blocking operations occurring on your Redis server you can see latency, but it would be really difficult to diagnose without more information.

**Comment by madlee** [comment]
OK, Thank you. I will try to find the problem out.

**Comment by michael-grunder** [comment]
I'm going to close this issue, but happy to help if you're still having issues and can provide a bit more info.
