### ISSUE TITLE
make: cc: Command not found

### ISSUE THREAD

**Issue by denept** [redis/hiredis#694]
installed gcc4.9.4

cc -std=c99 -pedantic -c -O3 -fPIC  -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb net.c
make: cc: Command not found
make: *** [net.o] Error 127

make swoole：
creating swoole.la
(cd .libs && rm -f swoole.la && ln -s ../swoole.la swoole.la)
/bin/sh /home/swoole-src-4.3.5/libtool --mode=install cp ./swoole.la /home/swoole-src-4.3.5/modules
cp ./.libs/swoole.so /home/swoole-src-4.3.5/modules/swoole.so
cp ./.libs/swoole.lai /home/swoole-src-4.3.5/modules/swoole.la
PATH="$PATH:/sbin" ldconfig -n /home/swoole-src-4.3.5/modules
----------------------------------------------------------------------
Libraries have been installed in:
   /home/swoole-src-4.3.5/modules

**Comment by denept** [comment]
gcc --version
gcc (GCC) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

yum install gcc
Loaded plugins: fastestmirror, security
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirrors.huaweicloud.com
 * epel: mirrors.yun-idc.com
 * extras: mirror.bit.edu.cn
 * updates: mirrors.aliyun.com
Package gcc-4.4.7-23.el6.x86_64 already installed and latest version
Nothing to do

**Comment by mnunberg** [comment]
try using `make CC=gcc`
