### ISSUE TITLE
Msgpack serializes data, writes redis data is lost

### ISSUE THREAD

**Issue by Ccaomei** [redis/hiredis#700]
For an int variable with a value of 0, msgpack serializes and writes the data to redis, and the value corresponding to the key above redis is lost

**Comment by michael-grunder** [comment]
I don't think I understand your issue.  I don't have a problem setting and getting a value of `0` when msgpack serialization is enabled.

```php
<?php
$obj_r = new Redis();
$obj_r->connect('127.0.0.1', 6379);

$obj_r->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_MSGPACK);
$obj_r->set('zero', 0);
var_dump($obj_r->get('zero'));
```

The value in redis is what I would expect too:

```bash
$ php /tmp/zero.php
/tmp/zero.php:8:
int(0)
$ redis-cli get zero
"\x00"

**Comment by Ccaomei** [comment]
> I don't think I understand your issue. I don't have a problem setting and getting a value of `0` when msgpack serialization is enabled.
> 
> ```
> <?php
> $obj_r = new Redis();
> $obj_r->connect('127.0.0.1', 6379);
> 
> $obj_r->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_MSGPACK);
> $obj_r->set('zero', 0);
> var_dump($obj_r->get('zero'));
> ```
> 
> The value in redis is what I would expect too:
> 
> ```shell
> $ php /tmp/zero.php
> /tmp/zero.php:8:
> int(0)
> $ redis-cli get zero
> "\x00"
> ```
Well, thank you very much for your reply. I wrote it in c
        redisContext *context = redisConnect(char *ip, int port);
	if (context == NULL || context->err) 
	{
   		if (context) 
   		{
   			printf("Error: %s\n", context->errstr);
        	        // handle error
   		} 
   		else 
   		{
        	        printf("Can't allocate redis context\n");
    	        }
        }
    
        msgpack_sbuffer sbuf;
	msgpack_sbuffer_init(&sbuf);
	msgpack_packer pk;
	msgpack_packer_init(&pk, &sbuf, msgpack_sbuffer_write);
	msgpack_pack_array(&pk, 1);
	uint8_t a = 0;
	msgpack_pack_uint8(&pk, a);
	for(int j = 0; j < sbuf.size; j++)
	{
		printf("%x  ", sbuf.data[j]);
	}
	printf("\n");
    
	redisCommand(context, "lpush abc %s", sbuf.data);

        lrange abc 0 10
        1) "\x91"

**Comment by michael-grunder** [comment]
OMG, I'm sorry.  I also maintain phpredis and mistook your questions as being related to that 🤦‍♂️

**Comment by michael-grunder** [comment]
> redisCommand(context, "lpush abc %s", sbuf.data);

I think you want to use `%b` and then the length of the data you're sending.

Something like:

```c
redisCommand(context, "lpush %b", sbuf.data, <however long sbuf.data is>);
```

**Comment by Ccaomei** [comment]
> > redisCommand(context, "lpush abc %s", sbuf.data);
> 
> I think you want to use `%b` and then the length of the data you're sending.
> 
> Something like:
> 
> ```c
> redisCommand(context, "lpush %b", sbuf.data, <however long sbuf.data is>);
> ```

yea， i find this, thank you very much ! 
This requires storing data to redis in binary mode, like this
redisCommand(context, "lpush abc %b", sbuf.data, sbuf.size);
it's ok!

**Comment by michael-grunder** [comment]
Glad you got it working!
