### ISSUE TITLE
Why example-ae is not included in examples/CMakeLists.txt?

### ISSUE THREAD

**Issue by dhruvkakadiya** [redis/hiredis#701]
I am newbie here for this repo so I apologize if I didn't get things correctly but curious to learn more.

To build `example-ae`, it's strictly depends on [libae](https://github.com/aisk/libae) then why it's not included as part of adapters(or just as submodule) so that everything gets built properly by just cloning this repo?

Also other examples have been included in `examples/CMakeLists.txt` for the build while `example-ae` is not there.

Though it's included inside root `Makefile` but while it complains about the build error, that's not much useful as on `master` branch `README` file doesn't mention [libae](https://github.com/aisk/libae) anywhere.
```
$ make hiredis-example-ae
Please specify AE_DIR (e.g. <redis repository>/src)
```
Maybe that can be made better to indicate correct repo location or something like that. Or if that can be made available within this repo as part of submodule then that would be best. I can do PR for this if it makes sense.

**Comment by michael-grunder** [comment]
I understand how this might be confusing for newcomers but I don't think we would want to include it as a submodule as typically people would want to point to Redis for the library.
