### ISSUE TITLE
freeReplyObject usage

### ISSUE THREAD

**Issue by ShePastAway0** [redis/hiredis#710]
1) why do i actually have to use freeReplyObject? what this function actually do? for example this code works even without freeReplyObject:
	redReply = (redisReply*)redisCommand(c, "PING"); // invoke PING command & return pointer to redisReply structure
	printf("PING: %s\n", redReply->str);
	//freeReplyObject(redReply); // free reply structure

    redReply = (redisReply*)redisCommand(c, "GET testkey");
	printf("testkey: %s\n", redReply->str);

2) is this information still relevant?
> Important: the current version of hiredis (0.10.0) frees replies when the asynchronous API is used. This means you should not call freeReplyObject when you use this API. The reply is cleaned up by hiredis after the callback returns. This behavior will probably change in future releases, so make sure to keep an eye on the changelog when upgrading (see issue #39).

**Comment by michael-grunder** [comment]
@h3xp1017 Hey, I just happened to look at one of your questions again and wanted to point something out.


[This program](https://github.com/redis/hiredis/issues/710#issuecomment-530921662) will leak memory:
```c
int main(int argc, const char **argv) {
    redisContext *c = redisConnect("127.0.0.1", 6379);
    redisReply *r;

    for (int i = 0; i < 100; i++)
        redisReply *r = (redisReply*)redisCommand(c, "PING %d", i);

    freeReplyObject(r);
    redisFree(c);
}
```

You need to call `freeReplyObject` each time you execute `redisCommand`, so in this program you would do something like:

```c

#include <stdio.h>
#include <hiredis/hiredis.h>

int main(int argc, const char **argv) {
    redisContext *c = redisConnect("127.0.0.1", 6379);
    redisReply *r;

    for (int i = 0; i < 100; i++) {
        redisReply *r = (redisReply*)redisCommand(c, "PING %d", i);
        if (r) freeReplyObject(r);
    }

    redisFree(c);
}
```

**Comment by h3xp1017** [comment]
> You need to call freeReplyObject each time you execute redisCommand
well this is what i wanted to know, thank you =)

**Comment by michael-grunder** [comment]
> why this happen? i mean i use only one redisReply structure which is overwritten every time in the loop, why it leaks memory if its doesnt creates new objects in heap/stack?

It does allocate memory on the heap.  If you were to step into hiredis you'd see it executing a `malloc` for the `redisReply` itself, and then additional allocations depending on what the return type is.

Here's a short program that does something similar but removes all of the complexity of hiredis

```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct exampleReply {
    char *str;
} exampleReply;

char *createString(int count) {
    char buf[1024], *str;
    size_t len;

    len = snprintf(buf, sizeof(buf), "Example reply %d", count);
    str = malloc(len + 1);
    memcpy(str, buf, len);
    str[len] = '\0';

    return str;
}

exampleReply *getReply(int count) {
    exampleReply *r = malloc(sizeof(exampleReply));
    r->str = createString(count);
    return r;
}

void freeReply(exampleReply *reply) {
    free(reply->str);
    free(reply);
}

int main(void) {
    for (int i = 0; i < 3; i++) {
        exampleReply *r = getReply(i);
        printf("exampleReply[%p]->str[%p] = '%s'\n", r, r->str, r->str);
        freeReply(r);
    }
}
```

Notice how `getReply` mallocs memory for the structure, and `makeString` mallocs memory for the string?  Hiredis is doing something similar to this internally (although the logic is substantially more complex).

I highly recommend using programs like [valgrind](http://www.valgrind.org/) or clang's [asan](https://clang.llvm.org/docs/AddressSanitizer.html) when learning to help you find things like memory leaks or invalid memory reads.  Even programmers who've been using C for decades use these tools.
