### ISSUE TITLE
How to XADD "fixed length string buffer" to Redis stream

### ISSUE THREAD

**Issue by bsriramprasad** [redis/hiredis#716]
Hi,

I have big string buffer that I would want to store in Redis which should be of fixed length. 
I do not want redis client to look into the buffer to find nulls or any such termination identifiers in calculating length of the data sent.

**Work around**
`redisResp = redisCommand(redisCtx,"SET %s %b", redis_key_name, str, dataSize);`

**Solution or interface looking for**
`redisResp = redisCommand(redisCtx,"XADD %s * %s %b", stream_name, redis_key_name, str, dataSize); */`

Can you suggest how I can achieve the work around type solution in to a Redis Stream XADD command? This is very important as I would want the data to be stored as a stream while with the work around I am storing them as just individual redis keys/value pairs,.

Do suggest any references in Redis/Hiredis documentation that I can refer to achieve this functionality.

Thanks a lot in advance for your kind support!

Regards
Sriram

**Comment by michael-grunder** [comment]
You should be able to use `%b` with `XADD` the same way you use it with `SET`

This works for me:
```c
#include <stdio.h>
#include <hiredis/hiredis.h>
#include <strings.h>
#include <stdlib.h>

void panicAbort(const char *message) {
    fprintf(stderr, "Error: %s\n", message);
    exit(-1);
}

int main(void) {
    redisContext *c;
    redisReply *reply;

    const char *buffer = "\0\0\0DATA\0\0\0";

    c = redisConnect("localhost", 6379);
    if (!c) panicAbort("Can't connect to Redis");

    reply = redisCommand(c, "XADD %s * %s %b", "stream", "binary", buffer, 10);
    if (!reply || c->err) panicAbort("Error sending XADD command");

    return 0;
}
```

```bash
$ cc xadd.c -lhiredis
$ ./a.out
$ redis-cli xrange stream - +
1) 1) "1569512677841-0"
   2) 1) "binary"
      2) "\x00\x00\x00DATA\x00\x00\x00"
```

**Comment by michael-grunder** [comment]
I'm going to close this issue because you should be able to send binary data into streams as shown above.  Feel free to reopen or comment again if I misunderstood your question.

**Comment by bsriramprasad** [comment]
I am sorry... I did not get back on this sooner, Yes your suggestion was really helpful. Thanks for your kind response.
