### ISSUE TITLE
hiredis support for CentOS 8

### ISSUE THREAD

**Issue by qingling128** [redis/hiredis#721]
Hi hiredis maintainers,

Is there a plan to add support for CentOS 8?

The package is available in CentOS 7:
https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/h/

But not CentOS 8:
https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/h/

We are trying to install it with

```
curl -O "https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
sudo rpm -Uvh "epel-release-latest-8.noarch.rpm"
sudo yum install hiredis
```

And we are getting:
```
Last metadata expiration check: 0:12:05 ago on Wed 16 Oct 2019 08:21:18 PM UTC.
No match for argument: hiredis
Error: Unable to find a match
```

**Comment by ifduyue** [comment]
Try remi https://centos.pkgs.org/8/remi-x86_64/hiredis-0.13.3-9.el8.remi.x86_64.rpm.html

**Comment by qingling128** [comment]
@ifduyue Thanks for the workaround! That's exactly what we are using for now. Is there a plan to add it to `dl.fedoraproject.org` though?

**Comment by michael-grunder** [comment]
Closing as we don't maintain pacakges
