### ISSUE TITLE
report a bug：with libuv async request, two problem and solutions

### ISSUE THREAD

**Issue by xingyun86** [redis/hiredis#726]
1.First problem:
#include <adapters/libuv.h>
In this file：
 // this is right,because c-fd already is socket fd.
  --if (uv_poll_init(loop, &p->handle, c->fd) != 0) {
  ++if (uv_poll_init_socket(loop, &p->handle, c->fd) != 0) {
    return REDIS_ERR;
  }
2.Second problem：
redisAsyncConnect -> ... ->_redisContextConnectTcp:
In this function, (origin report "Error: setsockopt(TCP_NODELAY): Input/output error")
        if (blocking && redisSetBlocking(c,1) != REDIS_OK)
            goto error;
++#ifndef _MSC_VER
++  sleep(0);
++#else
++	_sleep(0);
++#endif
        if (redisSetTcpNoDelay(c) != REDIS_OK)
            goto error;

Please confirm and repair it.

**Comment by michael-grunder** [comment]
Hi @xingyun86, can you post this as a `git` patch that I can apply?

**Comment by xingyun86** [comment]
> 
> 
> Hi @xingyun86, can you post this as a `git` patch that I can apply?

[patch-20191107.zip](https://github.com/redis/hiredis/files/3817375/patch-20191107.zip)

**Comment by michael-grunder** [comment]
Hey @mnunberg, @mbitsnbites

I don't have a Windows machine but taking a look at the [libuv docs](http://docs.libuv.org/en/v1.x/poll.html) it looks like this change to adapters/libuv.h might be correct.
 
```patch
diff --git adapters/libuv.h adapters/libuv.h
index 39ef7cf..049096e 100644
--- adapters/libuv.h
+++ adapters/libuv.h
@@ -84,7 +84,6 @@ static void redisLibuvCleanup(void *privdata) {
   uv_close((uv_handle_t*)&p->handle, on_close);
 }

-
 static int redisLibuvAttach(redisAsyncContext* ac, uv_loop_t* loop) {
   redisContext *c = &(ac->c);

@@ -106,7 +105,7 @@ static int redisLibuvAttach(redisAsyncContext* ac, uv_loop_t* loop) {

   memset(p, 0, sizeof(*p));

-  if (uv_poll_init(loop, &p->handle, c->fd) != 0) {
+  if (uv_poll_init_socket(loop, &p->handle, c->fd) != 0) {
     return REDIS_ERR;
   }
```

Relevant section:
> int uv_poll_init_socket(uv_loop_t* loop, uv_poll_t* handle, uv_os_sock_t socket)¶
Initialize the handle using a socket descriptor. On Unix this is identical to uv_poll_init(). On windows it takes a SOCKET handle.

And @xingyun86 can you explain why you're yielding control in the second change?  What problem is this solving?

```patch
diff --git net.c net.c
index e5f40b0..342d292 100644
--- net.c
+++ net.c
@@ -478,6 +478,13 @@ addrretry:
         }
         if (blocking && redisSetBlocking(c,1) != REDIS_OK)
             goto error;
+
+#ifndef _MSC_VER
+               sleep(0);
+#else
+               _sleep(0);
+#endif // !_MSC_VER
+
```

**Comment by xingyun86** [comment]
> 
> 
> Hey @mnunberg, @mbitsnbites
> 
> I don't have a Windows machine but taking a look at the [libuv docs](http://docs.libuv.org/en/v1.x/poll.html) it looks like this change to adapters/libuv.h might be correct.
> 
> ```diff
> diff --git adapters/libuv.h adapters/libuv.h
> index 39ef7cf..049096e 100644
> --- adapters/libuv.h
> +++ adapters/libuv.h
> @@ -84,7 +84,6 @@ static void redisLibuvCleanup(void *privdata) {
>    uv_close((uv_handle_t*)&p->handle, on_close);
>  }
> 
> -
>  static int redisLibuvAttach(redisAsyncContext* ac, uv_loop_t* loop) {
>    redisContext *c = &(ac->c);
> 
> @@ -106,7 +105,7 @@ static int redisLibuvAttach(redisAsyncContext* ac, uv_loop_t* loop) {
> 
>    memset(p, 0, sizeof(*p));
> 
> -  if (uv_poll_init(loop, &p->handle, c->fd) != 0) {
> +  if (uv_poll_init_socket(loop, &p->handle, c->fd) != 0) {
>      return REDIS_ERR;
>    }
> ```
> 
> Relevant section:
> 
> > int uv_poll_init_socket(uv_loop_t* loop, uv_poll_t* handle, uv_os_sock_t socket)¶
> > Initialize the handle using a socket descriptor. On Unix this is identical to uv_poll_init(). On windows it takes a SOCKET handle.
> 
> And @xingyun86 can you explain why you're yielding control in the second change? What problem is this solving?
> 
> ```diff
> diff --git net.c net.c
> index e5f40b0..342d292 100644
> --- net.c
> +++ net.c
> @@ -478,6 +478,13 @@ addrretry:
>          }
>          if (blocking && redisSetBlocking(c,1) != REDIS_OK)
>              goto error;
> +
> +#ifndef _MSC_VER
> +               sleep(0);
> +#else
> +               _sleep(0);
> +#endif // !_MSC_VER
> +
> ```

![图片](https://user-images.githubusercontent.com/8170682/68441991-bc483a00-020a-11ea-9978-06e5b008f46e.png)

**Comment by xingyun86** [comment]
![图片](https://user-images.githubusercontent.com/8170682/68445035-ac812380-0213-11ea-9b8a-fd102d8b348c.png)

**Comment by xingyun86** [comment]
![图片](https://user-images.githubusercontent.com/8170682/68445057-c6226b00-0213-11ea-984b-4caf335c1e3e.png)

**Comment by michael-grunder** [comment]
Yes, I think you're right about libuv init function from their docs, I just don't have a windows machine to check.  :smile:

**Comment by xingyun86** [comment]
`diff --git net.c net.c
index e5f40b0..342d292 100644
--- net.c
+++ net.c
@@ -478,6 +478,13 @@ addrretry:
         }
         if (blocking && redisSetBlocking(c,1) != REDIS_OK)
             goto error;
+
+#ifndef _MSC_VER
+               sleep(0);
+#else
+               _sleep(0);
+#endif // !_MSC_VER
+`
This modify on Linux does not need. The last modify is:
`diff --git net.c net.c
index e5f40b0..342d292 100644
--- net.c
+++ net.c
@@ -478,6 +478,13 @@ addrretry:
         }
         if (blocking && redisSetBlocking(c,1) != REDIS_OK)
             goto error;
+
+#ifdef _MSC_VER
+               _sleep(0);
+#endif // !_MSC_VER
+`

I have tested both Windows and Linux.

**Comment by mbitsnbites** [comment]
At least make a PR of this before merging, to get Travis testing first.

**Comment by michael-grunder** [comment]
Of course.  I just tagged you because you're on many of the Windows based commits.

@xingyun86 Do you mind creating a PR?

**Comment by xingyun86** [comment]
This is my project with hiredis and libuv. Support async request on Linux and Windows. I can do what with PR?
https://github.com/xingyun86/ppshuai_async_redis_cluster

**Comment by xingyun86** [comment]
> Of course. I just tagged you because you're on many of the Windows based commits.
> 
> @xingyun86 Do you mind creating a PR?

What I can do? How to do it?

**Comment by michael-grunder** [comment]
Just fork the repo then commit the changes you want and submit a pull request.

I'm happy to do it but then you wouldn't get any credit (in the git history). 😃

**Comment by xingyun86** [comment]
> Just fork the repo then commit the changes you want and submit a pull request.
> 
> I'm happy to do it but then you wouldn't get any credit (in the git history). 😃

Ok, no problem.Please give me a link.

**Comment by xingyun86** [comment]
> Just fork the repo then commit the changes you want and submit a pull request.
> 
> I'm happy to do it but then you wouldn't get any credit (in the git history). 😃

Ok.

**Comment by michael-grunder** [comment]
Closing in favor of #736
