### ISSUE TITLE
Documentation is confusing

### ISSUE THREAD

**Issue by mika314** [redis/hiredis#728]
"Redis may reply with nested arrays but this is fully supported." ->"Redis may reply with nested arrays and this is fully supported."

**Comment by michael-grunder** [comment]
Or maybe "Redis may reply with nested arrays which is supported by Hiredis".

Although to be precise recursive replies are only supported to a [depth of 7](https://github.com/redis/hiredis/blob/1ac8fca35de6d9ecc1b6b94cbd17aa7499cb8821/read.c#L418)

**Comment by michael-grunder** [comment]
I'm going to close this issue since it's not really a bug in Hiredis.  You're welcome to submit a PR with clearer language though.
