### ISSUE TITLE
delRead callback function is not called

### ISSUE THREAD

**Issue by AndrSar** [redis/hiredis#739]
Hello! I can't find where this callback function is called. Can you provide some info?

**Comment by michael-grunder** [comment]
Hi,

It looks like this depends on what event library you're using, and at as far as I can tell it isn't always being called for all of them.

I don't use the async functionality a great deal so I'm not sure if this is a bug or intended (perhaps it's not required for every library).

Which async adapter are you using?

**Comment by AndrSar** [comment]
I think that it doesn't depend on which event loop is used. The whole idea of a callback function is that it is set up by user of the library, but invoked by the library itself at specified condition or point in time. Actually, similar `delWrite()` function is used (called) by the library, so I wonder where `delRead()` might be used as well.

The whole story is that I've implemented an asynchronous event loop using `Boost.ASIO` and provided all necessary callbacks, but during debug session I've encountered error that `delRead()` callback is not being called, so it continues to read from socket when the `redisAsyncContext` has been disconnected and even freed by the library by `redisAsyncDisconnect()` function.

Either I don't understand something or this is actually a weird situation with delRead not being called.

**Comment by michael-grunder** [comment]
> The whole idea of a callback function is that it is set up by user of the library, but invoked by the library itself

Sure, I just mean that I instrumented example adapters to watch when `delRead` was invoked but the behavior varied for each adapter.

For example for `libuv` [we call delRead explicitly](https://github.com/redis/hiredis/blob/b2d1ad64d03ea237e18f26fc294af87180b70d63/adapters/libev.h#L106) during cleanup which appears to manually stop the read event.

In any case, every time I did see it invoked it happens in `__redisAsyncDisconnect`, specifically in the `_EL_CLEANUP` macro but I suspect you know this already.  😅

Are either of these projects useful to show how to handle this in ASIO?
https://github.com/ryangraham/hiredis-boostasio-adapter
https://github.com/basiliscos/cpp-bredis/tree/master/include/bredis

**Comment by AndrSar** [comment]
Thanks for the detailed reply!

It seems that I simply don't understand the purpose of these callback functions. I thought that they are called only once a disconnect or an error occurs. But after some short study of the examples I see now that they are possibly called to control the events on socket whether one should be monitored at given time or not.

Maybe it is even possible to ignore them for Boost.ASIO completely as this library enqueues each event listening request separately, and if, for example, hiredis library doesn't have any pending commands then it issues delWrite.

**Comment by michael-grunder** [comment]
Going to close this issue because I don't think it's a bug in hiredis.

Good luck with your adapter though!
