### ISSUE TITLE
[CMake] Add options to add STATIC library

### ISSUE THREAD

**Issue by irov** [redis/hiredis#742]
Hi,
add please OPTION like ENABLE_STATIC to choose compile static or shared type library

OPTION(ENABLE_STATIC "Build hiredis static library" OFF)

Thanks!

**Comment by michael-grunder** [comment]
Do you mean like this?

https://github.com/redis/hiredis/pull/730

**Comment by irov** [comment]
> Do you mean like this?
> 
> #730

Hm, yes, but if i create pull request i make switch between static or shared library. Why need compile shared and static library together?

**Comment by michael-grunder** [comment]
It's common practice, at least on Linux.

You'll probably find many of your libraries have installed both `.so` and `.a` files in `/usr/local/lib/`

**Comment by irov** [comment]
> It's common practice, at least on Linux.
> 
> You'll probably find many of your libraries have installed both `.so` and `.a` files in `/usr/local/lib/`

Ok, thanks for answer! How long wait to approved this pull request? ^_^

**Comment by michael-grunder** [comment]
See PR #792.  I just want to look into any issues mixing BSD and Apache but then I'll get it merged.

**Comment by OmriSteiner** [comment]
@michael-grunder any plan to merge this?

**Comment by michael-grunder** [comment]
As I mentioned my hesitation has to do with licensing.

I wouldn't much mind except hiredis is periodically pulled back into Redis and wouldn't want to cause annoyance there.

They sure seem compatible but I'm not a lawyer
[BSD Overview](https://tldrlegal.com/license/bsd-3-clause-license-(revised))
[Apache 2.0 Overview](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0))

@yossigo Do you think there's any backporting issue here?

**Comment by yossigo** [comment]
@michael-grunder Apache 2.0 and BSD do not conflict but with Apache 2.0 there are additional obligations to users who may not be aware that such code exist in an otherwise BSD-licensed project. I doubt that it's worth to go through this license confusing for this trivial snippet.

**Comment by OmriSteiner** [comment]
I'm not sure I understood what you wrote. I think it can go either way, please clarify.

1. Merging this code would cause license confusion. It is trivial, and thus should not be merged.
2. This snippet is trivial, and thus we shouldn't go through the hassle of making sure the licenses are compatible (this seems weird to me).

Assuming you meant the first option, how do we proceed, close the merge request?

**Comment by michael-grunder** [comment]
I think the consensus is that it's not worth the licensing annoyance for such a small, somewhat boiler-plate bit of code.

If this code weren't periodically pulled back into Redis it might not be such a big deal but I don't want it to cause pain upstream.

I'll Make an effort to RTFM with respect to CMake and building static libraries and see if I can't come up with a bespoke snippet myself.

**Comment by OmriSteiner** [comment]
Oh, I totally missed the file `msvc_static_runtime.cmake` in the pull request. Now everything makes sense. I was perplexed by the talk about apache, had no idea where it came from. But now everything makes sense!

**Comment by michael-grunder** [comment]
Closing via #851
