### ISSUE TITLE
Error connection Redis, then fd=0

### ISSUE THREAD

**Issue by srdunov** [redis/hiredis#744]
redisContext uses the calloc function to create the structure. Therefore, all values ​​are 0. I use Redis in my project. My project is a gateway. I am creating a tcp server. I have a lot of connections to Redis, so an error occurs and a socket for tcp connection with Redis is not created and therefore fd = 0. Further, by example, I clear the memory of the redisContext structure and at this time the socket closes with fd = 0. It is not right. Next, this fd is freed up and allocated by my client to connect to my tcp server, which causes my program to crash. Please set fd for the redisContext structure to InvalidSocket.

**Comment by michael-grunder** [comment]
I will take a look at this.  I'll need to do some investigating into what the analogous value would be in Windows as we support both platforms.

**Comment by michael-grunder** [comment]
Hi @srdunov can you clarify the issue you're running into again?

It looks like we set `redisContext->fd` to `REDIS_INVALID_FD` on construction.  How are you seeing it get set back to zero?

**Comment by michael-grunder** [comment]
I'm going to close this issue because we are using  REDIS_INVALID_FD already.

If you can provide more context feel free to reopen and I'm sure we can figure something out
