### ISSUE TITLE
error when make USE_SSL=1

### ISSUE THREAD

**Issue by njuyang14** [redis/hiredis#748]
branch: master
commit id: 0501c623c91344e54cb2775a91509650960789b1

when i compile with: make USE_SSL=1, i meet some errors. I see the error "No rule to make target '-lssl'", but i don't know why the '-ssl' is a target. Please help me, thanks!
 
`[root@80439c2caaee /usr1/newhiredis/hiredis]$make USE_SSL=1
cc -std=c99 -pedantic -c -O3 -fPIC  -DHIREDIS_TEST_SSL -Wall -W -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb net.c
cc -std=c99 -pedantic -c -O3 -fPIC  -DHIREDIS_TEST_SSL -Wall -W -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb hiredis.c
cc -std=c99 -pedantic -c -O3 -fPIC  -DHIREDIS_TEST_SSL -Wall -W -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb sds.c
cc -std=c99 -pedantic -c -O3 -fPIC  -DHIREDIS_TEST_SSL -Wall -W -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb async.c
cc -std=c99 -pedantic -c -O3 -fPIC  -DHIREDIS_TEST_SSL -Wall -W -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb read.c
cc -std=c99 -pedantic -c -O3 -fPIC  -DHIREDIS_TEST_SSL -Wall -W -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb sockcompat.c
cc -shared -Wl,-soname,libhiredis.so.0.14 -o libhiredis.so net.o hiredis.o sds.o async.o read.o sockcompat.o
ar rcs libhiredis.a net.o hiredis.o sds.o async.o read.o sockcompat.o
cc -std=c99 -pedantic -c -O3 -fPIC  -DHIREDIS_TEST_SSL -Wall -W -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb test.c
cc -std=c99 -pedantic -c -O3 -fPIC  -DHIREDIS_TEST_SSL -Wall -W -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb ssl.c
ar rcs libhiredis_ssl.a ssl.o
make: *** No rule to make target '-lssl', needed by 'hiredis-test'.  Stop.`

**Comment by michael-grunder** [comment]
Hi @njuyang14 sorry about the delay.

Are you by chance trying to build hiredis on OSX?

Can you try [building this branch linked in this thread](https://github.com/michael-grunder/hiredis/pull/new/osx-makefile-fix) and see if it works for you?

**Comment by michael-grunder** [comment]
Should be sorted in #786

**Comment by michael-grunder** [comment]
Closing via #789
