### ISSUE TITLE
Synchronous Redis commands - timeout handling

### ISSUE THREAD

**Issue by iyer-r** [redis/hiredis#749]
Hello, 

When doing an synchronous update command (INCRBY), if I receive a timeout, is it guaranteed that the server has not actually done the operation? 

What is the best way to ensure that the server-side operation is not done when the client receives a timeout?

Regards

**Comment by michael-grunder** [comment]
No there's no guarantee of that because it's possible for you to get a read timeout after Redis received the command.

I don't have a good answer for you as to how you can ensure the command is executed as it would depend on your exact situation.
