### ISSUE TITLE
extern "C" missing from hiredis_ssl.h

### ISSUE THREAD

**Issue by azmtnruz** [redis/hiredis#750]
I think hiredis_ssl.h header file needs:

```
#ifdef __cplusplus
extern "C" {
#endif
```

and

```
#ifdef __cplusplus
}
#endif
```

So that a c++ app can link to the libhiredis_ssl.so. The hiredis.h header file uses extern "C".

**Comment by michael-grunder** [comment]
We're about to merge a security related patch but once that's merged I'll merge this change into master.

**Comment by michael-grunder** [comment]
Closing via #759
