### ISSUE TITLE
What is the date for hiredis release version with SSL/TLS?

### ISSUE THREAD

**Issue by lisay-yan** [redis/hiredis#772]
Hi, Hiredis Team

It seems long time no new release version ready since Sep 2018.
https://github.com/redis/hiredis/releases

Any plan for next release? What is the due date?
Expect Hiredis can support SSL/TLS via release version soon.

Thanks
Lisa

**Comment by alanroche** [comment]
Bump

**Comment by michael-grunder** [comment]
Hi everyone,

Sorry for the delay but I was working on getting [v0.14.1](https://github.com/redis/hiredis/tree/v0.14.1) released.

Before we release v1.0.0 we want to add a level of indirection to every allocation/deallocation call to go through `hi_*` variants such that they are easily pluggable downstream (e.g. people may wish to use jemalloc, or tcmalloc, or their own allocator).

I'm sorry that I don't have an exact date, but this isn't all that large a job so it shouldn't be too long.

**Comment by lisay-yan** [comment]
@michael-grunder and Experts

It seems existing SSL is based on redisContext, how about redisAsyncContext?
Is it also in TLS support scope?
Will it be ready when release version announced?

Best Wishes
Lisa

**Comment by michael-grunder** [comment]
Closing in favor of #807 where all of the v1.0.0 discussion will be happening.
