### ISSUE TITLE
Initialization discards const qualifier

### ISSUE THREAD

**Issue by escherstair** [redis/hiredis#777]
Compiling with GCC 7.3.0 gives the error
Initialization discards const qualifier from pointer target type here

https://github.com/redis/hiredis/blob/a1405e172a3c57cb18e506afeb681551dce02620/sockcompat.c#L215

I think it hould be
`const struct timeval *tv = optval;`

**Comment by michael-grunder** [comment]
Fixed via ec18d790f165da1b2e7528828518a3034aa74b9
