### ISSUE TITLE
Did you forget to add scheduleTimer with libev? 

### ISSUE THREAD

**Issue by corznoc** [redis/hiredis#778]
I see you had add scheduleTimer for lib event in the attach function, could you add it to the libev? 
the redisAsyncSettimeout function can not work with libev.

**Comment by michael-grunder** [comment]
Apologies, I mixed up the two issue numbers in ec18d790f165da1b2e7528828518a3034aa74b9.

I'll take a look at this.

**Comment by michael-grunder** [comment]
Hi @corznoc can you please try [this branch on my fork](https://github.com/michael-grunder/hiredis/tree/libev-timeout)?

This is just a first pass but it seems to be working on my end.

Let me know how it works for you! :smile:

**Comment by corznoc** [comment]
Thank you very much, I'll try it later.

**Comment by corznoc** [comment]
This timer only support one by one?
Can I call many times redisAsyncCommand before the last callback returned?

**Comment by michael-grunder** [comment]
> Can I call many times redisAsyncCommand before the last callback returned?

Yes, you can send many commands before the last one returns and Hiredis will continually "reschedule" your timer to `now() + timeout value` every time it encounters a read/write event.

**Comment by michael-grunder** [comment]
Closing, since this has been implemented and merged.
