### ISSUE TITLE
redisAsyncConnect error:setsockopt(TCP_NODELAY)  

### ISSUE THREAD

**Issue by cosmosir** [redis/hiredis#779]
windows 
auto* ac = redisAsyncConnect(ip, port);
ac->err is -1
ac->errstr is setsockopt(TCP_NODELAY) 

if execute code:  connect(sockfd, addr, addrlen);  //(sockcompat.c line:178)
setsockopt //(net.c line:208)
then error:setsockopt(TCP_NODELAY) 

if execute code: (sockcompat.c line178) then Wait a moment 
and then execute (net.c line:208)
it is succeed

I guess,
The connection is asynchronous, if setsockopt immediately, it is fail. if wait for connect complete then setsockopt, it is succeed.

Is there any other way to avoid this problem

**Comment by michael-grunder** [comment]
Closing in favor if #785
