### ISSUE TITLE
Why refreshTimeout for each async request?

### ISSUE THREAD

**Issue by panyfx** [redis/hiredis#782]
I want to send a sequence Get requests one by one. 
GetKey1--->Getkey2 ---> GetKey3
if all respones are ok, then call back:
 Getkey1CallBack -->GetKey2CallBack--->GetKey3CallBack
if GetKey1 is timeout, then call back :
   Getkey1CallBack(timeout call) -->GetKey2CallBack--->GetKey3CallBack
they use  one same redisAsyncContext object.

**Comment by michael-grunder** [comment]
I'm not sure I totally understand the question.

Presently we refresh (extend) the timeout each time a read or write event is triggered.  This is a pretty normal way of handling timeouts in async.

**Comment by panyfx** [comment]
when   GetKey2 request, the timer of GetKey1 is not reseted?

**Comment by michael-grunder** [comment]
The way it works is this:

We schedule a repeating timer to go off in `N` seconds.  Every time hiredis encounters a read or write event the timer is rescheduled to a new time in the future.

In practice, this just means that there will be a limit to how long any command can take before we trigger the timeout at which point Hiredis will disconnect.

[Theoretically, we could handle this in a more robust way](https://github.com/redis/hiredis/issues/781) but it is not a trivial change.

Does that answer your question?

**Comment by panyfx** [comment]
Thank you.

**Comment by michael-grunder** [comment]
Closing as the question has been answered.

Still, feel free to add a comment if you have more questions though :smile:
