### ISSUE TITLE
read and write to remote redis server.

### ISSUE THREAD

**Issue by DeepthiV43** [redis/hiredis#798]
I am trying to achieve the following. Referred https://github.com/redis/hiredis/issues/453 to get an idea.

1. Writer connects to remote redis server and writes data to it. Publish sends a message on the channel to notify reader.
2. Reader that is running on the other machine where the redis server is residing needs to be notified of the write action and read the data. It waits for the publish message in a loop.
3. Here I'm using publish/subscribe model as signalling method for the reader to read the data. Is there a better way to do it?
4. Problem I see in the code below is - for debugging when I run redis-cli on the reader end and trying to dump all the keys using "KEYS *",  get the following error
127.0.0.1:6379[1]> keys *
(empty list or set)

Following is my code. Code below works fine. I can get the key value using "redisAppendCommand(readctx, "GET foo");" in read_redis_data_thread() but don't see it from redis cli

```
int write_redis_data()
{
    redisReply *reply;

	/* Connect to remote redis server */
	c = redisConnect(<remote_host_ip>, <remote_host_port>);
	
    /* PING server */
    reply = redisCommand(c,"PING");
    printf("PING: %s\n", reply->str);
    freeReplyObject(reply);

	/* To run a loop after behaviour is understood */
    redisAppendCommand(c, "SET foo bar");

    redisAppendCommand(c, "PUBLISH %s Hello", PSCHANNEL);
    int i;
    for (i = 0; i < 2; i++)
    {
      int r = redisGetReply(c, (void **) &reply);
      if ( r == REDIS_ERR )
      {
          perror("Error: %s\n");
          return -1;
      }
      freeReplyObject(reply);
    }
    return 0;
}

void *read_redis_data_thread()
{
    redisContext *readctx, *c;
    redisReply *reply;
    redisReply *readReply;
    int j = 0;

	
	c = redisConnect("127.0.0.1", 6379);
	
    /* PING server */
    reply = redisCommand(c,"PING");
    printf("PING: %s\n", reply->str);
    freeReplyObject(reply);

    /* Subscribe to the channel to get the config updates 
     * from the publisher. This is a synchronous operation where the
     * subscriber waits for the reply. */
    printf("Subscribing to channel %s\n", PSCHANNEL);
    reply = redisCommand(c, "subscribe %s", PSCHANNEL);
    if (!reply || c->err)
    {
         printf("Subscribe Failed (%s)\n", strerror(c->err));
         pthread_exit(0);
    }
    freeReplyObject(reply);


    /* Create a reader context that reads data from the local redis server */
    readctx = redisConnect("127.0.0.1", 6379);
    if (readctx == NULL || readctx->err)
    {
        if (readctx)
        {
            printf("Connection error: %s\n", readctx->errstr);
            redisFree(readctx);
        }
        else
        {
            printf("Connection error: can't allocate redis context\n");
        }
        exit(1);
    }

    while (redisGetReply(c, (void**)&reply) == REDIS_OK)
    {
         if (reply->type == REDIS_REPLY_ARRAY)
         {
            for (j = 0; j < reply->elements; j++)
            {
                printf("%u) %s\n", j, reply->element[j]->str);
            }
         }
         freeReplyObject(reply);

         redisAppendCommand(readctx, "GET foo");
         if (redisGetReply(readctx, (void*)&readReply) == REDIS_OK)
         {
             printf("type = %d elements = %d, str = %s\n", readReply->type, readReply->elements, readReply->str);
         }
         else
         {
             printf(" Error reading key\n");
         }
		 freeReplyObject(readReply);
    }
}
```

**Comment by michael-grunder** [comment]
I'm not sure I understand your question

```"redisAppendCommand(readctx, "GET foo");" in read_redis_data_thread() but don't see it from redis cli```

When I run your program I see the key `foo` from redis-cli.  Are you sure you're not connecting to a different redis-server?

**Comment by DeepthiV43** [comment]
I could debug it further and found that when I run redis-cli by explicitly mentioning the host IP it is running on I could dump the keys successfully. But if redis-cli is launched with default host, I don't find them. I am very sure that redis-cli is being run from the same machine where the data is written. 

root@ngv-8:/home/admin# redis-cli
127.0.0.1:6379> keys *
(empty list or set)
127.0.0.1:6379> quit
root@ngv-8:/home/admin# 
root@ngv-8:/home/admin# redis-cli -h 1.1.1.1 -p 6000
1.1.1.1:6000> 
1.1.1.1:6000> keys *
1) "foo"
1.1.1.1:6000> get foo
"bar"
1.1.1.1:6000>

By this line, ""redisAppendCommand(readctx, "GET foo");" in read_redis_data_thread() but don't see it from redis cli" I meant that from the code I'm able to get the keys and their values but from redis-cli prompt can't find them. It might be due to above mentioned issue.

I need some suggestions on how to improvise the code to return some data from the subscriber thread  back to the publisher after it has processed the data. Basically I'm looking for bidirectional communication without the need for creating another pubsub channel in opposite direction.

**Comment by michael-grunder** [comment]
Your two Redis servers are also running on different ports, so they're different instances of Redis unless you're doing some network mapping behind the scenes.

My guess is you'll see different IDs if you do this:

```bash
redis-cli -h 1.1.1.1 -p 6000 info|grep run_id
redis-cli info|grep run_id
```

Redis pub/sub is one directional so if you just want to use publish/subscribe you would need another one in the opposite direction to do two-way communication.  There are other options though.  One would be to push messages into a list and pop them from the other side.  This has the advantage that the messages are persistent (don't just disappear if you're not currently subscribing).

You may want to try asking in the Redis gitter chat room which is more for general design questions around Redis.

https://gitter.im/Redis

**Comment by michael-grunder** [comment]
I'm going to close this issue since it's not really a bug in Hiredis but good luck solving your problem.

**Comment by DeepthiV43** [comment]
> I'm going to close this issue since it's not really a bug in Hiredis but good luck solving your problem.

Thanks for the inputs.
