### ISSUE TITLE
INFO & CLUSTER commands failed when using RESP3

### ISSUE THREAD

**Issue by carlosabalde** [redis/hiredis#802]
The following toy implementation shows how execution of `INFO` command using current `RESP3` support in `master` fails with error `Protocol error, got "=" as reply type byte`. This has been tested using Redis Server 6.0.1. Same logic using `RESP2` works as expected.

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <hiredis/hiredis.h>

#define HOST "127.0.0.1"
#define PORT 6400

static redisContext *connect(unsigned version)
{
    redisContext *ctx = redisConnect(HOST, PORT);
    assert(ctx != NULL);
    if (ctx->err) {
        printf("CONNECT: %s\n", ctx->errstr);
    }
    assert(ctx != NULL && !ctx->err);

    redisReply *reply = redisCommand(ctx, "HELLO %d", version);
    if (ctx->err) {
        printf("HELLO: %s\n", ctx->errstr);
    }
    assert(
        !ctx->err && reply != NULL &&
        ((version == 2 && reply->type == REDIS_REPLY_ARRAY) ||
         (version == 3 && reply->type == REDIS_REPLY_MAP)));
    freeReplyObject(reply);

    return ctx;
}

int
main(int argc, char *argv[])
{
    redisContext *ctx = connect(3);
    redisReply *reply = redisCommand(ctx, "INFO");
    if (ctx->err) {
        printf("INFO: %s\n", ctx->errstr);
    }
    assert(!ctx->err && reply != NULL);
    printf("%s\n", reply->str);
    freeReplyObject(reply);
}
```

**Comment by carlosabalde** [comment]
Btw, I got same error with `RESP3` + `CLUSTER` command.

**Comment by michael-grunder** [comment]
Hi @carlosabalde, would you please try [this branch on my fork](https://github.com/michael-grunder/hiredis/tree/resp3-verbatum-string).

Looks like verbatim string handling was just lost in the shuffle back and forth between Redis and hiredis.

**Comment by carlosabalde** [comment]
Hi @michael-grunder,

I confirm your fork fixes both the issue shown in the snippet as well as other issues in a project I'm adding `RESP3` support.

However now `reply->type` is `REDIS_REPLY_STRING` when using `RESP2` but `REDIS_REPLY_VERB` when using `RESP3`. That's annoying when trying to support both protocols, but I'm assume that's correct, right? Any hint to understand when a command would return `REDIS_REPLY_STRING` both in `RESP2` and `RESP3` and when not? 

Thanks a lot! :)

**Comment by michael-grunder** [comment]
Closing in favor of #805
