### ISSUE TITLE
Makefile does not install TLS libraries 

### ISSUE THREAD

**Issue by theDogOfPavlov** [redis/hiredis#809]
### What do I see?

When I run the make and install, the tests complete as expected, however the TLS headers and libraries are not copied over.

### What do I expect to see?

The headers and libraries should be installed as expected.

### To reproduce
build
```
make USE_SSL=1
make install
```
TLS headers and libraries created as expected, but the Makefile does not copy them to the right locations
```
mkdir -p /usr/local/include/hiredis /usr/local/include/hiredis/adapters /usr/local/lib
cp -pPR hiredis.h async.h read.h sds.h alloc.h /usr/local/include/hiredis
cp -pPR adapters/*.h /usr/local/include/hiredis/adapters
cp -pPR libhiredis.so /usr/local/lib/libhiredis.so.0.15
cd /usr/local/lib && ln -sf libhiredis.so.0.15 libhiredis.so
cp -pPR libhiredis.a /usr/local/lib
mkdir -p /usr/local/lib/pkgconfig
cp -pPR hiredis.pc /usr/local/lib/pkgconfig
```

**Comment by michael-grunder** [comment]
I see the same thing.  I'll take a closer look later today after I've had coffee :smile:

**Comment by michael-grunder** [comment]
I got this working over on my fork.  I'm not sure this is the cleanest solution but it seems like both:

```bash
USE_SSL=1 make && sudo make install
```

and

```bash
sudo USE_SSL=1 make install
```

Should work to build and install the SSL libraries.
