### ISSUE TITLE
Not able to install hiredis in windows

### ISSUE THREAD

**Issue by mannesudhir** [redis/hiredis#816]
not able to npm install hiredis getting below error, any help on this  i am stuck for 3 days on this issue

![image](https://user-images.githubusercontent.com/13063282/82533347-b55a9680-9b60-11ea-926d-c938b2852dad.png)

**Comment by michael-grunder** [comment]
I'd love to help but this is an issue with [hiredis-node](https://github.com/redis/hiredis-node) not hiredis.

Also, I don't know anything about the node ecosystem so I couldn't really be very helpful anyway.  

Can you switch to using [redis-node](https://github.com/NodeRedis/node-redis) for your project?

**Comment by michael-grunder** [comment]
I'm going to close this because it's not about hiredis, but hiredis-node, which is archived.
