### ISSUE TITLE
hiredis C programming for XREADGROUP

### ISSUE THREAD

**Issue by rich-2020** [redis/hiredis#820]
I am trying to use hiredis as C redis client to program Redis stream, when I use XREADGROUP, I found some issues which I am not sure if it is hiredis ocde issue or my usage issue. I am using the version which comes with redis 6.0.3.

Here are my test cases:

TC 1: did not add data through redis-cli before running my program.
        from redis-cli.
```bash
127.0.0.1:6379> XREADGROUP GROUP diameter Tom BLOCK 1 COUNT 1 NOACK STREAMS update_db >
                (nil)
```
from my program:
```c
reply = redisCommand(c, "XREADGROUP GROUP diameter Tom BLOCK 1 COUNT 1 NOACK STREAMS update_db >");
// reply is NULL
```
TC 2: add data through redis-cli before running my program. from redis-cli, i can get:
```
127.0.0.1:6379> XREADGROUP GROUP diameter Tom BLOCK 1 COUNT 1 NOACK STREAMS update_db >
1) 1) "update_db"
2) 1) 1) "1590077941505-0"
   2) 1) "pri_key"
   2) "1006"
 ```    
  (add data again because data was read by redis-cli)
   from my program:         

```c                     
reply = redisCommand(c, "XREADGROUP GROUP diameter Tom BLOCK 1 COUNT 1 NOACK STREAMS update_db >");

size_t m = 0;
if (reply != NULL) {
    for (m = 0; m < reply->elements; m++)
    printf("XREADGROUP %s\n", reply->element[m]->str);
}
```
reply is not NULL but I did not get any data,  output is printed out but it is "null". it looks `reply->element[m]->str` contains null.

TC 3, change BLOCK to be 0, expect program to block until new data comes.

from redis-cli, 

the command: "XREADGROUP GROUP diameter Tom BLOCK 0 COUNT 1 NOACK STREAMS update_db >" would block, when the new data comes, it will read data and return.
        
However from program, I used: 

```c
reply = redisCommand(c, "XREADGROUP GROUP diameter Tom BLOCK 0 COUNT 1 NOACK STREAMS update_db >");           
```

I am hoping it would block and wait for the new data (before running my program, I clean up the data by using flushall from redis-cli), but it actually did not block as expected, it return and reply is NULL.

To me, TC 1 probably make sense, but TC 2 and TC 3 do not make sense for me.

Thank you,
Rich

**Comment by rich-2020** [comment]
add my  code pieces:

   printf("create a consumer group\n");
    reply = redisCommand(c, "XGROUP CREATE update_db diameter $ MKSTREAM");
    printf("XGROUP create %s\n", reply->str);
    freeReplyObject(reply);
 
    reply = redisCommand(c, "XADD update_db * %b %b", "pri_key",(size_t)7, "customer:1005", (size_t)13);
    if (reply != NULL) 
    {
        printf("XADD id is %s\n", reply->str);
    }
    freeReplyObject(reply);
    
    /*create consumer*/
    reply = redisCommand(c, "XREADGROUP GROUP diameter Tom BLOCK 0 COUNT 1 NOACK STREAMS update_db >");
    size_t m = 0;
    if (reply != NULL) {
    for (m = 0; m < reply->elements; m++)
        printf("XREADGROUP %s\n", reply->element[m]->str);
    }
    freeReplyObject(reply);

**Comment by michael-grunder** [comment]
> reply is not NULL but I did not get any data, output is printed out but it is "null". it looks reply->element[m]->str contains null.

That's because `XREADGROUP` will return a nested array (an array where each element is another array).

[Here's a quick program to demonstrate](https://gist.github.com/michael-grunder/3db92b4030badf34a86e714c1fdf3072)

Example output:
```bash
$ ./streams 2 2
Added foo -> mem:0 (id: 1590091105077-0)
Added foo -> mem:1 (id: 1590091105077-1)
[0] Sending XREADGROUP (stream: example-stream, BLOCK: 1)
    (string) example-stream
        (string) 1590091105077-0
          (string) foo
          (string) mem:0
[1] Sending XREADGROUP (stream: example-stream, BLOCK: 1)
    (string) example-stream
        (string) 1590091105077-1
          (string) foo
          (string) mem:1
```

If I specify block 0 and read more than I add, it blocks:

```bash
$ ./streams 2 3 0
Added foo -> mem:0 (id: 1590091151530-0)
Added foo -> mem:1 (id: 1590091151530-1)
[0] Sending XREADGROUP (stream: example-stream, BLOCK: 0)
    (string) example-stream
        (string) 1590091151530-0
          (string) foo
          (string) mem:0
[1] Sending XREADGROUP (stream: example-stream, BLOCK: 0)
    (string) example-stream
        (string) 1590091151530-1
          (string) foo
          (string) mem:1
[2] Sending XREADGROUP (stream: example-stream, BLOCK: 0)
```

Then I can `XADD` in `redis-cli` to and will see the new message.

**Comment by rich-2020** [comment]
Hi Michael,
Thank you so much for your time and your help. it was my knowledge gap to cause this issue, I am closing this issue.

Thank you,
Rich

**Comment by michael-grunder** [comment]
No worries, I'm glad I was able to help!
