### ISSUE TITLE
hiredis with libevent， build in vs2019， SIGPIPE undefined,  what can I do?

### ISSUE THREAD

**Issue by chris-shenzhen-china** [redis/hiredis#831]
hiredis with libevent， build in vs2019， SIGPIPE undefined,  what can I do?

**Comment by chris-shenzhen-china** [comment]
signal(SIGPIPE, SIG_IGN); ----it comes from example-libevent.c or ther example for hiredis.

int main (int argc, char **argv) {
    signal(SIGPIPE, SIG_IGN);
    struct event_base *base = event_base_new();
    redisOptions options = {0};
    REDIS_OPTIONS_SET_TCP(&options, "127.0.0.1", 6379);
    struct timeval tv = {0};
    tv.tv_sec = 1;
    options.timeout = &tv;


    redisAsyncContext *c = redisAsyncConnectWithOptions(&options);
    if (c->err) {
        /* Let *c leak for now... */
        printf("Error: %s\n", c->errstr);
        return 1;
    }

    redisLibeventAttach(c,base);
    redisAsyncSetConnectCallback(c,connectCallback);
    redisAsyncSetDisconnectCallback(c,disconnectCallback);
    redisAsyncCommand(c, NULL, NULL, "SET key %b", argv[argc-1], strlen(argv[argc-1]));
    redisAsyncCommand(c, getCallback, (char*)"end-1", "GET key");
    event_base_dispatch(base);
    return 0;
}

**Comment by michael-grunder** [comment]
> signal(SIGPIPE, SIG_IGN); ----it comes from example-libevent.c or ther example for hiredis.

I'm not sure what the equivalent would be in Windows but you should be able to just comment out that line.

That said, I will update the examples so they compile in Windows as well.

**Comment by chris-shenzhen-china** [comment]
thanks for your feedback.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Michael Grunder"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月17日(星期三) 上午10:25
收件人:&nbsp;"redis/hiredis"<hiredis@noreply.github.com&gt;;
抄送:&nbsp;"Lucky&amp;nbsp;Lee-0"<sz_lidong@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [redis/hiredis] hiredis with libevent， build in vs2019， SIGPIPE undefined,  what can I do? (#831)





  
signal(SIGPIPE, SIG_IGN); ----it comes from example-libevent.c or ther example for hiredis.
  
I'm not sure what the equivalent would be in Windows but you should be able to just comment out that line.
 
That said, I will update the examples so they compile in Windows as well.

**Comment by michael-grunder** [comment]
Closing as I've wrapped any `SIGPIPE` interaction in an `#ifdef`
