### ISSUE TITLE
hiredis with libevent, why write & read event could not be active, so event_base_dispatch(base) return

### ISSUE THREAD

**Issue by chris-shenzhen-china** [redis/hiredis#832]
![image](https://user-images.githubusercontent.com/42959931/84362827-6c967a80-ac00-11ea-9122-cbc3de812a0e.png)

**Comment by zestloveheart** [comment]
do you install libevent？

**Comment by michael-grunder** [comment]
Going to close this old issue, but feel free to reopen if you can provide an example program that demonstrates the problem.
