### ISSUE TITLE
hiredis release tag working with windows

### ISSUE THREAD

**Issue by r0nanhugh3s** [redis/hiredis#834]
Hello. Looking at the latest release tag version, it does not include the changes in master for windows.

e.g. 
#ifndef _MSC_VER
#include <strings.h>
#endif

Is there a release tag planned from current master? 
Where I work we have a couple of restrictions on 3rd party libs. 1) we are windows 2) we can only use release tags, no master clones. So if a release tag is coming soon that is good news.

Regards.

**Comment by michael-grunder** [comment]
Yes, we are planning on releasing v1.0.0 very soon although there will likely be a release candidate first.

**Comment by michael-grunder** [comment]
Closing as [v1.0.0](https://github.com/redis/hiredis/tree/v1.0.0) is released.
