### ISSUE TITLE
Is there a way to tell hiredis to disconnect in the async onConnect callback?

### ISSUE THREAD

**Issue by echoma** [redis/hiredis#835]
https://github.com/redis/hiredis/blob/master/async.c#L620
If I call redisAsyncDisconnect() in the onConnect callback, the redisContext pointer "c" will point to a freed memory, this might make a crash.

may be, a REDIS_IN_CALLBACK like flag which protecting the context object will help?

**Comment by michael-grunder** [comment]
The [onConnect](https://github.com/redis/hiredis/blob/8e0264cfd6889b73c241b60736fe96ba1322ee6e/async.h#L59) callback gives you a `const redisAsyncContext *ac` so you really shouldn't be mutating it there.

What's the use case for this?

**Comment by echoma** [comment]
I am a library writer, the library's user may do some checking logic in business layer in onConnect callback. On some situation, the user would like to close the connection when checking failed. @michael-grunder

**Comment by michael-grunder** [comment]
Closing as this is now possible as #931 was merged and then modified slightly in #1087
