### ISSUE TITLE
unnecessary prints 

### ISSUE THREAD

**Issue by Vishal7991** [redis/hiredis#837]
while firing any commands like
1. ping
2. or any set command 
while creating connections 
unnecessary prints are forming like +OK +PONG 
*2
$5 
slave
$10
<ip address>

i cant figure where might be this prints coming from,
could any 1 share solution
please

**Comment by michael-grunder** [comment]
Can you provide some sample code that demonstrates the problem you're seeing?

I'm not sure I fully understand the issue.

**Comment by michael-grunder** [comment]
I'm going to close the issue but if you can provide a sample of code that demonstrates the problem I'm happy to help.
