### ISSUE TITLE
Failed to build package hiredis ssl on windows*

### ISSUE THREAD

**Issue by RameshKandukuriB** [redis/hiredis#842]
**Failed to build package hiredis ssl on windows 64 bit with VS 2017/2019**

To Reproduce
vcpkg upgrade hiredis[ssl]:x64-windows-static
vcpkg upgrade hiredis[ssl]:x64-windows-static --no-dry-run
vcpkg install hiredis[ssl]:x64-windows-static --recurse
whereas vcpkg install hiredis:x64-windows-static is building successfully
Failure logs
\vcpkg\buildtrees\hiredis\src\4889033d94-d35835c897.clean\ssl.c(37): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory

**Comment by michael-grunder** [comment]
This may be an `#ifdef` issue.

Can you try building with [this branch on my fork](https://github.com/michael-grunder/hiredis/tree/fix-win32-detection)?

**Comment by michael-grunder** [comment]
If the switch to using `_WIN32` that was merged doesn't fix the problem let us know.

I don't know how `vcpkg` gets code so it will only help once they pull the newer version.

**Comment by RameshKandukuriB** [comment]
Thanks, I have similar issue #646 on azure redis cache and trying to figure out how to connect using ssl, any help appreciated.  I am still waiting for Microsoft response, mainly azure gives access key I don't find any certificate to use with ssl package.

**Comment by RameshKandukuriB** [comment]
What is the equivalent of following StackExchange.Redis connection to hiredis connection?  I think password can be set by AUTH. how to make the ssl = true in hiredis?
var conn = ConnectionMultiplexer.Connect("contoso5.redis.cache.windows.net,ssl=true,password=...");

**Comment by mcgradycchen** [comment]
@RameshKandukuriB  I have the same issue connect to Azure Cache for Redis by TLS. Did you solve this problem ?
