### ISSUE TITLE
using adapters\qt.h:undefined reference to ‘vtable for RedisQtAdapter’

### ISSUE THREAD

**Issue by Yes-Jumby** [redis/hiredis#847]
undefined reference to ‘vtable for RedisQtAdapter’
undefined reference to ‘vtable for ~RedisQtAdapter()’

anyone else could please give me a hand?

**Comment by michael-grunder** [comment]
Hi, what OS and compiler are you using?

It looks like this commonly happens when no destructor is implemented, but we do define a destructor.

**Comment by Yes-Jumby** [comment]
> Hi, what OS and compiler are you using?
> 
> It looks like this commonly happens when no destructor is implemented, but we do define a destructor.
> 
> Edit: Or this is a simple matter of you not linking with libhiredis. I don't use C++ that much but that message looks kind of like a linker error.

UBUNTU-X64、UBUNTU-ARM64  gcc  
I think in linux this qt module may have not been tested.

**Comment by michael-grunder** [comment]
I've never used the Qt library before but when I search that error message on Google most results talk about having to precompile your code with their `moc` utility.

I was able to compile the example-qt.cpp in our examples like this:

```bash
QT_MOC=~/Qt/5.9.9/gcc_64/bin/moc QT_INCLUDE_DIR=~/Qt/5.9.9/gcc_64/include QT_LIBRARY_DIR=~/Qt/5.9.9/gcc_64/lib make hiredis-example-qt
```
As you can see my Qt is installed in my `$HOME` directory.  I also had to change one thing in the Makefile to point at `Qt5` because my system doesn't have `Qt4`:

```patch
diff --git a/Makefile b/Makefile
index a8d37a2..8b5e256 100644
--- a/Makefile
+++ b/Makefile
@@ -190,7 +190,7 @@ hiredis-example-qt: examples/example-qt.cpp adapters/qt.h $(STLIBNAME)
 	    $(CXX) -x c++ -o qt-adapter-moc.o -c - $(REAL_CFLAGS) -I. -I$(QT_INCLUDE_DIR) -I$(QT_INCLUDE_DIR)/QtCore
 	$(QT_MOC) examples/example-qt.h -I. -I$(QT_INCLUDE_DIR) -I$(QT_INCLUDE_DIR)/QtCore | \
 	    $(CXX) -x c++ -o qt-example-moc.o -c - $(REAL_CFLAGS) -I. -I$(QT_INCLUDE_DIR) -I$(QT_INCLUDE_DIR)/QtCore
-	$(CXX) -o examples/$@ $(REAL_CFLAGS) $(REAL_LDFLAGS) -I. -I$(QT_INCLUDE_DIR) -I$(QT_INCLUDE_DIR)/QtCore -L$(QT_LIBRARY_DIR) qt-adapter-moc.o qt-example-moc.o $< -pthread $(STLIBNAME) -lQtCore
+	$(CXX) -o examples/$@ $(REAL_CFLAGS) $(REAL_LDFLAGS) -I. -I$(QT_INCLUDE_DIR) -I$(QT_INCLUDE_DIR)/QtCore -L$(QT_LIBRARY_DIR) qt-adapter-moc.o qt-example-moc.o $< -pthread $(STLIBNAME) -lQt5Core
 endif
 
 hiredis-example: examples/example.c $(STLIBNAME)
```

And I can run it like so:

```bash
LD_LIBRARY_PATH=~/Qt/5.9.9/gcc_64/lib examples/hiredis-example-qt
```

**Comment by Yes-Jumby** [comment]
> I've never used the Qt library before but when I search that error message on Google most results talk about having to precompile your code with their `moc` utility.
> 
> I was able to compile the example-qt.cpp in our examples like this:
> 
> ```shell
> QT_MOC=~/Qt/5.9.9/gcc_64/bin/moc QT_INCLUDE_DIR=~/Qt/5.9.9/gcc_64/include QT_LIBRARY_DIR=~/Qt/5.9.9/gcc_64/lib make hiredis-example-qt
> ```
> 
> As you can see my Qt5 is installed in my `$HOME/Qt/5.9.9` directory. I also had to change one thing in the Makefile to point at `Qt5` because my system doesn't have `Qt4`:
> 
> ```diff
> diff --git a/Makefile b/Makefile
> index a8d37a2..8b5e256 100644
> --- a/Makefile
> +++ b/Makefile
> @@ -190,7 +190,7 @@ hiredis-example-qt: examples/example-qt.cpp adapters/qt.h $(STLIBNAME)
>  	    $(CXX) -x c++ -o qt-adapter-moc.o -c - $(REAL_CFLAGS) -I. -I$(QT_INCLUDE_DIR) -I$(QT_INCLUDE_DIR)/QtCore
>  	$(QT_MOC) examples/example-qt.h -I. -I$(QT_INCLUDE_DIR) -I$(QT_INCLUDE_DIR)/QtCore | \
>  	    $(CXX) -x c++ -o qt-example-moc.o -c - $(REAL_CFLAGS) -I. -I$(QT_INCLUDE_DIR) -I$(QT_INCLUDE_DIR)/QtCore
> -	$(CXX) -o examples/$@ $(REAL_CFLAGS) $(REAL_LDFLAGS) -I. -I$(QT_INCLUDE_DIR) -I$(QT_INCLUDE_DIR)/QtCore -L$(QT_LIBRARY_DIR) qt-adapter-moc.o qt-example-moc.o $< -pthread $(STLIBNAME) -lQtCore
> +	$(CXX) -o examples/$@ $(REAL_CFLAGS) $(REAL_LDFLAGS) -I. -I$(QT_INCLUDE_DIR) -I$(QT_INCLUDE_DIR)/QtCore -L$(QT_LIBRARY_DIR) qt-adapter-moc.o qt-example-moc.o $< -pthread $(STLIBNAME) -lQt5Core
>  endif
>  
>  hiredis-example: examples/example.c $(STLIBNAME)
> ```
> 
> And I can run it like so:
> 
> ```shell
> LD_LIBRARY_PATH=~/Qt/5.9.9/gcc_64/lib examples/hiredis-example-qt
> ```

yes,i have build it successful in your ways.but My problems is that when I put it in QTCreator ,it will still have error.
Here is my project in ubuntu-ARM64 ,could you plz give me a hand?
you can download the project in this link :git clone https://github.com/Yes-Jumby/HIredis-qt

**Comment by michael-grunder** [comment]
The issue is that our adapters are header-only, so Qt creator doesn't compile `adapters/qt.h` as a source file, which is why you don't have the `vtable` for the class (linker error).

Right-click on the `headers` folder in your project tree and add `qt.h` (It will typically be in `/usr/local/include/hiredis/adapters` on your system).

![Screenshot from 2020-07-23 00-48-48](https://user-images.githubusercontent.com/468149/88263168-70490280-cc7e-11ea-894a-8cbadaf0add7.png)

Also, note that I have a `LIBS` line in my `.pro` file (so Qt creator links with hiredis).

``` 
unix|win32: LIBS += -lhiredis
```

**Comment by Yes-Jumby** [comment]
> The issue is that our adapters are header-only, so Qt creator doesn't compile `adapters/qt.h` as a source file, which is why you don't have the `vtable` for the class (linker error).
> 
> Right-click on the `headers` folder in your project tree and add `qt.h` (It will typically be in `/usr/local/include/hiredis/adapters` on your system).
> 
> ![Screenshot from 2020-07-23 00-48-48](https://user-images.githubusercontent.com/468149/88263168-70490280-cc7e-11ea-894a-8cbadaf0add7.png)
> 
> Also, note that I have a `LIBS` line in my `.pro` file (so Qt creator links with hiredis).
> 
> ```
> unix|win32: LIBS += -lhiredis
> ```

yes,you are right:) the problem had been solved! Thanks very much!
This is really hard for me to find this problem.Here is my another header-only.Make it not source file,it will works.so i wonder the difference between our adapters/qt.h and SpendTime.h is that qt.h need qt dependency but SpendTime.h do noe need qt dependency,is it right?
`//SpendTime.h
#ifndef SPENDTIME_H
#define SPENDTIME_H
#include<time.h>
#include<sys/time.h>
class CSpendTimeMicro
{
public:
    CSpendTimeMicro():m_lStart(0),m_lEnd(0){
    }
    ~CSpendTimeMicro(){}
    unsigned long long GetTimeStamp()
    {
    	return GetMicrosecond();
    }
    void Start()
    {
        m_lStart = GetMicrosecond();
    }
    unsigned long long End()
    {
        m_lEnd = GetMicrosecond();
        return (m_lEnd - m_lStart);
    }
private:
    unsigned long long GetMicrosecond() {
        timeval stTime;
        gettimeofday(&stTime, nullptr);
        return (static_cast<unsigned long long>(stTime.tv_sec) * 1000000 + static_cast<unsigned long long>(stTime.tv_usec));
    }
    unsigned long long m_lStart;
    unsigned long long m_lEnd;
};

class CSpendTimeNano
{
public:
    CSpendTimeNano():m_lStart(0),m_lEnd(0){
    }
    ~CSpendTimeNano(){}
    unsigned long long GetTimeStamp()
    {
        return GetNanosecond();
    }
    void Start()
    {
        m_lStart = GetNanosecond();
    }
    unsigned long long End()
    {
        m_lEnd = GetNanosecond();
        return (m_lEnd - m_lStart);
    }
private:
    unsigned long long GetNanosecond() {
        timespec stTime;
        clock_gettime(CLOCK_REALTIME, &stTime);
        return (static_cast<unsigned long long>(stTime.tv_sec) * 1000000000 + static_cast<unsigned long long>(stTime.tv_nsec));
    }
    unsigned long long m_lStart;
    unsigned long long m_lEnd;
};
#endif // SPENDTIME_H
`
