### ISSUE TITLE
1.1.0 on PyPI

### ISSUE THREAD

**Issue by ThiefMaster** [redis/hiredis#856]
There's a [hiredis 1.1.0](https://pypi.org/project/hiredis/1.1.0/) release on PyPI but there's no changelog anywhere, while recent commits in this repo still talk about 1.0.0-rc1.

This feels very odd, but the source archive for 1.1.0 looks clean. No idea about the binary wheels though. Could you confirm whether 1.1.0 is a proper release? If yes, then the 1.0.0-rc1 that's being prepared in a85346754 should probably become 2.0.0-rc1 instead (or 1.2.0-rc1 if there are no breaking changes).

**Comment by shogo82148** [comment]
from my understanding, hiredis on PyPI is a different project from this project.
I agree that this feels very odd, but you should ask it in https://github.com/redis/hiredis-py

**Comment by ThiefMaster** [comment]
ah that makes sense ;) nevermind then!
