### ISSUE TITLE
Where can I find 0.15.0?

### ISSUE THREAD

**Issue by yudataguy** [redis/hiredis#860]
I have a app that's specific looking for `libhiredis.so.0.15`, since 2 days ago after the release of 1.0.0-rc, my new build has been experiencing missing file issue. Any suggestion on how to overcome this issue?

**Comment by michael-grunder** [comment]
Hi,

We never released v0.15.0 but that was what was set for the version in the master branch at commit d8ff72387d5474e56228a3403dc91354d9916189, so if you can't rebuild your application you can checkout that hash and `make && sudo make install` and it should work for you.

**Comment by michael-grunder** [comment]
I'm going to close this issue and have changed hiredis.h so this doesn't happen in the future.

If you're not able to get your program working by using d8ff723 please let me know and I'll try to help.

**Comment by yudataguy** [comment]
@michael-grunder It's working fine now. Thank you so much!

**Comment by lamby** [comment]
Out of interest, how long do you plan to keep the `HIREDIS_SONAME` as `1.0.0-rc1`? (ie. with the `-rc-1` suffix)

**Comment by michael-grunder** [comment]
Assuming we don't get any bug reports I was thinking of releasing 1.0.0 GA Monday morning (August 3rd, PST).

**Comment by lamby** [comment]
Nice, how stable will this SONAME be? :+1:

**Comment by michael-grunder** [comment]
We're not going to break ABI or source compatibility until a new major version and I suspect that won't be for quite some time.

I'd be happy to @ you whenever we're planning a release to avoid any pain points.

**Comment by lamby** [comment]
As long as you aren't changing the SONAME every week or so, that's fine. :+1:  Bumping the soname in Debian (where I am the maintainer of this package) is a slight pain; certainly don't want to get everything building with `1.0.0-rc1` and then get everything building with `1.0.0` a few days later, so awaiting this `1.0.0` GA release in earnest.

**Comment by michael-grunder** [comment]
I'm preparing v1.0.0 [here](https://github.com/redis/hiredis/tree/release/v1.0.0).  Also, feel free to let me know if there are better naming conventions I should be using for things like release candidates.

Packaging isn't really my strong suit.

**Comment by lamby** [comment]
>  let me know if there are better naming conventions I should be using for things like release candidates.

Just using `-rcX` is fine. I suppose the only obvious mistake is to make them not sort properly, but luckily `alpha < beta < rc1 < rc2` etc. :+1:
