### ISSUE TITLE
hiredis 1.0.0 osx build issue

### ISSUE THREAD

**Issue by chenrui333** [redis/hiredis#862]
relates to https://github.com/Homebrew/homebrew-core/pull/59165

```
==> /usr/bin/clang -I/usr/local/Cellar/hiredis/1.0.0/include/hiredis -L/usr/local/Cellar/hiredis/1.0.0/lib -lhiredis /usr/local/Cellar/hiredis/1.0.0/share/hiredis/examples/example.c -o /private/tmp/hiredis-test-20200805-47091-13lreo0/test
/usr/local/Cellar/hiredis/1.0.0/share/hiredis/examples/example.c:5:10: fatal error: 'win32.h' file not found
#include <win32.h>
         ^~~~~~~~~
1 error generated.
Error: hiredis: failed
```

full build log in here, https://github.com/Homebrew/homebrew-core/runs/947208930

**Comment by michael-grunder** [comment]
Thanks for the report.

Looks like I broke this when fixing hiredis so we are able to run the unit tests on Windows.  Looks like it's only going to affect building examples but I'll put together a patch.

I'd rather not install our helper `win32.h` header so I'll see what it'll take to get the examples/tests compiling without it.

**Comment by michael-grunder** [comment]
This fix has been merged.  I'm not sure how homebrew build scripts work but let me know if it didn't solve the problem.

**Comment by chenrui333** [comment]
Thanks for the fix, I will adopt your patch and let you know how it goes. Thanks!
