### ISSUE TITLE
hiredis-1.0.0 make error once ENABLE_SSL=ON

### ISSUE THREAD

**Issue by lisay-yan** [redis/hiredis#869]
Hi, Hiredis expert

Once I turn on CMake flag to enable SSL, make will hit build error. Minor fix will work well.

hiredis-1.0.0]$ cmake -DENABLE_SSL=ON .

hiredis-1.0.0]$ make
Scanning dependencies of target hiredis_ssl
[  7%] Building C object CMakeFiles/hiredis_ssl.dir/ssl.c.o
[ 15%] Linking C shared library libhiredis_ssl.so
[ 15%] Built target hiredis_ssl
Scanning dependencies of target hiredis
[ 23%] Building C object CMakeFiles/hiredis.dir/alloc.c.o
[ 30%] Building C object CMakeFiles/hiredis.dir/async.c.o
[ 38%] Building C object CMakeFiles/hiredis.dir/dict.c.o
[ 46%] Building C object CMakeFiles/hiredis.dir/hiredis.c.o
[ 53%] Building C object CMakeFiles/hiredis.dir/net.c.o
[ 61%] Building C object CMakeFiles/hiredis.dir/read.c.o
/home/lisay/hiredis-1.0.0/read.c: In function ‘redisReaderFree’:
/home/lisay/hiredis-1.0.0/read.c:646:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (int i = 0; i < r->tasks; i++) {
         ^
/home/lisay/hiredis-1.0.0/read.c:646:9: note: use option -std=c99 or -std=gnu99 to compile your code
make[2]: *** [CMakeFiles/hiredis.dir/read.c.o] Error 1
make[1]: *** [CMakeFiles/hiredis.dir/all] Error 2
make: *** [all] Error 2

Best Wishes
Lisa

**Comment by michael-grunder** [comment]
Interesting,

Hiredis requires C99 (there's a lot of [code that's not C90 compliant](https://github.com/redis/hiredis/issues/494)).

I'd be interested to know what OS and compiler you're using (and what versions).

The solution may be to specify C99 in CMakeLists.txt.  I can fix this line but none of SDS will compile in C90 either.

**Comment by michael-grunder** [comment]
Let me know if [this branch on my fork](https://github.com/michael-grunder/hiredis/tree/cmake-c99) compiles for you.

As I mentioned, hiredis isn't c90 compliant but in theory, CMake should add `-std=c99` or equivalent to the makefile in that branch.

**Comment by lisay-yan** [comment]
Hi, Michael

Yes, I tried your branch. It works well.
Would you like push to hiredis-1.0.0 official? Thanks.

Best Wishes
Lisa

**Comment by michael-grunder** [comment]
I've merged it into hiredis master.  It's backward compatible so we will be able to include it when we release 1.0.1
