### ISSUE TITLE
redisCommandArgv return NULL

### ISSUE THREAD

**Issue by charach** [redis/hiredis#871]
Hello I am asking you because there is a problem while using hiredis.

While using redisCommandArgv and redisCommand, NULL may be returned while the connection is connected.
Can you tell me about the scenario where this situation occurs?

* There is no special log output by the redis, and it is a case where the hiredis returns NULL.

**Comment by michael-grunder** [comment]
Hiredis can return NULL in the event of an allocation or network failure and will typically set `redisContext->err` with the error that occurred.

**Comment by michael-grunder** [comment]
Going to close this because it's not about a bug in Hiredis but I'm always happy to help answer questions
