### ISSUE TITLE
Is this a memory leak ?

### ISSUE THREAD

**Issue by ChenQianCQ** [redis/hiredis#876]
I have a project use hiredis(redis version 5.0.5) , and code like this. 

>  int before, now;
    before = get_phy_mem(getpid()); /* read VmRSS from /proc/[pid]/status  */
    ret = redisReaderFeed(driver->reader, driver->in_buf.start, driver->in_offset);
    if (ret != REDIS_OK) {
        return;
    }
    now = get_phy_mem(getpid());
    if (before != now) {
        ERROR("redisReaderFeed. (%d - %d len:%d)", before, now, driver->reader->len);
    }

and , log file will print:

> 20200912095231.204[WARN]redisReaderFeed. (333632 - 333636 len:2057)
20200912095231.204[WARN]redisReaderFeed. (333636 - 333640 len:1039)
20200912095231.204[WARN]redisReaderFeed. (333640 - 333644 len:2062)
20200912095231.204[WARN]redisReaderFeed. (333644 - 333648 len:1043)
20200912095231.204[WARN]redisReaderFeed. (333648 - 333652 len:1091)
20200912095231.204[WARN]redisReaderFeed. (333652 - 333656 len:1046)
20200912095231.204[WARN]redisReaderFeed. (333656 - 333660 len:1095)
20200912095231.204[WARN]redisReaderFeed. (333660 - 333664 len:1053)
20200912095231.205[WARN]redisReaderFeed. (333664 - 333668 len:1101)
20200912095231.205[WARN]redisReaderFeed. (333668 - 333672 len:2082)
20200912095231.205[WARN]redisReaderFeed. (333672 - 333676 len:1063)
20200912095231.205[WARN]redisReaderFeed. (333676 - 333680 len:2085)
20200912095231.205[WARN]redisReaderFeed. (333680 - 333684 len:1067)
20200912095231.205[WARN]redisReaderFeed. (333684 - 333688 len:1116)
20200912095231.205[WARN]redisReaderFeed. (333688 - 333692 len:1029)
20200912095231.205[WARN]redisReaderFeed. (333692 - 333696 len:2051)
20200912095231.206[WARN]redisReaderFeed. (333696 - 333700 len:1032)

VmRSS grows up every 4KB !! 

finally, when i call 

> int before, now;
    before = get_phy_mem(getpid());
    ERROR("redisReaderFree <%d %p>.", driver->reader->len, driver->reader->buf);
    if (driver->reader) {
        redisReaderFree(driver->reader);
        driver->reader = NULL;
    }
    now = get_phy_mem(getpid());
    ERROR("redisReaderFree . (%d - %d)", before, now);

log shows

> 20200912095234.293[WARN]redisReaderFree  <699 0x7fbc8a048905>.
20200912095234.293[WARN]redisReaderFree . (323424 - 323424)

VmRSS NOT decrease as expected .
i thought this is memory leak . am i right ? @michael-grunder

**Comment by michael-grunder** [comment]
It's really hard for me to say whether there is a leak from what you posted, as it's not a complete program that I can run.

That said, I would be surprised if `redisReader` had such a straightforward leak as we test it heavily under valgrind in CI.  There could be a leak but I'd need you to provide an example program that I can run so I could check it.

I don't know the python internals very well but since it's garbage collected I would expect `get_phy_mem()` to fluctuate under normal use.

However, if you can provide some code I can compile and run I'll gladly take a look.

**Comment by ChenQianCQ** [comment]
thank you for reply !!

1. the function get_phy_mem() is not python code, it's just my test code. just read VmRSS from /proc/[pid]/status. 

> int get_phy_mem(const pid_t p)
{
    char file[64] = {0};
    FILE *fd;         
    char line_buff[256] = {0};  
    sprintf(file,"/proc/%d/status",p);
    fd = fopen(file, "r"); 

    int i;
    int vmrss = 0;

    for (i=0;i<VMRSS_LINE;i++)
    {
        char* ret = fgets(line_buff, sizeof(line_buff), fd);
        if (strstr(line_buff,"VmRSS:") != NULL) {
            sscanf(line_buff,"VmRSS: %u", &vmrss);
        }
    }

    fclose(fd);
    return vmrss;
}

2. sorry for the project is not fully to compile and run. I will update a demo program ASAP!

**Comment by michael-grunder** [comment]
I'm going to close the issue since a leak seems unlikely but feel free to reopen it or just post more complete code and I'll gladly take a look.
