### ISSUE TITLE
how to flush read buffer?

### ISSUE THREAD

**Issue by StyleTJy** [redis/hiredis#880]
I want to eval a command and get its reply, but before that I want to flush the read buffer first, because I don't want any other possible unconsumed reply by mistake. What should I do first, like what function should I call?

**Comment by michael-grunder** [comment]
I'm not sure I have enough information to give you a complete answer, but you can use `redisBufferRead` directly to have hiredis read on the socket.

Keep in mind this will block in sync mode so you'd probably need to set the socket non-blocking and then read until it's empty.

[Here's some code in redis-cli](https://github.com/redis/redis/blob/f1863a1fe760610cebfd1c121623a3c12a79d600/src/redis-cli.c#L7198) interacting directly with `redisBufferRead`.

Another option is to keep track of how many commands you've sent so you will know when to expect the `EVAL` response.

If you could post some pseudocode as to what you're doing exactly I'm happy to help.

**Comment by StyleTJy** [comment]
> I'm not sure I have enough information to give you a complete answer, but you can use `redisBufferRead` directly to have hiredis read on the socket.
> 
> Keep in mind this will block in sync mode so you'd probably need to set the socket non-blocking and then read until it's empty.
> 
> [Here's some code in redis-cli](https://github.com/redis/redis/blob/f1863a1fe760610cebfd1c121623a3c12a79d600/src/redis-cli.c#L7198) interacting directly with `redisBufferRead`.
> 
> Another option is to keep track of how many commands you've sent so you will know when to expect the `EVAL` response.
> 
> If you could post some pseudocode as to what you're doing exactly I'm happy to help.

thanks for replying.
here's a scenario, i subscribed a channle, and waiting for a publish message. then i got the reply and i unsubscribed the channel and eval another command. but before the unsubscribe operation is done, there may be unconsumed published message come to the buffer. in this case, will the next command got the former unconsumed published message which is not expected?

```
reply=redisCommand("subscribe channel");
redisGetReply(c, &reply);
reply=redisCommand("unsubscribe channel");
reply=redisCommand("evalsha sha1sum keys argv");
```

**Comment by michael-grunder** [comment]
There are a variety of different strategies you could use to accomplish this.

One solution would be to use a different connection object for your `EVAL` call which avoids the problem of having to deal with unconsumed `PUBLISH` messages.

Another solution would be to do something [like this](https://gist.github.com/michael-grunder/f3969eb59e77deb10e2164f71e7022a8)

Basically, once you detect the message that indicates you should unsubscribe, just keep reading replies with `redisGetReply` until you parse the `unsubscribe` message.  At that point you know for a fact there will not be more publish messages and can use the connection normally for your EVAL.

Even with extremely high volume (hundreds of thousands of messages a second), it won't take long to read until the unsubscribe response.

**Comment by michael-grunder** [comment]
I'm going to close the issue because it's not about a bug with Hiredis but I'm happy to further help if you have questions about the proposed solutions.
