### ISSUE TITLE
Windows 10 x64 build issues: hiredis with SSL support 

### ISSUE THREAD

**Issue by jcohen02** [redis/hiredis#890]
Hi,
I'm trying to build hiredis 1.0.0 on Windows 10 x64 with SSL support and encountering some issues. I previously had things working sometime ago based on the SSL updates that were in master prior to the 1.0.0 release but I recall needing to undertake some modification to the build configuration.

Now that the SSL updates have been incorporated into the latest realease, I'm looking for a straightforward way to build on Windows 10. I wonder if you can:
 - a) provide some guidance on your recommended configuration for building on Windows (e.g. do you run CI builds/testing on Windows? If so which compiler do you use, which SSL binaries, etc?)
 - b) suggest if I'm doing something wrong with my different approaches to attempting to build the library as detailed below.

In my current Windows 10 x64 environment, I have VS2019 available and also [RTools40](https://cran.r-project.org/bin/windows/Rtools/) which provides a `mingw-x64` environment. (I'm ultimately looking to link the built library into an R library which I had working successfully with the SSL updates pre 1.0.0). [In the mingw64 environment I've installed openssl using the `pacman` packaging tool]

For all of the examples below, I'm taking a clean copy of `hiredis-1.0.0` from the v1.0.0 release zip. Apologies if I'm missing something fundamental in any of the steps I'm attempting here.

**1) Attempting to build with Mingw64 toolchain:**
I'm starting simple without SSL support: In the hiredis-1.0.0 directory, run `make`. The build goes so far and fails during linking with a number of undefined symbols including `__imp_getsockopt`, `__imp_setsockopt`, `__imp_WSAGetLastError`. This looks to be a result of needing to link the Winsock library. Adding this to the end of the platform-specific conditionals in the `Makefile` resolves the problem and library builds ok:

```
ifeq ($(findstring MSYS_NT-10.0, $(uname_S)), MSYS_NT-10.0)
  $(warning Windows 10 platform detected)
  REAL_LDFLAGS+= -lws2_32
endif
``` 

Now trying to build with SSL support:
`make USE_SSL=1`

It gets as far as trying to link the `hiredis_ssl` library and then fails with a number of undefined symbols in `libcrypto`. It seems `libcrypt32` is also required in the linking. The link command line also has duplicate `-lssl -lcrypto` and includes `-lpthread` which I don't think is required? I made some further Win-specific tweaks in the `Makefile` to modify the linking flags and the _static_ library then builds successfully. For the _shared_ library, it was giving a number of undefined symbol errors that looked like symbols from the main hiredis library. It was necessary to add `-lhiredis` to the linking and this results in the shared library also building successfully. The following addition to the Makefile results in a successful build of the `hiredis_ssl` library:

```
ifeq ($(findstring MSYS_NT-10.0, $(uname_S)), MSYS_NT-10.0)
  $(warning Windows 10 platform detected)
  REAL_LDFLAGS+= -lws2_32
  SSL_LDFLAGS+= -lcrypt32 -L. -lhiredis -lws2_32 
endif
```

I don't know if using mingw64 is intended to be an accepted build configuration but if it is, I'm assuming I may be doing something wrong in my approach that's resulting in encountering these issues. If these are indeed problems that need resolving, I can contribute a PR with my changes.

**2) Attempting to build with VS2019:**
With VS2019 and CMake building without SSL support seems fine. I create a `build` directory in `hiredis-1.0.0`, change to it, run `cmake -DCMAKE_INSTALL_PREFIX=<install location> ..` then I run `msbuild /p:Configuration=Release INSTALL.vcxproj`, the build and install work fine.

With SSL: `cmake -DCMAKE_INSTALL_PREFIX=<install location> -DENABLE_SSL ..`
The initial issue was OpenSSL not being present. I tried a couple of different binary releases of OpenSSL from those [listed on the OpenSSLWiki](https://wiki.openssl.org/index.php/Binaries). In some cases, CMake couldn't find the OpenSSL installation (and I needed to manually point it to the actually library files by setting `-DLIB_EAY_RELEASE` and `SSL_EAY_RELEASE`), but ultimately there were undefined symbols when linking. One particular issue was a failure with the `SSL_library_init` undefined symbol.

Eventually I built OpenSSL from source and linking against this build, `hiredis_ssl` is successfully built with VS2019: `cmake -DCMAKE_INSTALL_PREFIX=<install location> -DENABLE_SSL=ON -DOPENSSL_ROOT_DIR=<path to my OpenSSL build> ..`

Apologies for the long issue description but any advice you can provide on recommended Windows build configurations that might make building with SSL more straightforward would be most helpful. This would ensure this can be cleanly built as a dependency as part of the build of another library.

Many thanks for your help.

**Comment by RameshKandukuriB** [comment]
hiredis vcpkg port available on windows  (https://vcpkg.info/port/hiredis) however its not the latest one.

**Comment by michael-grunder** [comment]
Hi @jcohen02,

I'm not sure how much help I can be as I haven't done much Windows development since the 90s.

That said, perhaps our Windows build section in [.travis.yml](https://github.com/redis/hiredis/blob/297f6551da11d4a22fefe4d385d42edf27a6cd73/.travis.yml#L119) could be useful?

I'm able to build hiredis in Windows in a VM with a couple of helper .bat files.

vcv.bat:

```bat
call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
```

win-build.bat:

```bat
rd /s /q "win-build"
mkdir win-build
cd win-build
cmake .. -G Ninja -DCMAKE_C_COMPILER=cl.exe -DCMAKE_CXX_COMPILER=cl.exe -DENABLE_SSL=ON -DENABLE_EXAMPLES=ON && ninja -v
```

This requires the `ninja` build system being installed which I installed via `choco install ninja` if I recall correctly.  I don't remember doing anything special around OpenSSL but it's possible there were some hoops to jump through that I've forgotten.

My CMake build output indicates OpenSSL was found automatically:

```bat
C:\Users\User\hiredis-github\win-build>cmake .. -G Ninja -DCMAKE_C_COMPILER=cl.exe -DCMAKE_CXX_COMPILER=cl.exe -DENABLE_SSL=ON -DENABLE_EXAMPLES=ON && ninja -v
-- The C compiler identification is MSVC 19.25.28612.0
-- The CXX compiler identification is MSVC 19.25.28612.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Detected version: 1.0.1
-- Found OpenSSL: optimized;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MD.lib;debug;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MDd.lib (found version "1.1.1f")
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Configuring done
-- Generating done
```

I'm not sure if this is helpful but that's how I build in Windows.

**Comment by jcohen02** [comment]
Many thanks both for the feedback. @michael-grunder, thanks for the CMake output. I hadn't tried using the `ninja` build system. I think there was also an issue with me not using the right binary release of OpenSSL. Good to see that this works fine via MSVC tooling with this configuration.

For the R-related approach, it looks like I'll need to use a mingw64 toolchain. As per my original message above, that works with a couple of minor tweaks to the linking flags and it's also been suggested that I take a look at creating a [pacman](https://github.com/trinker/pacman) package for this environment which I'm going to investigate.

Thanks again and I'll close this issue.

**Comment by zhangxued923** [comment]
1、Create folder "sln" in hiredis-1.0.0
![image](https://user-images.githubusercontent.com/55131944/96701360-14982d80-13c3-11eb-90e2-dfe3599ffce7.png)
2、Use it
![image](https://user-images.githubusercontent.com/55131944/96701689-76f12e00-13c3-11eb-9ebe-e7f5497f30f0.png)
3、Enter the folder "sln",  execute command (you should change the version and path):
cmake -G "Visual Studio 12 2013" -DENABLE_SSL=1 -DOPENSSL_ROOT_DIR=C:\Users\D\Desktop\openssl-1.1.1g\release -DOPENSSL_INCLUDE_DIR=C:\Users\D\Desktop\openssl-1.1.1g\release\include -DOPENSSL_CRYPTO_LIBRARY=C:\Users\D\Desktop\openssl-1.1.1g\release\lib ../

**Comment by taozuhong** [comment]
Build hiredis on MSYS2:
```bash
MSYS2_ARG_CONV_EXCL=- cmake . -G"MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=$MINGW_PREFIX -DENABLE_SSL=ON

make install DESTDIR=/
```
