### ISSUE TITLE
Documentation error for opening SSL connections via hiredis

### ISSUE THREAD

**Issue by jcohen02** [redis/hiredis#893]
Hi, I've been trying to initiate an SSL connection to Redis via hiredis and, unless I've misunderstood, I think there's an error in the example given in the [README](https://github.com/redis/hiredis/blob/master/README.md).

At [line 535 of README.md](https://github.com/redis/hiredis/blame/master/README.md#L535) (linking using Blame view since I couldn't see how else to link to a specific line in a Markdown file) there is a check to see if the result of `redisCreateSSLContext` is `!= REDIS_OK`. I was caught out by this for a while - aside from the fact that the parentheses don't seem to match up, `[redisCreateSSLContext](https://github.com/redis/hiredis/blob/297f6551da11d4a22fefe4d385d42edf27a6cd73/ssl.c#L218)` returns a pointer to the context or `NULL` if there's an error. Checking in `test.c` it looks like there's simply a check to see that the return value is not `NULL`.

Since the `redisSSLContextError` is also set in some cases, I ended up with something similar to the following:

```
/* Create SSL context */
ssl_context = redisCreateSSLContext(
    "cacertbundle.crt",     /* File name of trusted CA/ca bundle file, optional */
    "/path/to/certs",       /* Path of trusted certificates, optional */
    "client_cert.pem",      /* File name of client certificate file, optional */
    "client_key.pem",       /* File name of client private key, optional */
    "redis.mydomain.com",   /* Server name to request (SNI), optional */
    &ssl_error);

if(ssl_context == NULL || ssl_error != 0) {
    /* Handle error and abort... */
    /* e.g. printf("SSL error: %s\n", 
                   (ssl_error != 0) ? 
                       redisSSLContextGetError(ssl_error) : "Unknown error");
             // Abort
    */
}
```

Maybe there's a better way to do this but I'll open a PR with a suggested update based on the above and happy to change this if there's a preferred way to handle this.

**Comment by michael-grunder** [comment]
Merged, thanks!

Closing via #894
