### ISSUE TITLE
Upgrade to a more recent version

### ISSUE THREAD

**Issue by alex-weej** [redis/hiredis#898]
Looks like we are 4-5 years(!) out of date here.

**Comment by michael-grunder** [comment]
Hi @alex-weej, who is we?  :smile: 

Hiredis released v1.0.0 on [august 3rd](https://github.com/redis/hiredis/tree/v1.0.0)

**Comment by alex-weej** [comment]
lmao, I meant to post this issue on my org's internal GitHub Enterprise. OOPS!
