### ISSUE TITLE
RPOP/LPOP the type of list's value is REDIS_REPLY_INTEGER

### ISSUE THREAD

**Issue by vspyan** [redis/hiredis#903]
I had  executed statement "lpush list value1/value2..."with a redis-cli client，
 reply = (redisReply *)redisCommand(context, "rpop list");
 if (reply->type == REDIS_REPLY_STRING)    //sometimes reply->type is REDIS_REPLY_INTEGER instead of  REDIS_REPLY_STRING，  why???
     printf(" str: %s\n", reply->str); //when reply->type==REDIS_REPLY_INTEGER, reply->integer ==1/2/3 ,Why？？？

**Comment by michael-grunder** [comment]
Can you provide a full example that replicates the issue?

`RPOP` may return `REDIS_REPLY_STRING` or `REDIS_REPLY_NIL` depending on whether the list is empty, but I don't know why or how you'd get `REDIS_REPLY_INTEGER`.

**Comment by michael-grunder** [comment]
Closing this issue but feel free to reopen if you can provide code that replicates the issue.
