### ISSUE TITLE
how to uninstall hiredis?

### ISSUE THREAD

**Issue by ashwani29** [redis/hiredis#911]
I've multiple `hiredis` versions installed which is creating problems while compilation, how can I uninstall them?

**Comment by michael-grunder** [comment]
Hi @ashwani29 

If you run `make -n install` in the hiredis directory you'll see all of the operations hiredis will execute when running `make install`.

Can you provide more information about how the different versions are causing problems?  Uninstalling a specific version would just involve removing those symlinks in `/usr/local/` but this can be a bit tricky to do.

**Comment by ashwani29** [comment]
Yes, I'm using a c++ client library for redis, as obvious that also depends on hiredis but on compilation, i was getting this error:
` root@user-HP-Pavilion-Notebook:/home/user/tests/redisclient# g++ -std=c++11 -o hclient hclient.cpp -lredis++ -lhiredis
/usr/bin/ld: warning: libhiredis.so.1.0.1-dev, needed by /usr/local/lib/libredis++.so, may conflict with libhiredis.so.0.14`

**Comment by michael-grunder** [comment]
I don't use C++ much but in theory you should be able to have multiple versions of a shared object on your system and each library can link to the one it wants.

You _can_ remove the older version of hiredis by simply deleting the specific version:

e.g.

```
-rwxrwxr-x 1 mike mike 345064 Jan 11 10:28 libhiredis.so.0.14
```

But that could cause problems if you have any binaries that depend on the older version.

It looks like `redisplusplus` suggests using hiredis v1.0.0 so you should be OK with 1.0.1 as there aren't any breaking changes.

**Comment by ashwani29** [comment]
I uninstalled all versions of `hiredis`, first from source directory,  then deleted any binary if any still exist from  `usr/local/lib/`  where it was installed and verified if any package is still left with `dpkg`  command and then removed it using `dpkg uninstall hiredis*`. 

simply stating for future references if somebody get the same error just uninstall it with dpkg command then build again from `redisplusplus` page.

**Comment by michael-grunder** [comment]
Awesome, I'm glad you got it working.  Going to close this issue but feel free to reopen/comment if you run into trouble
