### ISSUE TITLE
redisAsyncCommandArgv is not working with redis 6.0.7 version.

### ISSUE THREAD

**Issue by hyungkchoi** [redis/hiredis#915]
redisAsyncCommandArgv is not working properly with redis 6.0.7

it is working well with 5.0.6. But when i use redisAsyncCommandArgv with redis.6.0.7. it works abnormally.

When trying to save a value with HMSET, a unexpected strange value is entered.

**Comment by michael-grunder** [comment]
Hi @hyungkchoi 

Can you provide some example code that demonstrates the problem?  I did a quick test and don't see any issues.

**Comment by michael-grunder** [comment]
@hyungkchoi Are you still having issues with Hiredis?

I'm going to close the issue but feel free to post some sample code that can replicate the problem.
