### ISSUE TITLE
[hiredis_ssl] Add support for skipping certificate verification

### ISSUE THREAD

**Issue by sewenew** [redis/hiredis#927]
**redis-cli 6.2** already supports skipping certificate verification and setting default verification path: [#8416](https://github.com/redis/redis/commit/be83bb13a8eaad68b7580b95c696f2554cf7100e#). However, it seems that hiredis_ssl doesn't catch up with this feature.

Is there a plan to port this feature to hiredis_ssl? Thanks!

Regards

**Comment by michael-grunder** [comment]
Closing as #1085 was merged
