### ISSUE TITLE
freeReplyObject coredump

### ISSUE THREAD

**Issue by qsdzwb** [redis/hiredis#940]
![image](https://user-images.githubusercontent.com/21100004/114516398-f1fb1900-9c6f-11eb-89d3-e94c805c6b09.png)
As shown above，on line 106, coredump happens occasionally（code: freeReplyObject(r->element[j]) )
![image](https://user-images.githubusercontent.com/21100004/114998362-78fbfb80-9ed3-11eb-85ce-22807ed3779a.png)

**Comment by michael-grunder** [comment]
Maybe I haven't had enough coffee yet but I'm not following this gdb output.

When you `p *r` it outputs the struct showing that `element` points to `0x7f6060c9780`, but then when you print `r->element[0]` it print `0x6`, which is what I would expect if `r` was `NULL`, which it isn't.

Can you provide code that replicates this issue?

**Comment by michael-grunder** [comment]
Going to close this since we've not received any more information and it doesn't look like a bug in Hiredis.

Feel free to reopen if you've got some code to replicate the problem.
