### ISSUE TITLE
RESP3 Pub/Sub not in line with resp3 specification

### ISSUE THREAD

**Issue by kristjanvalur** [redis/hiredis#941]
Hi there.
I noticed, when perusing the documentation for RESP3 (https://github.com/antirez/RESP3/blob/master/spec.md) 
```
>4<CR><LF>
+pubsub<CR><LF>
+message<CR><LF>
+somechannel<CR><LF>
+this is the message<CR><LF>
```
However, the implementation does not look for the `pubsub` line.
The curious thing is that the hiredis client does work with the server implemented by docker container `redislab/rejson`, in `hello 3` mode.

Even more curious, is that the redis-cli, from the same container, will fail when receiving pub/sub messages in RESP3 mode.

I am unsure about the relation of varous redis projects, how hiredis connects with the redis server, and the RESP3 specification, but I thought I'd remark on this.

**Comment by zuiderkwast** [comment]
Hello.

The RESP3 specification is not the documentation of Redis. It is simply the specification of RESP3 protocol. The quoted example a push message is not an actual example of a pubsub message in Redis.

Instead, in Redis, the message has 3 elements. If PSUBSCRIBE is used, it is a 4 element push message with "pmessage" as the first element. Or "smessage" if it is a sharded pubsub message. All of this is documented on the page https://redis.io/docs/manual/pubsub/.

Anyway, I think this is not a hiredis issue, so I think this issue can be closed.

**Comment by kristjanvalur** [comment]
Fine by me :)
