### ISSUE TITLE
Connect/disconnect callbacks cannot invoke other async apis

### ISSUE THREAD

**Issue by kristjanvalur** [redis/hiredis#946]
The proper flags aren't set to guard against api calls from connect/disconnect callbacks.
In particular, the connect callback cannot call redisAsyncDisconnect.
PR #931 addresses these issues

**Comment by kristjanvalur** [comment]
Still nothing?  Please see the associated PR

**Comment by michael-grunder** [comment]
Closing as #931 was merged
