### ISSUE TITLE
[coredump] hiredis coredump with double free when call __redisAsyncDisconnect

### ISSUE THREAD

**Issue by hdhyy** [redis/hiredis#965]
![image](https://user-images.githubusercontent.com/14343414/122366757-69aa3480-cf8e-11eb-988b-66cfbe8ab608.png)

**some example code**

> bool CRedisSubscriber::disconnect() {
>     // let event loop exit
>     event_base_loopbreak(_event_base);
>     // disconnect
>     if (_redis_context) {
>         redisAsyncDisconnect(_redis_context);
>         _redis_context = NULL;
>     }
>     return true;
> }

**Comment by Esp9527** [comment]
Have you solved it

**Comment by bjosv** [comment]
Calling `redisAsyncDisconnect()` before `event_base_loopbreak()` would make sure the disconnect is done correctly before the event loop breaks. This should also avoid the double free (see async testcases in test.c).

**Comment by hdhyy** [comment]
> Calling `redisAsyncDisconnect()` before `event_base_loopbreak()` would make sure the disconnect is done correctly before the event loop breaks. This might also avoid the double free in your case? (see async testcases in test.c).

It seems like that redisAsyncDisconnect() does not promise the disconnect done

I just add a lock to avoid double free, like:

`event_base_loopbreak(_event_base);`
`while (!_s_event_exit.load()) {`
`boost::this_thread::sleep()`
`}`
`if (_redis_context && _s_connect_status.load()) {`
`redisAsyncDisconnect(_redis_context);`
`}`
