### ISSUE TITLE
Is hiredis support config Cipher suite

### ISSUE THREAD

**Issue by lisay-yan** [redis/hiredis#979]
Is hiredis open any API for TLS cipher setting?
•	Cipher suite that can be used for TLS
o	TLS 1.2 :
	AES128-GCM-SHA256
	AES128-SHA256
	AES256-GCM-SHA384
	AES256-SHA256
	DH-DSS-AES128-GCM-SHA256
	DH-DSS-AES128-SHA256
	DH-DSS-AES256-GCM-SHA384
	DH-DSS-AES256-SHA256
	DHE-DSS-AES128-GCM-SHA256
	DHE-DSS-AES128-SHA256
	DHE-DSS-AES256-GCM-SHA384
	DHE-DSS-AES256-SHA256
	DHE-RSA-AES128-GCM-SHA256
	DHE-RSA-AES128-SHA256
	DHE-RSA-AES256-GCM-SHA384
	DHE-RSA-AES256-SHA256
	DH-RSA-AES128-GCM-SHA256
	DH-RSA-AES128-SHA256
	DH-RSA-AES256-GCM-SHA384
	DH-RSA-AES256-SHA256
	ECDH-ECDSA-AES128-GCM-SHA256
	ECDH-ECDSA-AES128-SHA256
	ECDH-ECDSA-AES256-GCM-SHA384
	ECDH-ECDSA-AES256-SHA384
	ECDHE-ECDSA-AES128-GCM-SHA256
	ECDHE-ECDSA-AES128-SHA256
	ECDHE-ECDSA-AES256-GCM-SHA384
	ECDHE-ECDSA-AES256-SHA384
	ECDHE-RSA-AES128-GCM-SHA256
	ECDHE-RSA-AES128-SHA256
	ECDHE-RSA-AES256-GCM-SHA384
	ECDHE-RSA-AES256-SHA384
	ECDH-RSA-AES128-GCM-SHA256
	ECDH-RSA-AES128-SHA256
	ECDH-RSA-AES256-GCM-SHA384
	ECDH-RSA-AES256-SHA384
o	TLS 1.3 : AES256-GCM-SHA384

**Comment by michael-grunder** [comment]
You are able to directly configure any ciphers or other TLS options by directly creating the `SSL` and `SSL_CTX` yourself and then calling [redisInitializeSSL](https://github.com/redis/hiredis#hiredis-openssl-wrappers).

It's more work but lets you configure TLS however you need to.

**Comment by michael-grunder** [comment]
@lisay-yan does this answer make sense?
