### ISSUE TITLE
Reusing an async context with libevent 

### ISSUE THREAD

**Issue by picanumber** [redis/hiredis#981]
In the [libevent example](https://github.com/redis/hiredis/blob/master/examples/example-libevent.c) we observe the following callback for the get function: 

```
void getCallback(redisAsyncContext *c, void *r, void *privdata) {
    redisReply *reply = r;
    if (reply == NULL) {
        if (c->errstr) {
            printf("errstr: %s\n", c->errstr);
        }
        return;
    }
    printf("argv[%s]: %s\n", (char*)privdata, reply->str);

    /* Disconnect after receiving the reply to GET */
    redisAsyncDisconnect(c);
}
```

The problem with calling `redisAsyncDisconnect(c);` is that it kills the connection in order to ext the loop. Since I'm using libevent, I imagined it could be feasible to call `event_base_loopbreak` in order to exit the loop but keep the connection alive; this is not doable because the event base is not passed in the callback. 

My alternative would be to somehow set the event as "non persistent" in order to allow the loop to terminate after a single run. Again I don't see an option to do this. Bottom line is this: 

* Is an asynchronous context supposed to "die" after the execution of a single command? If not how can I reuse it, since not killing the connection causes the program to loop forever around `event_base_dispatch`? 
* Is doing `event_base_loopbreak(((redisLibeventEvents *)c->ev.data)->base);`  (instead of the disconnection call in the callback) a viable alternative? It seems to work, but looks too brittle to solve such a common problem.

**Comment by michael-grunder** [comment]
Hi @picanumber,

I'm not sure I completely understand your use-case, but you certainly don't need to call `redisAsyncDisconnect` from the command callbacks.  That's just what's being done in the simple sample programs.

Typically with async and an event loop, the loop would be long-running (often for the total length of the program), and you would attach various timers, IO, or other watchers to handle the actual program logic.  

> Is an asynchronous context supposed to "die" after the execution of a single command? If not how can I reuse it, since not killing the connection causes the program to loop forever around event_base_dispatch?

You can use the `REDIS_NO_AUTO_FREE` to stop hiredis from cleaning up the connection on disconnect, but I'm not sure that's really what you would want.  What kind of program are you trying to make.  I can try to help outline how you might go about it via async hiredis.

**Comment by picanumber** [comment]
Maybe the most succinct use case I can describe is this: I want to use an async connection to issue `SET` commands (so my program doesn't stall waiting for the `SET` result). Doing what the examples do, after issuing a single command I get stuck in the same event loop  and cannot re-use the async context. In detail that would be:

1 Create an async context, put it in a pool of connections
2 Pop a context `C` from the pool 
3 Issue a `SET` command using `C` and launch the event loop (`event_base_dispatch`)
4 The callback gets called, I process the results of SET, stop the loop and put the context back in the pool
5 Redo from 2 (Issue another command)

**Comment by picanumber** [comment]
> Typically with async and an event loop, the loop would be long-running (often for the total length of the program), and you would attach various timers, IO, or other watchers to handle the actual program logic.

If there's an accessible example of how to attach "watchers", or other means to handle program logic I'd appreciate a reference.

**Comment by picanumber** [comment]
@michael-grunder  I think with this example makes it clear that this a libevent enquiry and not a hiredis one. Thanks for the reply and demo, I have enough info to close the issue.

P.S. it would be helpful if a more extended async example was available.
